### ISSUE TITLE
Add support for taking pictures using camera

### ISSUE THREAD

**Issue by rupert2133** [Sh1d0w/multi_image_picker#1]

**Comment by Sh1d0w** [comment]
Hi, thanks for opening this issue.

Currently the key challenges here are on the side of the libraries I use for the gallery on iOS and Andoird.

On the iOS side there are two possible issues that stops me from implementing this:

https://github.com/mikaoj/BSImagePicker/issues/118
https://github.com/mikaoj/BSImagePicker/issues/139

On the Android side this feature is still in development in the library I am using:

https://github.com/zhihu/Matisse/wiki/Capture

Until those are resolved I do not have a way to add support for it in this plugin. 

You can still use image capture plugin separately (https://pub.dartlang.org/packages/camera) to allow your users to take photos, separately from this library.

**Comment by rupert2133** [comment]
Thanks for the fast reply. Will check out the camera plugin instead. Thanks again! Hope this feature will be implemented soon! 👍

**Comment by Sh1d0w** [comment]
@rupert2133 This is now available in version 2.2.40. More info how to enable it here: https://github.com/Sh1d0w/multi_image_picker#enable-camera-in-the-gallery
