### ISSUE TITLE
Please Updated to Swift 4.2

### ISSUE THREAD

**Issue by KennyLisc** [Sh1d0w/multi_image_picker#10]
Need to update to swift 4.2, The BSImagePicker have been upgrade, so no update build failed.

'UIImageJPEGRepresentation' has been replaced by instance method 'UIImage.jpegData(compressionQuality:)'

**Comment by Sh1d0w** [comment]
Hi, it has already been updated. 

Please make sure you are using the latest version of the plugin: 2.2.10.
