### ISSUE TITLE
Upload requestOriginal stream infact not ORIGINAL,Exif data has been removed

### ISSUE THREAD

**Issue by leapit** [Sh1d0w/multi_image_picker#103]
**Bug Report**

`multi_image_picker` version: 4.0.1

Is it happening on Android: Yes 

Is it happening on iOS: Yes

```

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.6 17G6029, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)
```

**Describe the bug**

Just run api like demo [https://sh1d0w.github.io/multi_image_picker/#/upload](https://sh1d0w.github.io/multi_image_picker/#/upload) the image server saved infact not same as stored before upload in mobile,the Exif data has been removed.

It seems no api to upload a REAL ORIGINAL image,I don't think it is a good idea to remove Exit data when uploading,beacause there are many ways to do that on server side if needed.

Is there any way to handle this?

**Comment by Sh1d0w** [comment]
Good, idea I will look into it when I have time.

**Comment by leapit** [comment]
@Sh1d0w Thanks,look forward a update with a full original image data api. multi_image_picker
 is awesome,and this feature is also necessary.

**Comment by Sh1d0w** [comment]
The plugin now allows you to access the file path of the picked images directly as well as the byte data. You can try with the file paths, they are returned "as is" without any transformations or compressions.

https://github.com/Sh1d0w/multi_image_picker/blob/master/CHANGELOG.md#2019-08-12
