### ISSUE TITLE
Error: A value of type 'dart.core::List<#lib1::Asset>' can't be assigned to a variable of type 'dart.core::List<dart.io::File>'.

### ISSUE THREAD

**Issue by rupert2133** [Sh1d0w/multi_image_picker#105]
Hi Sir,

I got this error after upgrading from 1.0.51 to 4.0.1

`Error: A value of type 'dart.core::List<#lib1::Asset>' can't be assigned to a variable of type 'dart.core::List<dart.io::File>'.
Try changing the type of the left hand side, or casting the right hand side to 'dart.core::List<dart.io::File>'.
      resultList = await MultiImagePicker.pickImages(maxImages: 10);`

i can't seems to fix it. and can't trace the root cause.

**Comment by Sh1d0w** [comment]
@rupert2133 This is because in version the plugin returned Files, but was changed to return asset objects instead.

Please read the docs before using the plugin https://sh1d0w.github.io/multi_image_picker/#/

**Comment by rupert2133** [comment]
Thanks!
