### ISSUE TITLE
Use the latest unstable version of Matisse

### ISSUE THREAD

**Issue by agnoam** [Sh1d0w/multi_image_picker#107]
By Matisse, the "[Crash if user try to select more than maxSelectable()](https://github.com/zhihu/Matisse/issues/462)" is fixed in the latest unstable version.
Can you use it too ?

**Comment by Sh1d0w** [comment]
Since version 4 this plugin not longer uses Matisse. See the change log and the docs for more info.

**Comment by agnoam** [comment]
But I can use just version 2.4.11 because I can't migrate into android x,
because it effect on other plugins.

**Comment by Sh1d0w** [comment]
You are free to fork the project at version 2.4.11 update Matisse version and include it as git dependency in your project :)
