### ISSUE TITLE
Error Running Project on Android Studio. BuildConfig is public, should be declared in .....

### ISSUE THREAD

**Issue by ueabu** [Sh1d0w/multi_image_picker#108]
**Bug Report**

`multi_image_picker` version: 4.0.1

Is it happening on Android: Yes

Is it happening on iOS: Didnt check

```
 [✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.14.3 18D109, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[!] IntelliJ IDEA Community Edition (version 2018.3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

```

**Describe the bug**
When I try to build my project in android studio, I get a bug stating 
```
error: class BuildConfig is public, should be declared in a file named BuildConfig.java
```

Further look at the file I see this: 
<img width="1325" alt="Screen Shot 2019-04-02 at 12 09 46 AM" src="https://user-images.githubusercontent.com/26811323/55377871-8278bd80-54dc-11e9-86de-c3173acdb3c9.png">

**Comment by Sh1d0w** [comment]
Did you try to run `flutter build apk` or `flutter run`, from he command line? Is it happening only in Android Studio?

**Comment by ueabu** [comment]
I tried `flutter run` but that was giving a whole other set of issues found here [https://github.com/flutter/flutter/issues/30278](#30278). I tried `flutter build apk` and that worked fine. May the problems is with android studio. I ended up copy the apk file to my physical device and installing it there. Thank you.
