### ISSUE TITLE
my android can't get photo's path when result,but all id/width/height have the value

### ISSUE THREAD

**Issue by kiradan** [Sh1d0w/multi_image_picker#11]
**Describe the bug**

**To Reproduce**

```
<!-- Insert example code here, that will help to reproduce the bug -->
```

**Expected behavior**

**Screenshots**

**Flutter (please complete the following information):**
- Which version of `multi_image_picker` are you using: [e.g. 2.0.04]

```
 <!-- run `flutter doctor` and paste the output here: -->
```

**iOS (please complete the following information):**
 - Swift Version: [e.g. 4.0]

**Android (please complete the following information):**
 - Device: [e.g. Nexus 5]
 - OS: [e.g. Lollipop 5.1]

**Additional context**

**Comment by Sh1d0w** [comment]
Hi, the plugin does not return photo paths. It returns Asset class, which you can then use to request the original image or thumb image as ByteData as described in the example [here](https://github.com/Sh1d0w/multi_image_picker/blob/master/example/lib/asset_view.dart) .

**Comment by morad00** [comment]
@Sh1d0w So how could I convert them to base64 images?
