### ISSUE TITLE
Add option to start Android picker in "All Photos", the same way as iOS does and as Matisse used to do.

### ISSUE THREAD

**Issue by acherkashyn** [Sh1d0w/multi_image_picker#111]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
When I open image picker on Android I want to have similar experience to iOS - A photo grid in All Photos and camera button(if enableCamera = true). Instead I land on a list of directories and get confused.

**Describe alternatives you've considered**
There are none currently.

**Additional context**
This seems to be a FishBun limitation. Feature request in FishBun open: https://github.com/sangcomz/FishBun/issues/143

**Comment by Sh1d0w** [comment]
This is released in version 4.1.2
