### ISSUE TITLE
Android: Auto-select photos taken by camera.

### ISSUE THREAD

**Issue by acherkashyn** [Sh1d0w/multi_image_picker#112]
**Is your feature request related to a problem? Please describe.**
When I open photo picker and tap a camera button and take a photo, Android photo picker doesn't select that new photo. I have to manually tap on it again. This is frustrating, it should automatically select the new photo. After all, if I took a photo and didn't tap "Back", then the photo is good and I intend to keep it.

**Describe the solution you'd like**
A default behavior on Android that matches iOS. Taking a photo in multi_image_picker via camera should take me back to the photo grid, and the new photo should be automatically selected.

**Describe alternatives you've considered**
The alternative is a manual step of tapping on an image after taking a photo.

**Additional context**
It looks like this is a FishBun limitation, there is currently no way to instruct it to behave like this.
See FishBun issue https://github.com/sangcomz/FishBun/issues/144 . If/when it is implemented I think this behavior should be default, as it matches iOS library's behavior.

**Comment by Sh1d0w** [comment]
I saw you've opened several issues with suggestions in the FishBun repo, will keep eye on them and will update the version here if/when they get implemented. 👍

**Comment by 26shruti** [comment]
@Sh1d0w In urgent need to this enhancement. When can we expect this?

**Comment by ThinkDigitalSoftware** [comment]
You need to ask is the fishbun repo since this is out of @sh1d0w's control
