### ISSUE TITLE
White radial buttons don't show up well on images with white / light backgrounds

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [Sh1d0w/multi_image_picker#113]
**Is your feature request related to a problem? Please describe.**

![Screenshot_20190404-174750](https://user-images.githubusercontent.com/23037821/55597339-f1832b80-5701-11e9-95a8-2cc6526ea5ab.jpg)

White radial buttons don't show up well on images with white / light backgrounds.

**Describe the solution you'd like**
The option to customize or provide our own widget if possible, or have a background where the indicator shows up and provide customization for that color. Similar to iOS.
<img width="238" alt="Screen Shot 2019-04-04 at 5 51 32 PM" src="https://user-images.githubusercontent.com/23037821/55597416-58a0e000-5702-11e9-9182-25fdac68b793.png">

**Comment by Sh1d0w** [comment]
Thanks for the suggestion, opened a feature request in the FishBun repo: https://github.com/sangcomz/FishBun/issues/145

Once implemented I will add it here as well.

**Comment by ThinkDigitalRepair** [comment]
Thank you very much

**Comment by Sh1d0w** [comment]
This is released in version 4.1.2

**Comment by ThinkDigitalRepair** [comment]
Awesome, thank you so much

**Comment by ThinkDigitalRepair** [comment]
What about the fade? since we couldn't possibly determine what color would be needed dynamically? It's still nice to be able to change the stroke color, but it still doesn't solve the issue of dynamically accounting for different colored photos.
![Screenshot_20190414-184555_Photos](https://user-images.githubusercontent.com/23037821/56103112-e5f3e980-5ee5-11e9-8c00-576f448b37ca.jpg)

**Comment by Sh1d0w** [comment]
@ThinkDigitalRepair You should ask this the maintainer of FishBun, I've just added support for what he added in his plugin.

**Comment by ThinkDigitalRepair** [comment]
OK, will do, thank you

**Comment by ThinkDigitalRepair** [comment]
https://github.com/sangcomz/FishBun/issues/148
