### ISSUE TITLE
my android can't receive the real path in v2.2.10

### ISSUE THREAD

**Issue by kiradan** [Sh1d0w/multi_image_picker#12]
hello,my android can't receive the real path in v2.2.10. but id/width/height have the values.
i find your old version solved this problem,which can receive the real path.but why the new verison remove this funcion?can you tell me?

**Comment by Sh1d0w** [comment]
This was leftover from a PR merged into the core. Currently there is bug in Flutter ( see [here](https://github.com/flutter/flutter/issues/20522) ) that prevent displaying images via file path on iOS. Until flutter team fixes that I do not plan to return file paths in the plugin, you can use getThumb and getOriginal methods to obtain the image data safely.
