### ISSUE TITLE
can‘t get this package，I've run the command ‘packages get’ on ios

### ISSUE THREAD

**Issue by WyyNever** [Sh1d0w/multi_image_picker#121]
Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A custom_multi_image_picker
      - Flutter
      - flutter_baidu_texttovioce
      - flutter_image_compress
      - flutter_wechat
      - image_crop
      - image_picker
      - image_picker_saver
      - image_saver
      - jpush_flutter
      - path_provider
      - shared_preferences

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios-release`
    -> Fetching podspec for `custom_multi_image_picker` from `.symlinks/plugins/custom_multi_image_picker/ios`
    [!] No podspec found for `custom_multi_image_picker` in `.symlinks/plugins/custom_multi_image_picker/ios`

    /Users/zxk/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.0.beta.2/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
    /Users/zxk/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.0.beta.2/lib/cocoapods/user_interface.rb:86:in `titled_section'
    /Users/zxk/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.0.beta.2/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
    /Users/zxk/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.0.beta.2/lib/cocoapods/installer/analyzer.rb:853:in `fetch_external_source'
    /Users/zxk/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.0.beta.2/lib/cocoapods/installer/analyzer.rb:832:in `block (2 levels) in fetch_external_sources'
    /Users/zxk/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.0.beta.2/lib/cocoapods/installer/analyzer.rb:831:in `each'
    /Users/zxk/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.0.beta.2/lib/cocoapods/installer/analyzer.rb:831:in `block in fetch_external_sources'
    /Users/zxk/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/zxk/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.0.beta.2/lib/cocoapods/installer/analyzer.rb:830:in `fetch_external_sources'
    /Users/zxk/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.0.beta.2/lib/cocoapods/installer/analyzer.rb:111:in `analyze'
    /Users/zxk/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.0.beta.2/lib/cocoapods/installer.rb:398:in `analyze'
    /Users/zxk/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.0.beta.2/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
    /Users/zxk/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/zxk/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.0.beta.2/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
    /Users/zxk/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.0.beta.2/lib/cocoapods/installer.rb:156:in `install!'
    /Users/zxk/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.0.beta.2/lib/cocoapods/command/install.rb:51:in `run'
    /Users/zxk/.rvm/gems/ruby-2.4.1@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Users/zxk/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.0.beta.2/lib/cocoapods/command.rb:52:in `run'
    /Users/zxk/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.0.beta.2/bin/pod:55:in `<top (required)>'
    /Users/zxk/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `load'
    /Users/zxk/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `<main>'
    /Users/zxk/.rvm/gems/ruby-2.4.1@global/bin/ruby_executable_hooks:24:in `eval'
    /Users/zxk/.rvm/gems/ruby-2.4.1@global/bin/ruby_executable_hooks:24:in `<main>'

Error running pod install

**Comment by Sh1d0w** [comment]
You are using `custom_multi_image_picker`, this is not maintained by me. My plugin is called `multi_image_picker`. See [here](https://pub.dartlang.org/packages/multi_image_picker#-installing-tab-) how to install it.
