### ISSUE TITLE
The method 'releaseThumb' isn't defined for the class 'Asset'.

### ISSUE THREAD

**Issue by kostasoft** [Sh1d0w/multi_image_picker#123]
**Bug Report**

`multi_image_picker` version: 4.1.2

**Describe the bug**

After the update does not find this method ('releaseThumb'). How now to release a resource?

**Comment by Sh1d0w** [comment]
When you update, or before that always read the changelog https://github.com/Sh1d0w/multi_image_picker/blob/master/CHANGELOG.md

This method was removed.
