### ISSUE TITLE
Ability to change color of the back button

### ISSUE THREAD

**Issue by ImaginationRoom** [Sh1d0w/multi_image_picker#124]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Sh1d0w** [comment]
Please open a feature request in the Android plugin repo that I am using and link this issue there https://github.com/sangcomz/FishBun 

If it gets implemented I will add support for it here.

**Comment by liuchuancong** [comment]
![image](https://user-images.githubusercontent.com/36957912/57746118-51f28900-7702-11e9-830b-e50b6f22c927.png)
![image](https://user-images.githubusercontent.com/36957912/57746140-62a2ff00-7702-11e9-88fd-b382f7967f55.png)

**Comment by Sh1d0w** [comment]
Hi, this has been implemented in version 4.4.0

New options are available in the MaterialOptions to set back and ok buttons, which should exists as drawables in the project.
