### ISSUE TITLE
android crash

### ISSUE THREAD

**Issue by vici-5423** [Sh1d0w/multi_image_picker#125]
**Bug Report**

`multi_image_picker` version: 4.1.2

Is it happening on Android: Yes

Is it happening on iOS: No

```
 [✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (3 available)

• No issues found!
```

**Describe the bug**

Add this plugin to pubspec.yaml, the Android app crashes and doesn't start, iOS works fine.

**Comment by Sh1d0w** [comment]
Did you migrate your project to AndroidX as described in the docs?

If yes, then please run `adb logcat` in separate terminal tab then run the app and provide the logs here so we can see what is the actual error.
