### ISSUE TITLE
ByteData returned as File

### ISSUE THREAD

**Issue by AlexVincent525** [Sh1d0w/multi_image_picker#128]
Hi there! As I use this plugin for the first time with 2 hours experience, I have a request for this plugin.

**[Issue]**
`requestOriginal()` return ByteData instead of File.

**[Details]**
Upload assets in document uses `http` to request upload. But if I want to migrate to `dio` with `FormData`, it required `File` instance.

**[Expectation]**
`requestOriginal()` return ByteData instead of File, or it can be choose by user.

**Comment by Sh1d0w** [comment]
According to the [Dio documentation](https://github.com/flutterchina/dio) you can provide either File or ByteData, I see no problem with this. This plugin would not return files, reasons for the are stated in the [FAQ](https://sh1d0w.github.io/multi_image_picker/#/faq) section.

**Comment by AlexVincent525** [comment]
@Sh1d0w Thanks for your quick reply, and sorry for my mistake in reading the document. :(

But I have another question to ask:
Using `assets.name` to get image's name, sometimes it return a complete filename like `5b629bd3e7bce75e1ab2b5b3.jpg`, but some of them return `5b629bd3e7bce75e1ab2b5b3`. How this happened?

**Comment by Sh1d0w** [comment]
Please open a bug report with all relevant info - OS, plugin version, is it regular gallery image or taken with the camera, etc and I will investigate.

Thanks.
