### ISSUE TITLE
Asset's name not equals to full filename sometime

### ISSUE THREAD

**Issue by AlexVincent525** [Sh1d0w/multi_image_picker#129]
**Bug Report**
`multi_image_picker` version: 4.2.0

Is it happening on Android: Yes

Is it happening on iOS: Not tested yet.

```
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.437], locale zh-CN)
    • Flutter version 1.2.1 at H:\Android\flutter
    • Framework revision 8661d8aecd (9 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\AlexV\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (1 available)
    • ONEPLUS A3000 • 78c66f41 • android-arm64 • Android 8.0.0 (API 26)
```

**Describe the bug**
After image picked from this plugin, `print(assets.name)` sometimes return full filename but sometimes not.
Such as `2018-10-13 02.07.15 2.jpg` and `Screenshot_20190417-172256.jpg` is full filename. And `I/flutter ( 3963): 5b629bd3e7bce75e1ab2b5b3` is filename without extension's name.

**Comment by Sh1d0w** [comment]
@AlexVincent525 I am not able to reproduce this problem. Can you give me more context how to reproduce it. What device you are testing on, which Android version? Also can you provide example image that I can try?

For name resolution I am following the official Android docs [here](https://developer.android.com/training/secure-file-sharing/retrieve-info.html#RetrieveFileInfo). It properly returns file names for both images on the device or taken with the camera.

**Comment by AlexVincent525** [comment]
> @AlexVincent525 I am not able to reproduce this problem. Can you give me more context how to reproduce it. What device you are testing on, which Android version? Also can you provide example image that I can try?
> 
> For name resolution I am following the official Android docs [here](https://developer.android.com/training/secure-file-sharing/retrieve-info.html#RetrieveFileInfo). It properly returns file names for both images on the device or taken with the camera.

As my flutter doctor displayed, I'm using OnePlus 3 with Android 8.0.0.
Images can be download in here: [http://project.alexv525.com/temp/](http://project.alexv525.com/temp/)

**Comment by AlexVincent525** [comment]
@Sh1d0w Is there any progress with this issue? 😄

**Comment by AlexVincent525** [comment]
@Sh1d0w And is this issue been solved?

**Comment by Sh1d0w** [comment]
@AlexVincent525 Not yet, I haven't had a chance to work on this yet.

Currently on Android I am using the ContentProvider to obtain the file name as it is suggested in the docs. After a short investigation it turned out it is expected not always the metadata stored in Android content provider to have the file extension, so this is expected behaviour.

To make it consistent I could check and append the extension. Currently the plugin converts all picked images to JPEG for compatibility reasons, so this should not be hard task. 

Pull requests are also welcome in the meantime.

**Comment by AlexVincent525** [comment]
> @AlexVincent525 Not yet, I haven't had a chance to work on this yet as I am swamped at my regular job currently.
> 
> Currently on Android I am using the ContentProvider to obtain the file name as it is suggested in the docs. After a short investigation it turned out it is expected not always the metadata stored in Android content provider to have the file extension, so this is expected behaviour.
> 
> To make it consistent I could check and append the extension. Currently the plugin converts all picked images to JPEG for compatibility reasons, so this should not be hard task.
> 
> Pull requests are also welcome in the meantime.

I just add `.jpg` after every filename :sad:.This is a pretty bad method handling this.

**Comment by Sh1d0w** [comment]
The plugin now allows you to access the file path of the picked images directly as well as the byte data. You can try and get the file name from the path.

https://github.com/Sh1d0w/multi_image_picker/blob/master/CHANGELOG.md#2019-08-12
