### ISSUE TITLE
Image resizing function

### ISSUE THREAD

**Issue by shpy2001** [Sh1d0w/multi_image_picker#130]
Can you provide an image resizing function that still retains the aspect ratio? With image compression option?

Thank you so much.

**Comment by AlexVincent525** [comment]
`flutter_native_image` [here](https://github.com/btastic/flutter_native_image) can do this with `File` instance, `image` [here](https://pub.dev/packages/image) can do this with `Image` instance, choose one of them if you want.

**Comment by jeffaknine** [comment]
@AlexVincent525 Hi, in order to do that we would have to convert the Asset file into a File. Is there a way to do that ?

**Comment by Sh1d0w** [comment]
@jeffaknine Latest version of the plugin now allows you to access the file path of the picked images, so you can easily use it as a File instance if you wish.

I am going to close this, as it is not something that this plugin should be responsible to do.

**Comment by temirfe** [comment]
@Sh1d0w "..not something that this plugin should be responsible to do". Are you serious? This plugin is used mainly to upload images to server, and most images on people's phones are taken from camera which weights around 3MB, so resizing it before sending to server is done most of the time. The method `getThumbByteData` [doesn't work well](https://github.com/Sh1d0w/multi_image_picker/issues/391), even if it did work, it just crops, not resizes. Resizing is the direct responsibility of this plugin.

**Comment by Sh1d0w** [comment]
The feel free to open a PR that introduces such functionality, you know it is open source so if you need something nothing stops you to implement it and contribute to the community.

**Comment by temirfe** [comment]
I'm not good enough for it yet, but you could easily do it and I'm sure many people would appreciate. It's like you've built a mansion but found unnecessary to provide electricity ;)

**Comment by AlexVincent525** [comment]
> Are you serious? This plugin is used mainly to upload images to server

Sometimes you need to be focus about what is the main idea of the package. In here I think it's **"Picker"** , not a uploader/cropper/saver.
