### ISSUE TITLE
AssetThumb widget cannot find and use

### ISSUE THREAD

**Issue by swingywc** [Sh1d0w/multi_image_picker#131]
**Bug Report**

`multi_image_picker` version: ^4.2.0

Is it happening on Android: I don't know

Is it happening on iOS: Yes

```
 <!-- run `flutter doctor` and paste the output here: -->
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.13.6 17G65, locale zh-Hant-HK)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.1)
[✓] Connected device (1 available)

• No issues found!

**Describe the bug**

Hi there. I just copy the code from the "Basic Usage" guide, trying to run and see if it's work.
The following error show:

    The method 'AssetThumb' isn't defined for the class 'XXXXXXPageState';

Please help. Thanks.

**Comment by Sh1d0w** [comment]
Please run the code in the example folder of this repo it is working just fine.
