### ISSUE TITLE
How can i upload image after pick ?

### ISSUE THREAD

**Issue by minh98** [Sh1d0w/multi_image_picker#133]
I want to upload image to server but picker return list of Asset. I don't know way to up it to server/api

**Comment by Sh1d0w** [comment]
Please read the documentation it is explained there.

**Comment by minh98** [comment]
I don't see any way to use them ?
I want upload them to server by http.post

**Comment by Sh1d0w** [comment]
https://sh1d0w.github.io/multi_image_picker/#/upload

**Comment by minh98** [comment]
oh thanks.
sorry my mistake
