### ISSUE TITLE
Crash when build on android 6.0

### ISSUE THREAD

**Issue by minh98** [Sh1d0w/multi_image_picker#134]
![58377839_418314289001149_5770446518188244992_n](https://user-images.githubusercontent.com/26597466/56864599-94238700-69ee-11e9-94e5-c2bf6c51b9b9.png)
![58570908_2330342717022675_769012038922928128_n](https://user-images.githubusercontent.com/26597466/56864600-94bc1d80-69ee-11e9-994a-a1a472ed2b96.png)
no console log

**Comment by minh98** [comment]
same result with emulator 8.0

**Comment by Sh1d0w** [comment]
File provider was removed since version 3 of this plugin if you have it in your AndroidManifest you have to remove it. Also this plugin need your project migrated to AndroidX as described in the docs.

**Comment by minh98** [comment]
i was try replace minsdk of module app to 19 or repace minsdk of module picker image to 16 but same result . but run example fine

**Comment by minh98** [comment]
i was migrated to AndroidX . worked thanks :)
