### ISSUE TITLE
How do I change the text of the "done" button, such as "完成" or something?

### ISSUE THREAD

**Issue by pakyo-pan** [Sh1d0w/multi_image_picker#136]
![image](https://user-images.githubusercontent.com/13342613/57065915-6f385800-6cfd-11e9-983f-4eda940d6072.png)

**Comment by Sh1d0w** [comment]
The iOS plugin I am using uses system localisations for most of the stuff. For the done button you have  to follow this guide: https://medium.com/lean-localization/ios-localization-tutorial-938231f9f881

Then you can add "Done" = "完成";
