### ISSUE TITLE
#import <multi_image_picker / multi_image_picker-Swift.h> 

### ISSUE THREAD

**Issue by Upromise** [Sh1d0w/multi_image_picker#138]
=== BUILD TARGET multi_image_picker OF PROJECT Pods WITH CONFIGURATION Debug
    ===
    /Users/myuser/.pub-cache/hosted/pub.flutter-io.cn/multi_image_picker-2.4.11/
    ios/Classes/MultiImagePickerPlugin.m:2:9: fatal error:
    'multi_image_picker/multi_image_picker-Swift.h' file not found
    #import <multi_image_picker/multi_image_picker-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by Sh1d0w** [comment]
You are missing Swift Bridging header, please read the documentation how to create one.

**Comment by xuwankang** [comment]
same problem, i use multi_image_picker-4.3.1, # use_frameworks! in podfile,
![image](https://user-images.githubusercontent.com/19919380/57678538-fff72800-765b-11e9-8b66-6683e2396858.png)
i have Swift Bridging header already
