### ISSUE TITLE
选择图片上限的提示语句Selection full，怎么改成中文？

### ISSUE THREAD

**Issue by laiqitian** [Sh1d0w/multi_image_picker#139]

**Comment by Sh1d0w** [comment]
I don't speak your language, please open an issue in English, following the issue template.

**Comment by laiqitian** [comment]
How to change the picture cap prompt into Chinese?

**Comment by Iongtao** [comment]
i have the same problem

**Comment by Iongtao** [comment]
> i have the same problem

i got

**Comment by Sh1d0w** [comment]
Please read the documentation for this plugin, there is a section for localisation.

**Comment by yuexunshi** [comment]
> How to change the picture cap prompt into Chinese?

打开Xode “Runner” -> “info.plist”，添加一项“Localized resources can be mixed”，值设置为“yes”即可！
`但是done没有中文翻译，需要自己添加ios的国际化文件，在文件里写下翻译。"Done" = "确定";`
[ios国际化连接](https://www.jianshu.com/p/88c1b65e3ddb)
