### ISSUE TITLE
How to change the picture cap prompt into Chinese

### ISSUE THREAD

**Issue by laiqitian** [Sh1d0w/multi_image_picker#140]

**Comment by Sh1d0w** [comment]
What do you refer to with "picture cap prompt"? Can you provide screenshot and highlight the exact area?

**Comment by laiqitian** [comment]
![Uploading Inked360手机助手截图0508_14_06_01_LI.jpg…]()
How to change it into Chinese？

**Comment by laiqitian** [comment]
![图片](https://user-images.githubusercontent.com/37677923/57353815-50720f80-719c-11e9-94bd-568850437828.png)
How to change it into Chinese？

**Comment by Sh1d0w** [comment]
I've just added this to version 4.2.2. See the docs [here](https://sh1d0w.github.io/multi_image_picker/#/theming). There is new option called `selectionLimitReachedText`.

**Comment by laiqitian** [comment]
ok  thank you
