### ISSUE TITLE
The image is cut when uploading to the server

### ISSUE THREAD

**Issue by hahai96** [Sh1d0w/multi_image_picker#143]
**Bug Report**

multi_image_picker: ^4.2.2

Is it happening on Android,  iOS

```
 Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.5.8, on Microsoft Windows [Version 10.0.17134.706], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] Connected device (1 available)

• No issues found!
```

**Describe the bug**
I am trying to upload a photo to the server using frombytes (dio), I uploaded it successfully, but the uploaded image has been cropped. Is this a bug because I use get bytes or not?

```
FormData formData = FormData.from({"post_id": postId, "typeFile": "image"});
    List<UploadFileInfo> filesUp = List();
    for (int i = 0; i < assets.length; i++) {
      Asset asset = assets[i];
      ByteData byteData = await asset.requestOriginal();
      List<int> imageData = byteData.buffer.asUint8List();
      filesUp.add(UploadFileInfo.fromBytes(imageData, asset.name));
    }

    formData['files'] = filesUp;
```

![images 1](https://user-images.githubusercontent.com/23280338/57427254-54119f00-724d-11e9-9210-377a830d153b.jpg)
![904_1557377103195](https://user-images.githubusercontent.com/23280338/57427890-16624580-7250-11e9-82c1-d970de4fc120.jpg)

**Comment by Sh1d0w** [comment]
You can easily check if requestOriginal returns the full image. Just put it in an Image widget and render it in the app. If it appears full then you can try to use http library instead of dio (see example in the docs of this plugin) to see if the problem is not in Dio. Finally you can check if your server correctly handles the image upload and saves it.

**Comment by hahai96** [comment]
@Sh1d0w Thanks very much. Problems at our server.
