### ISSUE TITLE
How to convert image from Asset to File

### ISSUE THREAD

**Issue by JohnPang1204** [Sh1d0w/multi_image_picker#144]
Hi, Sh1dow. Is there any way to convert images from **Asset**  type to  **File** type? because i need to put images into Firebase Storage. Thank you for your helping.

**Comment by Sh1d0w** [comment]
Hi,

Please read the docs before using the plugin, it as all well described.

https://sh1d0w.github.io/multi_image_picker/#/upload?id=firebase
