### ISSUE TITLE
'multi_image_picker/multi_image_picker-Swift.h' file not found

### ISSUE THREAD

**Issue by xuwankang** [Sh1d0w/multi_image_picker#148]
**Bug Report**

`multi_image_picker` version: 4.3.1

Is it happening on Android: No

Is it happening on iOS: Yes

```
 Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale zh-Hans-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)

• No issues found!
kevindeMacBook-Pro:~ kevin$ 

```

**Describe the bug**

 === BUILD TARGET multi_image_picker OF PROJECT Pods WITH CONFIGURATION Release ===
    /Users/kevin/flutter/.pub-cache/hosted/pub.flutter-io.cn/multi_image_picker-4.3.1/ios/Classes/MultiImagePickerPlugin.m:2:9: fatal error:
    'multi_image_picker/multi_image_picker-Swift.h' file not found
    #import <multi_image_picker/multi_image_picker-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**i have follow the document ,but didnt work,still got this problem**

**Comment by Sh1d0w** [comment]
You need to create a Swift Bridging header as described in the docs. If you can, just recreate your project correctly with `flutter create -i swift myapp` and move your files.
