### ISSUE TITLE
Feature Request - Button/action for the camera

### ISSUE THREAD

**Issue by acidjazz** [Sh1d0w/multi_image_picker#15]
I'd love to use as an alternative to image_picker since it keeps [crashing](https://github.com/flutter/flutter/issues/17950) on Android, but I can't lose the functionality for the user to take a picture.  Is this possible?

**Comment by Sh1d0w** [comment]
Yes, it is absolutely possible, but I don't plan to implement it soon, as I don't have much free time currently and also I don't need it for my projects. PRs are welcome though, to enable this functionality, both libraries I use in the picker for Android and iOS supports it.

**Comment by acidjazz** [comment]
@Sh1d0w Thanks I'll give it a shot!

**Comment by Sh1d0w** [comment]
@acidjazz This is now available in version 2.2.40. More info how to enable it here: https://github.com/Sh1d0w/multi_image_picker#enable-camera-in-the-gallery
