### ISSUE TITLE
The photo taken by camera is forced to be landscape mode(Android only)

### ISSUE THREAD

**Issue by h19881103** [Sh1d0w/multi_image_picker#150]
**Bug Report**

`multi_image_picker` version: ^4.3.1

Is it happening on Android: Yes

Is it happening on iOS: No

```
[√] Flutter (Channel beta, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.706], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at D:\flutter
    • Framework revision 7a4c33425d (2 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\danny.hui\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (2 available)
    • POCOPHONE F1                 • 1aad3288      • android-arm64 • Android 8.1.0 (API 27)
    • Android SDK built for x86 64 • emulator-5554 • android-x64   • Android 7.1.1 (API 25) (emulator)

```

**Describe the bug**
The photo taken by camera is forced to be landscape mode.

To reproduce the issue, 

1) pickImages with enableCamera=true.
i.e. MultiImagePicker.pickImages(enableCamera: true);

2) choose taking photo by camera in the picker.

3) take a photo.

4) confirm to use that photo in the picker.

5) the photo is in landscape mode.

It seems to be an issue of the FishBun implementation.
https://github.com/Sh1d0w/multi_image_picker/blob/8e9c3cd529e0fad5125875061872054d7461551f/android/src/main/java/com/vitanov/multiimagepicker/MultiImagePickerPlugin.java#L601-L623

**Comment by Sh1d0w** [comment]
Just to confirm - is the image taken by the camera is landscape if you open it in the Android gallery, or the image returned by the image picker plugin and which you display in your flutter app is in landscape mode? Also from the info you have provided I see you have two devices - does this occur on both of them and if no on which of them?

**Comment by h19881103** [comment]
> 
> 
> Just to confirm - is the image taken by the camera is landscape if you open it in the Android gallery, or the image returned by the image picker plugin and which you display in your flutter app is in landscape mode? Also from the info you have provided I see you have two devices - does this occur on both of them and if no on which of them?

Hi Sh1d0w,

Thanks for getting back to me.

The image taken by the camera is not landscape if I open it in the Android gallery. 
The image returned by the image picker plugin is in landscape mode when it is just taken by the camera.
If we open the picker and select the image from Android gallery(not taking photo), it is also fine(not in landscape mode).

Both my android device and the emulator can reproduce the same issue. I think it is not related to the specific Android camera behaviuor.

Thanks!

**Comment by Sh1d0w** [comment]
On Android it is known that there is some inconsistency when we speak about orientation of photos taken by the camera - [see here](https://stackoverflow.com/questions/14066038/why-does-an-image-captured-using-camera-intent-gets-rotated-on-some-devices-on-a?answertab=votes#tab-top).

Currently in my plugin I check the image orientation based on the media store data, and rotate it so it can be properly displayed in the device [code](https://github.com/Sh1d0w/multi_image_picker/blob/master/android/src/main/java/com/vitanov/multiimagepicker/MultiImagePickerPlugin.java#L744). For some reason this does not seem to work on your device.

Will need to find a way to reproduce this when I have some time.

**Comment by brux88** [comment]
hi have the same problem

**Comment by minhdtb** [comment]
same issue here

**Comment by Sh1d0w** [comment]
Pull requests to fix this are welcome.

**Comment by shpy2001** [comment]
Hi, i have the same problem. 
More info is when reselect that image, it work well.

**Comment by Sh1d0w** [comment]
The plugin now allows you to access the file path of the picked images directly as well as the byte data. You can try with the file paths, they are returned "as is" without any transformations or compressions.

https://github.com/Sh1d0w/multi_image_picker/blob/master/CHANGELOG.md#2019-08-12
