### ISSUE TITLE
failed to merge the upload code. a detailed example could do magic

### ISSUE THREAD

**Issue by Leisser** [Sh1d0w/multi_image_picker#156]
import 'package:flutter/material.dart';
import 'dart:async';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/services.dart';
import 'package:multi_image_picker/multi_image_picker.dart';

class PageTwo extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<PageTwo> {
  List<Asset> images = List<Asset>();
  String _error;

  @override
  void initState() {
    super.initState();
  }

  Widget buildGridView() {
    return GridView.count(
      crossAxisCount: 3,
      children: List.generate(images.length, (index) {
        Asset asset = images[index];
        return AssetThumb(
          asset: asset,
          width: 300,
          height: 300,
        );
      }),
    );
  }

  Future<void> loadAssets() async {
    setState(() {
      images = List<Asset>();
    });

    List<Asset> resultList;
    String error;

    try {
      resultList = await MultiImagePicker.pickImages(
        maxImages: 300,
      );
    } on PlatformException catch (e) {
      error = e.message;
    }

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;

    setState(() {
      images = resultList;
      if (error == null) _error = 'No Error Dectected';
    });
  }

  Future saveImage(Asset asset) async {
    ByteData byteData = await asset.requestOriginal();
    List<int> imageData = byteData.buffer.asUint8List();
    StorageReference ref = FirebaseStorage.instance.ref().child("some_image_bame.jpg");
    StorageUploadTask uploadTask = ref.putData(imageData);

    return await (await uploadTask.onComplete).ref.getDownloadURL();
  }

@override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          title: const Text('Plugin example app'),
        ),
        body: Column(
          children: <Widget>[
            Center(child: Text('Error: $_error')),
            RaisedButton(
              child: Text("Pick images"),
              onPressed: loadAssets,
            ),
            images.length > 0
                ? RaisedButton(
              child: Text("Delete images"),
              onPressed: () => saveImage,
            )
                : Container(),
            Expanded(
              child: buildGridView(),
            )
          ],
        ),
      ),
    );
  }
}

**Comment by Sh1d0w** [comment]
Issues that does not follow the issue template are instantly closed.

**Comment by Leisser** [comment]
Am so sorry, was only requesting for some help as regards uploading the
images. You did give us guidelines through
https://sh1d0w.github.io/multi_image_picker thou I've failed to incorporate
the upload bit. Please help maybe by adding the upload part in the example
or just a page layout of both loading the assets and uploading them thanks.

**Comment by Leisser** [comment]
Am only requesting for a favour, and will be grateful. Thanks
