### ISSUE TITLE
Corrupted JPG images when uploading to Azure Blob Rest API 

### ISSUE THREAD

**Issue by ArcSoftware** [Sh1d0w/multi_image_picker#157]
When retrieving image data as instructed in the documentation via: 
```
 ByteData byteData = await _images[i].requestOriginal();
 List<int> imageData = byteData.buffer.asUint8List();
```
When inserted into a PUT request via Azure Blob API requirements, uploaded file does not contain any image information and can not be opened even when downloaded unless using Photoshop. 

Request:
```
    for(var i = 0; i < fileNames.length; i++) {
      print(fileNames[i]); 
      Uri uri = Uri.parse("https://<ServiceAccountHere>.blob.core.windows.net/<FolderHere>/" +
        fileNames[i] + <SAT Here>);
      MultipartRequest request = http.MultipartRequest("PUT", uri);
      request.headers['x-ms-blob-type'] = 'BlockBlob';
      request.headers['content-type'] = 'image/jpeg';

     ByteData byteData = await _images[i].requestOriginal();
     List<int> imageData = byteData.buffer.asUint8List();

     MultipartFile multipartFile = MultipartFile.fromBytes(
          'photo', imageData,
          filename: fileNames[i],
          contentType: MediaType("image", "jpg"),
      );

      request.files.add(multipartFile);

      var response = await request.send();
```

The same request, with the same image works just fine with Postman. The difference may lie in the fact that in Postman, you attach the image as a Binary??

![image](https://user-images.githubusercontent.com/22686980/58181178-4f031580-7c79-11e9-8201-ca66710034fd.png)

This is what I get when I view the image when downloaded: 
![image](https://user-images.githubusercontent.com/22686980/58181238-6d691100-7c79-11e9-9454-de4e51ee5f03.png)

Here is the image:
![2-2019051001240 (1)](https://user-images.githubusercontent.com/22686980/58181282-7fe34a80-7c79-11e9-819f-7d247fe62e93.jpg)

It has to be a one-liner fix here but if I can't solve it soon, I"m going to have to use a different image picker package.. Please help!

PS: I've tried uploading with http and dio with no change in result:
```
    Dio dio = new Dio(); 
      // var response = await dio.put(
      //   "https://<ServiceAccountHere>.blob.core.windows.net/<FolderHere>/" +
        fileNames[i] + <SAT Here>,
      //   data: Stream.fromIterable(imageData.map((e) => [e])),
      //   options: Options(
      //     headers: headers
      //   ),
      // );

    // var requestCall = await http.put(
    //  "https://<ServiceAccountHere>.blob.core.windows.net/<FolderHere>/" +
        fileNames[i] + <SAT Here>,
    //     headers: headers,
    //     body: new ByteStream.fromBytes(byteData.buffer.asInt8List())
    // );
```

**Comment by ArcSoftware** [comment]
@Sh1d0w

**Comment by Sh1d0w** [comment]
Your files object has the content type, no need to set it in the request, this is invalid. Remove the content type from the request and try again.

I am going to close this as this is not problem in the package, rather than your server / code.
