### ISSUE TITLE
build failed in IOS 

### ISSUE THREAD

**Issue by Huai-Dc** [Sh1d0w/multi_image_picker#158]
**Bug Report**

`multi_image_picker` version: 

Is it happening on Android: 

Is it happening on iOS: 

```
 <!-- run `flutter doctor` and paste the output here: -->
```

**Describe the bug**

Launching lib/main.dart on iPhone X in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `multi_image_picker` from `.symlinks/plugins/multi_image_picker/ios`

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "multi_image_picker":
      In Podfile:
        multi_image_picker (from `.symlinks/plugins/multi_image_picker/ios`)

    Specs satisfying the `multi_image_picker (from `.symlinks/plugins/multi_image_picker/ios`)` dependency were found, but they required a higher minimum deployment target.

    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/cocoapods-1.6.2/lib/cocoapods/resolver.rb:91:in `resolve'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/cocoapods-1.6.2/lib/cocoapods/installer/analyzer.rb:909:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/cocoapods-1.6.2/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/cocoapods-1.6.2/lib/cocoapods/installer/analyzer.rb:907:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/cocoapods-1.6.2/lib/cocoapods/installer/analyzer.rb:114:in `analyze'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:266:in `analyze'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:174:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/cocoapods-1.6.2/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:173:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:136:in `install!'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/cocoapods-1.6.2/lib/cocoapods/command/install.rb:48:in `run'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/cocoapods-1.6.2/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/gems/cocoapods-1.6.2/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.6.2/libexec/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone X.

**Comment by Sh1d0w** [comment]
As the error suggest you have lower deployment target than what the plugin requires. Set it to 9 in your podfile.
