### ISSUE TITLE
Add maxHeight and maxWidth feature like the image_picker plugin

### ISSUE THREAD

**Issue by rupert2133** [Sh1d0w/multi_image_picker#16]
` await ImagePicker.pickImage(source: source, maxHeight: 1000.0);`

**Comment by Sh1d0w** [comment]
Once the user selects the images from the gallery you get back array of Asset instances which represent those images. You can then call `requestThumbnail` method on those passing the desired width and height, please take a look at the example provided, to see how to use the library https://github.com/Sh1d0w/multi_image_picker/blob/master/example/lib/asset_view.dart#L26

**Comment by LSmint** [comment]
@Sh1d0w ,

By using the provided properties width or height in requestThumbnail,  the image will getting crop instead of resize in Android platform. Anyway to provide height and make width as optional value?

**Comment by Sh1d0w** [comment]
@LSmint There is an open feature request https://github.com/Sh1d0w/multi_image_picker/issues/130

Pull requests are also welcome.
