### ISSUE TITLE
ios bug

### ISSUE THREAD

**Issue by houqinzhe** [Sh1d0w/multi_image_picker#161]
The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
    Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 12.2'
    Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 12.2'
    Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 12.2'

**Comment by Sh1d0w** [comment]
Issues that does not follow the issue template are instantly closed.
