### ISSUE TITLE
iCloud photos will display white block when picker images

### ISSUE THREAD

**Issue by chenft** [Sh1d0w/multi_image_picker#163]
**Bug Report**

`multi_image_picker` version:  ^4.3.2

Is it happening on Android:  No

Is it happening on iOS:  Yes

```
 <!-- run `flutter doctor` and paste the output here: -->
```

**Describe the bug**

When people select photos,  iCloud's photos will display like a white block.But after selectd, it will display a really photo in AssetThumb.

**Comment by Sh1d0w** [comment]
Please report the issue in the iOS plugin repo that I am using

https://github.com/mikaoj/BSImagePicker

**Comment by chenft** [comment]
@Sh1d0w The BSImagePicker's author maybe has been solved this provlem. [https://github.com/mikaoj/BSImagePicker/issues/213#issuecomment-518284166](url)

**Comment by Sh1d0w** [comment]
@chenft I see the issue you’ve linked is still open? My plugin already uses the latest version of BSImagePicker which is 2.10.0

**Comment by chenft** [comment]
@chenft The author did not reply to me before，so I did not continue to pay attention to this issue. Thanks for your answer.

**Comment by chenft** [comment]
@Sh1d0w The author did not reply to me before，so I did not continue to pay attention to this issue. Thanks for your answer.

**Comment by malikdoksoz** [comment]
Before 6 hours ago, icloud problem and several more problems solved. Please update your library to BSImagePicker 2.10.2.

**Comment by Sh1d0w** [comment]
@malikdoksoz I've just release version 4.5.5 which has BSImagePicker 2.10.2
