### ISSUE TITLE
Run the error report on the android emulator

### ISSUE THREAD

**Issue by houqinzhe** [Sh1d0w/multi_image_picker#164]
**Bug Report**

`multi_image_picker` version: 4.3.3 

Is it happening on Android: Yes

Is it happening on iOS: 

```
 <!-- run `flutter doctor` and paste the output here: -->
```

**Describe the bug**

Didn't find class "com.sangcomz.fishbun.FishBunFileProvider

**Comment by Sh1d0w** [comment]
Make sure you are using latest version of the plugin and run `flutter clean` after than `flutter run`
