### ISSUE TITLE
Error ExifInterface.TAG_ISO_SPEED

### ISSUE THREAD

**Issue by brux88** [Sh1d0w/multi_image_picker#166]
FLUTTER DOCTGOR
[√] Flutter (Channel beta, v1.5.4-hotfix.2, on Microsoft Windows [Versione 10.0.17763.503], locale it-IT)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.34.0)
[√] VS Code, 32-bit edition (version 1.33.1)
[√] Connected device (2 available)

I had this mistake:
D:\Documents\flutter.pub-cache\hosted\pub.dartlang.org\multi_image_picker-2.3.31\android\src\main\java\com\vitanov\multiimagepicker\MultiImagePickerPlugin.java:313: error: cannot find symbol
ExifInterface.TAG_ISO_SPEED,
^
symbol: variable TAG_ISO_SPEED
location: class ExifInterface
1 error

THEN I ADDED :
 configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.group == 'com.android.support') {
        details.useVersion "28.0.3"
        }
      }
    }

FAILURE: Build failed with an exception.

MY GRADLE ANDROID:
```
`buildscript {
    repositories {
        // ...
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal
    }
    dependencies {
        // ...
        // OneSignal-Gradle-Plugin
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.1, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.brux88.cinturrino"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        // Enabling multidex support.
        multiDexEnabled true
    }
  /* signingConfigs {
        release {
            keyAlias localProperties['keyAlias']
            keyPassword localProperties['keyPassword']
            storeFile file(localProperties['storeFile'])
            storePassword localProperties['storePassword']
        }
    }*/
    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.google.firebase:firebase-core:16.0.1'
    compile 'com.android.support:multidex:1.0.0'
    configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.group == 'com.android.support') {
        details.useVersion "28.0.3"
        }
      }
    }
}

apply plugin: 'com.google.gms.google-services'
`

```
BUT NOW SHOW ME THIS ERROR:
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find com.android.support:multidex:28.0.3.
  Required by:
      project :app
> Could not find com.android.support:multidex:28.0.3.
  Required by:
      project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 41s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by Sh1d0w** [comment]
You are using very old version of the plugin, please update to the latest. You also need to migrate your project to Android X as described in the docs.

**Comment by brux88** [comment]
But i cant migrate to Android x beacause i use different plugin that it arent compatibile with Android x

**Comment by Sh1d0w** [comment]
Every Flutter plugin has migrated to Android X, if some plugin haven't migrated yet you should ask them to do.

I do not provide support for older versions, sorry.
