### ISSUE TITLE
Enable Camera Android

### ISSUE THREAD

**Issue by brux88** [Sh1d0w/multi_image_picker#168]
**Bug Report**

`multi_image_picker` version: 4.3.3

Is it happening on Android:  YES

Is it happening on iOS:  NO

```
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.34.0)
[√] VS Code, 32-bit edition (version 1.33.1)
[√] Connected device (1 available)
```

**Describe the bug**

on android even if I set enablcamera: true, I don't have the possibility to take more photos?

**Comment by Sh1d0w** [comment]
1 .Are you testing on real device or emulator?

2. Did you grant permissions when asked to the camera?

3. Camera tile is present only when you select an album, it is not present in the initial all albums view

4. Can you reproduce this when running the example app in this repo?

**Comment by brux88** [comment]
thanks, if I select the album I can take the photos, but it turns them around as soon as I take the photo. if, on the other hand, I close and return and take the photos I have just taken, I no longer turn them around and take them right

**Comment by Sh1d0w** [comment]
So everything with taking images is working fine then.

Regarding the orientation problem you can add a comment to the reported issue in the official image picker plugin for android that I am using here https://github.com/sangcomz/FishBun/issues/147
