### ISSUE TITLE
After taking a photo, I get the file type, how to convert it to an asset type

### ISSUE THREAD

**Issue by gaojuanjuan** [Sh1d0w/multi_image_picker#17]

**Comment by Sh1d0w** [comment]
Hi, I am not sure I understand the issue you have? You have to invoke the image picker, then the user have to select the photo from the gallery, which then will return an Asset class instance. Have you looked into the example folder, for example usage?

Currently the image picker does not support invoking camera and taking picture directly from the gallery, it is possible to be implemented as both libraries I use in the plugin support this, so if someone want to support this PRs are welcome.

**Comment by gaojuanjuan** [comment]
I am using the image_picker library to return that the image is a file type, but with your return is the asset type, I want to convert the file type to the asset type.

**Comment by Sh1d0w** [comment]
There is no way to convert it, the plugin internally does that when you pick image from it. Why are you using image_picker and multi_image_picker, instead of using only multi_image_picker?

**Comment by gaojuanjuan** [comment]
Because image_picker can take pictures with the camera

**Comment by gaojuanjuan** [comment]
Because image_picker can take photos with the camera, multi_image_picker can only select images from the album. Both of my functions require

**Comment by gaojuanjuan** [comment]
The path of the image selected by multi_image_picker is null, that is, the value of asset.path is null.

**Comment by gaojuanjuan** [comment]
I saw your source code. Did not pass the image path in Android native to flutter

**Comment by Sh1d0w** [comment]
@gaojuanjuan I will implement image picking in my plugin in the next few days. Will let you know once it is done.

Currently it is blocked by this issue in the iOS plugin I am using.

https://github.com/mikaoj/BSImagePicker/issues/191

Once this is resolved I will push an update.

Thanks you for using the library!

**Comment by gaojuanjuan** [comment]
I still have a problem, the value of the path field of the Asset entity class is null.
![image](https://user-images.githubusercontent.com/14133759/47846680-b0f64d80-de03-11e8-973b-0726a0eea428.png)

![image](https://user-images.githubusercontent.com/14133759/47846745-f155cb80-de03-11e8-85e7-2b36aee1b8e5.png)

I think I need to change the code of the red box above.

**Comment by gaojuanjuan** [comment]
> @gaojuanjuan I will implement image picking in my plugin in the next few days. Will let you know once it is done.
> 
> Currently it is blocked by this issue in the iOS plugin I am using.
> 
> [mikaoj/BSImagePicker#191](https://github.com/mikaoj/BSImagePicker/issues/191)
> 
> Once this is resolved I will push an update.
> 
> Thanks you for using the library!

I need the path of the image when I upload the image, but the path value in the asset class is null.

**Comment by Sh1d0w** [comment]
The plugin does not return file paths for now because of cross platform compatibility.

On android this will work, but on iOS it won't because from iOS 11 and above default file format for images is HEIC, and flutter currently does not support HEIC codec, thus if you try to put that image into Image widget it won't show.

I've opened an issue on flutter repo here https://github.com/flutter/flutter/issues/20522

Once it is fixed I may consider returning direct image paths, until then if you want this plugin to work both on android and iOS you should use the requestOriginal or requestThumb methods on the Asset class to obtain the image data, as shown in the example in this repo.

**Comment by Sh1d0w** [comment]
Once you obtain the image data, you can do whatever you like with it - display it in image widget or upload it anywhere.

**Comment by gaojuanjuan** [comment]
> Once you obtain the image data, you can do whatever you like with it - display it in image widget or upload it anywhere.

Oh, thank you very much, look forward to your update. Urgent need for camera function.

**Comment by gaojuanjuan** [comment]
Can you assign the path field of the entity class Asset?

**Comment by Sh1d0w** [comment]
Hi @gaojuanjuan , I've just released version 2.2.40, which allows you to enable camera in the gallery both on Android and iOS.

You can read how to enable it from the README here: https://github.com/Sh1d0w/multi_image_picker#enable-camera-in-the-gallery

**Comment by Sh1d0w** [comment]
Update: I've just published 2.2.41 which fixes a small error related to the example, please use this version instead
