### ISSUE TITLE
If you continue to take pictures, you can exceed the limit of maxImages.

### ISSUE THREAD

**Issue by pakyo-pan** [Sh1d0w/multi_image_picker#171]
**Bug Report**

`multi_image_picker` version: 4.3.3

Is it happening on Android: No

Is it happening on iOS: Yes

```
[✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.13.6 17G7024, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.34.0)
[!] Connected device
```

**Describe the bug**

I am sorry for my English.
code as  below:
```dart
List<Asset> _assets = await MultiImagePicker.pickImages(
  enableCamera: true,
  maxImages: 3,
 );
```
1. I set `maxImages: 3` and selected 3 photos
2. I continue to take photos
3. The number of photos already selected exceeds the limit of `maxImages`, and `maxImages` is invalid.

**Comment by Sh1d0w** [comment]
This is related to the native iOS image picker I am using in the plugin.

Please report the bug in the official repo and I am sure the mantainer will look into it

https://github.com/mikaoj/BSImagePicker
