### ISSUE TITLE
Can't delete camera permission

### ISSUE THREAD

**Issue by Nastya-Scherbakova** [Sh1d0w/multi_image_picker#173]
**Bug Report**

`multi_image_picker` version: 4.3.3

Is it happening on Android: Yes 

Is it happening on iOS: Yes

```
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.765], locale ru-UA)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.4)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.34.0)
[√] Connected device (1 available)
```
I don't use Android Studio.

I don't need to use camera, only multi-picking from gallery. And if I'll add this permission - I will need to create Privacy Policy in Google Play Console, I don't want to and I don't need to! Please, make this optional. I can't use this library because of that.

**Comment by Sh1d0w** [comment]
Since GDPR became mandatory, every app on the Google App Store must provide Privacy Policy no matter what features you use in your app. You can’t publish an app without providing Privacy Policy.

Either way, pull requests are welcome if you want to propose such change of behavior.
