### ISSUE TITLE
Take Picture without preview

### ISSUE THREAD

**Issue by brux88** [Sh1d0w/multi_image_picker#174]
hello meanwhile, congratulations for the plugin, excellent.
then I wanted to know is it possible to see to see the preview after I take the photo? that is, I would like to be able to take the picture and then directly select it without clicking on the screen where it says "retake" "ok". how it works a little whatsapp that I can take many photos without confirming

**Comment by Sh1d0w** [comment]
Hi,

currently it is not possible, you can open a feature request in the plugin repos that I am using

https://github.com/Sh1d0w/multi_image_picker#credits
