### ISSUE TITLE
How to get Asset from Network

### ISSUE THREAD

**Issue by jasonwenst** [Sh1d0w/multi_image_picker#175]
**Is your feature request related to a problem? Please describe.**
Since I upload picture to image server, I want to edit the images that uploaded, but I cant find a way to create Asset by network(a image url by image server).

**Describe the solution you'd like**
If there is an way to create Asset by URL in network

**Comment by Sh1d0w** [comment]
You don't need to create Assets for images coming from your network, you can edit those images directly?

Asset objects are created only by the library internally and represent an image resource on the phone.

**Comment by jasonwenst** [comment]
thank you ,I know how to do.

**Comment by tusharspol** [comment]
@jasonwenst - How did you resolved this issue ?

**Comment by darshitArkay** [comment]
I had the same scenario where images are uploaded to the server and now I want to edit those images, what's the solution to this? @jasonwenst

**Comment by Sh1d0w** [comment]
@darshitArkay You can simply create a wrapper class that accepts either Asset object or image link. You can then implement logic to properly display render them based on the image type in your gallery.
