### ISSUE TITLE
Asset identifier for iOS

### ISSUE THREAD

**Issue by GerGodfrey** [Sh1d0w/multi_image_picker#176]
I use the multi_image_picker  library for obtain the metadata of images.

I create a new Asset on Android all is fine if i put a **'file://' + filePath** in the property identifier but for iOS all is wrong with and without 'file://'  can you help me ? 

**filePath**
```
      extDir = await getApplicationDocumentsDirectory();
      dirPath = p.join(extDir.path,'img');
      await new Directory(dirPath).create(recursive: true).then( (Directory directory) {print(directory.path);} );
      filePath = p.join(dirPath,timestamp()+'.jpg');
```

**Asset**
```
          if(Platform.isIOS){
            assetR = new Asset(filePath,"Reescalada",224,224);
          }else{
            assetR = new Asset('file://'+filePath,"Reescalada",224,224);
          }
          ByteData bd224 = await assetR.requestThumbnail(224,224,quality: 100);
```

**Error**

> assetR = new Asset(filePath,"Reescalada",224,224);

thanks!

**Comment by Sh1d0w** [comment]
Asset class is meant to be created only by the plugin, not externally. On iOS the identifier is the PHAsset ID not a file path, it is different from Android.

The purpose of this library is to pick images from a gallery, the EXIF data is additional feature on the images picked, not meant to be used outside of it. If you use it only for this, I suggest to install a library that main purpose is to decode image metadata https://pub.dev/packages?q=exif
