### ISSUE TITLE
Bigger selection button of Gallery

### ISSUE THREAD

**Issue by LeandroMoura3** [Sh1d0w/multi_image_picker#178]
I'm having a hard time selecting images from the gallery. I want to tap the selection box, but I open the photo.

Could you put the option to increase the size of the selection circle? Or even the whole image being selection?

I think the size of the circle selection being 1/4 of the gallery image would be ideal.

Thanks for listening.

**Comment by Sh1d0w** [comment]
Please open this issue in the official Android plugin repo that I am using - FishBun. If the author implements this it will appear in this plugin as well.
