### ISSUE TITLE
fatal error: 'multi_image_picker/multi_image_picker-Swift.h' file not found

### ISSUE THREAD

**Issue by swanoofl** [Sh1d0w/multi_image_picker#179]
**Bug Report**

`multi_image_picker` version: 

Is it happening on Android: 

Is it happening on iOS: 

```
 <!-- run `flutter doctor` and paste the output here: -->
```

**Describe the bug**

**Comment by Sh1d0w** [comment]
Please read the documentation how to setup the plugin on iOS.
