### ISSUE TITLE
Swift 4.2  2.2.10  not compile 

### ISSUE THREAD

**Issue by rlbee** [Sh1d0w/multi_image_picker#18]
X code 10 
Swift 4.2 
new clear project with  multi_image_picker 2.2.10
PodFile
added 
use_frameworks!
 and
config.build_settings['SWIFT_VERSION'] = '4.2'

**flutter run** ->

> ...pub-cache/hosted/pub.dartlang.org/multi_image_picker-2.2.10/ios/Classes/SwiftMultiImagePickerPlugin.swift:63:48:
> 
> error: 'NSAttributedStringKey' has been renamed to 'NSAttributedString.Key'
>                         vc.selectionTextAttributes[NSAttributedStringKey.foregroundColor] = hexStringToUIColor(hex: selectionTextColor)

Podfile.lock 
`PODS:
  - BSGridCollectionViewLayout (1.2.2)
  - BSImagePicker (2.8.2):
    - BSGridCollectionViewLayout (= 1.2.2)
    - BSImageView (= 1.0.2)
  - BSImageView (1.0.2)
  - Flutter (1.0.0)
  - multi_image_picker (2.1.22):
    - BSImagePicker (~> 2.8.2)
    - Flutter`

**Comment by Sh1d0w** [comment]
Hi and thanks for reporting this issue. It have to be fixed now in version `2.2.30`, that I've just released.
