### ISSUE TITLE
gif display none on android

### ISSUE THREAD

**Issue by chenft** [Sh1d0w/multi_image_picker#180]
**Bug Report**

`multi_image_picker` version: 

Is it happening on Android:  Yes

Is it happening on iOS:  No

```
 <!-- run `flutter doctor` and paste the output here: -->
```

**Describe the bug**

Gif display none on android, after confirm selection, will crash.
This is crash message: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference

Something like don't support gif. But, how can I ignore gif images?

**Comment by Sh1d0w** [comment]
Version 4.3.4 should not show GIFs on Android.

**Comment by kunkaamd** [comment]
I see GIFs on v4.6.3 android. pls check again.
