### ISSUE TITLE
app crashes in start up when using version 4.x.x

### ISSUE THREAD

**Issue by mahmoudparandeh** [Sh1d0w/multi_image_picker#181]
**Bug Report**

`multi_image_picker` version: 4.x.x

Is it happening on Android: yes

Is it happening on iOS: i don't know

```
 [√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.18362.175], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] VS Code
[√] VS Code, 64-bit edition (version 1.35.0)
[√] Connected device (2 available)

```

**Describe the bug**

app crashes on startup when using this package on 4.x.x version.  in version 3.x.x apps launched but when calling imagePicker its crashed.

**Comment by Sh1d0w** [comment]
Did you migrate your project to AndroidX as described in the docs?

**Comment by mahmoudparandeh** [comment]
yes i think i migrate my project to android x.

**Comment by Sh1d0w** [comment]
Please open a terminal, run `adb logcat` then run you app on Android and paste the error you get in ADB here, so I can tell you what is the problem.

**Comment by mahmoudparandeh** [comment]
the log sows something like this:
`06-08 08:32:09.844 19205 19205 D AndroidRuntime: Shutting down VM
06-08 08:32:09.862 19205 19205 E AndroidRuntime: FATAL EXCEPTION: main
06-08 08:32:09.862 19205 19205 E AndroidRuntime: Process: ir.arkatech.tahator, PID: 19205
06-08 08:32:09.862 19205 19205 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.sangcomz.fishbun.FishBunFileProvider: java.lang.ClassNotFou
ndException: Didn't find class "com.sangcomz.fishbun.FishBunFileProvider" on path: DexPathList[[zip file "/data/app/ir.arkatech.tahator-Rw60PevBTtWBSJhzzg900Q==/ba
se.apk"],nativeLibraryDirectories=[/data/app/ir.arkatech.tahator-Rw60PevBTtWBSJhzzg900Q==/lib/arm64, /data/app/ir.arkatech.tahator-Rw60PevBTtWBSJhzzg900Q==/base.ap
k!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
06-08 08:32:09.862 19205 19205 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:6248)
06-08 08:32:09.862 19205 19205 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5811)
06-08 08:32:09.862 19205 19205 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5728)
06-08 08:32:09.862 19205 19205 E AndroidRuntime:        at android.app.ActivityThread.-wrap1(Unknown Source:0)
06-08 08:32:09.862 19205 19205 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1658)
06-08 08:32:09.862 19205 19205 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
06-08 08:32:09.862 19205 19205 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
06-08 08:32:09.862 19205 19205 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6500)
06-08 08:32:09.862 19205 19205 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-08 08:32:09.862 19205 19205 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
06-08 08:32:09.862 19205 19205 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
06-08 08:32:09.862 19205 19205 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sangcomz.fishbun.FishBunFileProvider" on path:
 DexPathList[[zip file "/data/app/ir.arkatech.tahator-Rw60PevBTtWBSJhzzg900Q==/base.apk"],nativeLibraryDirectories=[/data/app/ir.arkatech.tahator-Rw60PevBTtWBSJhzz
g900Q==/lib/arm64, /data/app/ir.arkatech.tahator-Rw60PevBTtWBSJhzzg900Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
06-08 08:32:09.862 19205 19205 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:126)
06-08 08:32:09.862 19205 19205 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
06-08 08:32:09.862 19205 19205 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
06-08 08:32:09.862 19205 19205 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:6233)
06-08 08:32:09.862 19205 19205 E AndroidRuntime:        ... 10 more
06-08 08:32:09.862 19205 19205 E AndroidRuntime:        Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/FileProvider;
06-08 08:32:09.862 19205 19205 E AndroidRuntime:                at java.lang.VMClassLoader.findLoadedClass(Native Method)
06-08 08:32:09.862 19205 19205 E AndroidRuntime:                at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
06-08 08:32:09.862 19205 19205 E AndroidRuntime:                at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
06-08 08:32:09.862 19205 19205 E AndroidRuntime:                ... 12 more
06-08 08:32:09.862 19205 19205 E AndroidRuntime:        Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on
 path: DexPathList[[zip file "/data/app/ir.arkatech.tahator-Rw60PevBTtWBSJhzzg900Q==/base.apk"],nativeLibraryDirectories=[/data/app/ir.arkatech.tahator-Rw60PevBTtW
BSJhzzg900Q==/lib/arm64, /data/app/ir.arkatech.tahator-Rw60PevBTtWBSJhzzg900Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
06-08 08:32:09.862 19205 19205 E AndroidRuntime:                at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:126)
06-08 08:32:09.862 19205 19205 E AndroidRuntime:                at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
06-08 08:32:09.862 19205 19205 E AndroidRuntime:                at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
06-08 08:32:09.862 19205 19205 E AndroidRuntime:                ... 15 more
06-08 08:32:09.881   930  3392 W ActivityManager:   Force finishing activity ir.arkatech.tahator/.MainActivity
`

**Comment by Sh1d0w** [comment]
This is because you haven't migrated your project to AndroidX properly. Please folow the official instructions form google https://developer.android.com/jetpack/androidx/migrate
