### ISSUE TITLE
The version 4.3.4 don't filter gif photo successed on android

### ISSUE THREAD

**Issue by chenft** [Sh1d0w/multi_image_picker#183]
**Bug Report**

`multi_image_picker` version:  4.3.4

Is it happening on Android:  YES

Is it happening on iOS:  

```
 <!-- run `flutter doctor` and paste the output here: -->
```

**Describe the bug**

The version 4.3.4 don't fix the bug: [https://github.com/Sh1d0w/multi_image_picker/issues/180](url).
In this version, android mobile filter gif photos, but it also has some bugs.
![image](https://user-images.githubusercontent.com/17562266/59654090-3c6ff380-91c7-11e9-8e89-44c3ed4ee216.png)

On this folder has three gifs on bottom and display none.

![image](https://user-images.githubusercontent.com/17562266/59654158-8ce75100-91c7-11e9-9aa6-5289edf784d9.png)

And then I scroll the screen, gifs's area will display another photos, and these photos are repeated.These photos are are already displayed on the top, you can see the first photo.

**Comment by Sh1d0w** [comment]
Please open an issue in the official Android plugin repo that I am using, there is not much I can do about it here.

https://github.com/sangcomz/FishBun
