### ISSUE TITLE
How to convert path to Asset

### ISSUE THREAD

**Issue by zhangruiyu** [Sh1d0w/multi_image_picker#187]
I have a picture of another path, but it's file, how to show it with the graph selected by multi_image_picker

**Comment by Sh1d0w** [comment]
What do you mean by "graph"? Do you mean when you open the image selection page, you want this image to appear pre-selected?

**Comment by zhangruiyu** [comment]
> What do you mean by "graph"? Do you mean when you open the image selection page, you want this image to appear pre-selected?
I have an image path that comes in from somewhere else, of type File, and I want it to be displayed with the image that multi_image_picker has selected, which means I want to convert File to Asset

**Comment by Sh1d0w** [comment]
The Asset API is internal and I would not suggest to do it, as most of its parts come from the plugin channel for the given platform.

What I think would be the best case to implement this is for you to create a custom wrapper class for the image, which accepts either File or Asset and expose common methods to obtain the  image - for file by reading the file, and for the Asset by invoking requestOriginal or requestThumb.
