### ISSUE TITLE
Unable to send multiple images to server by hitting api once .

### ISSUE THREAD

**Issue by ADARSHAGNIHOTRI** [Sh1d0w/multi_image_picker#188]
**Is your feature request related to a problem? Please describe.**

My api body adopts multiple file objects at a time but the plugin returns  only Asset objects so there is compatibility error.
------>>>>
"DioError [DioErrorType.DEFAULT]: FileSystemException: Cannot retrieve length of file, path = '����"
**Describe the solution you'd like**
Can you please tell me how to change Asset object to file object.

**Describe alternatives you've considered**

**Additional context**
Map<String, String> _headers = {"Authorization": "Token " + token};

      List<FormData> formData=[];
      //formData.
      for(int i=0;i<_listOfassetObjects.length;i++){
        byteData= await listOfassetObjects[0].requestOriginal();
        formData.add(FormData.from({
          "image_file":new UploadFileInfo(File.fromRawPath(_byteData.buffer.asUint8List()), "${DateTime.now().toString()}.jpg"),
          //"image_file": file,
        }));
      }
      dio.options.headers.addAll(_headers);
      var response =
          await dio.post(RestDatasource.IMAGE_UPLOAD_URL2, data: formData).timeout(const Duration(seconds: 90) );

      if (response.statusCode == 200) {
        _view.onUpdateImageSuccess(response.data);
        print("Image Upload response=${response}");
      }

**Comment by Sh1d0w** [comment]
Read the documentation, there is example there is an example how to upload files.
