### ISSUE TITLE
Getting file size

### ISSUE THREAD

**Issue by veenatic** [Sh1d0w/multi_image_picker#191]
Is there a way to get the file size of image? I don't see any such property in the Asset class or Metadata class.

My use case is that i want to reduce the quality of the image only if it is greater than certain size.

**Comment by Sh1d0w** [comment]
Currently there is no exposed method to do this, I guess you can do this if you request the original image data, and then you can use elementSizeInBytes (https://api.dartlang.org/stable/2.4.0/dart-typed_data/ByteData-class.html) .
