### ISSUE TITLE
Permissions has to be added manually to the manifest.

### ISSUE THREAD

**Issue by saif97** [Sh1d0w/multi_image_picker#192]
I had the issue w/ the plug-in that even if I grant it w/ Storage Permission, it keeps saying that I've to grant the app the permission. The way I solved it was through giving Camera Permission in the Manifest. 
If that's the way it should be done, a written note in the plug-in README.md would be great. 
Those are the permissions: 
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

**Comment by Sh1d0w** [comment]
It is already explained in the plugin documentation which you should have read before using the plugin.

https://sh1d0w.github.io/multi_image_picker/#/initialsetup?id=android
