### ISSUE TITLE
Activity Problem

### ISSUE THREAD

**Issue by VitalikShcherbyna** [Sh1d0w/multi_image_picker#193]
**Bug Report**

`multi_image_picker` version: 4.3.5

Is it happening on Android: Yes 

```
[✓] Flutter
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Community Edition (version 2018.3.6)
[✓] VS Code (version 1.36.0)
[✓] Connected device (4 available)
```

**Describe the bug**
Thank you for perfect plugin, but I have some problem with Android, maybe you can suggest me something)

java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=2001, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.example.project/com.example.project.MainActivity}: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.project/com.sangcomz.fishbun.ui.album.AlbumActivity}; have you declared this activity in your AndroidManifest.xml

**Comment by Sh1d0w** [comment]
Hi. This is a strange error, as this activity is already declared in the Android plugin I am using

https://github.com/sangcomz/FishBun/blob/master/FishBun/src/main/AndroidManifest.xml#L17

It may be a cache problem, can you try to run `flutter clean` and run the project again. Or you could also try removing and adding the plugin again after you run the clean command.

**Comment by VitalikShcherbyna** [comment]
Yes, sure as you said it was a cache problem, thank you so much for the help 🙂
