### ISSUE TITLE
how to get file from asset

### ISSUE THREAD

**Issue by tranquoctrungcntt** [Sh1d0w/multi_image_picker#195]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Sh1d0w** [comment]
Please read the documentation before posting issues.

**Comment by tranquoctrungcntt** [comment]
quick question please, is "indentifier" is an uri ?

**Comment by Sh1d0w** [comment]
On Android it is the URI on iOS it is the PHAssetID. You should not use that directly, instead you should use the Asset methods requestOriginal and requestThumb to obtain the image data.

**Comment by tranquoctrungcntt** [comment]
thanks, let me try. because I am an Android Dev and new with Flutter

**Comment by tranquoctrungcntt** [comment]
the docs just shows how to get bytedata, but I need to get File from asset . could you please show me how ?

**Comment by Sh1d0w** [comment]
Why do you need a file? You can always save the byte data as tmp file.

**Comment by tranquoctrungcntt** [comment]
I need a file to upload with another library. this lib require a List of File as an input

**Comment by Sh1d0w** [comment]
There is section in documentation showing you how to do uploads.... please read whole docs.

**Comment by tranquoctrungcntt** [comment]
please, I read that section, but I would like to use another library to upload not http of dart
