### ISSUE TITLE
App is restarted without stracktrace when returning from image picker

### ISSUE THREAD

**Issue by Hawlitschek** [Sh1d0w/multi_image_picker#196]
**Bug Report**

`multi_image_picker` version: 4.3.5

Is it happening on Android: No

Is it happening on iOS: Yes

```
 [✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

```

**Describe the bug**

When returning from the image picker on iOS, if cancelled or images selected, the app gets reseted to the start screen. 
There is no error within the logs. 

On Android it works perfectly. 
Swift Support is enabled, swift version set to 4.2 

```
Future<void> loadAssets() async {
    List<Asset> resultList;

    try {
      resultList = await MultiImagePicker.pickImages(
        materialOptions: MaterialOptions(
          actionBarColor: '#D6E7D4',
          statusBarColor: '#A0AD9F',
          actionBarTitleColor: '#2B3725',
          lightStatusBar: false,
        ),
        maxImages: 300,
      );
    } on PlatformException catch (e) {
      print(e.message);
    }
    
    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;

    if (resultList.length != 0) {
      setState(() {
        _current = 0;
        _max = resultList.length;
        _uploading = true;
      });

      for (var asset in resultList) {
        ByteData byteData = await asset.requestOriginal();
        List<int> imageData = byteData.buffer.asUint8List();

        Response response =
            await Api().scopedImageUpload(imageData, asset.name);
        if (response.statusCode == 201) {
          print('Success');
        } else {
          print('Failed ${response.statusCode} ${response.data}');
        }

        setState(() {
          _current++;
        });
      }

      setState(() {
        _uploading = false;
      });
    }
  }
```

**Comment by Hawlitschek** [comment]
**UPDATE** For everyone having the same issue:

I was testing several things and it might be related to the use of ScopedModel. 
Somehow returning from the ImagePicker in iOS seems to kill the ScopedModel, resulting in a rest of the Widget tree until the origin scoped model. 

I changed to the provider pattern and it seems to work now. 
It sometimes resets the widget tree, too, but the provider seems to store the last state, only resulting in a short flicker.

**Comment by Sh1d0w** [comment]
Hi @Hawlitschek 

Basically when invoking the image picker Flutter launches a native activity, leaving the Flutter app activity on background (onPause event is triggered in Flutter Platform). When selection is made or you cancel the picker, the picker activity itself is closed, and you are returned back to you Flutter activity (onResume is triggered in Flutter Platform).

I don't know about you implementation, but it might be related to how you store state and navigate through your app, although I use the plugin in several production apps with no problems (one uses flutter redux for state management the other flutter_bloc).

Do you have an example repo where I can reproduce the problem? It might be bug in the new Flutter release or something that might worth reporting on the Flutter repo.

**Comment by Hawlitschek** [comment]
Hi,

I will try to provide you an example project tommorow or starting next week.

Greetings from Darmstadt
Adrian

**Comment by Sh1d0w** [comment]
Closing due of inactivity. If you still have a problem please provide the exact error you get.
