### ISSUE TITLE
ios ：Album crashes when scrolling

### ISSUE THREAD

**Issue by LoseRecall** [Sh1d0w/multi_image_picker#197]
**Bug Report**

`multi_image_picker` version: 

Is it happening on Android: 

Is it happening on iOS: 

```
 <!-- run `flutter doctor` and paste the output here: -->
```

**Describe the bug**

**Comment by Sh1d0w** [comment]
Issue does not follow issue template, thus it will be instantly closed.

**Comment by csiy** [comment]
Still collapse on ios
