### ISSUE TITLE
Images rotated when selecting multiple on latest version

### ISSUE THREAD

**Issue by mugikhan** [Sh1d0w/multi_image_picker#198]
**Bug Report**

`multi_image_picker` version: 4.3.5
Is it happening on Android: Yes

Is it happening on iOS: Untested

```
[✓] Flutter (Channel beta, v1.7.8+hotfix.2, on Mac OS X 10.14.5 18F203, locale en-ZA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[!] Android Studio (version 3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
[!] VS Code (version 1.34.0)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

```

**Describe the bug**

On version 4.3.5, when selecting multiple images they are rotated. When selecting one it is fine but when selecting multiple the images are rotated.

Using the exact same code on version 4.2.0 it is completely fine with selecting multiple images.

**Comment by Sh1d0w** [comment]
Hi, I can't seem to reproduce the problem. Can you please provide some images that I can test with and reproduce? I guess it is somehow related to the image rotation exif data, but need some way to reproduce it.

Thanks

**Comment by lifenautjoe** [comment]
I see this all the time in Android before even using this plugin. Their exif parsing is buggy.

**Comment by Sh1d0w** [comment]
@lifenautjoe Yeah I guess this is the case. I am using the MediaStore to retrieve the image orientation ([here](https://github.com/Sh1d0w/multi_image_picker/blob/master/android/src/main/java/com/vitanov/multiimagepicker/MultiImagePickerPlugin.java#L846)). The only way this could not work is if the MediaStore does not correctly return the image ExIF metadata.

Will have to do some research how to correctly obtain this, if the built in way is not working correctly. Generally image orientation on Android phones is a pain, as some device manufacturers make their cameras as landscape and others make them as portrait. If the image metadata is missing or incorrect it may show pictures rotated incorrectly ([more info here](https://stackoverflow.com/questions/14066038/why-does-an-image-captured-using-camera-intent-gets-rotated-on-some-devices-on-a)).

**Comment by Sh1d0w** [comment]
The plugin now allows you to access the file path of the picked images directly as well as the byte data. You can try with the file paths, they are returned "as is" without any transformations or compressions.

https://github.com/Sh1d0w/multi_image_picker/blob/master/CHANGELOG.md#2019-08-12
