### ISSUE TITLE
How to change the color theme of the picker? (Default is Blue)

### ISSUE THREAD

**Issue by rupert2133** [Sh1d0w/multi_image_picker#2]

**Comment by Sh1d0w** [comment]
Thanks for the opening the issue. 

This feature is actually in my todo list and will be implemented in the next few days.

**Comment by Sh1d0w** [comment]
@rupert2133 You can check now the [Theming and customization](https://github.com/Sh1d0w/multi_image_picker#theming-and-localization) section.

**Comment by rupert2133** [comment]
Hi again, after changing the picker theme color, the status bar color is still in blue. How can I change it?

**Comment by rupert2133** [comment]
Never mind, I fixed it by adding `<color name="zhihu_primary_dark">YOUR_COLOR</color>`
