### ISSUE TITLE
textOnNothingSelected map from FishBun to multi_image_picker

### ISSUE THREAD

**Issue by LeandroMoura3** [Sh1d0w/multi_image_picker#201]
Hello,

In FishBun have the option "textOnNothingSelected". Can you map it to your function MultiImagePicker like the "selectionLimitReachedText"? I need to code in your package to set it but I think that is important thing for translate.

Thanks.

**Comment by Sh1d0w** [comment]
Hi this has been implemented in version 4.4.0
