### ISSUE TITLE
Facing issue in post method contentType

### ISSUE THREAD

**Issue by nivethaKumar** [Sh1d0w/multi_image_picker#204]
![MediaType error](https://user-images.githubusercontent.com/34262141/61950203-c5e6c280-afca-11e9-83b3-a2b663e8d711.png)

**Comment by Sh1d0w** [comment]
You need to import the media type class to use it.

https://pub.dev/documentation/http_parser/latest/http_parser/MediaType-class.html

**Comment by nivethaKumar** [comment]
thank you
