### ISSUE TITLE
how to get bytedata

### ISSUE THREAD

**Issue by dsourav** [Sh1d0w/multi_image_picker#205]
**Bug Report**

`multi_image_picker` version: 

Is it happening on Android: yes

Is it happening on iOS: 

**Describe the bug**

here is my code:
   
    print(asset.requestThumbnail(120, 120).asStream().toString()); 
output is:  Instance of '_ControllerStream<ByteData>'

**Comment by Sh1d0w** [comment]
Please read the plugin documentation there is an example there.

**Comment by dsourav** [comment]
Ok I got this. Documentation describe everything we need. Thanks a lot
