### ISSUE TITLE
How do I convert the returned Asset to File because I need the selected path

### ISSUE THREAD

**Issue by yousaywhat** [Sh1d0w/multi_image_picker#206]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yousaywhat** [comment]
Can you provide a method to get the path, just don't call it on iOS platform

**Comment by yousaywhat** [comment]
This plugin is really great, but I need to upload multiple photos

**Comment by Sh1d0w** [comment]
Hi, please read the FAQ section in the documentation, it explains why the plugin does not return file paths.

Moreover on Android not all photos have file paths, this is expected behaviour on Android platform.

You can upload multiple photos still, see the documentation about image uploading.
