### ISSUE TITLE
need file not asset  to upload images in graphql

### ISSUE THREAD

**Issue by dsourav** [Sh1d0w/multi_image_picker#207]
**Bug Report**

`multi_image_picker` version: 

Is it happening on Android: yes

Is it happening on iOS: 

I am trying to upload image in GRAPHQL but it only supports file. I am getting bytedata which is not required. please help me.

**Comment by Sh1d0w** [comment]
In the readme there is an example how to attach images as files to a request. Also if you need a file for any other reason that I may not think of, you can always save the byte data to a file in the tmp dir.

I am going to close this, as there is no problem with the plugin itself.

**Comment by dsourav** [comment]
where is the readme give me the link
