### ISSUE TITLE
Missing space in title

### ISSUE THREAD

**Issue by deakjahn** [Sh1d0w/multi_image_picker#208]
**Bug Report**

`multi_image_picker` version: 4.3.6

Is it happening on Android: yes

Is it happening on iOS: n/a

**Describe the bug**

A space is missing between the title and the following "(n/n)" designator. Yes, we can inject it if we add the trailing space to `actionBarTitle` but this isn't the right solution. Besides, it also happens on the deeper album pages that we have no influence over.

**Comment by Sh1d0w** [comment]
Please open a bug in the Android picker plugin that I am using, I can't do anything about it.

https://github.com/sangcomz/FishBun

**Comment by deakjahn** [comment]
Well, there is something at https://github.com/sangcomz/FishBun/pull/154 but I can make head or tail of whether this is finally incorporated or not.

**Comment by Sh1d0w** [comment]
It says it is closed, not merged so it was not incorporated unfortunately. Please open an issue in the owner repo, he is very responsive.
