### ISSUE TITLE
When I clicked on the photo, I got an error.

### ISSUE THREAD

**Issue by gaojuanjuan** [Sh1d0w/multi_image_picker#21]
![image](https://user-images.githubusercontent.com/14133759/47990227-fa0b1200-e121-11e8-9fd3-a372d2a71729.png)

**Comment by Sh1d0w** [comment]
Hi, which version of the plugin are you using?

Did you follow the setup steps as discussed here https://github.com/Sh1d0w/multi_image_picker#enable-camera-in-the-gallery ?

**Comment by gaojuanjuan** [comment]
> Hi, which version of the plugin are you using?
> 
> Did you follow the setup steps as discussed here https://github.com/Sh1d0w/multi_image_picker#enable-camera-in-the-gallery ?

I set it up，
![image](https://user-images.githubusercontent.com/14133759/47991413-0e9cd980-e125-11e8-9948-c341a88e7f27.png)

**Comment by gaojuanjuan** [comment]
> > Hi, which version of the plugin are you using?
> > Did you follow the setup steps as discussed here https://github.com/Sh1d0w/multi_image_picker#enable-camera-in-the-gallery ?
> 
> I set it up

The package name has also been changed to the package name of my own application.
![image](https://user-images.githubusercontent.com/14133759/47991686-d9dd5200-e125-11e8-911b-865df7a633ba.png)

**Comment by gaojuanjuan** [comment]
Camera permissions are not dynamically applied when taking photos??（Need to be manually turned on in the phone's settings）

**Comment by gaojuanjuan** [comment]
> @gaojuanjuan The first time you invoke the image picker it will prompt you for permissions (this is handled by the Android plugin I am using). If you deny that, next time you invoke it it will not prompt you again.



> @gaojuanjuan The first time you invoke the image picker it will prompt you for permissions (this is handled by the Android plugin I am using). If you deny that, next time you invoke it it will not prompt you again.

What I want to say is that there is no dynamic application for android.permission.CAMERA when taking photos with the camera.

**Comment by Sh1d0w** [comment]
That's right, this should work without the permission, can you try to run the example from this repository on your device and see if you get the same error? Also on which Android version you get the error?

**Comment by gaojuanjuan** [comment]
> That's right, this should work without the permission, can you try to run the example from this repository on your device and see if you get the same error? Also on which Android version you get the error?

I am running your demo with Android 8.0 device. I will also report the following error.
![image](https://user-images.githubusercontent.com/14133759/48037471-56644500-e1a7-11e8-9a8c-82536f5f021e.png)

**Comment by Sh1d0w** [comment]
@gaojuanjuan Thanks for the info, I was able to reproduce. 

The error from your first post is now fixed in version 2.2.44 of the plugin.

Regarding the camera permission error - this will happen if you added `android.permission.CAMERA` to your `AndroidManifest.xml`. If you have it there you need to remove it (you only need those permission for the plugin https://github.com/Sh1d0w/multi_image_picker#android-1) and then it should work ok.

Let me know if that resolves it for you.

**Comment by gaojuanjuan** [comment]
> @gaojuanjuan Thanks for the info, I was able to reproduce.
> 
> The error from your first post is now fixed in version 2.2.44 of the plugin.
> 
> Regarding the camera permission error - this will happen if you added `android.permission.CAMERA` to your `AndroidManifest.xml`. If you have it there you need to remove it (you only need those permission for the plugin https://github.com/Sh1d0w/multi_image_picker#android-1) and then it should work ok.
> 
> Let me know if that resolves it for you.

About camera permissions error - I have removed android.permission.CAMERA from AndroidManifest.xml, or this will happen.
![image](https://user-images.githubusercontent.com/14133759/48045554-ba006980-e1cb-11e8-8c5d-e8ef9da5ca23.png)

**Comment by Sh1d0w** [comment]
@gaojuanjuan Can you paste how your `AndroidManifest.xml` looks, please?

**Comment by gaojuanjuan** [comment]
> @gaojuanjuan Can you paste how your `AndroidManifest.xml` looks, please?

![image](https://user-images.githubusercontent.com/14133759/48045836-e1a40180-e1cc-11e8-9402-fac3077914dd.png)
The part of the mosaic is the package name.

**Comment by Sh1d0w** [comment]
Seems fine, do you experience any other errors now? Are you able to take pictures with the camera?

**Comment by gaojuanjuan** [comment]
> Seems fine, do you experience any other errors now? Are you able to take pictures with the camera?

No other error, it is the error that the camera permission is rejected when taking a photo.

**Comment by gaojuanjuan** [comment]
> > Seems fine, do you experience any other errors now? Are you able to take pictures with the camera?
> 
> No other error, it is the error that the camera permission is rejected when taking a photo.

This is a complete error when clicking to take a photo.
![image](https://user-images.githubusercontent.com/14133759/48046349-13b66300-e1cf-11e8-8819-258734669f9e.png)

**Comment by gaojuanjuan** [comment]
> @gaojuanjuan This should be fixed in version 2.2.45, can you try it, please?
> 
> You can add now `<uses-permission android:name="android.permission.CAMERA" />` to your manifest, and the plugin will prompt you for permission if they are missing.
> 
> Let me know if you still experience an error.

No problem, perfect。

**Comment by Sh1d0w** [comment]
@gaojuanjuan 👌🍻

**Comment by gaojuanjuan** [comment]
But the path field of the Asset is still null.

**Comment by Sh1d0w** [comment]
@gaojuanjuan The plugin does not return paths, this property was leftover from a PR previously merged. I've now removed it in version 2.2.46.

You can read more about why here https://github.com/Sh1d0w/multi_image_picker#faq

You can also take a look in the example folder to see how you can use `requestThumb` or `requestOriginal` methods on the Asset class to obtain the image.
