### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by deakjahn** [Sh1d0w/multi_image_picker#210]
General ideas (I'm on Android, I never checked what the iOS side does). When we pick images and want to use them later, we call `requestOriginal()` and the trouble begins there. The performance is terrible. You completely decode the image, rotate if you see fit, this involves a complete re-creation, and then re-encode it again. Add the inevitable overhead of the native-Dart communication channel and this ends up terribly slow, up to probably several seconds per picture with today's higher resolution cameras. Not to mention that this changes (re-encodes and re-compresses) the picture even if it isn't required at all. Depending on what you do with the picture later, chances are the rotation will be handled correctly, anyway, by whatever processing you do (normal Android drawing routines do so), so we end up with a totally unnecessary and time consuming step.

Second. I'm torn between solutions because I like the straightforward, to-the-point approach of FishBun. But in the Xamarin app I'm porting to Flutter now, I used the Android stock picker that, since API 18, also supports multiple file picks. And has automatic support for all sources, Google Drive, Downloads and every other appropriate service the user has installed. Plus Recents.

I don't know if you know Xamarin to any extent, but for our discussion, it works just like Flutter in this case, you create similar plugins with common calling code and native logic that acts upon it. In my specific case, I simply passed a folder path to my native picker code and that, after the picking, having direct access to the images themselves by the internal path, simply copied all selected photos to that folder. This was very fast, just file operations, nothing about reading and interpreting bitmap data.

To go a bit further, I now copied your plugin code to a local copy and started to experiment. As a first, I added a `requestOriginalRaw()` call with the corresponding `GetRawImageTask` that does nothing but returns the bitmap stream as bytes, nothing more. This alone sped up the handling to about three times the previous speed, so it could be added as a no-brainer for anybody who doesn't want that auto-rotation.

All sources are at your disposal, if you're interested to see and discuss this, including the Xamarin two-pager. Even if you never did Xamarin, it's actually Android Java code in disguise, very easy to follow.

**Comment by Sh1d0w** [comment]
Hi and thanks for the suggestions.

Usually you don't need to call `requestOriginal` through your app, unless you want to upload / store the original raw image to a server or anywhere else. In the plugin docs I suggest to use `requestThumb` with appropriate for your UI sizes. Instead of sending 16 MB of date through the flutter channels you will send less than 700 KB which is fast.

The reasons of the current implementation are well explained in the [FAQ](https://sh1d0w.github.io/multi_image_picker/#/faq). Also there are some hidden caveats both on Android and iOS. On Android returning the raw bitmap stream does not always works as expected, sometimes images appear rotated. You can read more about this on internet, but what I've found is because of different phone manufacturers store image metadata for rotation differently.

On iOS however not all images reside locally on your phone. Also Flutter is missing some image drivers (see https://github.com/flutter/flutter/issues/20522) which makes every image picked on iOS 11+ to not be possible to be rendered in Flutter.

When we speak for cross OS compatibility there are some compromises you have to make to make it working flawlessly for everyone.

I am happy to discuss any possible improvements, but not for the price of cross compatibility. If the suggested improvements work ok both on iOS and Android on different devices I will be more than happy to accept such contributions :)

**Comment by deakjahn** [comment]
Yes, not all scenarios are the same, hence the suggestion of the addition of the raw call, not a replacement of existing functionality. In my case I need the original images because I need to let the user prepare something that will be printed in the end. This involves the original size and quality of the image.

Yes, I know the HEIC problem, I already faced it on Xamarin. iOS can be asked to provide a JPG even if it stores a HEIC.

I like FishBun's style as well. Still, what the stock offers and FishBun does not, are providers like Google Drive. So, I'm not yet sure what solution I'll end up with. Drive access might be more important in the end than pleasing UI, I'M afraid, but don't know yet.

**Comment by Sh1d0w** [comment]
@deakjahn That's interesting thanks. I did not know about iOS and that you could ask for JPEG, I will check it out. Also your suggestion regarding Skia seems reasonable, will need to find some time to play with it and see if it will actually bring some speed benefits.

**Comment by Sh1d0w** [comment]
The plugin now allows you to access the file path of the picked images as well as the byte data. Whatever works for you.

https://github.com/Sh1d0w/multi_image_picker/blob/master/CHANGELOG.md#2019-08-12

**Comment by deakjahn** [comment]
Well, before we disappear, here are the fragments to get the raw data, without rotation. Sorry, really no time to work this into a PR now but I hope it helps, anyway, Simply just more call to return a different data:
asset.dart:
===========

  Future<ByteData> requestOriginalRaw() {
    Completer completer = new Completer<ByteData>();
    BinaryMessages.setMessageHandler(_originalChannel, (ByteData message) {
      completer.complete(message);
      BinaryMessages.setMessageHandler(_originalChannel, null);
    });

    MultiImagePicker.requestOriginalRaw(_identifier);
    return completer.future;
  }

MultiImagePickerPlugin.java:
============================

    private static final String REQUEST_ORIGINAL_RAW = "requestOriginalRaw";

...

        } else if (REQUEST_ORIGINAL_RAW.equals(call.method)) {
            final String identifier = call.argument("identifier");
            GetRawImageTask task = new GetRawImageTask(this.activity, this.messenger, identifier);
            task.execute();
            finishWithSuccess();

...

    private static class GetRawImageTask extends AsyncTask<String, Void, ByteBuffer> {
        private final WeakReference<Activity> activityReference;

        final BinaryMessenger messenger;
        final String identifier;

        GetRawImageTask(Activity context, BinaryMessenger messenger, String identifier) {
            super();
            this.messenger = messenger;
            this.identifier = identifier;
            this.activityReference = new WeakReference<>(context);
        }

        @Override
        protected ByteBuffer doInBackground(String... strings) {
            final Uri uri = Uri.parse(this.identifier);
            byte[] bytesArray = null;

            try {
                // get a reference to the activity if it is still there
                Activity activity = activityReference.get();
                if (activity == null || activity.isFinishing()) return null;

                InputStream is = activity.getContentResolver().openInputStream(uri);
                bytesArray = readAllBytes(is);
                is.close();
            } catch (IOException e) {
                e.printStackTrace();
            }

            assert bytesArray != null;
            final ByteBuffer buffer = ByteBuffer.allocateDirect(bytesArray.length);
            buffer.put(bytesArray);
            return buffer;
        }

        @Override
        protected void onPostExecute(ByteBuffer buffer) {
            super.onPostExecute(buffer);
            this.messenger.send("multi_image_picker/image/" + this.identifier + ".original", buffer);
            buffer.clear();
        }
    }

    private static byte[] readAllBytes(InputStream inputStream) throws IOException {
        final int bufLen = 65536;
        byte[] buf = new byte[bufLen];
        int readLen;
        IOException exception = null;
    
        try {
            try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
                while ((readLen = inputStream.read(buf, 0, bufLen)) != -1)
                    outputStream.write(buf, 0, readLen);
                return outputStream.toByteArray();
            }
        } catch (IOException e) {
            exception = e;
            throw e;
        } finally {
            if (exception == null)
              inputStream.close();
            else try {
                inputStream.close();
            } catch (IOException e) {
                exception.addSuppressed(e);
            }
        }
    }

**Comment by deakjahn** [comment]
And I have my code fragments to read rotated images with Skia, probably faster because back then, I spent some time on making it as fast as possible. It's in Xamarin, so C# code, but calls the very same Skia function so it should be relatively straightforward to port. I can send it in e-mail if you want to take a look.
