### ISSUE TITLE
Wrong EXIF date formatting

### ISSUE THREAD

**Issue by deakjahn** [Sh1d0w/multi_image_picker#211]
**Bug Report**

`MultiImagePickerPlugin.java` parses the image date using this line:

    long dateTime = formatTime(TAG_DATETIME, "yy:mm:dd hh:mm:ss");

This is clearly wrong, months are `MM`, not `mm`, this makes any parsing attempt on the Flutter side blow up if the month happens to be outside 01-12. And if it doesn't blow up, it doesn't make sense. :-) In addition to that, as it can be read in your source, Exif seems to use four-digit years, not two.

Besides, although it would be a breaking change, it wasn't a wise decision to retain semicolons in the date part when sending up to Dart. That doesn't conform to any existing standard and `DateTime.parse()` in Dart doesn't parse it readily (https://api.dartlang.org/stable/2.4.0/dart-core/DateTime/parse.html). Considering that with the months and minutes mixed, nobody could have used it normally, anyway, I don't think a complete change to a supported, standard ISO/RFC format (practically, "yyyy-MM-dd hh:mm:ss") would mean trouble now.

Oops. You don't even send up the semicolon version of the date. You send up the milliseconds long converted to string. :-)

    if (dateTime != 0) result.put(ExifInterface.TAG_DATETIME, dateTime);

**Comment by Sh1d0w** [comment]
Hey, thanks for the report. I completely agree. Feel free to open a PR with the proposed fixes and I will merge them :)

**Comment by Sh1d0w** [comment]
Hi again,

as per specification the format that the exif data hold is with colons.

<img width="1601" alt="Screenshot 2019-08-06 at 8 29 37" src="https://user-images.githubusercontent.com/5074917/62514530-2924f000-b828-11e9-8e2b-ec77fac83bfd.png">

See [here](https://androidx.de/androidx/exifinterface/media/ExifInterface.html)

I've made a fix and now it will always return it as string with semicolons, on dart side you can parse it if needed to DateTime object.

**Comment by deakjahn** [comment]
Yep, that's why I do right now, you were quicker than me looking up how to make PRs. I use the `intl` package anyway, so it was easy to parse. But I don't know if it1s good to force the user to depend to ˙intl˙ just for this. Yes, Exif stores it that way, I know, still it's crazy. :-) That's all I did, you must have done the same:

    long dateTime = formatTime(TAG_DATETIME, "yyyy:MM:dd hh:mm:ss");
    if (dateTime != 0) result.put(ExifInterface.TAG_DATETIME, TAG_DATETIME);

But formatting dates on the Android side comes for free, you don't have to include and extra package like in Dart. So if you do nothing else but SimpleDateFormat it to ""yyyy-MM-dd hh:mm:ss" before sending it back, you do a great service to your users who can parse it with the simple `DateTime.parse()` on Dart instead of relying on `intl` and crafting their own pattern.

**Comment by Sh1d0w** [comment]
@deakjahn I am not convinced this package should do that. After all the ExIF data has an RFI specifying the format of the dates that the ExIF data holds.

So anyone requesting ExIF data will expect it to be in this format. Thats what my fix did - return the data as per ExIF specification.

What you do with the data after this is not a concern of this plugin - you can send it to server for processing or process and transform it in Dart - that's up to you.

The purpose of this plugin is to simply allow you to pick images and to obtain their meta data as it is.

Thanks again for your report.
