### ISSUE TITLE
I  follow the Initial setup,but App still getting crashed.

### ISSUE THREAD

**Issue by dreamknight0** [Sh1d0w/multi_image_picker#212]
**Bug Report**

`multi_image_picker` version:  multi_image_picker: ^4.3.6

Is it happening on iOS: Yes 

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)

• No issues found!
```

**Describe the bug**
I  follow the Initial setup,but App still getting crashed.
```
 === BUILD TARGET multi_image_picker OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/vincent/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.3.6/ios/Classes/MultiImagePickerPlugin.m:2:9: fatal error: 'multi_image_picker/multi_image_picker-Swift.h' file not found
    #import <multi_image_picker/multi_image_picker-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone Xʀ.
Exited (sigterm)
```
Add Strings in  Info.plist file:
![image](https://user-images.githubusercontent.com/15058363/62424462-4b701e00-b701-11e9-80d5-c46539eaac57.png)

Add platform :ios, '9.0' on top in ios/Podfile:
![image](https://user-images.githubusercontent.com/15058363/62424369-75751080-b700-11e9-9a39-49d38cda1504.png)

Create Bridging Header:
![image](https://user-images.githubusercontent.com/15058363/62424375-8291ff80-b700-11e9-910d-405c6fb75d56.png)

Please help,Thanks.

**Comment by Sh1d0w** [comment]
Try to recreate your project with Swift support.

Execute `flutter create -i swift .` in your project directory.

**Comment by dreamknight0** [comment]
> Try to recreate your project with Swift support.
> 
> Execute `flutter create -i swift .` in your project directory.

Sorry,it does not work.
![image](https://user-images.githubusercontent.com/15058363/62466380-c39f1800-b7c3-11e9-8fdb-d511c0d6314b.png)

**Comment by Sh1d0w** [comment]
The screenshot only shows an error that your app name is invalid, please fix it as per the suggestion.

**Comment by dreamknight0** [comment]
> The screenshot only shows an error that your app name is invalid, please fix it as per the suggestion.

Mate,I fixed  and run it,but it does not work
 
![image](https://user-images.githubusercontent.com/15058363/62473763-0537bf00-b7d4-11e9-8732-5636a4f5e882.png)
![image](https://user-images.githubusercontent.com/15058363/62473778-0e289080-b7d4-11e9-88b1-6441e0082907.png)

**Comment by dreamknight0** [comment]
1.Add platform :ios, '9.0' at the top of  ios/Podfile
2.Run flutter clean
3.In the ios folder run pod repo update
It works.
