### ISSUE TITLE
Error compiler

### ISSUE THREAD

**Issue by badrussamsi** [Sh1d0w/multi_image_picker#214]
**Bug Report**
Compiler message:
file:///D:/flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.4.0/lib/src/asset.dart:99:7: Error: Getter not found: 'defaultBinaryMessenger'.
      defaultBinaryMessenger.setMessageHandler(_thumbChannel, null);
      ^^^^^^^^^^^^^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.4.0/lib/src/asset.dart:96:5: Error: Getter not found: 'defaultBinaryMessenger'.
    defaultBinaryMessenger.setMessageHandler(_thumbChannel,
    ^^^^^^^^^^^^^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.4.0/lib/src/asset.dart:96:5: Error: The getter 'defaultBinaryMessenger' isn't defined for the class 'Asset'.
 - 'Asset' is from 'package:multi_image_picker/src/asset.dart' ('file:///D:/flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.4.0/lib/src/asset.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'defaultBinaryMessenger'.
    defaultBinaryMessenger.setMessageHandler(_thumbChannel,
    ^^^^^^^^^^^^^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.4.0/lib/src/asset.dart:99:7: Error: The getter 'defaultBinaryMessenger' isn't defined for the class 'Asset'.
 - 'Asset' is from 'package:multi_image_picker/src/asset.dart' ('file:///D:/flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.4.0/lib/src/asset.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'defaultBinaryMessenger'.
      defaultBinaryMessenger.setMessageHandler(_thumbChannel, null);
      ^^^^^^^^^^^^^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.4.0/lib/src/asset.dart:129:7: Error: Getter not found: 'defaultBinaryMessenger'.
      defaultBinaryMessenger.setMessageHandler(_originalChannel, null);
      ^^^^^^^^^^^^^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.4.0/lib/src/asset.dart:126:5: Error: Getter not found: 'defaultBinaryMessenger'.
    defaultBinaryMessenger.setMessageHandler(_originalChannel,
    ^^^^^^^^^^^^^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.4.0/lib/src/asset.dart:126:5: Error: The getter 'defaultBinaryMessenger' isn't defined for the class 'Asset'.
 - 'Asset' is from 'package:multi_image_picker/src/asset.dart' ('file:///D:/flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.4.0/lib/src/asset.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'defaultBinaryMessenger'.
    defaultBinaryMessenger.setMessageHandler(_originalChannel,
    ^^^^^^^^^^^^^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.4.0/lib/src/asset.dart:129:7: Error: The getter 'defaultBinaryMessenger' isn't defined for the class 'Asset'.
 - 'Asset' is from 'package:multi_image_picker/src/asset.dart' ('file:///D:/flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.4.0/lib/src/asset.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'defaultBinaryMessenger'.
      defaultBinaryMessenger.setMessageHandler(_originalChannel, null);
      ^^^^^^^^^^^^^^^^^^^^^^
Compiler failed on D:\AndroidProject\flutter_app\ukm_bersama\lib\main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

`multi_image_picker` version: 4.4.0

Is it happening on Android: Yes

```
D:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel dev, v1.5.8, on Microsoft Windows [Version 10.0.18362.239], locale en-ID)
    • Flutter version 1.5.8 at D:\flutter
    • Framework revision 0ba67226ee (3 months ago), 2019-04-24 17:18:28 -0700
    • Engine revision c63d1cf9c9
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 1f1592edce)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:/Users/DIDBSAMSI/AppData/Local/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:/Users/DIDBSAMSI/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.33.1)
    • VS Code at C:\Users\DIDBSAMSI\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.0.2

[√] Connected device (2 available)
    • Redmi 5A                  • 5668a4637d05  • android-arm64 • Android 7.1.2 (API 25)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 8.1.0 (API 27) (emulator)

• No issues found!
Process finished with exit code 0
```

**Describe the bug**

**Comment by Sh1d0w** [comment]
You need at least Flutter version Flutter 1.7.8, your current is 1.5.8.

It is suggested to upgrade to the latest stable version - 1.7.8
