### ISSUE TITLE
Images getting deleted from phone on MultiImagePicker.deleteImages()

### ISSUE THREAD

**Issue by HardikkMadaan** [Sh1d0w/multi_image_picker#215]
**Bug Report**

`multi_image_picker` version: ^4.4.1

Is it happening on Android: Yes

Is it happening on iOS: Not Tried

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Linux, locale en_IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
[✓] Connected device (1 available)

• No issues found!

```

**Describe the bug**

I have copied the exact same code given in the example folder of this repo. And when clicking on the Delete Images icon the MultiImagePicker.deleteImages() is called which not only removes the images from the app but also from the main directory . That is from the Internal Storage of the phone. Please check

**Comment by Sh1d0w** [comment]
This is the purpose of this method, it deletes the images from the storage.
