### ISSUE TITLE
add photo cropping After taking a photo by the camera

### ISSUE THREAD

**Issue by turkidkil** [Sh1d0w/multi_image_picker#216]
After taking a photo by the camera
please add photo cropping
See the example in the picture:

![Image of Yaktocat](https://flutterawesome.com/content/images/2019/07/Image-Cropper.jpg)

**Comment by Sh1d0w** [comment]
You can achieve this by using the crop plugin.

The purpose of multi_image_picker plugin is to allow picking multiple images, I don't want to bloat it with features that other plugins already have.
