### ISSUE TITLE
PlatformException(already_active, Image picker is already active, null)

### ISSUE THREAD

**Issue by lxk123** [Sh1d0w/multi_image_picker#217]
PlatformException(already_active, Image picker is already active, null),android flutter
 混编无法打开

**Comment by Sh1d0w** [comment]
Please follow the issue template and provide steps to reproduce.

Thanks.

**Comment by yuhaocan** [comment]
> PlatformException(already_active, Image picker is already active, null),android flutter
> 混编无法打开

I guess you had use flutter_boost result in this problem 
https://github.com/alibaba/flutter_boost/issues/263
