### ISSUE TITLE
Mark images as selected manually.

### ISSUE THREAD

**Issue by ajilo297** [Sh1d0w/multi_image_picker#219]
**Is your feature request related to a problem? Please describe.**
Is there a way I can mark some images I have downloaded as selected?

**Describe the solution you'd like**
Once I download some Images from the network, I want to show them as selected. Is it possible to make those images selected in the image picker if I can provide the path to the image?

**Comment by Sh1d0w** [comment]
Yes, you can pass list of pre selected assets before invoking the image picker, see the method signature here https://pub.dev/documentation/multi_image_picker/latest/multi_image_picker/MultiImagePicker/pickImages.html

It only supports passing image assets (which you previously picked), not file paths directly, as on iOS those have to be the PHAsset ids (they are handled by the Asset class).
