### ISSUE TITLE
Asset.path returning null

### ISSUE THREAD

**Issue by Udaychinthala** [Sh1d0w/multi_image_picker#22]
**Describe the bug**
when i selected a image and ASSET.PATH not returning original path of image BUT returning NULL

**To Reproduce**

```
<!-- Insert example code here, that will help to reproduce the bug -->
```

**Expected behavior**
i want the orginal paths of of images when i have selected them But it returning null, please rectify this error asap
**Screenshots**

**Flutter (please complete the following information):**
- Which version of `multi_image_picker` are you using: [e.g. 2.0.04]

```
 <!-- run `flutter doctor` and paste the output here: -->
```

**iOS (please complete the following information):**
 - Swift Version: [e.g. 4.0]

**Android (please complete the following information):**
 - Device: [e.g. Nexus 5]
 - OS: [e.g. Lollipop 5.1]

**Additional context**

**Comment by Sh1d0w** [comment]
This plugin does not return paths. Please use requestThumb or requestOriginal methods on the asset class to obtain the image data, as shown in the example app here https://github.com/Sh1d0w/multi_image_picker/blob/master/example/lib/asset_view.dart#L26

**Comment by Sh1d0w** [comment]
I've added FAQ section explaining why the plugin is and will not return file paths: https://github.com/Sh1d0w/multi_image_picker#faq
