### ISSUE TITLE
use camera crash

### ISSUE THREAD

**Issue by fcu-d0542397** [Sh1d0w/multi_image_picker#224]
in android 
E/AndroidRuntime( 4974): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
E/AndroidRuntime( 4974): 	at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:604)
E/AndroidRuntime( 4974): 	at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:578)
E/AndroidRuntime( 4974): 	at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:416)
E/AndroidRuntime( 4974): 	at com.zhihu.matisse.internal.utils.MediaStoreCompat.dispatchCaptureIntent(MediaStoreCompat.java:86)
E/AndroidRuntime( 4974): 	at com.zhihu.matisse.ui.MatisseActivity.capture(MatisseActivity.java:424)
E/AndroidRuntime( 4974): 	at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter$1.onClick(AlbumMediaAdapter.java:75)
E/AndroidRuntime( 4974): 	at android.view.View.performClick(View.java:6597)
E/AndroidRuntime( 4974): 	at android.view.View.performClickInternal(View.java:6574)
E/AndroidRuntime( 4974): 	at android.view.View.access$3100(View.java:778)
E/AndroidRuntime( 4974): 	at android.view.View$PerformClick.run(View.java:25885)
E/AndroidRuntime( 4974): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 4974): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 4974): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 4974): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime( 4974): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4974): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 4974): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process ( 4974): Sending signal. PID: 4974 SIG: 9
Lost connection to device.

**Comment by Sh1d0w** [comment]
You are using very outdated version of the plugin, this was fixed in most recent versions, please update.
