### ISSUE TITLE
OutOfMemory Exception

### ISSUE THREAD

**Issue by Yunus0or1** [Sh1d0w/multi_image_picker#225]
**Bug Report**

`multi_image_picker` version: 4.5.2

Is it happening on Android: Yes

Is it happening on iOS: Not tested yet

```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.239], locale en-IN)
    • Flutter version 1.7.8+hotfix.4 at C:\Flutter
    • Framework revision 20e59316b8 (5 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Yunus\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.37.1)
    • VS Code at C:\Users\Yunus\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.3.0

[√] Connected device (1 available)
    • SM G900H • 3208562a41745157 • android-arm • Android 6.0.1 (API 23)

• No issues found!


```

**Describe the bug**

Causing OutOfMemory error in weak devices like Samsung S5 when selecting even one image and loading it in GridView using the codes written in Documentation with a fresh new app. Same app is running smoothly on Samsung S9 loading multiple images at once. This is the error that is being highlighted by compiler :

`I/art     (27403): Starting a blocking GC Alloc
I/art     (27403): Starting a blocking GC Alloc
I/art     (27403): Alloc sticky concurrent mark sweep GC freed 345(14KB) AllocSpace objects, 0(0B) LOS objects, 16% free, 83MB/99MB, paused 214us total 5.280ms
I/art     (27403): Starting a blocking GC Alloc
I/art     (27403): Alloc partial concurrent mark sweep GC freed 2190(137KB) AllocSpace objects, 2(44KB) LOS objects, 16% free, 83MB/99MB, paused 264us total 9.247ms
I/art     (27403): Starting a blocking GC Alloc
I/art     (27403): Alloc concurrent mark sweep GC freed 135(18KB) AllocSpace objects, 0(0B) LOS objects, 16% free, 83MB/99MB, paused 233us total 15.725ms
I/art     (27403): Forcing collection of SoftReferences for 60MB allocation
I/art     (27403): Starting a blocking GC Alloc
I/art     (27403): Alloc concurrent mark sweep GC freed 2958(197KB) AllocSpace objects, 2(48KB) LOS objects, 16% free, 83MB/99MB, paused 216us total 11.453ms
W/art     (27403): Throwing OutOfMemoryError "Failed to allocate a 63489036 byte allocation with 16777216 free bytes and 44MB until OOM"
I/art     (27403): Starting a blocking GC Alloc
I/art     (27403): Starting a blocking GC Alloc
I/art     (27403): Starting a blocking GC Alloc
I/art     (27403): Alloc partial concurrent mark sweep GC freed 15(592B) AllocSpace objects, 0(0B) LOS objects, 16% free, 83MB/99MB, paused 258us total 8.110ms
I/art     (27403): Starting a blocking GC Alloc
I/art     (27403): Alloc concurrent mark sweep GC freed 2(64B) AllocSpace objects, 0(0B) LOS objects, 16% free, 83MB/99MB, paused 431us total 13.509ms
I/art     (27403): Forcing collection of SoftReferences for 60MB allocation
I/art     (27403): Starting a blocking GC Alloc
I/art     (27403): Alloc concurrent mark sweep GC freed 11(448B) AllocSpace objects, 0(0B) LOS objects, 16% free, 83MB/99MB, paused 266us total 13.752ms
W/art     (27403): Throwing OutOfMemoryError "Failed to allocate a 63489036 byte allocation with 16777216 free bytes and 44MB until OOM"
E/AndroidRuntime(27403): FATAL EXCEPTION: AsyncTask #4
E/AndroidRuntime(27403): Process: com.example.flutter_app_test, PID: 27403
E/AndroidRuntime(27403): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(27403): 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
E/AndroidRuntime(27403): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
E/AndroidRuntime(27403): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
E/AndroidRuntime(27403): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(27403): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
E/AndroidRuntime(27403): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/AndroidRuntime(27403): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/AndroidRuntime(27403): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(27403): Caused by: java.lang.OutOfMemoryError: Failed to allocate a 63489036 byte allocation with 16777216 free bytes and 44MB until OOM
E/AndroidRuntime(27403): 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
E/AndroidRuntime(27403): 	at android.graphics.Bitmap.nativeCreate(Native Method)
E/AndroidRuntime(27403): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:975)
E/AndroidRuntime(27403): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
E/AndroidRuntime(27403): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:877)
E/AndroidRuntime(27403): 	at com.vitanov.multiimagepicker.MultiImagePickerPlugin.getCorrectlyOrientedImage(MultiImagePickerPlugin.java:835)
E/AndroidRuntime(27403): 	at com.vitanov.multiimagepicker.MultiImagePickerPlugin.access$000(MultiImagePickerPlugin.java:70)
E/AndroidRuntime(27403): 	at com.vitanov.multiimagepicker.MultiImagePickerPlugin$GetThumbnailTask.doInBackground(MultiImagePickerPlugin.java:172)
E/AndroidRuntime(27403): 	at com.vitanov.multiimagepicker.MultiImagePickerPlugin$GetThumbnailTask.doInBackground(MultiImagePickerPlugin.java:144)
E/AndroidRuntime(27403): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
E/AndroidRuntime(27403): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(27403): 	... 4 more
D/libEGL  (27403): eglTerminate EGLDisplay = 0xbe9b9a04
W/art     (27403): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[21,tid=27418,Native,Thread*=0x9b2d2500,peer=0x12cf70a0,"Thread-12002"]
D/ViewRootImpl(27403): #3 mView = null
I/Process (27403): Sending signal. PID: 27403 SIG: 9
Lost connection to device.
`

**Comment by Sh1d0w** [comment]
@Yunus0or1 Thanks for the report. Since version 4.5.2 you can access the image path directly without requesting the image data. Can you try that? It should not cause OOM as it won't attempt to read the image, and you can display it in image widget with the file path directly. You need to call `await asset.filePath` to obtain it.

**Comment by Yunus0or1** [comment]
So you are suggesting me to take images, then not to show them using AssetThumb rather using the filePath and manually show them ?

**Comment by Sh1d0w** [comment]
Sorry I thought you wanted to request original image data, not thumbs. That seems strange, if you are requesting thumbs they should be very small and compressed. 

What Android version is this?
What thumb dimensions are you requesting? 
What is the size of the image you are trying to pick?

The thumbnail resizing is done via Android's Thumbnail Utils, so I am not sure there is anything that can be made regarding this.

**Comment by Yunus0or1** [comment]
Here is the full code and this is a fresh app. No other codes. Android Version : 6.0.1. Samsung S5

`import 'package:flutter/material.dart';
import 'dart:async';

import 'package:multi_image_picker/multi_image_picker.dart';

void main() => runApp(new MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  List<Asset> images = List<Asset>();
  String _error;

  @override
  void initState() {
    super.initState();
  }

  Widget buildGridView() {
    return GridView.count(
      crossAxisCount: 3,
      children: List.generate(images.length, (index) {
        Asset asset = images[index];
        return AssetThumb(
          asset: asset,
          width: 300,
          height: 300,
        );
      }),
    );
  }

  Future<void> loadAssets() async {
    setState(() {
      images = List<Asset>();
    });

    List<Asset> resultList;
    String error;


    try {
      resultList = await MultiImagePicker.pickImages(
        maxImages: 300,
      );
    } on Exception catch (e) {
      error = e.toString();
    }

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;

    setState(() {
      images = resultList;
      if (error == null) _error = 'No Error Dectected';
    });
  }

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          title: const Text('Plugin example app'),
        ),
        body: Column(
          children: <Widget>[
            Center(child: Text('Error: $_error')),
            RaisedButton(
              child: Text("Pick images"),
              onPressed: loadAssets,
            ),
            Expanded(
              child: buildGridView(),
            )
          ],
        ),
      ),
    );
  }
}`

**Comment by Sh1d0w** [comment]
@Yunus0or1 Can you try to reduce quality slightly to see if it will make any difference?

```
    return AssetThumb(
        asset: asset,
	width: 300,
	height: 300,
        quality: 40,
    );
```

**Comment by Yunus0or1** [comment]
Sorry sir, it crashed again. But same app runs smoothly in Samsung S9

**Comment by Yunus0or1** [comment]
One thing must  to be mentioned: if I do not use GridView then no crashes happen. So if I only select the images but not to demonstrate them in GridView then the app is okay

**Comment by Yunus0or1** [comment]
Solved the issue like this : Stored all images path into a List then rendered 

	  Widget buildGridView() {
		return GridView.count(
		  crossAxisCount: 3,
		  children: List.generate(image_paths.length, (index) {
			String path = image_paths[index];
			return Image.file(File(path));
		  }),
		);
	  }
