### ISSUE TITLE
Deselect all previously  selected images after  opening gallery again. 

### ISSUE THREAD

**Issue by MTayyibSarfraz** [Sh1d0w/multi_image_picker#227]
**Is your feature request related to a problem? Please describe.**
The scenario occurred when i deleted the images programatically and opened the gallery again.
the previously selected images were still selected ..

**Describe the solution you'd like**
There should also b an option to deselect the selected images programatically. 

**Describe alternatives you've considered**
Still looking for solution.

**Comment by Sh1d0w** [comment]
Hi. By default when you invoke the image picker every time it should start without any images selected. The only time you will see pre selected images is if you pass selectedImages argument.

Can you please check if this is the case? If not please provide example code.
