### ISSUE TITLE
Metadata (FormatException: Invalid double 333/1)

### ISSUE THREAD

**Issue by b-jan** [Sh1d0w/multi_image_picker#231]
**Bug Report**

`multi_image_picker` version: 4.5.2 (same issue for older versions)

Is it happening on Android: Yes
Is it happening on iOS: ?

```
[✓] Flutter (Channel dev, v1.8.2, on Linux, locale fr_FR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Community Edition (version 2017.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.33.1)
[✓] Connected device (1 available)
```

**Describe the bug**

I cannot get the metadata of any picture (taken on Google Pixel 2). I used the following code to request metadata:

```
    Metadata mainMetadata = await widget._assetList[0].metadata;
```

I think the issue is coming from a format error linked to GPSImgDirection line 849 ofmetadata.dart) because it says : 'Invalid double 333/1'. And it is the value I logged on it during my debug. And "333/1" is not an int or double variable. Can you change _castAsDouble to _castAsString of this vairable gpsImgDirection?

Changing this in the code is fixing the issue on my side.
I opened a Pull request : https://github.com/Sh1d0w/multi_image_picker/pull/230

Thank you :)

**Comment by Sh1d0w** [comment]
Thanks for the PR! Merged 👍
