### ISSUE TITLE
java.lang.NoSuchFieldError: No static field recycler_picker_list

### ISSUE THREAD

**Issue by longdw** [Sh1d0w/multi_image_picker#233]
**Bug Report**

`multi_image_picker` version: 4.5.2

Is it happening on Android: Yes

Is it happening on iOS: No

```
[✓] Flutter (Channel master, v1.9.1-pre.58, on Mac OS X 10.13.6 17G2307, locale
    zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.0)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.1)
[!] IntelliJ IDEA Community Edition (version 2018.2.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.36.1)
[✓] Connected device (2 available)
```

**Describe the bug**
I use this library like this:
```
MultiImagePicker. pickImages(enableCamera: true, maxImages: 5, selectedAssets: datas).then((List<Asset> assetList) {
                          if (assetList.length != 0) {
//                            contentWidgetCacheMap[ActionHeaderFlag.warranty] = null;
                            setState(() {
                              datas.clear();
                              datas.addAll(assetList);
                            });
                          }
                        });
```
It can show all folder's list, when I click the list item it throws follow errors:
```
java.lang.NoSuchFieldError: No static field recycler_picker_list of type I in class Lcom/sangcomz/fishbun/R$id; or its superclasses (declaration of 'com.sangcomz.fishbun.R$id' appears in /data/app/com.fotile.android.artificer.dev-zwr6MPGOQJ-rkrtXAVetZA==/base.apk)
        at com.sangcomz.fishbun.ui.picker.PickerActivity.initView(PickerActivity.java:193)
        at com.sangcomz.fishbun.ui.picker.PickerActivity.onCreate(PickerActivity.java:89)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
```

**Comment by Sh1d0w** [comment]
Hi, this error is related to the native Android picker I am using, please report it in the maintainer repo here https://github.com/sangcomz/FishBun . Once he fixes it I will update this plugin as well.

**Comment by longdw** [comment]
I download the  https://github.com/sangcomz/FishBun source, compile and run it, it's ok. don't have the error I have posted above.

**Comment by longdw** [comment]
@Sh1d0w

**Comment by Sh1d0w** [comment]
@longdw Hm, that's strange. The picker is already using the latest version of FishBun which is 0.11.0 . I see you are not using stable flutter version, can you try it on the stable channel and see if it still errors?

**Comment by longdw** [comment]
I switch channel to stable, still throws the error, so strange. I prepare to download your source and create a plugin myself.

**Comment by longdw** [comment]
I found that this error casued by [add flutter to exist app](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps). when I add flutter to my exist android project it throws these errors, but it works well when I run flutter project directly. I don't know why.

**Comment by Sh1d0w** [comment]
@longdw Unfortunately I can't help you with that. It reads that this is unstable yet

```
Since Flutter's "Add-to-App" functionality is in preview, the associated APIs and tooling are not stable and are subject to change.
```

So it could be anything - from bug in flutter, to mismatch of Android version or other thing.

The plugin works fine on projects created with Flutter, so I am going to close this issue. You can rise issue in Fishbun or Flutter repos asking for help regarding this.

**Comment by longdw** [comment]
I found answer! If android project contains the same resources as plugins, it will throws these errors. Such as my android project has a same file named `activity_photo_picker`, when I renamed this file, it works very well!
