### ISSUE TITLE
Building for iOS is not working

### ISSUE THREAD

**Issue by b-jan** [Sh1d0w/multi_image_picker#234]
**Bug Report**

`multi_image_picker` version: 4.5.2

Is it happening on Android: No
Is it happening on iOS: Yes

```
[✓] Flutter (Channel dev, v1.8.2, on Linux, locale fr_FR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Community Edition (version 2017.3)
✗ Flutter plugin not installed; this adds Flutter specific functionality.
✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.33.1)
[✓] Connected device (1 available)
```

**Describe the bug**

Here is the output of the building for iOS :
```
/usr/local/bin/flutter build ios --debug --no-codesign
```

![image](https://user-images.githubusercontent.com/24225949/63693996-b8189d00-c815-11e9-977e-585d61d7d2fe.png)

**Comment by Sh1d0w** [comment]
You can resolve this error by doing what the error suggest - rise the build target to iOS 10 which the plugin supports. See the example app https://github.com/Sh1d0w/multi_image_picker/blob/master/example/ios/Podfile#L2
