### ISSUE TITLE
Not support HEIC extension IOS IMAGE

### ISSUE THREAD

**Issue by SunryTeang** [Sh1d0w/multi_image_picker#235]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Sh1d0w** [comment]
The plugin itself does support picking HEIC images. However Flutter does not supports HEIC images yet, see this issue https://github.com/flutter/flutter/issues/20522

You can use `getByteData` do get the image data in JPEG format.
