### ISSUE TITLE
您好，我在ios上选择照片，照片的排序能不能按我保存到手机的时间排序呢

### ISSUE THREAD

**Issue by cy798919835** [Sh1d0w/multi_image_picker#236]
现在就是，一张上个月拍的照片，别人发给我，我保存到手机，我想选择它时，它不在最后的位置，我得一直翻到上个月的位置才能找到它。我想，我最后保存的就应该在最后面显示才对，并不是按照照片的拍照时间排序。

**Comment by Sh1d0w** [comment]
Please write in english, I don't speak your language.
