### ISSUE TITLE
Hello, I choose photos on ios. Can I sort photos according to the time I save them to my phone

### ISSUE THREAD

**Issue by cy798919835** [Sh1d0w/multi_image_picker#238]
Now here's a picture I took last month, someone sent it to me, I saved it to my phone, and when I want to select it, it's not in the last position, I have to go all the way to the last position to find it. I think the last one I saved should be displayed at the end, not sorted by the time the photos were taken.

**Comment by Sh1d0w** [comment]
Please open a feature request in the iOS plugin repo that I am using. If they agree and implement it I will add support here as well, otherwise I can't do anything

https://github.com/mikaoj/BSImagePicker
