### ISSUE TITLE
takePhotoIcon is always colored in system blue color

### ISSUE THREAD

**Issue by fralways** [Sh1d0w/multi_image_picker#239]
**Bug Report**

`multi_image_picker` version: 4.5.2

Is it happening on Android: didn't test

Is it happening on iOS: yes

**Describe the bug**

takePhotoIcon is always blue as is color of navigation bar buttons. Render as original doesn't help. Photo icon should not be tinted or at least should match "Render as..." option in asset catalog. 
Furthermore it would be great if we could set tint color. (blue color for navigation bar buttons is not matching my ui)

**Comment by Sh1d0w** [comment]
Thanks for the suggestion, PRs are also welcome :)
