### ISSUE TITLE
requestOriginal returning null

### ISSUE THREAD

**Issue by Udaychinthala** [Sh1d0w/multi_image_picker#24]

**Comment by Sh1d0w** [comment]
Please provide more info, code example or image you tried to pick, what is etc.

This method returns Future, so make sure you await the result.

**Comment by Udaychinthala** [comment]
List resultList;
    try {
      resultList = await MultiImagePicker.pickImages(
        maxImages: 300,
        enableCamera: true,
      );
    } on PlatformException catch (e) {
      print("Error in picking");
    }
    setState(() {
      a1s = resultList;
    });
    await a1s[0].requestOriginal(quality:100);
    data=a1s[0].imageData;
    if (null != a1s[0].thumbData) {
     c= Image.memory(
        a1s[0].thumbData.buffer.asUint8List(),
        gaplessPlayback: true,
      );
    }
    iwidth=a1s[0].originalWidth;
    print(c);

and here c is printing as null

**Comment by Sh1d0w** [comment]
You are requesting the original image data, but then you are assigning thumbData? you correctly has assigned imageData to data variable, just use this, e.g.:

```dart
ByteData data = await a1s[0].requestOriginal(quality:100);
c= Image.memory(
   data.buffer.asUint8List(),
   gaplessPlayback: true,
);
```

**Comment by Udaychinthala** [comment]
im facing trouble in sending the Image through http POST method ?

**Comment by Udaychinthala** [comment]
hi ,
appbar color is changing but Appbar text color("All Media") and backbutton color is not changing
i have tried everything but Its not changing
Can you plese Help!!

**Comment by Sh1d0w** [comment]
@Udaychinthala You can ask this question in the issue tracker of the plugin I am using for Android here https://github.com/zhihu/Matisse .
