### ISSUE TITLE
android.content.res.Resources$NotFoundException: Resource ID #0x0

### ISSUE THREAD

**Issue by wseng92** [Sh1d0w/multi_image_picker#240]
I clone this project and run, it works perfectly.
But when I implement this to my project (by moving all files to my project), I get this error when pick images button is clicked.

```
E/MethodChannel#multi_image_picker( 1055): Failed to handle method call
E/MethodChannel#multi_image_picker( 1055): android.content.res.Resources$NotFoundException: Resource ID #0x0
E/MethodChannel#multi_image_picker( 1055): 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:225)
E/MethodChannel#multi_image_picker( 1055): 	at android.content.res.Resources.getDrawableForDensity(Resources.java:887)
E/MethodChannel#multi_image_picker( 1055): 	at android.content.res.Resources.getDrawable(Resources.java:827)
E/MethodChannel#multi_image_picker( 1055): 	at android.content.Context.getDrawable(Context.java:626)
E/MethodChannel#multi_image_picker( 1055): 	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:463)
```

It seems like image not found ?

**Comment by Sh1d0w** [comment]
The e ample app uses custom image for the back button either copy the asset to your android folder or. Remove it from the options when invoking the picker to use the default one.

**Comment by tony123S** [comment]
Thanks, I have remove this line in loadAssets(), 
`
backButtonDrawable: "ic_back_arrow"`

but get error

```
E/MethodChannel#multi_image_picker( 1487): Failed to handle method call
E/MethodChannel#multi_image_picker( 1487): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
E/MethodChannel#multi_image_picker( 1487): 	at com.vitanov.multiimagepicker.MultiImagePickerPlugin.presentPicker(MultiImagePickerPlugin.java:617)

```

**Comment by tony123S** [comment]
> custom

Where is the asset folder? Sorry, I can't found.

**Comment by Sh1d0w** [comment]
@tony123S I've removed the arrow from the example app so it does not confuses new starters. It works just fine, I can't reproduce the error you are getting. You need to remove the whole line, not to pass null. See the example app again.

**Comment by tony123S** [comment]
Thanks, it works now after I remove it
