### ISSUE TITLE
MissingPluginException(No implementation found for method pickImages on channel multi_image_picker)

### ISSUE THREAD

**Issue by shinewanna** [Sh1d0w/multi_image_picker#242]
**Bug Report**

`multi_image_picker` version: 

Is it happening on Android: Yes

Is it happening on iOS: Not tested yet.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.37.1)
[✓] Connected device (1 available)

• No issues found!
exit code 0
```

**Describe the bug**
When i click pick image it doesn't go to gallery,i already added uses permission in manifest 
MissingPluginException(No implementation found for method pickImages on channel multi_image_picker)

**Comment by Sh1d0w** [comment]
This does not seem right, can you try removing the plugin, clearing Flutter cache and then add it again?

**Comment by shinewanna** [comment]
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than
version 19 declared in library [:multi_image_picker]
/home/jsh/android-studio-project/flutter-project/aungadsapp/build/multi_image_picker/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml
as the library might be using APIs not available in 16
Suggestion: use a compatible library with a minSdk of at most 16, or
increase this project's minSdk version to at least 19, or use
tools:overrideLibrary="com.vitanov.multiimagepicker" to force usage (may
lead to runtime failures) * Try: Run with --stacktrace option to get the
stack trace. Run with --info or --debug option to get more log output. Run
with --scan to get full insights.
Build Faliure

**Comment by shinewanna** [comment]
bro,i change the minSdk to 19 now it's work....
and one suggestion intialize you List<Asset> resultList = [];
else if you not select image that take me into null pointer exception....

**Comment by Sh1d0w** [comment]
Great glad you got it working :)
