### ISSUE TITLE
Customize the selected image displayed on Grid View.

### ISSUE THREAD

**Issue by tony123S** [Sh1d0w/multi_image_picker#245]
After selected image display on Grid View, can we customize the image ? Like adding a close button on the upper right of selected image?

Thanks.

**Comment by Sh1d0w** [comment]
After you pick the images from the image picker, you can do whatever you want to do with it. You can display it in a list or grid of your preference.

**Comment by tony123S** [comment]
I mean this
https://i.stack.imgur.com/tvvp7.png

**Comment by Sh1d0w** [comment]
Yes you can do that, what is bothering you?

**Comment by tony123S** [comment]
fixed. Thanks.
