### ISSUE TITLE
Get images directory path

### ISSUE THREAD

**Issue by HTMHell** [Sh1d0w/multi_image_picker#246]
**Is your feature request related to a problem? Please describe.**
I'm implementing an app that you can sync the images with a server. Now let's say you login from a fresh new device, I want to download all images. I can't do that because I need to know the directory's path and save the image at $path/$id.

**Describe the solution you'd like**
It would be nice to have a getter of the general path, and not only a specific asset path.

If there is a way to achieve that in the current state I'd appreciate if you'd let me know.

**Comment by Sh1d0w** [comment]
Sorry, I don't know what you mean by general path? Can you give an example?

In the latest version you can obtain the asset file path. How you can save and map them then is up to you. Bear in mind that different devices may not have same folder structure or even OS, so it is advisable to not save any file paths directly on your server.

**Comment by HTMHell** [comment]
> Sorry, I don't know what you mean by general path? Can you give an example?
> 
> In the latest version you can obtain the asset file path. How you can save and map them then is up to you. Bear in mind that different devices may not have same folder structure or even OS, so it is advisable to not save any file paths directly on your server.

I'll explain my situation:
I have items, each item holds images.
First the client chooses the images of the item.
I save all item's details including images's identifier, name , originalWidth, originalHeight in a local database.

Now I can retrieve  images easily. I iterate the images, create an `Asset` instance for each, and call `await asset.filePath`.

But I also want to "sync" the data with a remote database.
So let's say I store all the data in my local database into a remote one.

Now the user logs in from a new device, so I need to sync his data and retrieve his item and the item's images.

After I download the images, I want to do something like that:
`Asset(identifier, name, originalWidth, originalHeight)`, like I did with the local database.
How will `Asset` "know" the downloaded file path?
So I was thinking about downloading the images to the directory where `multi_image_picker` saves them. But how can I get that directory?

**Comment by Sh1d0w** [comment]
@HTMHell I see what you want to achieve, but you can't do it like this unfortunately.

The asset identifier is the resource unique id - on iOS this is PHAssetID, on android this is a media store content uri. The idea of Assets was to be generated only from the plugin when the user picks the images, not manually.

You can change your logic to no use Assets when displaying the images, you can use them only when you pick them to obtain the file path and the upload / do whatever you want with the image.

**Comment by HTMHell** [comment]
> @HTMHell I see what you want to achieve, but you can't do it like this unfortunately.
> 
> The asset identifier is the resource unique id - on iOS this is PHAssetID, on android this is a media store content uri. The idea of Assets was to be generated only from the plugin when the user picks the images, not manually.
> 
> You can change your logic to no use Assets when displaying the images, you can use them only when you pick them to obtain the file path and the upload / do whatever you want with the image.

Thank you.
I will be able to display the images,
but when the user edits the item, he has an option to change the images. (using you plugin)
with that approach, will I be able to "tell" the plugin that those images are already "selected"?

**Comment by Emex4gman** [comment]
is there a way to get the path when selecting the images?

**Comment by Sh1d0w** [comment]
@Emex4gman https://sh1d0w.github.io/multi_image_picker/#/faq?id=why-the-plugin-don39t-return-image-paths-directly
