### ISSUE TITLE
How can I display existing images and picked images together?

### ISSUE THREAD

**Issue by winsonet** [Sh1d0w/multi_image_picker#247]
for my case:
1. I will pickup the images from `multi_image_picker` and show in a grid
2. I will save these selected images in another temp folder
3. Next time when I enter this page, I want to show the images what I selected last time(in temp folder) and also want to continue to use `multi_image_picker` for pickup more images

problems:
1. I can't convert the existing image file from the file object to an Asset object
2. Even I can create another wrapper calss for pass normal file object and asset object to display, but when I pickup image again, I can't pass the existing selected images(if pass the asset object will be ok) to picker so it will clean all of what I selected before

so do you have any ideas?

thanks!!

**Comment by Sh1d0w** [comment]
You need to persist all constructor parameters that the Asset class accepts in order to reconstruct it. Especially the identifier. Then you will be able tor create it.

**Comment by winsonet** [comment]
that's great!

but I have another problem, I want to cache that selected images (that's why I save them to other temp folder), so that even I delete the original item(from native gallary) I also can show the cached images, but if I just reconstruct the asset with the old identifier then after I delete the original one it will can't find and show it, it possible to solve this case?

thanks!
