### ISSUE TITLE
CocoaPods could not find compatible versions for pod "multi_image_picker"

### ISSUE THREAD

**Issue by CodeGather** [Sh1d0w/multi_image_picker#249]
**Bug Report**

`multi_image_picker` version: 4.5.3

Is it happening on Android: 

Is it happening on iOS: 

**Describe the bug**

Recently, the following bug information has been unresolved

[!] CocoaPods could not find compatible versions for pod "multi_image_picker":
  In Podfile:
    multi_image_picker (from `.symlinks/plugins/multi_image_picker/ios`)

Specs satisfying the `multi_image_picker (from `.symlinks/plugins/multi_image_picker/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by Sh1d0w** [comment]
You need to pin the minimum iOS version to 10 see the example pod file in the example folder of this repo.
