### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by I-am-original** [Sh1d0w/multi_image_picker#25]
Hi. I have this issue and want to know what should I do with it ) 

MultiImagePickerPlugin.m:2:9: fatal error: 'multi_image_picker/multi_image_picker-Swift.h' file not found
#import <multi_image_picker/multi_image_picker-Swift.h>

**Comment by Sh1d0w** [comment]
Seems like you don't have Swift support enabled in your project (it was created without Swift template param).

To enable Swift support open your project in Xcode, the File -> New -> File choose Swift file. After you create it Xcode will automatically create bridging header.

Also make sure in your Podfile you have `use_frameworks!` like it is defined in the example [here](https://github.com/Sh1d0w/multi_image_picker/blob/master/example/ios/Podfile#L30)

Let me know if the problem still persists?

**Comment by I-am-original** [comment]
Hi there, 
I still have but other issue

```
<unknown>:0: error: merge-module command failed with exit code 1 (use -v to see invocation)
    Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
    /Users/raccoon/Library/Developer/Xcode/DerivedData/Runner-bledgromuoqenacxrgnjloowgcnu/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/BSImageView.build/module.modulemap:9:12: error: header 'BSImageView-Swift.h' not found
        header "BSImageView-Swift.h"
               ^
    <unknown>:0: error: could not build Objective-C module 'BSImageView'

```

**Comment by Sh1d0w** [comment]
Can you try following steps:

1. run `flutter clean`
2. Remove Podfile.lock and then do pod install in the ios directory
3. Open Xcode, go to build setting search for Swift version and change that to Swift 4.2

**Comment by I-am-original** [comment]
BTW, what should be inside of this file?

`
//
//  Use this file to import your target's public headers that you would like to expose to Swift.
//
`

Sorry for questions ) I am 0 in iOS )

**Comment by I-am-original** [comment]
@Sh1d0w thanks a lot ) it is working ) but I have no idea how )
1. For what we need this Bridging Header?
2. Do we need to set Swift version to 4.2 in Build Setting for Pods or for Runner?

**Comment by Sh1d0w** [comment]
@I-am-original Glad that I could help.

If you want to import an Objective-C code into a Swift Xcode or visa versa project you definitely have to create a bridging header (this allows you to communicate with your old Objective-C classes from your Swift classes).

You need to set the Swift version for your project, e.g. Runner.

**Comment by Sh1d0w** [comment]
@I-am-original Hm did you run the steps from my previous comment (Removing podfile.lock and doing pod install, etc)? What version of the plugin are you using?

Are you able to run the example app in this repo?

**Comment by I-am-original** [comment]
@Sh1d0w 
- I did all you said ) 
- Yes example running fine on iPhone

**Comment by I-am-original** [comment]
@Sh1d0w  maybe something here ?
for Runner Target
<img width="871" alt="screen shot 2018-11-09 at 10 37 22 am" src="https://user-images.githubusercontent.com/9134717/48251762-7bf18880-e40b-11e8-8d73-553e1e12b726.png">

for Image lib:
<img width="821" alt="screen shot 2018-11-09 at 10 38 42 am" src="https://user-images.githubusercontent.com/9134717/48251842-b0fddb00-e40b-11e8-866b-8ae54f3fc16e.png">

**Comment by I-am-original** [comment]
ok, I have changed 
`platform :ios, '10.0'` from 8.0 and run with Android Studio. It is working. however with `flutter run `it is not

**Comment by Sh1d0w** [comment]
@I-am-original can you try this: in your Podfile search for the section where you have this:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```
and change it to this

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/7463
    target.headers_build_phase.files.each do |file|
      file.settings = { 'ATTRIBUTES' => ['Public'] }
    end
  end
end
```

Let me know if it helps.

**Comment by I-am-original** [comment]
@Sh1d0w for let's say it is working. I will be looking on this issue if any ) and will be comparing with example pod file. thanks
