### ISSUE TITLE
'multi_image_picker/multi_image_picker-Swift.h' file not found

### ISSUE THREAD

**Issue by longdw** [Sh1d0w/multi_image_picker#250]
`multi_image_picker: ^4.5.3`

`Objective-C Project`

According to the description of the [document](https://sh1d0w.github.io/multi_image_picker/#/initialsetup) described, I add Swift file and create Bridging Header automatically, but project always build failed and Xcode's output:

Swift Compiler Error Group

Module map file '/Users/longdw/Library/Developer/Xcode/DerivedData/Runner-grijtckhfwcfwbatccjavbisjvsj/Build/Products/Debug-iphonesimulator/multi_image_picker/multi_image_picker.modulemap' not found

Failed to emit precompiled header '/Users/longdw/Library/Developer/Xcode/DerivedData/Runner-grijtckhfwcfwbatccjavbisjvsj/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_1KTVSY7L9NXDI-clang_1CAHUYQRUY429.pch' for bridging header '/Users/longdw/Documents/iOSLab/flutter_keyboard/.ios/Runner/Runner-Bridging-Header.h'

`/Users/longdw/flutter/.pub-cache/hosted/pub.flutter-io.cn/multi_image_picker-4.5.3/ios/Classes/MultiImagePickerPlugin.m:2:9: 'multi_image_picker/multi_image_picker-Swift.h' file not found`

this is a test project https://github.com/longdw/flutter_keyboard

**Comment by Sh1d0w** [comment]
That does not seem right. Can you please delete your `ios` folder and run `flutter create -i swift .` to recreate your project with Swift support correctly and see if it will solve your problem?

**Comment by longdw** [comment]
1. `flutter clean`
2. `flutter create -i swift .`
3. modify Podfile to `platform :ios, '10.0'`
4. open the xxx.xcworkspace, the problem still exists.

by the way, my project is a flutter module.

**Comment by longdw** [comment]
1. add multi_image_picker to Flutter Application can work well when I modify Podfile to platform :ios, '10.0' 

2. add multi_image_picker to Flutter Module can't work, but when I add `use_frameworks!` like this:
```
target 'Runner' do
  install_flutter_engine_pod
  install_flutter_plugin_pods flutter_application_path
  
  **use_frameworks!**
end
``` 
it works well also.
But I can't add `use_frameworks!`, because I'm going to add flutter module to exist ios project, if I add it, there will be more mistakes in my ios project.

**Comment by Sh1d0w** [comment]
Unfortunately there is no way to run it without `!use_frameworks` as the plugin is written in Swift and won't work with flutter core which is Objective-C.
