### ISSUE TITLE
Generate asset manually via code

### ISSUE THREAD

**Issue by HTMHell** [Sh1d0w/multi_image_picker#252]
**Is your feature request related to a problem? Please describe.**
Following my first [issue](https://github.com/Sh1d0w/multi_image_picker/issues/246) I would like to be able to pass to `selectedAssets` images that the user never picked.

**Describe the solution you'd like**
To be able to create an `Asset` instance via code (given a file path or a `File` instance)

**Describe alternatives you've considered**
I couldn't find any other solution.

**Comment by Sh1d0w** [comment]
The only way to create Asset instance manually is if you previously picked that image and you saved the identifier. On Android usually this is the content URI, but in iOS is the PHAssetID, which there is no way you can know that from a file path.

It was never an intention Assets to be able to be created outside of the image picker plugin, so I am going to close this.

**Comment by Emex4gman** [comment]
is there a way to get the path when selecting the images?
