### ISSUE TITLE
Reordered selected assets are displayed out of order on iOS.

### ISSUE THREAD

**Issue by karistonavila** [Sh1d0w/multi_image_picker#253]
**Bug Report**

`multi_image_picker` version: 4.5.3

Is it happening on Android: No

Is it happening on iOS: Yes

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale pt-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

• No issues found!
```

Given 3 assets: [0] [1] [2].
After reordering to [2] [0] [1] and calling pickImages, passing the reordered list to selectedAssets, the selected images are displayed like [2] [1] [0]. It happens only on iOS, on Android it works like expected.

**Comment by Sh1d0w** [comment]
What do you mean you render them? The order of the images in the native picker is by the date the images are taken and is not possible to be changed?

**Comment by karistonavila** [comment]
I just want to change the order the assets were selected. For example, once the user has selected some photos, they have the option to reorder them. If he wants to go back to the gallery and select more photos, I want the new order to be shown in the gallery. The problem is that on iOS and new order does not appear correctly. If I select the photos [0] [1] [2] and re-order them to [2] [0] [1], when I return to the gallery they appear as [2] [1] [0]. On Android photos appear correctly selected in the new order.

**Comment by Sh1d0w** [comment]
I understand what you are asking about. The case is that this thing is handled by the native plugins I am using for Android and iOS. Obviously if on Android you pass array of pre-selected images it will honour that order when picking again, which is not the case on iOS.

Please open a feature request and describe your case in the iOS plugin repo that I am using, if the maintainer implements this all I need will be to update the dependency here and you will have that functionality.

Here is the repo https://github.com/mikaoj/BSImagePicker
