### ISSUE TITLE
From version 4.5.4, building on ios is failing

### ISSUE THREAD

**Issue by veenatic82** [Sh1d0w/multi_image_picker#258]
**Bug Report**

`multi_image_picker` version: 4.5.4

Is it happening on Android: No

Is it happening on iOS: Yes

### Building on Ios is failing

**Getting Following error:**
Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "BSImagePicker":
      In snapshot (Podfile.lock):
        BSImagePicker (= 2.10.0, ~> 2.10.0)

      In Podfile:
        multi_image_picker (from `.symlinks/plugins/multi_image_picker/ios`) was resolved to 4.5.4, which depends on
          BSImagePicker (~> 2.10.1)

    Specs satisfying the `BSImagePicker (= 2.10.0, ~> 2.10.0), BSImagePicker (~> 2.10.1)` dependency were found, but they required a higher minimum deployment target.

**Comment by Sh1d0w** [comment]
You have a cache problem executed flutter cache clean and then install the dependencies again.

**Comment by veenatic82** [comment]
Is there such command "flutter cache clean" ?
I tried "flutter clean". But still the same issue

**Comment by veenatic82** [comment]
I will try with a fresh project tomorrow and check if the same happens

**Comment by Sh1d0w** [comment]
New project it will work since you won’t have the pos cache. You can try going in your ios folder and execute pod update there it will refresh the podfile. Alternatively you can try removing and adding the plugin again.

**Comment by veenatic82** [comment]
Yes, pod update worked. Thanks for your help.

**Comment by Sh1d0w** [comment]
👌

**Comment by EHBradford** [comment]
Hi, I am having this exact problem.  I have tried flutter clean, flutter update, and pod update and nothing works.  FYI the developers of BSImagePicker have a similar issue logged on their Github.

[https://github.com/mikaoj/BSImagePicker/issues/217](url)

**Comment by Sh1d0w** [comment]
@EHBradford I can't reproduce this error running the example app in this repo? Can you provide GitHub example where I can reproduce the error? I am using Xcode 11 btw.

**Comment by dheeraj2dj** [comment]
I removed `Podfile.lock` and executed `flutter build`. it worked!
