### ISSUE TITLE
Improve picking a single image

### ISSUE THREAD

**Issue by kinex** [Sh1d0w/multi_image_picker#259]
In my app there is need to pick a single image or multiple images depending on situation. Why should we have different plugins for picking a single image or multiple images? And currently the official Flutter plugin image_picker is too buggy for production use. This plugin can already be used for picking a single image, but with small enhancements it would be much better.

Suggested enhancements:
If `maxImages` is 1, pick selected image automatically without requiring user to tap the "ok" button and replace the "ok" button with a close "x" button to allow user to cancel the operation. Or optionally if you want to require tapping the "ok" button, deselect previous image automatically if user selects a new image (instead of displaying the "selection full" message). This enhancement could be added to current `MultiImagePicker.pickImages` method or optionally add a new method `MultiImagePicker.pickImage`.

**Comment by Sh1d0w** [comment]
Hi and thanks for the suggestions. I completely agree with you but unfortunately the functionality you suggested needs to be implemented by both of the two native libraries I am using in this project. You can open a feature request in their repos and if they both implement the behavior you want all I need to do is to update the dependency here and it will work.

You can find link to the both native image picking libraries in the readme file of this repo.

**Comment by kinex** [comment]
Ok understood. I will consider what to do as I need this asap. Thanks!
