### ISSUE TITLE
NoSuchMethodError: Class 'Asset' has no instance method 'requestThumb'.

### ISSUE THREAD

**Issue by Apurv2017** [Sh1d0w/multi_image_picker#26]
**Describe the bug**
NoSuchMethodError: Class 'Asset' has no instance method 'requestThumb'.

**To Reproduce**
```
await image[i].requestThumb(20.0,10.0),
```

**Expected behavior**
this works fine for me -

`await image[i].requestOriginal(); 
`

**Flutter:**

multi_image_picker: ^2.2.53

```
 [✓] Flutter (Channel unknown, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[!] VS Code (version 1.28.2)
[✓] Connected devices (1 available)

```

**Additional context**
@Sh1d0w thanks for creating a really useful plug-in.

whats the correct way to implement requestThumb()?

**Comment by Sh1d0w** [comment]
@Apurv2017 Hi and thanks. The method is called `requestThumbnail`

To see what params it accepts you can check the API docs [here](https://pub.dartlang.org/documentation/multi_image_picker/latest/asset/Asset/requestThumbnail.html) .

Also you can check the [example](https://github.com/Sh1d0w/multi_image_picker/blob/master/example/lib/asset_view.dart#L26) for example implementation :)

**Comment by Apurv2017** [comment]
thanks, @Sh1d0w 

can you please also update FAQ with requestThumbnail(), it says requestThumb()

**Comment by Sh1d0w** [comment]
@Apurv2017 Ah, good catch! Will update it now, thanks.
