### ISSUE TITLE
Convert image to Base64 encode?

### ISSUE THREAD

**Issue by ifarankhan** [Sh1d0w/multi_image_picker#262]
Hi,

I am using your plugin to upload images. The mobile part is working great. But I am not able to upload image. I am using forms to update information and send multiple images to server. My fields are like before_images and after_images which i need to upload via form.

I am creating base64 encode like

`
for (var asset in resultList) {
        ByteData byteData = await asset.getByteData(50);
        List<int> imageData = byteData.buffer.asUint8List();
        String imageB64 = base64Encode(imageData);
        print(imageB64);
}
`

But this is producing a very large string. And it time out if I attach more then 3 images. 
Can you please let me know what I can do to upload images with form. Or is there any other way to upload images in my case.

**Comment by Sh1d0w** [comment]
Hi

Please read the documentation for this plugin, there is a section with examples how you could upload images.

**Comment by ifarankhan** [comment]
I already have seen that and I have explained my question to you. I need to upload it via form with other information. The code above is from documentation. I ask you about the base64 encode and there is nothing related to base64 in documentation. I expected more from you to answer as i am looking forward to you guys.

**Comment by Sh1d0w** [comment]
I am not sure why you are trying to convert it to base64. Just send it as a file attachment with the same request you are sending form data. Base64 is expensive operation, creates very big strings and takes a lot of memory, it is not recommended to do this.

**Comment by Sh1d0w** [comment]
Also I don’t recommend it to do it in a loop as you do as you are requesting image data one by one but you are not freeing it causing memory usage to grow with each iteration. Instead split the logic into separate requests for each image or request the file path not the image data and attach it via file path so files are not read into the memory.

**Comment by ifarankhan** [comment]
Ok I got your point. 
Can you please tell me how can I attach my body data with this form request?
`// string to uri
Uri uri = Uri.parse('$_apiEndpoint/some/path');

// create multipart request
MultipartRequest request = http.MultipartRequest("POST", uri);

ByteData byteData = await asset.getByteData();
List<int> imageData = byteData.buffer.asUint8List();

MultipartFile multipartFile = MultipartFile.fromBytes(
  'photo',
  imageData,
  filename: 'some-file-name.jpg',
  contentType: MediaType("image", "jpg"),
);

// add file to multipart
request.files.add(multipartFile);
// send
var response = await request.send();`

Because when I tried, there was some issue with it.
