### ISSUE TITLE
'multi_image_picker/multi_image_picker-Swift.h' file not found

### ISSUE THREAD

**Issue by Allenyoungreal** [Sh1d0w/multi_image_picker#264]
**Bug Report**
`multi_image_picker` version:4.5.2
Is it happening on iOS: Yes

**Describe the bug**
'multi_image_picker/multi_image_picker-Swift.h' file not found
    #import <multi_image_picker/multi_image_picker-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Hi Owner,
I have the same issue like that, I try all solutions to fix it, but it seems didn't work.
1、I add Strings in Info.plist file
2、Add platform :ios, '9.0' on top in ios/Podfile:
3、Create Runner Bridging Header:
4、Change the swift language version to 4.2 or 4.
5、Do 
flutter clean 
flutter create -i swift [myprojecct]
flutter run 

Please help, Thanks.

![image](https://user-images.githubusercontent.com/50233301/65809701-e1409a80-e1d2-11e9-8a98-4c747075fbcf.png)
![image](https://user-images.githubusercontent.com/50233301/65809705-fae1e200-e1d2-11e9-9d71-378258a587ed.png)
![image](https://user-images.githubusercontent.com/50233301/65809711-0d5c1b80-e1d3-11e9-9f6d-c3f3c62c5079.png)
![image](https://user-images.githubusercontent.com/50233301/65809719-1a790a80-e1d3-11e9-8eb6-27de095a3e17.png)

**Comment by Allenyoungreal** [comment]
issue screenshot
![image](https://user-images.githubusercontent.com/50233301/65809734-59a75b80-e1d3-11e9-8e21-68f52b8035bd.png)

**Comment by Allenyoungreal** [comment]
I will close this issue ticket and comment, because I find the solution as you said before.

1、run flutter clean
2、And remove Podfile.lock and then do pod install in the ios directory (most important).
3、Open Xcode, go to build setting search for Swift version and change that to Swift 4.2

Thank you so much.

**Comment by zhiqiangpan** [comment]
> I will close this issue ticket and comment, because I find the solution as you said before.
> 
> 1、run flutter clean
> 2、And remove Podfile.lock and then do pod install in the ios directory (**### most important**).
> 3、Open Xcode, go to build setting search for Swift version and change that to Swift 4.2
> 
> Thank you so much.

it doesn't work!

**Comment by Sh1d0w** [comment]
@zhiqiangpan can you please let me know what does not work? What error do you get and what actions did you try to resolve?

**Comment by zhiqiangpan** [comment]
Bug Report
multi_image_picker version:3.0.0
Is it happening on iOS: Yes

Describe the bug   
 === BUILD TARGET multi_image_picker OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/terry/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/multi_image_picker-3.0.23/ios/Classes/MultiImagePickerPlugin.m:2:9: fatal error: 'multi_image_picker/multi_image_picker-Swift.h' file not found
    #import <multi_image_picker/multi_image_picker-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Actions:
1、run flutter clean
2、And remove Podfile.lock and then do pod install in the ios directory (### most important).
3、Open Xcode, go to build setting search for Swift version and change that to Swift 4.2

But the error is still here!

**Comment by Sh1d0w** [comment]
@zhiqiangpan That’s because you are using version 3.0.0 of the plugin which is no longer supported. Please upgrade to the latest version.

**Comment by zhiqiangpan** [comment]
I have updated to ^4.5.9，but the error is still here!

Describe the bug

Launching lib/main.dart on Qiang in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: Q4V56F4B3B
Running pod install...
Running Xcode build...
Xcode build done.                                           20.0s
Failed to build iOS app
Error output from Xcode build:
↳
    2019-11-05 15:07:11.714 xcodebuild[42828:657144]  DTDeviceKit: deviceType from 577d4a1fad940d9b9f4cd0cb9167865ed88d0328 was NULL
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET multi_image_picker OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/terry/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/multi_image_picker-4.5.9/ios/Classes/MultiImagePickerPlugin.m:2:9: fatal error: 'multi_image_picker/multi_image_picker-Swift.h' file not found
    #import <multi_image_picker/multi_image_picker-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the precompiled application for the device.

Error launching application on Qiang.

**Comment by Sh1d0w** [comment]
You are missing a bridging header, this is iOS thing not related to Flutter or the plugin.

You need to recreate your project with Swift support, or create the bridging header manually as described in this plugin docs.

**Comment by zhiqiangpan** [comment]
Can you please tell me the URL of "create the bridging header manually as described in this plugin docs"?

**Comment by Sh1d0w** [comment]
You can find documentation link in the README file of this repository.

**Comment by zhiqiangpan** [comment]
I don't add ‘use_frameworks! ’，so it doesn't work!
But I can't add use_frameworks! if I add it, there will be more mistakes in my ios project.
What can I do?
