### ISSUE TITLE
Immediate selection for single image

### ISSUE THREAD

**Issue by ianpark** [Sh1d0w/multi_image_picker#266]
Hi, thanks for this great package! I am looking into this to replace the `image_picker` plugin because of  `multi_image_picker` looks better and performant. One issue blocking me right now to do that is the way of its single image selection.

For selecting one image only, what user expects to see is that the image select UI closes as soon as one image is touched. However `multi_image_picker` does not fit to the purpose because:
- you need to select an image and then touch the button on the top-right corner
- you still see the select circle even after selecting the max number of images
- when you try to select another image again, then you see the warning popup which is not a case for single image selection.

Proposal:
when `maxImages` is set to 1, `multi_image_picker`  can do:
- hide the select circle completely
- return the selected image asset immediately.

Thanks!

**Comment by Sh1d0w** [comment]
Hi and thanks for your suggestion.

However this is on the side of the native Android image picker library that I am using. You can open a feature request in the FishBun repo and if the owner implements it I’ll update the plugin version and release the feature as well.

You can find link to fishbun repo in the Readme file if this repo.

**Comment by ianpark** [comment]
Thanks for reply. Created on for FishBun:
https://github.com/sangcomz/FishBun/issues/178

Seems like the iOS one already supports it?
https://github.com/mikaoj/BSImagePicker/issues/181

Can you keep this issue open so that I can update you through it?

**Comment by Sh1d0w** [comment]
Sure. 

I am not sure about the iOS plugin, can you please check the behavior? I am currently on a vacation.

If it already supports it that’s great.

**Comment by ianpark** [comment]
Thanks! Have a great holiday.

**Comment by ianpark** [comment]
@Sh1d0w another good news:

it seems like FishBun also supports the auto close after x number of selection.
https://github.com/sangcomz/FishBun/issues/178

**Comment by Sh1d0w** [comment]
Cool, I will look into that this weekend.

**Comment by Sh1d0w** [comment]
This is now implemented in version 4.5.7
