### ISSUE TITLE
Length returning null

### ISSUE THREAD

**Issue by malikdoksoz** [Sh1d0w/multi_image_picker#267]
`multi_image_picker` version: 4.5.6

Is it happening on Android:  No

Is it happening on iOS: Yes

iOS version: 13.1

Video: https://streamable.com/n3jk5

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G103, locale
    tr-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (2 available)

• No issues found!
```
The photo library opens, but if I exit without selecting a photo, I get the following error **the getter 'length' was called on null.** when I press the cancel button.

BSImagePicker updated to 2.10.3

**Comment by Sh1d0w** [comment]
Hi and thanks for the report.

Unfortunately I am not able to reproduce the issue in the example folder in this plugin.

Can you provide full stack trace of the error? Are you getting this on the Flutter or iOS code?

![cancel](https://user-images.githubusercontent.com/5074917/65836910-5effc580-e2fb-11e9-905c-65e0ac07cbd4.gif)

**Comment by malikdoksoz** [comment]
in example directory files are working good. I used this: https://sh1d0w.github.io/multi_image_picker/#/basicusage
