### ISSUE TITLE
Ability to use TextFields removed after calling pickImages

### ISSUE THREAD

**Issue by adriancmurray** [Sh1d0w/multi_image_picker#27]
When you are using a TextField the ability for the text widget to bring up the keyboard is completely removed after one calls the pickImage method. I've reproduced the problem here: 

```
import 'package:flutter/material.dart';
import 'package:multi_image_picker/multi_image_picker.dart';


void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.grey,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with TickerProviderStateMixin {

  Future<void> selectImages() async {
    await MultiImagePicker.pickImages(
      maxImages: 50,
      enableCamera: true,
    );
  }

  @override
  Widget build(BuildContext context) {
    var media = MediaQuery.of(context);

    return Scaffold(

      body: new Container(
        alignment: Alignment.bottomCenter,
        padding: new EdgeInsets.only(
          bottom: 20.0
        ),

        child: Stack(
          children: <Widget>[
            Positioned(
              bottom: media.viewInsets.bottom + 10.0,
              child: new Row (
                children: <Widget>[
                  new Row(
                    mainAxisAlignment: MainAxisAlignment.end,
                    crossAxisAlignment: CrossAxisAlignment.end,
                    mainAxisSize: MainAxisSize.min,
                    children: <Widget>[

                      new Container(
                        child: new IconButton(
                            icon: Icon(Icons.image),
                            onPressed: selectImages
                        ),
                      ),


                      new Container(
                        constraints: BoxConstraints(
                            maxWidth: media.size.width - 95.0,
                            maxHeight: media.size.height / 2 - 220.0
                        ),
                        child: new TextField (
                          maxLines: null,
                          decoration: new InputDecoration (
                            hintText: 'Type Here',
                          ),
                        ),
                      ),

                    ],
                  ),
                ],
              ),
            )
          ],
        ),
      ),
      resizeToAvoidBottomPadding: false,
    );
  }
}
```
[✓] Flutter (Channel beta, v0.10.2, on Mac OS X 10.13.6 17G65, locale en-US)

**Comment by adriancmurray** [comment]
Apologies, I actually solved the problem minutes after posting this. It's probably a good thing to have on here for others who run into this issue. I decided to try and change the FocusScope before I called the pickImages method and that solved the problem. If someone else needs to know how to do this, just use the code below inserted right before you call _await MultiImagePicker.pickImages_ : 
```
FocusScope.of(context).requestFocus(new FocusNode());
```

**Comment by Sh1d0w** [comment]
Hi @adriancmurray and thanks for opening this issue. I don't think this issue is caused by the plugin itself, it seems to me like a Flutter bug, where when you are returning for a native view to the app, it does not regain focus correctly.

I will open an issue on the official Flutter repo to report this, thanks for the solution as well!

**Comment by adriancmurray** [comment]
@Sh1d0w Yeah, I sort of figured it was more of a Flutter once I thought out how to get things to work. Thank _you_ for the excellent plug-in.

**Comment by JesseBlackman** [comment]
thanks. it's useful!

**Comment by JesseBlackman** [comment]
> Apologies, I actually solved the problem minutes after posting this. It's probably a good thing to have on here for others who run into this issue. I decided to try and change the FocusScope before I called the pickImages method and that solved the problem. If someone else needs to know how to do this, just use the code below inserted right before you call _await MultiImagePicker.pickImages_ :
> 
> ```
> FocusScope.of(context).requestFocus(new FocusNode());
> ```

thanks. it's useful!
