### ISSUE TITLE
AndroidX compatibility issue with latest version of the library 

### ISSUE THREAD

**Issue by domchikdev** [Sh1d0w/multi_image_picker#270]
**Bug Report**

`multi_image_picker` version: 4.5.6

Is it happening on Android: Yes 

Is it happening on iOS: Not sure
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G95, locale en-IL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (3 available)

• No issues found!

```
I am getting AndroidX compatibility problem despite using the latest version of the library:

Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.localbroadcastmanager:localbroadcastmanager' has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by Sh1d0w** [comment]
Hi. Which version of gradle are you using? AFAIK this should be fixed in the latest version of gradle.

You can also look into this issue for possible solution https://github.com/flutter/flutter/issues/27254#issuecomment-537399153

**Comment by domchikdev** [comment]
Upgrading gradle version fixed it. Thank you
