### ISSUE TITLE
Plugin not working in xcode 11 & Ios 13

### ISSUE THREAD

**Issue by Ahmedgagan** [Sh1d0w/multi_image_picker#271]
it show to recompile with swift 5.1 and don't allow to run using Android studio.

Xcode's output:
↳
    === BUILD TARGET BSImagePicker OF PROJECT Pods WITH CONFIGURATION Debug ===
    <unknown>:0: error: module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: /Users/ahmedgagan/Desktop/Flutter Projects/woocommerce/build/ios/Debug-iphonesimulator/BSGridCollectionViewLayout/BSGridCollectionViewLayout.swiftmodule/x86_64.swiftmodule
    === BUILD TARGET BSImagePicker OF PROJECT Pods WITH CONFIGURATION Debug ===
    <unknown>:0: error: merge-module command failed with exit code 1 (use -v to see invocation)
    Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

**Comment by Sh1d0w** [comment]
It seems you are trying to compile your project with Swift 5.1. Can you try to change it to 5.0?

**Comment by Ahmedgagan** [comment]
> It seems you are trying to compile your project with Swift 5.1. Can you try to change it to 5.0?

Can I get to know how to change the compiling Swift version to 5.0?
I am using Android Studio to develop my app.

**Comment by Sh1d0w** [comment]
You need to open your app with Xcode in order to change the swift version. On the left side click on your Runner project, select Build Settings and search for SWIFT_VERSION, then from the dropdown you can change it.

**Comment by Ahmedgagan** [comment]
I tried this but there's no option which lets me select SWIFT_VERSION in Xcode

**Comment by Ahmedgagan** [comment]
hey Radoslav Vitanov,
I tried this but there's no option which lets me select SWIFT_VERSION in
Xcode.
I've attached the image of the build setting.

thanks,
Ahmed

**Comment by Ahmedgagan** [comment]
I also tried to edit Podfile but the error is the same.

i added this code in podfile
 "config.build_settings['SWIFT_VERSION'] = '5.0.1' # required"

**Comment by Sh1d0w** [comment]
Don't you have this field in your build settings?

<img width="1172" alt="Screenshot 2019-10-06 at 21 26 47" src="https://user-images.githubusercontent.com/5074917/66273811-15295900-e880-11e9-8e1a-5ad69564ee55.png">

I am currently running Xcode 11 and the example app runs just fine. Until you provide repository where I can reproduce the problem I may not be able to help you.

<img width="527" alt="Screenshot 2019-10-06 at 21 26 55" src="https://user-images.githubusercontent.com/5074917/66273822-2a9e8300-e880-11e9-97ef-0967d964e8e3.png">
