### ISSUE TITLE
Swipe down from header on iOS 13 doesn't perform callback to flutter

### ISSUE THREAD

**Issue by gabrielginter** [Sh1d0w/multi_image_picker#272]
**Bug Report**

`multi_image_picker` version: 4.5.6

Is it happening on Android: No

Is it happening on iOS: Yes

```
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.387], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)
```

**Describe the bug**
On iOS 13, the way the multi image picker is presented has changed, it allows the user to slide down the whole screen down from the header; when the user performs this action, there is no callback to flutter, I believe that the same callback as the "Cancel" button should be triggered, throwing the "NoImagesSelectedException" exception back to flutter. As of now there is no way to know the user is back to the app and the picker has been dismissed.

**Comment by Sh1d0w** [comment]
Please report this to the maintainer of the iOS plugin. It seems this new feature in iOS 13 does not trigger the cancel callback which the plugin provides.
