### ISSUE TITLE
iOS: tapping on header, triggers touch events on flutter app on the background

### ISSUE THREAD

**Issue by gabrielginter** [Sh1d0w/multi_image_picker#273]
**Bug Report**

`multi_image_picker` version: 4.5.6

Is it happening on Android: No

Is it happening on iOS: Yes

```
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.387], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)
```

**Describe the bug**

On iOS, when the picker is opened if the user taps on the header (avoiding the cancel button and the foldler menu), those taps are caught by the app running under, so if you have a button or a nav bar under, the user could be tapping on those elements without knowing before leaving the picker.

**Comment by Sh1d0w** [comment]
That seems odd, can you provide example repo? This issue maybe needs to be reported to Flutter official repo, since the image picker activity is a native one that is on top of the Flutter app and I can't do much about it.

**Comment by gabrielginter** [comment]
It seems to only be happening on the header of the picker, but I will test it further and provide more information and an example, although you can just place a button at the top and see how it gets triggered.

**Comment by ZHanOBa** [comment]
i need help.
I had the same problem.
