### ISSUE TITLE
Not getting any response from MultiImagePicker.pickImages() in android

### ISSUE THREAD

**Issue by vivekkujur** [Sh1d0w/multi_image_picker#275]
hi,
i am using Flutter 1.7.8+hotfix.4 • channel unknown • unknown source
Framework • revision 20e59316b8 (3 months ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0

  multi_image_picker: ^4.5.6

problem:
not getting any response after selecting images from gallery. then try again to call  MultiImagePicker.pickImages() then it  give error :
**I/flutter: Image picker is already active**

**in IOS simulator working fine .
in android not working 
**I/flutter: Image picker is already active****

resultList = await MultiImagePicker.pickImages(
            maxImages: 300,
            enableCamera: true,
            selectedAssets: images,
            cupertinoOptions: CupertinoOptions(takePhotoIcon: "chat"),
            materialOptions: MaterialOptions(
              actionBarColor: "#abcdef",
              actionBarTitle: "App",
              allViewTitle: "All Photos",
              selectCircleStrokeColor: "#000000",
            ));

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G95, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] iOS tools - develop for iOS devices
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.35.1)
[✓] Connected device (4 available)

• No issues found!

**Comment by Sh1d0w** [comment]
Hi, can you please paste me the contents of your `pubspec.yaml` file?

**Comment by vivekkujur** [comment]
name: app
description: new customer app
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.2.23+50

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences:
  cupertino_icons:
  http:
  qr_flutter:
  flutter_calendar:
  liquid_pull_to_refresh:
  flutter_offline:
  flutter_counter:
  onesignalflutter:
    git: git://github.com/jmrobles/OneSignal-Flutter-SDK.git
  rubber:
  qrcode_reader:
  image_picker: 0.6.0+7
  flutter_datetime_picker: ^1.1.4
  carousel_slider: ^1.3.0
  sliding_up_panel: ^0.3.3
  fluttertoast: ^3.0.4
  uri: ^0.11.3+1
  android_intent: ^0.3.0+2
#  razorpay_plugin: ^0.2.9
  package_info: ^0.4.0+3
  url_launcher: ^5.1.4
  path_provider: ^1.1.0
  barcode_scan: ^1.0.0
  mobx: 0.3.5
  flutter_mobx: 0.3.0+1
  sticky_headers: "^0.1.8"
  firebase_crashlytics: ^0.0.4
  firebase_core: ^0.4.0+8  # add dependency for Firebase Core
  permission_handler: ^3.1.0
  screen: ^0.0.5
  toast: ^0.1.4
  flutter_rating: ^0.0.2
  material_search: ^0.2.8
  flutter_local_notifications: ^0.7.1+3
  pie_chart: ^1.0.0
  datetime_picker_formfield: 0.2.0
  cached_network_image: ^1.1.1
#  razorpay_flutter: ^1.1.1
  flutter_account_kit: ^0.7.0
  flutter_hooks: ^0.6.0
  auto_size_text: ^2.0.2+1
  webview_flutter: ^0.3.13
  #  webview_flutter 0.3.10+3
  device_info: ^0.4.0+2
  firebase_messaging: 5.1.5
  multi_image_picker: ^4.5.6
  #  flutter_upi: 0.0.2
  razorpay_plugin:
    git:
      url: https://github.com/vivekkujur/razorpay_flutter.git
      ref: "fix-pay"
  flutter_upi:
    git:
      url: https://github.com/vivekkujur/flutter_upi.git
      ref: "fix_upi"

#  webview_flutter:
#  path: webview_flutter

#  razorpay_flutter:
#    git:
#      url: git://github.com/razorpay/razorpay-flutter.git
#      ref: "add-manifest"


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.3.1
  mobx_codegen: 0.3.3+1

  flutter_launcher_icons: "^0.7.0"


flutter_icons:
  image_path: "assets/icon.png"
  ios: true
  image_path_ios: "assets/launcher/ic_launcher.png"
  android: true
  adaptive_icon_foreground: "assets/launcher/ic_launcher_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/download.png
    - assets/breakfast.jpeg
    - assets/lunch.jpg
    - assets/snack.jpg
    - assets/dinner.jpg
    - assets/login.jpg
    - assets/Logo.png
    - assets/logo1.png
    - assets/internet.png
    - assets/icon1.jpg
    - assets/icon.png
    - assets/wallet.png
    - assets/Upi.jpg
    - assets/Bhim.png
    - assets/google.jpg
    - assets/paytm.png
    - assets/phone.png
    - assets/whatsapp.jpg
    - assets/true.png
    - assets/or.jpg
    - assets/Rupee.png
    - assets/forward.png
    - assets/check.png
    - assets/circleforward.png
    - assets/himi.jpg
    - assets/veg.png
    - assets/success.png
    - assets/drawable.jpg
    - assets/launcher/ic_launcher.png
    - assets/launcher/ic_launcher_foreground.png
    - assets/scooter.png
    - assets/selfservice.png
    - assets/coffee_shop.png
    - assets/service.png
    - assets/home.png
    - assets/restaurant.png
    - assets/imagesbhim.png
    - assets/upipin.jpg
    - amazon.jpg
  fonts:
    - family: Rubik
      fonts:
        - asset: font/Rubik-Black.ttf
        - asset: font/Rubik-Bold.ttf
        - asset: font/Rubik-Regular.ttf
        - asset: font/Rubik-MediumItalic.ttf
        - asset: font/Rubik-LightItalic.ttf
        - asset: font/Rubik-Light.ttf

**Comment by vivekkujur** [comment]
name: app
description: new customer app
version: 3.2.23+50

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences:
  cupertino_icons:
  http:
  qr_flutter:
  flutter_calendar:
  liquid_pull_to_refresh:
  flutter_offline:
  flutter_counter:
  onesignalflutter:
    git: git://github.com/jmrobles/OneSignal-Flutter-SDK.git
  rubber:
  qrcode_reader:
  image_picker: 0.6.0+7
  flutter_datetime_picker: ^1.1.4
  carousel_slider: ^1.3.0
  sliding_up_panel: ^0.3.3
  fluttertoast: ^3.0.4
  uri: ^0.11.3+1
  android_intent: ^0.3.0+2
  package_info: ^0.4.0+3
  url_launcher: ^5.1.4
  path_provider: ^1.1.0
  barcode_scan: ^1.0.0
  mobx: 0.3.5
  flutter_mobx: 0.3.0+1
  sticky_headers: "^0.1.8"
  firebase_crashlytics: ^0.0.4
  firebase_core: ^0.4.0+8  # add dependency for Firebase Core
  permission_handler: ^3.1.0
  screen: ^0.0.5
  toast: ^0.1.4
  flutter_rating: ^0.0.2
  material_search: ^0.2.8
  flutter_local_notifications: ^0.7.1+3
  pie_chart: ^1.0.0
  datetime_picker_formfield: 0.2.0
  cached_network_image: ^1.1.1
  flutter_account_kit: ^0.7.0
  flutter_hooks: ^0.6.0
  auto_size_text: ^2.0.2+1
  webview_flutter: ^0.3.13
  device_info: ^0.4.0+2
  firebase_messaging: 5.1.5
  multi_image_picker: ^4.5.6
  razorpay_plugin:
    git:
      url: https://github.com/vivekkujur/razorpay_flutter.git
      ref: "fix-pay"
  flutter_upi:
    git:
      url: https://github.com/vivekkujur/flutter_upi.git
      ref: "fix_upi"



dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.3.1
  mobx_codegen: 0.3.3+1

  flutter_launcher_icons: "^0.7.0"


flutter_icons:
  image_path: "assets/icon.png"
  ios: true
  image_path_ios: "assets/launcher/ic_launcher.png"
  android: true
  adaptive_icon_foreground: "assets/launcher/ic_launcher_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/download.png
    - assets/breakfast.jpeg
    - assets/lunch.jpg
    - assets/snack.jpg
    - assets/dinner.jpg
    - assets/login.jpg
    - assets/Logo.png
    - assets/logo1.png
    - assets/internet.png
    - assets/icon1.jpg
    - assets/icon.png
    - assets/wallet.png
    - assets/Upi.jpg
    - assets/Bhim.png
    - assets/google.jpg
    - assets/paytm.png
    - assets/phone.png
    - assets/whatsapp.jpg
    - assets/true.png
    - assets/or.jpg
    - assets/Rupee.png
    - assets/forward.png
    - assets/check.png
    - assets/circleforward.png
    - assets/himi.jpg
    - assets/veg.png
    - assets/success.png
    - assets/drawable.jpg
    - assets/launcher/ic_launcher.png
    - assets/launcher/ic_launcher_foreground.png
    - assets/scooter.png
    - assets/selfservice.png
    - assets/coffee_shop.png
    - assets/service.png
    - assets/home.png
    - assets/restaurant.png
    - assets/imagesbhim.png
    - assets/upipin.jpg
    - amazon.jpg
  fonts:
    - family: Rubik
      fonts:
        - asset: font/Rubik-Black.ttf
        - asset: font/Rubik-Bold.ttf
        - asset: font/Rubik-Regular.ttf
        - asset: font/Rubik-MediumItalic.ttf
        - asset: font/Rubik-LightItalic.ttf
        - asset: font/Rubik-Light.ttf

**Comment by vivekkujur** [comment]
> Hi, can you please paste me the contents of your `pubspec.yaml` file?

name: app
description: new customer app
version: 3.2.23+50

environment:
sdk: ">=2.2.2 <3.0.0"

dependencies:
flutter:
sdk: flutter

shared_preferences:
cupertino_icons:
http:
qr_flutter:
flutter_calendar:
liquid_pull_to_refresh:
flutter_offline:
flutter_counter:
onesignalflutter:
git: git://github.com/jmrobles/OneSignal-Flutter-SDK.git
rubber:
qrcode_reader:
image_picker: 0.6.0+7
flutter_datetime_picker: ^1.1.4
carousel_slider: ^1.3.0
sliding_up_panel: ^0.3.3
fluttertoast: ^3.0.4
uri: ^0.11.3+1
android_intent: ^0.3.0+2
package_info: ^0.4.0+3
url_launcher: ^5.1.4
path_provider: ^1.1.0
barcode_scan: ^1.0.0
mobx: 0.3.5
flutter_mobx: 0.3.0+1
sticky_headers: "^0.1.8"
firebase_crashlytics: ^0.0.4
firebase_core: ^0.4.0+8 # add dependency for Firebase Core
permission_handler: ^3.1.0
screen: ^0.0.5
toast: ^0.1.4
flutter_rating: ^0.0.2
material_search: ^0.2.8
flutter_local_notifications: ^0.7.1+3
pie_chart: ^1.0.0
datetime_picker_formfield: 0.2.0
cached_network_image: ^1.1.1
flutter_account_kit: ^0.7.0
flutter_hooks: ^0.6.0
auto_size_text: ^2.0.2+1
webview_flutter: ^0.3.13
device_info: ^0.4.0+2
firebase_messaging: 5.1.5
multi_image_picker: ^4.5.6
razorpay_plugin:
git:
url: https://github.com/vivekkujur/razorpay_flutter.git
ref: "fix-pay"
flutter_upi:
git:
url: https://github.com/vivekkujur/flutter_upi.git
ref: "fix_upi"

dev_dependencies:
flutter_test:
sdk: flutter

build_runner: ^1.3.1
mobx_codegen: 0.3.3+1

flutter_launcher_icons: "^0.7.0"

flutter_icons:
image_path: "assets/icon.png"
ios: true
image_path_ios: "assets/launcher/ic_launcher.png"
android: true
adaptive_icon_foreground: "assets/launcher/ic_launcher_foreground.png"

flutter:
uses-material-design: true
assets:
- assets/download.png
- assets/breakfast.jpeg
- assets/lunch.jpg
- assets/snack.jpg
- assets/dinner.jpg
- assets/login.jpg
- assets/Logo.png
- assets/logo1.png
- assets/internet.png
- assets/icon1.jpg
- assets/icon.png
- assets/wallet.png
- assets/Upi.jpg
- assets/Bhim.png
- assets/google.jpg
- assets/paytm.png
- assets/phone.png
- assets/whatsapp.jpg
- assets/true.png
- assets/or.jpg
- assets/Rupee.png
- assets/forward.png
- assets/check.png
- assets/circleforward.png
- assets/himi.jpg
- assets/veg.png
- assets/success.png
- assets/drawable.jpg
- assets/launcher/ic_launcher.png
- assets/launcher/ic_launcher_foreground.png
- assets/scooter.png
- assets/selfservice.png
- assets/coffee_shop.png
- assets/service.png
- assets/home.png
- assets/restaurant.png
- assets/imagesbhim.png
- assets/upipin.jpg
- amazon.jpg
fonts:
- family: Rubik
fonts:
- asset: font/Rubik-Black.ttf
- asset: font/Rubik-Bold.ttf
- asset: font/Rubik-Regular.ttf
- asset: font/Rubik-MediumItalic.ttf
- asset: font/Rubik-LightItalic.ttf
- asset: font/Rubik-Light.ttf

**Comment by vivekkujur** [comment]
> Hi, can you please paste me the contents of your `pubspec.yaml` file?

i found issue .
its conflicting with  "flutter_upi" packages .

**Comment by Sh1d0w** [comment]
Hi, yes this plugin does not correctly handle the `onActivityResult` callback [here](https://github.com/samarthagarwal/flutter_upi/blob/master/android/src/main/java/com/samarth/flutter_upi/FlutterUpiPlugin.java#L95)

For more info see my response in a similar issue https://github.com/Sh1d0w/multi_image_picker/issues/199#issuecomment-511081008

You should contact the developer of the plugin to correctly handle only code related to his plugin, otherwise he is breaking a lot other plugins relaying on this callback without checking if the registered response is for his plugin.

I've already raised this possible issue with the flutter team as the issue lies in the core of how flutter handle plugins https://github.com/flutter/flutter/issues/31301
