### ISSUE TITLE
Get app crash when run example code.

### ISSUE THREAD

**Issue by maituongan11zz** [Sh1d0w/multi_image_picker#279]
**Bug Report**

`multi_image_picker` version: 

Is it happening on Android:

```
 <!-- run `flutter doctor` and paste the output here: -->
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.356], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.38.1)
[√] Connected device (1 available)

```

**Describe the bug**

I use code main.dart in example folder but get crash when click on icon add multi image. `W/est_multi_imag(24279): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/est_multi_imag(24279): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
E/RecyclerView(24279): No adapter attached; skipping layout
D/EGL_emulation(24279): eglMakeCurrent: 0xdcfe7600: ver 3 0 (tinfo 0xdd0c8f10)
D/AndroidRuntime(24279): Shutting down VM
E/AndroidRuntime(24279): FATAL EXCEPTION: main
E/AndroidRuntime(24279): Process: com.example.test_multi_image, PID: 24279
E/AndroidRuntime(24279): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArrayMap;
E/AndroidRuntime(24279): 	at com.sangcomz.fishbun.adapter.image.impl.GlideAdapter.loadImage(GlideAdapter.java:17)
E/AndroidRuntime(24279): 	at com.sangcomz.fishbun.adapter.view.AlbumListAdapter.onBindViewHolder(AlbumListAdapter.java:56)
E/AndroidRuntime(24279): 	at com.sangcomz.fishbun.adapter.view.AlbumListAdapter.onBindViewHolder(AlbumListAdapter.java:25)
E/AndroidRuntime(24279): 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
E/AndroidRuntime(24279): 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
E/AndroidRuntime(24279): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
E/AndroidRuntime(24279): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
E/AndroidRuntime(24279): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
E/AndroidRuntime(24279): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
E/AndroidRuntime(24279): 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
E/AndroidRuntime(24279): 	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:557)
E/AndroidRuntime(24279): 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
E/AndroidRuntime(24279): 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
E/AndroidRuntime(24279): 	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
E/AndroidRuntime(24279): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
E/AndroidRuntime(24279): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
E/AndroidRuntime(24279): 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
E/AndroidRuntime(24279): 	at android.view.View.layout(View.java:21912)
E/AndroidRuntime(24279): 	at android.view.ViewGroup.layout(ViewGroup.java:6260)
E/AndroidRuntime(24279): 	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:142)
E/AndroidRuntime(24279): 	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:41)
E/AndroidRuntime(24279): 	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1556)
E/AndroidRuntime(24279): 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:888)
`

**Comment by Sh1d0w** [comment]
You need to migrate your project to Android X as described in the docs.

**Comment by maituongan11zz** [comment]
Thanks you. Sorry my bad

Vào Th 4, 9 thg 10, 2019 lúc 17:34 Radoslav Vitanov <
notifications@github.com> đã viết:
