### ISSUE TITLE
Run image picker in same process

### ISSUE THREAD

**Issue by I-am-original** [Sh1d0w/multi_image_picker#28]
Is there any possibility to run image picker in the same process? 
Currently I catch lifecycle callbacks about app going to background and it cause some issues.

**Comment by Sh1d0w** [comment]
Hi @I-am-original . As described in the README this plugin is just a bridge to a third party image picker libraries (Mattisse for Android and BSImagePicker for iOS). Thus when you invoke the picker it spawns another native view, so the app goes to background.

With the current implementation it is not possible.

I was thinking to release separate library, which will be 100% dart multi image picker, which also means same experience on Android and iOS and a lot more ways of customisation (it will also run in the same process), but I currently don't have the time to finish it.

What you can do to solve your problem maybe before invoking the picker, set a flag in your state that the picker is invoked, so in your lifecycle hooks you can check that and act based on that.
