### ISSUE TITLE
iOS: How to handle camera permission denied?

### ISSUE THREAD

**Issue by dao-wkm** [Sh1d0w/multi_image_picker#281]
Can you response Camera Permission denied. I want to handle this case to navigate user to App Setting

**Comment by malikdoksoz** [comment]
What does this library have to do with anything? https://pub.dev/packages/permission_handler

**Comment by Sh1d0w** [comment]
The plugin throws a specific error if the permission to pick images is not granted. Please read the docs https://sh1d0w.github.io/multi_image_picker/#/errorhandling
