### ISSUE TITLE
I have a need

### ISSUE THREAD

**Issue by gaojuanjuan** [Sh1d0w/multi_image_picker#29]
Can you provide an interface to directly adjust the camera? That is, don't put photos and photo albums together, I want to directly pick up the camera to get pictures.

**Comment by gaojuanjuan** [comment]
I want to use my button on the screen to pick up the camera and take a photo.

**Comment by Sh1d0w** [comment]
@gaojuanjuan Thats exactly what the plugin I've suggested you does, take a look at the example:

https://pub.dartlang.org/packages/camera#-example-tab-

The purpose of the multi image picker is to present gallery with albums/images. What you want to achieve is out of the scope of this plugin.
