### ISSUE TITLE
multi_image_picker/multi_image_picker-Swift.h' file not found

### ISSUE THREAD

**Issue by MdcGIt** [Sh1d0w/multi_image_picker#290]
multi_image_picker/multi_image_picker-Swift.h' file not found

flutter启动iOS项目可以启动 但是Xcode直接启动iOS项目 会报这个错 怎么解决

**Comment by Sh1d0w** [comment]
You need to create Bridging header, or re-create your project with Swift support.

Remove iOS folder in your project and execute `flutter create -i swift .`
