### ISSUE TITLE
GPSmetadata is not accessible on Android 10 device

### ISSUE THREAD

**Issue by Martibis** [Sh1d0w/multi_image_picker#291]
**Bug Report**

`multi_image_picker` version: v4.5.8 

Is it happening on Android: Yes 

Is it happening on iOS: Not tested 

```
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.17763.805], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[!] Android Studio (version 3.4)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.39.2)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Describe the bug**

All values in gpsmetadata are null on Android 10 device. I tried on Android 9 device as well and here I don't have the issue.

**Comment by Martibis** [comment]
#232

**Comment by claudioredi** [comment]
@Sh1d0w : this is related to [scoped storage](https://developer.android.com/about/versions/10/privacy/changes#scoped-storage) in Android 10

I have a pull request ready for this if you're interested.

**Comment by Sh1d0w** [comment]
I've added a section to the docs please follow them and you will be able to access GPS metadata https://sh1d0w.github.io/multi_image_picker/#/metadata
