### ISSUE TITLE
There must be a way to update images.

### ISSUE THREAD

**Issue by HathTech** [Sh1d0w/multi_image_picker#292]
Say I have 3 old images and I want to keep 2 old and delete one and add two images. 
How can I achieve this? I am using firebase storage.

**Comment by Sh1d0w** [comment]
There is an option to pass array of already selected assets in the pickImages function. They will be shown as pre-selected in the image picker https://pub.dev/documentation/multi_image_picker/latest/multi_image_picker/MultiImagePicker/pickImages.html

**Comment by HathTech** [comment]
What if the image is not an asset image? 
Old images are coming from firebase.

**Comment by Sh1d0w** [comment]
You need to save the Asset.identifier and re-construct the asset object before passing it to the array with selectedAssets.

**Comment by HathTech** [comment]
Thank you. Let me try this.
