### ISSUE TITLE
Experience optimization suggestions

### ISSUE THREAD

**Issue by kinsens** [Sh1d0w/multi_image_picker#293]
If I want to take a photo with the camera, then I have to enter the album page first, then just select a folder, and finally enter the page to see the camera button, I think this process is not convenient, if I want to take photos directly, Several operations are required to enter the photo page.
I want to pop up two options for me to choose when I click to select a photo, "camera" and "album", which will be a lot easier.
<img width="389" alt="image" src="https://user-images.githubusercontent.com/31468203/67474807-a887ca00-f687-11e9-8a1e-d2f56f6b153f.png">

**Comment by Sh1d0w** [comment]
The purpose of this plugin is to pick images from the gallery, with the extra option to take a picture if you want.

If you want to directly take a picture you can use the camera plugin instead you are not required to use this plugin to take pictures.

**Comment by kinsens** [comment]
Hello, I don't mean to say that I need a UI like this screenshot. I mean, can you expose a method of taking a photo, if I call the camera to take another plug-in, then another plug-in takes a photo. The return value is not the same as the return value of your "pickimages" method. For a person who does not have an Android or dart basis, it takes a lot of time to convert the data type, such as the "image_picker" plugin, the return method of the photo method. The value is list<File> and your plugin return value is List<Asset>.

**Comment by kinsens** [comment]
Hello, I don't mean to say that I need a UI like this screenshot. I mean, can you expose a method of taking a photo, if I call the camera to take another plug-in, then another plug-in takes a photo. The return value is not the same as the return value of your "pickimages" method. For a person who does not have an Android or dart basis, it takes a lot of time to convert the data type, such as the "image_picker" plugin, the return method of the photo method. The value is list<File> and your plugin return value is List<Asset>.

**Comment by kinsens** [comment]
Hello, I don't mean to say that I need a UI like this screenshot. I mean, can you expose a method of taking a photo, if I call the camera to take another plug-in, then another plug-in takes a photo. The return value is not the same as the return value of your "pickimages" method. For a person who does not have an Android or dart basis, it takes a lot of time to convert the data type, such as the "image_picker" plugin, the return method of the photo method. The value is list<File> and your plugin return value is List<Asset>.

**Comment by kinsens** [comment]
Hello, I don't mean to say that I need a UI like this screenshot. I mean, can you expose a method of taking a photo, if I call the camera to take another plug-in, then another plug-in takes a photo. The return value is not the same as the return value of your "pickimages" method. For a person who does not have an Android or dart basis, it takes a lot of time to convert the data type, such as the "image_picker" plugin, the return method of the photo method. The value is List of 'File' type and your plugin return value is List of 'Asset' type.

**Comment by kinsens** [comment]
My idea is that if you separate the method of taking photos separately, the return values of the two methods of taking photos and selecting photos are the same, then many users only need your plug-in to realize the full function of taking photos and selecting multiple images. Instead of installing and using another plugin because of the camera function,

**Comment by kinsens** [comment]
I only personally think that from the perspective of personal development, I think the function that a plug-in can implement, why use multiple plug-ins in the project to achieve.
