### ISSUE TITLE
how to change ios title into Chinese

### ISSUE THREAD

**Issue by qiuqiu0113** [Sh1d0w/multi_image_picker#294]
android can display Chinese by default but ios cannot

android：
https://user-images.githubusercontent.com/12025770/67851063-93f27880-fb44-11e9-9777-b0846501bf12.jpg

iOS：
https://user-images.githubusercontent.com/12025770/67850797-10d12280-fb44-11e9-8de9-168714f75e29.png

**Comment by Sh1d0w** [comment]
According to the docs of the iOS library I am using this plugin it happens automatically. It will use translations from the current language set on your iPhone.

**Comment by Sh1d0w** [comment]
@BadReese Please open an issue then in https://github.com/mikaoj/BSImagePicker

This is the native iOS library I am using to present the picker. There isn't much I can do about this otherwise, sorry. Once the maintainer fixes it I will update the library 👍

**Comment by onewkl** [comment]
> although

Edit info.plist  
![image](https://user-images.githubusercontent.com/39547225/79437378-af731200-8004-11ea-8f6a-1945d522a979.png)
