### ISSUE TITLE
Not able to change back and select drawable.

### ISSUE THREAD

**Issue by Nikhil-Khule** [Sh1d0w/multi_image_picker#295]
Hello sir, 
As you have mentioned in your document to send a string value to change the drawable but what exactly the string value I have to pass to get it working. I tried passing the name of the XML drawable but didn't work. Please help!

Thank you! 🙏

**Comment by Sh1d0w** [comment]
Hi, yes it needs to be the file name. You also need to have the image for each possible resolution.

Take a look at the example app in this repo: https://github.com/Sh1d0w/multi_image_picker/tree/master/example/android/app/src/main/res

To change the back arrow in this case I can add `backButtonDrawable: "ic_back_arrow"`
