### ISSUE TITLE
sort bug

### ISSUE THREAD

**Issue by CoderXiaoming** [Sh1d0w/multi_image_picker#298]
![Snip20191106_8](https://user-images.githubusercontent.com/23111683/68305645-046c3d00-00e3-11ea-8a8c-47c5daa4954c.png)

**Comment by Sh1d0w** [comment]
Do you change the order of Assets passed into the selected array?

**Comment by CoderXiaoming** [comment]
> Do you change the order of Assets passed into the selected array?

yeah, changed

**Comment by Sh1d0w** [comment]
In such case please report this bug into the native library I am using for iOS, as the bug seems to be there I can't do much about it https://github.com/mikaoj/BSImagePicker

You can say that you change the order of selectedAssets but the order they re selected in the UI does not change.
