### ISSUE TITLE
flutter 1.10.15 handle

### ISSUE THREAD

**Issue by jinfagang** [Sh1d0w/multi_image_picker#299]
```
multi_image_picker-e07bd82fd2df52082fe5d034a3c5556350ceaa9f/lib/src/asset_thumb_
provider.dart:31:24: Error: The method 'AssetThumbImageProvider.load' has fewer positional arguments than those of overridden
method 'ImageProvider.load'.
  ImageStreamCompleter load(AssetThumbImageProvider key) {
                       ^
/Users/jintian/development/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden
method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Exception: Errors during snapshot creation: null
```

I believe lots of image related lib got this issue with latest flutter update:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.405, on Mac OS X 10.14.6 18G71a, locale en-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[!] Android Studio (not installed)
[✓] Connected device (2 available)
```

Does any fix on support master flutter for now?

**Comment by sh0umik** [comment]
I am getting the same problem after the 1.10.15 upgrade

**Comment by jinfagang** [comment]
@sh0umik  Flutter 1.10.15 is release today, author previous says he only maintains stable flutter.

Now if he doesn't catch up these updates of flutter, we should consider deperacat this old lib....

**Comment by kormemis** [comment]
I think he will catch-up if it is possible, he always did. :)

**Comment by jinfagang** [comment]
@kormemis  This error also happens on lib such as extend_image, image_picker... but they all changes for flutter master at least on git master branch..

**Comment by Sh1d0w** [comment]
Hi, this is now fixed in version 4.6.0-rc.1

**Comment by duongtruong12** [comment]
excuse me, did version v4.6.0-rc.3 has been removed

**Comment by Sh1d0w** [comment]
Yes, it is documented in the change log as it was not working properly neither on Android nor iOS. Recommended way of accessing image is as before to obtain the image data through the methods.

**Comment by duongtruong12** [comment]
> Yes, it is documented in the change log as it was not working properly neither on Android nor iOS. Recommended way of accessing image is as before to obtain the image data through the methods.

Thanks you, but i try to get file from asset but it cause exception like below:
`FileSystemException: Cannot retrieve length of file, path = '����`

the code i'm trying to get File:
` ByteData bd = await asset.getByteData(quality: 100);
   var pngBytes = bd.buffer.asUint8List();
   File f = new File.fromRawPath(pngBytes);`

do you know why? Thanks you

**Comment by Sh1d0w** [comment]
I don't believe that will work. Why are you trying to convert the ByteData to a file, you already have all you need to display the image?

**Comment by duongtruong12** [comment]
> I don't believe that will work. Why are you trying to convert the ByteData to a file, you already have all you need to display the image?

well i was trying convert to a file for upload to Server, the showing path was ok though.

**Comment by Sh1d0w** [comment]
You don't need a file to upload the image to a server, please checkout the docs https://sh1d0w.github.io/multi_image_picker/#/upload

**Comment by duongtruong12** [comment]
Wow thanks you so much. This is just what i need. It's not much but thanks to save my time on project
![Screenshot_20191128-002700_Chrome](https://user-images.githubusercontent.com/32258832/69745975-e475e980-1175-11ea-9262-27aa185e1ab4.jpg)
