### ISSUE TITLE
Ios compile error

### ISSUE THREAD

**Issue by Daibaku0615** [Sh1d0w/multi_image_picker#3]
Hi, I would like to use this package because I can manipulate many things and seems brilliant. 
But when run app error says this

`/Users/pusan0615/Desktop/flutter/demomo/ios/Pods/BSImageView/Source/BSImageView.swift:70:9: error: 'imageView' is inaccessible due to 'private' protection level
imageView.image = image
^
/Users/pusan0615/Desktop/flutter/demomo/ios/Pods/BSImageView/Source/BSImageView.swift:27:17: note: 'imageView' declared here
private let imageView: UIImageView = UIImageView(frame: .zero)
^
/Users/pusan0615/Desktop/flutter/demomo/ios/Pods/BSImageView/Source/BSImageView.swift:76:9: error: 'imageView' is inaccessible due to 'private' protection level
imageView.image = image
^
/Users/pusan0615/Desktop/flutter/demomo/ios/Pods/BSImageView/Source/BSImageView.swift:27:17: note: 'imageView' declared here
private let imageView: UIImageView = UIImageView(frame: .zero)
^
/Users/pusan0615/Desktop/flutter/demomo/ios/Pods/BSImageView/Source/BSImageView.swift:77:9: error: 'imageView' is inaccessible due to 'private' protection level
imageView.highlightedImage = highlightedImage
^
/Users/pusan0615/Desktop/flutter/demomo/ios/Pods/BSImageView/Source/BSImageView.swift:27:17: note: 'imageView' declared here
private let imageView: UIImageView = UIImageView(frame: .zero)
^
/Users/pusan0615/Desktop/flutter/demomo/ios/Pods/BSImageView/Source/BSImageView.swift:133:9: error: 'imageView' is inaccessible due to 'private' protection level
imageView.startAnimating()
^
/Users/pusan0615/Desktop/flutter/demomo/ios/Pods/BSImageView/Source/BSImageView.swift:27:17: note: 'imageView' declared here
private let imageView: UIImageView = UIImageView(frame: .zero)
^
/Users/pusan0615/Desktop/flutter/demomo/ios/Pods/BSImageView/Source/BSImageView.swift:138:9: error: 'imageView' is inaccessible due to 'private' protection level
imageView.stopAnimating()
^
/Users/pusan0615/Desktop/flutter/demomo/ios/Pods/BSImageView/Source/BSImageView.swift:27:17: note: 'imageView' declared here
private let imageView: UIImageView = UIImageView(frame: .zero)
^`

I added `use_frameworks!` and `config.build_settings['SWIFT_VERSION'] = '3.2'` but still not working
 
Do you have any idea how to fix it?

**Comment by Sh1d0w** [comment]
Hello, thanks for using the plugin.

Can you please run `flutter doctor` in your project and paste the output here?

Also can you please search for SWIFT_VERSION in your project and let me know to what version it is set?

**Comment by Daibaku0615** [comment]
Thank you for the quick reply.

this is **flutter doctor** 

`[flutter] flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale ja-JP)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    ✗ Brew not installed; use this to install tools for iOS device development.
      Download brew at https://brew.sh/.
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

! Doctor found issues in 2 categories.
exit code 0
`

I set it this because I saw issue says this worked out.
`config.build_settings['SWIFT_VERSION'] = '3.2'`

**Comment by Sh1d0w** [comment]
The [https://github.com/mikaoj/BSImagePicker](library) I use for the picker on iOS supports Swift 4.

Can you please set it to `config.build_settings['SWIFT_VERSION'] = '4.0'` and try again?

**Comment by Daibaku0615** [comment]
I just tried that and says

`"type metadata for Swift.Bool", referenced from:
multi_image_picker.SwiftMultiImagePickerPlugin.handle(__ObjC.FlutterMethodCall, result: (Any?) -> ()) -> () in multi_image_picker(SwiftMultiImagePickerPlugin.o)
"__swift_release", referenced from:
_swift_rt_swift_release in multi_image_picker(SwiftMultiImagePickerPlugin.o)
"static (extension in Swift):Swift.FixedWidthInteger.&<< infix<A where A1: Swift.BinaryInteger>(A, A1) -> A", referenced from:
multi_image_picker.SwiftMultiImagePickerPlugin.hexStringToUIColor(hex: Swift.String) -> __ObjC.UIColor in multi_image_picker(SwiftMultiImagePickerPlugin.o)
"Swift.String._compareDeterministicUnicodeCollation(Swift.String) -> Swift.Int", referenced from:
multi_image_picker.SwiftMultiImagePickerPlugin.handle(__ObjC.FlutterMethodCall, result: (Any?) -> ()) -> () in multi_image_picker(SwiftMultiImagePickerPlugin.o)
"__swift_getInitializedObjCClass", referenced from:
_swift_rt_swift_getInitializedObjCClass in multi_image_picker(SwiftMultiImagePickerPlugin.o)
"type metadata for Swift.String", referenced from:
multi_image_picker.SwiftMultiImagePickerPlugin.handle(__ObjC.FlutterMethodCall, result: (Any?) -> ()) -> () in multi_image_picker(SwiftMultiImagePickerPlugin.o)
type metadata accessor for [Swift.String : Swift.AnyObject] in multi_image_picker(SwiftMultiImagePickerPlugin.o)
closure #4 ([__ObjC.PHAsset]) -> () in multi_image_picker.SwiftMultiImagePickerPlugin.handle(__ObjC.FlutterMethodCall, result: (Any?) -> ()) -> () in multi_image_picker(SwiftMultiImagePickerPlugin.o)
multi_image_picker.SwiftMultiImagePickerPlugin.hexStringToUIColor(hex: Swift.String) -> __ObjC.UIColor in multi_image_picker(SwiftMultiImagePickerPlugin.o)
type metadata accessor for [Swift.String : Swift.String] in multi_image_picker(SwiftMultiImagePickerPlugin.o)
l_get_field_types_SwiftMultiImagePickerPlugin in multi_image_picker(SwiftMultiImagePickerPlugin.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Showing first 200 notices only`

Am I missing some setting or something?

**Comment by Sh1d0w** [comment]
Ok, I've just tried it on a new project created with `flutter create myapp`

There are several steps required, because the plugin is written in Swift, while the default flutter app comes with Objective-C syntax (for Swift syntax the create command have to be run with `-i swift` param).

Here are the steps in order to use the plugin in such case:

- flutter create myapp
- Add the plugin to your pubspec.yaml file `multi_image_picker: ^2.0.04` under dependencies
- Open `ios/Podfile` . Find `target 'Runner' do` line and after it, on the next line paste `use_frameworks!`, so it becomes:

```
target 'Runner' do
    use_frameworks!
    ......
```
Finally open you `ios/` folder with Xcode, in the left bar right click on Runner -> Create new file. From the window select Swift File, give it some dummy name. After you create it Xcode will prompt you to add a bridging header to you project (this is needed so the Objective-C code can talk to Swift libraries) click yes and you will be ready.

Let me know if this solves it for you. Also you can try to run the example provided in this repository, just `cd example && flutter run`.

**Comment by Daibaku0615** [comment]
Thank you so much it worked like a champ. You are life saver thanks again!

**Comment by Sh1d0w** [comment]
No worries, glad I could help.

**Comment by toby1991** [comment]
> Ok, I've just tried it on a new project created with `flutter create myapp`
> 
> There are several steps required, because the plugin is written in Swift, while the default flutter app comes with Objective-C syntax (for Swift syntax the create command have to be run with `-i swift` param).
> 
> Here are the steps in order to use the plugin in such case:
> 
> * flutter create myapp
> * Add the plugin to your pubspec.yaml file `multi_image_picker: ^2.0.04` under dependencies
> * Open `ios/Podfile` . Find `target 'Runner' do` line and after it, on the next line paste `use_frameworks!`, so it becomes:
> 
> ```
> target 'Runner' do
>     use_frameworks!
>     ......
> ```
> Finally open your `ios/` folder with Xcode, in the left bar right click on Runner -> Create new file. From the window select Swift File, give it some dummy name. After you create it Xcode will prompt you to add a bridging header to you project (this is needed so the Objective-C code can talk to Swift libraries) click yes.
> 
> * While still in Xcode click on Runner -> Build Settings. Search for Swift Version and change it to 4.1
> 
> After that you will be good to go.
> 
> Let me know if this solves it for you. Also you can try to run the example provided in this repository, just `cd example && flutter run`.

I think the doc should be improved by this.

**Comment by Sh1d0w** [comment]
@toby1991 I agree. This however is a known problem with projects created with older Flutter version as described in their official docs:

https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated

I will add this link to the documentation of the image picker as well.
