### ISSUE TITLE
help!help~~~V4.5.9，Android Compile failed methods: 71200 > 65536

### ISSUE THREAD

**Issue by kangkanger** [Sh1d0w/multi_image_picker#302]
D8: Cannot fit requested classes in a single dex file (# methods: 71200 > 65536)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: D:\demo_work\flutter_ruyi\build\app\intermediates\transforms\dexBuilder\debug\0.jar, D:\demo_work\flutter_ruyi\build\app\intermediates\transforms\dexBuilder\debug\1.jar, D:\demo_work\flutter_ruyi\build\app\intermediates\transforms\dexBuilder\debug\2.jar, D:\demo_work\flutter_ruyi\build\app\intermediates\transforms\dexBuilder\debug\3.jar, D:\demo_work\flutter_ruyi\build\app\intermediates\transforms\dexBuilder\debug\8.jar, D:\demo_work\flutter_ruyi\build\app\intermediates\transforms\dexBuilder\debug\9.jar, 
......
D:\demo_work\flutter_ruyi\build\app\intermediates\transforms\dexBuilder\debug\59.jar
  The number of method references in a .dex file cannot exceed 64K.
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 48s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by Sh1d0w** [comment]
You need to migrate your project to Android X as described in the docs.
