### ISSUE TITLE
Pick from internal storage

### ISSUE THREAD

**Issue by guit4eva** [Sh1d0w/multi_image_picker#304]
Is it possible to select images from internal storage, similar to [image_picker](https://pub.dev/packages/image_picker)? At the moment, it's only possible to select images from "Album" which is very limiting when choosing images.

For example:

image_picker:
https://ibb.co/zVCy3N0

multi_image_picker:
https://ibb.co/Cw7N4LP

**Comment by Sh1d0w** [comment]
Please open a feature request in FishBun (the android plugin I am using you can see the link in the reademe). If they implement it, I will add support no problems. There isn’t much I can do about it otherwise.
