### ISSUE TITLE
Where can I change the following prompt text

### ISSUE THREAD

**Issue by kinsens** [Sh1d0w/multi_image_picker#307]
![image](https://user-images.githubusercontent.com/31468203/68736102-b099b080-061a-11ea-8593-a3bd0a3501e3.png)

**Comment by Sh1d0w** [comment]
Please read the doc https://sh1d0w.github.io/multi_image_picker/#/theming . You need to pass `selectionLimitReachedText`

**Comment by kinsens** [comment]
sorry, I didn't read your instructions carefully. I will read the following carefully later. Thank you very much
