### ISSUE TITLE
error while debugging on ios device

### ISSUE THREAD

**Issue by ektelat** [Sh1d0w/multi_image_picker#308]
when i treid to debug on ios device all the time i get an error related to mutli image picke
and just when i removed the package it's work fine. this is the error:
 2019-11-12 16:39:30.354 xcodebuild[2340:28658]  iPhoneSupport:
    📱<DVTiOSDevice (0x7fbdb5fc7a10), iPhone, iPhone, 13.1.3 (17A878),
    00008030-00050D121150802E> unable to mount DeveloperDiskImage (Error
    Domain=com.apple.dtdevicekit Code=-402653035 "Xcode encountered an error"
    UserInfo={NSLocalizedFailureReason=The device rejected the pairing
    attempt., com.apple.dtdevicekit.stacktrace=(
        0   DTDeviceKitBase                     0x000000011d1cf6e7
        DTDKCreateNSError + 109
        1   DTDeviceKitBase                     0x000000011d1cfde9
        DTDK_AMDErrorToNSError + 792
        2   DTDeviceKitBase                     0x000000011d20d780
        -[DTDKMobileDeviceToken _mountDeveloperDiskImage:withError:] + 844
        3   DTDeviceKitBase                     0x000000011d20e29d
        __58-[DTDKMobileDeviceToken
        mountDeveloperDiskImageWithError:]_block_invoke + 699
        4   libdispatch.dylib                   0x00007fff6d09f50e
        _dispatch_client_callout + 8
        5   libdispatch.dylib                   0x00007fff6d0ab8b3
        _dispatch_sync_invoke_and_complete_recurse + 65
        6   libdispatch.dylib                   0x00007fff6d0ab426
        _dispatch_sync_f_slow + 195
        7   DTDeviceKitBase                     0x000000011d20df80
        -[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:] + 199
        8   IDEiOSSupportCore                   0x000000011cdf3107
        __28-[DVTiOSDevice attachToken:]_block_invoke_4 + 254
        9   DVTFoundation                       0x000000010dbf23ba
        __DVT_CALLING_CLIENT_BLOCK__ + 7
        10  DVTFoundation                       0x000000010dbf3a92
        __DVTDispatchAsync_block_invoke + 809
        11  libdispatch.dylib                   0x00007fff6d09e583
        _dispatch_call_block_and_release + 12
        12  libdispatch.dylib                   0x00007fff6d09f50e
        _dispatch_client_callout + 8
        13  libdispatch.dylib                   0x00007fff6d0a16c0
        _dispatch_continuation_pop + 414
        14  libdispatch.dylib                   0x00007fff6d0a0dbe
        _dispatch_async_redirect_invoke + 703
        15  libdispatch.dylib                   0x00007fff6d0ad7e2
        _dispatch_root_queue_drain + 326
        16  libdispatch.dylib                   0x00007fff6d0adf22
        _dispatch_worker_thread2 + 92
        17  libsystem_pthread.dylib             0x00007fff6d2fc6d5
        _pthread_wqthread + 220
        18  libsystem_pthread.dylib             0x00007fff6d2fc57b
        start_wqthread + 15
    ), DVTRadarComponentKey=487927, NSLocalizedDescription=Xcode encountered
    an error})
    ** BUILD FAILED **

Xcode's output:
↳
    /**Users/mac/development/flutter/.pub-cache/hosted/pub.dartlang.org/multi_i
    mage_picker-4.5.9/ios/Classes/MultiImagePickerPlugin.m:2:9: fatal error:
    'multi_image_picker/multi_image_picker-Swift.h' file not found
    #import <multi_image_picker/multi_image_picker-Swift.h>**
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    **1 error generated.
    **/Users/mac/development/flutter/.pub-cache/hosted/pub.dartlang.org/multi_i
    mage_picker-4.5.9/ios/Classes/MultiImagePickerPlugin.m:2:9: fatal error:
    'multi_image_picker/multi_image_picker-Swift.h' file not found
    #import <multi_image_picker/multi_image_picker-Swift.h>****
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to
    5.0, but the range of supported deployment target versions is 8.0 to
    13.2.99. (in target 'Mantle' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to
    6.0, but the range of supported deployment target versions is 8.0 to
    13.2.99. (in target 'Reachability' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to
    5.0, but the range of supported deployment target versions is 8.0 to
    13.2.99. (in target 'leveldb-library' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to
    4.3, but the range of supported deployment target versions is 8.0 to
    13.2.99. (in target 'FMDB' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to
    7.0, but the range of supported deployment target versions is 8.0 to
    13.2.99. (in target 'Protobuf' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to
    7.0, but the range of supported deployment target versions is 8.0 to
    13.2.99. (in target 'GTMSessionFetcher' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to
    4.3, but the range of supported deployment target versions is 8.0 to
    13.2.99. (in target 'nanopb' from project 'Pods')
    build session not created after 15 seconds - still waiting

Could not build the precompiled application for the device.

Error launching application on iPhone.

**Comment by Sh1d0w** [comment]
You need to create a bridging header as described in the docs, or re-create your project with Swift support with `flutter create -i swift .`
