### ISSUE TITLE
localizations function is incomplete on iOS platform.

### ISSUE THREAD

**Issue by glennWang** [Sh1d0w/multi_image_picker#309]
As the title say,  localizations function is incomplete  on iOS platform.

My iOS simulator is already selecting simple-Chinese, however,   upper-right corner still display English "Done".

And,  I think a fraction like 2/3 on Android platform will be better than only a number on iOS platform.

![image](https://user-images.githubusercontent.com/7918942/68932166-fdbd8400-07cc-11ea-84d2-422615629e63.png)

**Comment by Sh1d0w** [comment]
Please open an issue and n BSImagePicker repo, I can’t do anything about that as this is third party library I am using. Once implemented there I will update the version used here.
