### ISSUE TITLE
iOS failed to issue sandbox extension for file

### ISSUE THREAD

**Issue by bogdannedelcu** [Sh1d0w/multi_image_picker#310]
**Bug Report**

`multi_image_picker` version: 4.5.9

Is it happening on Android: No

Is it happening on iOS: Yes 

On iOS Phisical device i get: "failed to issue sandbox extension for file  file:////var/mobile/Media/DCIM/107APPLE/IMG_9011.JPG, errno = 1"  after I select an image and try to read it and use in my app.

What settings Am I Missing. I enabled AppSandbox access to Pictures Folder, 

Thank you

**Comment by Sh1d0w** [comment]
Can you please provide more info? Where the image is located? Did you pick it from the iOS gallery?

**Comment by Sh1d0w** [comment]
Actually see https://github.com/Sh1d0w/multi_image_picker/issues/319

If you are accessing the url directly, don't do it. Use the methods getByteData or getThumbData
