### ISSUE TITLE
can you create a short video that how to create this multi image picker component for my own app i m getting ambiguity that what are the files to edit to perform this multi image picker component and which version are you using in this project i didnt get that

### ISSUE THREAD

**Issue by mubeenalam5** [Sh1d0w/multi_image_picker#311]
**Bug Report**

`multi_image_picker` version: 

Is it happening on Android: 

Is it happening on iOS: 

```
 <!-- run `flutter doctor` and paste the output here: -->
```

**Describe the bug**

**Comment by Sh1d0w** [comment]
You can read the documentation for the plugin and also there is an example app in the example folder of this repository.
