### ISSUE TITLE
how to change back and confirm button icon color ?

### ISSUE THREAD

**Issue by iyuhang** [Sh1d0w/multi_image_picker#312]
**Bug Report**

`multi_image_picker` version: 4.5.9

Is it happening on Android: yes

Is it happening on iOS: yes

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G87, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)

• No issues found!
```

**Describe the bug**

how to change the confirm and back button icon color when set the status bar color white ??

![Screenshot_20191117-222801](https://user-images.githubusercontent.com/14176635/69009101-4885fa00-098d-11ea-9d8b-658c6bdc8681.jpg)

**Comment by Sh1d0w** [comment]
https://sh1d0w.github.io/multi_image_picker/#/theming?id=android-customization

**Comment by iyuhang** [comment]
actionBarColor - HEX string
actionBarTitleColor - HEX string
actionBarTitleColor - HEX string
statusBarColor - HEX string
selectCircleStrokeColor - HEX string

I only found this keys above, no key to set the back and confirm button color.

**Comment by Sh1d0w** [comment]
You have okButtonDrawable and backButtonDrawable so you can provide whatever color icons you want for the back and done button.
