### ISSUE TITLE
The three values enclosed by the red frame can I modify it? I want to change to Chinese.

### ISSUE THREAD

**Issue by gaojuanjuan** [Sh1d0w/multi_image_picker#313]
![image](https://user-images.githubusercontent.com/14133759/69047942-4a0bfc80-0a37-11ea-9c4d-0cdaf72a76da.png)

**Comment by Sh1d0w** [comment]
Please refer to the BSImagePicker repository. This is the native plugin I am using for iOS.

Those links may help you:

https://github.com/mikaoj/BSImagePicker/issues/229
https://github.com/mikaoj/BSImagePicker/issues/226
