### ISSUE TITLE
getThumbByteData with QUALITY parameters return wrong quality of images on iOS

### ISSUE THREAD

**Issue by Huuvt** [Sh1d0w/multi_image_picker#317]
**Bug Report**

`multi_image_picker` version: ^4.5.9

Is it happening on Android:  
NO

Is it happening on iOS:  
YES, ONLY ON iOS

```
 <!-- run `flutter doctor` and paste the output here: -->
```
Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.9.1+hotfix.6 at /Users/apple/developments/src_flutter/flutter
    • Framework revision 68587a0916 (10 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.2

**Describe the bug**

+ pubspec.yaml:  multi_image_picker:  ^4.5.9

+ Try to use getThumbByteData with multiple QUALITY parameter on iOS (less than 100) return the same quality of images
1) QUALITY = 50 --> return image of 42kB that compressed from original image 450kB
2) QUALITY = 60 --> still return image of 42kB that compressed from original image 450kB (same 1)
3) QUALITY = 70 --> still return image of 42kB that compressed from original image 450kB (same 1)
4) QUALITY = 80 --> still return image of 42kB that compressed from original image 450kB (same 1)
5) QUALITY = 90 --> still return image of 42kB that compressed from original image 450kB (same 1)

+ This bug only happens on iOS, it's working fine on Andriod

Thank you

**Comment by Sh1d0w** [comment]
I am using [UIImage.jpegData](https://github.com/Sh1d0w/multi_image_picker/blob/master/ios/Classes/SwiftMultiImagePickerPlugin.swift#L209), which accepts [compressionQuality](https://developer.apple.com/documentation/uikit/uiimage/1624115-jpegdata) param. I guess this is what iOS can offer, there is big difference in file size between 100 and the rest.

I am not fluent enough to say how exactly iOS compresses the image, but I don't think there is much I can do about this.

Feel free to open a PR if you find better solution and I will review it.
