### ISSUE TITLE
required a higher minimum deployment target.

### ISSUE THREAD

**Issue by thief1010** [Sh1d0w/multi_image_picker#320]
**Bug Report**

`multi_image_picker` version: 

Is it happening on Android: 

Is it happening on iOS: YES

```
 <!-- run `flutter doctor` and paste the output here: -->
```

**Describe the bug**

when I run ''pod install'' ,it has showed 
[!] CocoaPods could not find compatible versions for pod "multi_image_picker":
  In Podfile:
    multi_image_picker (from `.symlinks/plugins/multi_image_picker/ios`)

Specs satisfying the `multi_image_picker (from `.symlinks/plugins/multi_image_picker/ios`)` dependency were found, but they required a higher minimum deployment target.

next I run ''vim podfile'' and modified the ios minimum  dependenced version with 10.0,but it still counldn't work

**Comment by Sh1d0w** [comment]
Could be something with the cache. Can you remove the plugin and add it again to your project?

**Comment by thief1010** [comment]
> Could be something with the cache. Can you remove the plugin and add it again to your project?

I have done it with your idea,but it also couldn't work!

**Comment by Sh1d0w** [comment]
Please provide example repo where I can reproduce the issue.

**Comment by nightfallsad** [comment]
> **Bug Report**
> 
> `multi_image_picker` version:
> 
> Is it happening on Android:
> 
> Is it happening on iOS: YES
> 
> ```
>  
> ```
> 
> **Describe the bug**
> 
> A clear and concise description of what the bug is.
> 
> when I run ''pod install'' ,it has showed
> [!] CocoaPods could not find compatible versions for pod "multi_image_picker":
> In Podfile:
> multi_image_picker (from `.symlinks/plugins/multi_image_picker/ios`)
> 
> Specs satisfying the `multi_image_picker (from `.symlinks/plugins/multi_image_picker/ios`)` dependency were found, but they required a higher minimum deployment target.
> 
> next I run ''vim podfile'' and modified the ios minimum dependenced version with 10.0,but it still counldn't work

Same issue and resolved it.Check your project profiles carefully,must be somewhere the target version is less than 10.0.

**Comment by jiandandkl** [comment]
ios/Runner.xcodeproj/project.pbxproj
IPHONEOS_DEPLOYMENT_TARGET = 8.0; --> 9.0
