### ISSUE TITLE
fatal error: 'multi_image_picker/multi_image_picker-Swift.h' file not found

### ISSUE THREAD

**Issue by nightfallsad** [Sh1d0w/multi_image_picker#325]
When I used multi_image_picker to my flutter_module project and run the project on iphone,it threw an error like 'fatal error: 'multi_image_picker/multi_image_picker-Swift.h' file not found#import <multi_image_picker/multi_image_picker-Swift.h>'.It seems like a hybrid programming problem.
flutter doctor
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.1)
[✓] Connected device (1 available)

multi_image_picker-4.5.9

**Comment by Sh1d0w** [comment]
Your project does not have Swift support. Either create bridingin header as described in the plugin docs or re - create your project with Sift support enabled.

**Comment by nightfallsad** [comment]
> Your project does not have Swift support. Either create bridging header as described in the plugin docs or re - create your project with Sift support enabled.

All right,thanks.
