### ISSUE TITLE
Flutter 1.11.0 • channel beta 

### ISSUE THREAD

**Issue by beiger** [Sh1d0w/multi_image_picker#328]
class **AssetThumbImageProvider**  ....

@override
  ImageStreamCompleter load(AssetThumbImageProvider key) {
    return new MultiFrameImageStreamCompleter(
      codec: _loadAsync(key),
      scale: key.scale,
    );
  }

isn't a valid override of ImageProvider.load

**Comment by Sh1d0w** [comment]
The plugin supports Flutter on the stable channel, you are not using the stable version of Flutter.

If you want to use unstable version which is not recommended you can install version 4.6.0-rc.3 of this plugin and you won’t get this error.
