### ISSUE TITLE
The getter 'filePath' isn't defined for the class 'Asset'.

### ISSUE THREAD

**Issue by guit4eva** [Sh1d0w/multi_image_picker#329]
After upgrading to **4.6.0-rc.3**, I'm getting the following error:

> The getter 'filePath' isn't defined for the class 'Asset'

What is the correct way of obtaining the file path now?

```
// -----------------------------------------------------------------------------
// Convert Asset to File
// -----------------------------------------------------------------------------
  Future<File> _convertAssetToFile(String path) async {
    final file = File(path);
    return file;
  }

// -----------------------------------------------------------------------------
// Select Multiple Images
// -----------------------------------------------------------------------------
  Future<void> pickMultipleImages(
      {List<File> tmpGalleryImages, int imageLimit, int index, String insertAt, Function callback}) async {
    try {
      await MultiImagePicker.pickImages(
        maxImages: imageLimit - tmpGalleryImages.length,
      ).then(
        (chosenImages) async {
          for (var asset in chosenImages) {
            await _convertAssetToFile(await asset.filePath).then(
              (convertedFile) {
                if (index == null) tmpGalleryImages.add(convertedFile);
                if (index != null)
                  insertAt == "left"
                      ? tmpGalleryImages.insertAll(index, [convertedFile])
                      : tmpGalleryImages.insertAll(index + 1, [convertedFile]);
              },
            );
          }
        },
      );
    } on Exception catch (e) {
      print(e.toString());
    }

    multipleImageSink.add(tmpGalleryImages);
    callback(tmpGalleryImages);
  }
```

**Comment by Sh1d0w** [comment]
The correct way was and always has been `getByteData` or `getThumbByteData`. The filePath property was introduced recently as experimental, but has numerous issues on Android and iOS as both systems added a lot of restrictions to how files are accessed, so I've decided to remove it. 

You can see example usage in the plugin docs or the example folder.

**Comment by guit4eva** [comment]
> The correct way was and always has been `getByteData` or `getThumbByteData`. The filePath property was introduced recently as experimental, but has numerous issues on Android and iOS as both systems added a lot of restrictions to how files are accessed, so I've decided to remove it.
> 
> You can see example usage in the plugin docs or the example folder.

I'm only able to find examples of filePath in the docs and GitHub example? I tried to use getByteData after reading the changelog, but I'm not 100% sure how to actually get the URL that way. If you could point me in the right direction to an example, I'd really appreciate that. I'm properly stumped at the moment

**Comment by Sh1d0w** [comment]
The docs reflect the current stable version which is 4.5.9. File path is removed in the RC version which currently supports flutter master channel because of a breaking change made there.

You don't need the file url, with those two methods I gave you you have everything you need to display an image or upload it to a server.

Generally speaking file paths are only trouble as recent versions of Android and iOS have plenty of restrictions (e.g. on iOS returned file paths since iOS 13 are temporary and you can access them only for a short period of time, where in android the content URIs are also not alway posting to a files. Not to mention on iOS all images since iOS 11 are in HEIC format, which flutter does not support yet. This is however automatically handled and converted to a JPEG when you use `getByteData` or `getThumbByteData`).

**Comment by guit4eva** [comment]
Thanks so much for that insightful reply. That's a real problem about the file paths becoming troublesome to work with. At the moment, I have structured my whole app so that a user is guided through different screens to set up an event - where the image paths are stored in a map until the event is submitted, after which they are then uploaded to Firestorage. With Multi Image Picker, is there any way around this limitation, or would the app have to be structured in a way that the images are always uploaded straight away to Firestorage after being selected?

**Comment by guit4eva** [comment]
Sorry, ignore that previous message. Confusing myself heavily here after not enough sleep!
