### ISSUE TITLE
Question - Is there any change to close image picker?

### ISSUE THREAD

**Issue by I-am-original** [Sh1d0w/multi_image_picker#33]
I would like to close image picker by some action. While our app collapsed. Is there any chance?

Thanks a lot

**Comment by I-am-original** [comment]
@Sh1d0w actually I am interested more in image picker, run inside of app, without usage of native Android and iOS libs. In that case - our Flutter app would not go to background. And it would be the best case. But For now while app going to background, and then picker shown - while collapsing app - we will return to picker, but it would be cool to close picker and resume our app instead of picker. As an option - some kind of flag - to close picker while app collapsed.

**Comment by Sh1d0w** [comment]
@I-am-original The usage of native Android and iOS libs, I make sure the user experience is the best the platform can provide - both from performance and usability.

If you want a pure flutter image picker, you may take a look at https://github.com/CaiJingLong/flutter_photo - this is exactly what are you looking for, but in my opinion is too clunky and buggy yet. I hope the maintainer can make it better in the future.

I will consider your feature request, but first I will need to do some research how best (and if) it can be implemented in my package.

Will close the issue now.
