### ISSUE TITLE
Resizing an image

### ISSUE THREAD

**Issue by guit4eva** [Sh1d0w/multi_image_picker#330]
Is there a way to resize an image after selection? ie, maxWidth = 200

**Comment by Sh1d0w** [comment]
Please read the docs it is all explained there https://sh1d0w.github.io/multi_image_picker/#/imagedata?id=thumbnail-data

**Comment by guit4eva** [comment]
As far as I'm aware, using getThumbByteData crops the image? I'm trying to find out if it's possible to resize the image without cropping - this will then be uploaded as a smaller file to Firestorage

**Comment by Sh1d0w** [comment]
You can open a feature request, however if you urgent need this I will gladly review and accept a PR introducing this functionality to the plugin.

The current implementation crops the image that’s correct. A possible solution is to create two new methods getCroppedByteData and getResizedByteData. First one will do what the current implementation does, and the old getThumbData method will be marked as deprecated.

**Comment by guit4eva** [comment]
I definitely think that would be extremely useful to users of the plugin. There's not really any other viable options out there, and every workaround I've seen so far has been very cumbersome. How difficult would it be to implement resizing into multi_image_picker?
