### ISSUE TITLE
iOS has no camera icon button

### ISSUE THREAD

**Issue by mfkwgizhoujian** [Sh1d0w/multi_image_picker#332]
**Bug Report**

`multi_image_picker` version: 4.5.9

Is it happening on Android: No

Is it happening on iOS: Yes

```
 Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale
    zh-Hans-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/setup/#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Describe the bug**

Enable camera on iOS, has no camera icon button, how can I take a photo use camera?
iOS:
![image](https://user-images.githubusercontent.com/33543763/69924395-2096aa80-14e6-11ea-9309-5a0c077dc1bd.png)

Android:
![image](https://user-images.githubusercontent.com/33543763/69924440-5e93ce80-14e6-11ea-9931-927c7f2f16bb.png)

**Comment by Sh1d0w** [comment]
This is not a bug this is how iOS simulator works.

iOS simulators does not have cameras, thats why you don’t see the camera icon.

If you run the app on a real device it will show up.

**Comment by mfkwgizhoujian** [comment]
> This is not a bug this is how iOS simulator works.
> 
> iOS simulators does not have cameras, thats why you don’t see the camera icon.
> 
> If you run the app on a real device it will show up.

I see, thank u.
