### ISSUE TITLE
Failed resolution of: Landroid/support/v4/util/ArrayMap;

### ISSUE THREAD

**Issue by guqun** [Sh1d0w/multi_image_picker#336]
**Bug Report**
there is a compile error. is there an resloution to fix it. thanks
`multi_image_picker` version: 4.5.9

Is it happening on Android: yes

Is it happening on iOS:no

```
 <!-- run `flutter doctor` and paste the output here: -->
```

**Describe the bug**

java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArrayMap;
E/AndroidRuntime(13477): 	at com.sangcomz.fishbun.adapter.image.impl.GlideAdapter.loadImage(GlideAdapter.java:17)
E/AndroidRuntime(13477): 	at com.sangcomz.fishbun.adapter.view.AlbumListAdapter.onBindViewHolder(AlbumListAdapter.java:56)
E/AndroidRuntime(13477): 	at com.sangcomz.fishbun.adapter.view.AlbumListAdapter.onBindViewHolder(AlbumListAdapter.java:25)
E/AndroidRuntime(13477): 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
E/AndroidRuntime(13477): 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
E/AndroidRuntime(13477): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
E/AndroidRuntime(13477): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
E/AndroidRuntime(13477): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
E/AndroidRuntime(13477): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
E/AndroidRuntime(13477): 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
E/AndroidRuntime(13477): 	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:557)
E/AndroidRuntime(13477): 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
E/AndroidRuntime(13477): 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
E/AndroidRuntime(13477): 	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
E/AndroidRuntime(13477): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
E/AndroidRuntime(13477): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
E/AndroidRuntime(13477): 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)

**Comment by Sh1d0w** [comment]
Yes, as described in the plugin docs the plugin version you are using required your project to be migrated to Android X.

You can migrate to Android X through Android Studio as described in Google Android Developer docs.

**Comment by guqun** [comment]
thank you, i have resloved it!

**Comment by helloJincheng** [comment]
Add these two lines to `project_folder/android/gradle.properties:`
```
android.useAndroidX=true
android.enableJetifier=true
```
