### ISSUE TITLE
Could you please add the filePath option for the new version as the old ones ? thanks

### ISSUE THREAD

**Issue by DyaryRaoof** [Sh1d0w/multi_image_picker#337]
**Is your feature request related to a problem? Please describe.**
I have a problem with picking multiple images and sending them over to server. 
Here is a scenario ; I pick multiple images , I have the option to delete these images or have them later sent to server. 
in this case to get the path for the images I need to first use the getByteDate , then convert that to Unit8List. then right the file. Then get the filePath for that image and pass it along the pipeline before sending it to serve.

When it is actually time to send the files to severI have to get the saved file path from memory and load the byte data and send them over to server as base64.

It's a lot of hassle doing the above steps for no good reason at all. It has made my app very unstable and it crashes a lot.
So cold you please add the option for getting filePath to the new rc version. Any help is appreciated. Thanks.

**Comment by Sh1d0w** [comment]
The filePath was removed because it was not working at all on iOS 13. On iOS 13 file paths now have short expiration time, meaning even if you obtain a file path you have several seconds to do something with it and then it expires and is no longer usable. There was also problem on Android where file path for image taken with camera was incorrect.

Actually filePath was never needed it was added as experiment which turned out to be not good. Using the getByteData method is always reliable to work.

In your case you are doing things wrong. You don’t need to save file paths nor you need to request byte data when you pick the images or base64 encode it when you are sending it to the server.

Asset class has the identifier property which is the only thing needed to reconstruct the image resource picked by the picker. When you pick some images you can store the identifier instead of file path. Later when you want to upload your selection of images to the server just re create the asset class passing the identifier. You can upload the images following the docs https://sh1d0w.github.io/multi_image_picker/#/upload

**Comment by DyaryRaoof** [comment]
Thank you so much for the prompt response and for creating this awesome plugin. Please keep up the good work. I love your work.

And Just as a side note ,  having this info in the docs would be really helpful to others as  well because the docs are not yet updated and still rely on the `filePath`. 

Again thank you so much.

**Comment by mostafambestawy** [comment]
on recreating asset from identifier,there are other three mandatory parameters (_name,_originalWidth,_originalHeight,)

**Comment by mostafambestawy** [comment]
> The filePath was removed because it was not working at all on iOS 13. On iOS 13 file paths now have short expiration time, meaning even if you obtain a file path you have several seconds to do something with it and then it expires and is no longer usable. There was also problem on Android where file path for image taken with camera was incorrect.
> 
> Actually filePath was never needed it was added as experiment which turned out to be not good. Using the getByteData method is always reliable to work.
> 
> In your case you are doing things wrong. You don’t need to save file paths nor you need to request byte data when you pick the images or base64 encode it when you are sending it to the server.
> 
> Asset class has the identifier property which is the only thing needed to reconstruct the image resource picked by the picker. When you pick some images you can store the identifier instead of file path. Later when you want to upload your selection of images to the server just re create the asset class passing the identifier. You can upload the images following the docs https://sh1d0w.github.io/multi_image_picker/#/upload

on recreating asset from identifier,there are other three mandatory parameters (_name,_originalWidth,_originalHeight,)
could you please explain how to re create the asset class passing the identifier

**Comment by Sh1d0w** [comment]
@mostafambestawy If you need those you can save them along with the identifier and pass them to the constructor. Otherwise you can pass just dummy values, the only thing the plugin uses in order to obtain the image data, thumbs etc is the identifier, rest are just for reference on dart side.

**Comment by duzenko** [comment]
@Sh1d0w 

> On iOS 13 file paths now have short expiration time, meaning even if you obtain a file path you have several seconds to do something with it and then it expires and is no longer usable.

Are you sure you're doing this right? Are you retaining the reference to the underlying native NSDictionary<>?

**Comment by Sh1d0w** [comment]
@duzenko Unfortunately this won't work, as the plugin does not keep the PHAsset objects in memory.

The way flutter plugins work is that they communicate with the native side through so called method channels. When you want to request something from the native platform you fire a call to the method channel and then return the response through it.

So the plugin just retrieves the selected PHAssets from the native picker, serializes the data the dart part expects and returns it through the method channel back to Flutter where you actually store the objects and the references under the Asset instance.

Honestly as I said many times before you don't need file paths for many reasons and the effort to implement such functionality is not acceptable for me.

**Comment by duzenko** [comment]
Maybe you could keep the reference in native code and clear it from a separate call when your Asset instance gets disposed.
Anyway I guess I can live without the directory name in my project as long you still provide the file name.

**Comment by LeDuyTho** [comment]
No need filePath in new version, I can get base64 from image like this code:
```
/// --new api: data upload multipick--------------
    List<Upload> lstUpload = [];

    for (int i = 0; i < images.length; i++) {
      /// new multi_picker_img lib------
      // https://sh1d0w.github.io/multi_image_picker/#/upload
      ByteData byteData = await images[i].getByteData();
      String base64String =
          await Base64Utils.getBase64StringFromByteData(byteData);

      String fileName = FileUtils.getFileName(images[i].name);
      String fileExtension = FileUtils.getFileExtension(images[i].name);

      Upload upload = new Upload(
        fileContent: base64String,
        fileName: fileName,
        fileExtension: fileExtension,
      );

      print('base64 last10char=' +
          base64String.substring(base64String.length - 10));
      print('name=' + fileName);
      print('ex=' + fileExtension);

      lstUpload.add(upload);
    }
```

And utils get base64:
```
static Future<String> getBase64StringFromByteData(ByteData byteData) async {
    try {
      Uint8List fileBytes = byteData.buffer.asUint8List();
      String base64String = base64.encode(fileBytes);
      return base64String;
    } catch (e) {
      // if path invalid or not able to read
      print(e);
    }
    return '';
  }
```
