### ISSUE TITLE
crash in iphoneX

### ISSUE THREAD

**Issue by monnguyen2512** [Sh1d0w/multi_image_picker#339]
**Bug Report**

`multi_image_picker` version: 4.5.9

Is it happening on Android: NO

Is it happening on iOS: YES (iPhone X)

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

```

**Describe the bug**
Pick images one time: ok
Pick images second time: images does not display and crash if swipe down.
![Image from iOS](https://user-images.githubusercontent.com/56006777/70694606-9a9f0e80-1cf2-11ea-893c-29e34e096ef1.png)

**Comment by Sh1d0w** [comment]
Please report this to the BSImagePicker repository (the native ios library I use to present the ios image picker) and provide full log from XDebug with the crash dump

https://github.com/mikaoj/BSImagePicker
