### ISSUE TITLE
App crashes in Android after allowing camera and storage permission

### ISSUE THREAD

**Issue by SureshSc** [Sh1d0w/multi_image_picker#341]
**Bug Report**

`multi_image_picker` version: 4.6.0

Is it happening on Android: Yes

Is it happening on iOS: No

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.12.13, on Mac OS X 10.15.2 19C57, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2019.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.40.2)
[✓] Connected device (2 available)
```

**Describe the bug**

The app is getting crash after user allows storage and camera permission in Android greater than Version 8.

Its getting crash in **multiimagepickerplugin** line 107 refer screenshot 
 ```
 
public boolean onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        if (requestCode == REQUEST_CODE_GRANT_PERMISSIONS && permissions.length == 3) {
            if (grantResults[0] == PackageManager.PERMISSION_GRANTED
                    && grantResults[1] == PackageManager.PERMISSION_GRANTED
                    && grantResults[2] == PackageManager.PERMISSION_GRANTED) {
                int maxImages = (int) this.methodCall.argument(MAX_IMAGES);
                boolean enableCamera = (boolean) this.methodCall.argument(ENABLE_CAMERA);
                HashMap<String, String> options = this.methodCall.argument(ANDROID_OPTIONS);
                ArrayList<String> selectedAssets = this.methodCall.argument(SELECTED_ASSETS);
                assert options != null;
                presentPicker(maxImages, enableCamera, selectedAssets, options);
            } else {
                if (
                        ActivityCompat.shouldShowRequestPermissionRationale(activity, Manifest.permission.READ_EXTERNAL_STORAGE) ||
                                ActivityCompat.shouldShowRequestPermissionRationale(activity, Manifest.permission.WRITE_EXTERNAL_STORAGE) ||
                                ActivityCompat.shouldShowRequestPermissionRationale(activity, Manifest.permission.CAMERA)) {
                    finishWithError("PERMISSION_DENIED", "Read, write or camera permission was not granted");
                } else{
                    finishWithError("PERMISSION_PERMANENTLY_DENIED", "Please enable access to the storage and the camera.");
                }
                return false;
            }

            return true;
        }
        finishWithError("PERMISSION_DENIED", "Read, write or camera permission was not granted");
        return false;
    }

```

Crashing line:  `int maxImages = (int) this.methodCall.argument(MAX_IMAGES);`

It happens first time alone
<img width="1083" alt="Screenshot 2019-12-12 at 8 10 50 PM" src="https://user-images.githubusercontent.com/5052940/70721810-43ae2f00-1d1c-11ea-8c1e-aa2c3fce322b.png">

Crash log:

<img width="1378" alt="Screenshot 2019-12-12 at 8 20 32 PM" src="https://user-images.githubusercontent.com/5052940/70722357-262d9500-1d1d-11ea-9b5f-2f507416d0a9.png">

Implementation:
```

resultList = await MultiImagePicker.pickImages(
        maxImages: 1,
        enableCamera: true,
);

```

**Comment by IwantBEStrong** [comment]
I had the same problem

**Comment by IwantBEStrong** [comment]
![image](https://user-images.githubusercontent.com/26560902/70784096-65fb8780-1dc4-11ea-93fd-5cc02ce5e6b4.png)

**Comment by 2607861760** [comment]
I had the same problem.        
Please enable access to the storage and the camera.

**Comment by shiyiya** [comment]
the same problem.

```

 try {
      resultList =
          await MultiImagePicker.pickImages(maxImages: 5, enableCamera: true);
    } on Exception catch (e) {
      print('===error $e===');
    }


env:

sdk: '>=2.2.2 <3.0.0'
 Flutter (Channel stable, v1.12.13+hotfix.5
one plus 7 android 10
```

**Comment by dimiril** [comment]
I had the same problem

**Comment by dimiril** [comment]
Plz fix this problem

**Comment by dimiril** [comment]
?????????

**Comment by Sh1d0w** [comment]
Can’t reproduce it. If you want me to help you please provide example repository where I can reproduce the problem.

It seems like a conflict with other plugin that listens for permissions so you can try removing some plugins in order to see which one it is.

**Comment by dimiril** [comment]
cupertino_icons: ^0.1.2
  dio: ^3.0.7
  shared_preferences: ^0.5.6
  fluttertoast: ^3.1.0
  firebase_messaging: ^5.1.5
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.3
  google_sign_in: ^4.1.1
  carousel_pro: ^1.0.0
  share: ^0.6.3+5
  url_launcher: ^5.4.1
  flutter_html: ^0.11.1
  multi_image_picker: ^4.6.0
  cached_network_image: ^2.0.0-rc.1
  eva_icons_flutter: ^2.0.0
  photo_view: ^0.9.0
  flutter_facebook_login: ^3.0.0
  country_pickers: ^1.1.0

**Comment by dimiril** [comment]
This works multi_image_picker: ^4.5.8
This not works multi_image_picker: ^4.6.0

**Comment by Sh1d0w** [comment]
What version of flutter are you using? Version 4.5.8 and 4.6.0 require different versions of flutter and are not compatible.

**Comment by dimiril** [comment]
Flutter 1.13.4-pre.13 • channel master • https://github.com/flutter/flutter.git
Framework • revision 93f718b386 (12 days ago) • 2019-12-20 03:33:01 -0800
Engine • revision 472197a8e9
Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 8d11c1dce6)

**Comment by Sh1d0w** [comment]
The plugin supports only flutter on stable channel, which current version is 1.12.13+hotfix.5

Please switch to stable channel and try with the example app in this repo. If the problem exists I will look into it again, if not then please provide example repo where the problem is reproducible.

**Comment by IwantBEStrong** [comment]
This problem still exists，please fix it,thanks!
Flutter version 1.12.13+hotfix.5
multi_image_picker: ^4.6.0

**Comment by dimiril** [comment]
Plz fix this problim 4.6.0

**Comment by topex-psy** [comment]
App crash still occur after giving permission

Android 8
Flutter version 1.12.13+hotfix.6
multi_image_picker: ^4.6.0

**Comment by Sh1d0w** [comment]
Please provide repository where I can reproduce the error.

I am testing with the example app in this repo on Android 9:

<img width="1179" alt="Screenshot 2020-01-03 at 14 42 30" src="https://user-images.githubusercontent.com/5074917/71724261-683b8980-2e38-11ea-843b-d65131c57737.png">

Can't reproduce the error:


![ezgif-7-28a24cb735c8](https://user-images.githubusercontent.com/5074917/71724343-a46eea00-2e38-11ea-93e5-fb7a07afaed8.gif)

**Comment by dimiril** [comment]
Pls test androidx

**Comment by Sh1d0w** [comment]
I will @topex-psy said he was getting this error on Android 8, which I can't reproduce either.

**Comment by dimiril** [comment]
> قلت @ topex-psy إنه كان يحصل على هذا الخطأ على نظام Android 8 ، والذي لا يمكنني إعادة إنتاجه أيضًا.

Yes android 8 not work

**Comment by Sh1d0w** [comment]
I can't reproduce it neither on Android 8, 9 or 10. I am testing with the example app in this folder.

<img width="989" alt="Screenshot 2020-01-03 at 21 27 47" src="https://user-images.githubusercontent.com/5074917/71744978-8c678c80-2e71-11ea-9e8e-224316995e5b.png">

![ezgif-7-591d25f88fbe](https://user-images.githubusercontent.com/5074917/71744997-9a1d1200-2e71-11ea-8cd5-ec147523cc17.gif)

If you think there is a problem please provide example repository where I can reproduce the problem, until then I can't help you.

**Comment by dimiril** [comment]
![20200101_1753142](https://user-images.githubusercontent.com/46597539/71746085-e5c8bf00-2e63-11ea-9227-e9d2a8ebe770.gif)

**Comment by Sh1d0w** [comment]
@dimiril  You know this screenshot does not help me reproduce and fix the problem. I did not say I don't believe it is happening, I said I can not reproduce it. I can't fix something I can not reproduce.

You are welcome to debug and provide a PR that fixes the problem if you wish, if you want me to look into this please provide example repository where I can reproduce it. It does not happens with the example app so it is something specific to your project.

**Comment by dimiril** [comment]
@Sh1d0w  What exactly do I want to send you?

**Comment by Sh1d0w** [comment]
Link to a repository with example project which I can run and reproduce the error, as I can not fix something that I can not reproduce.

You can try the example app in this repo and see if you will get it to crash, but it works for me. If it does not crash for you then I need a repo with project that it crashes in as it can be specific to some plugins or setup.

**Comment by dimiril** [comment]
android 8       
minSdkVersion 19
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
dependencies {
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.mockito:mockito-core:2.17.0'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'androidx.appcompat:appcompat:1.2.0-alpha01'
}
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^3.0.7
  shared_preferences: ^0.5.6
  fluttertoast: ^3.1.0
  firebase_messaging: ^5.1.5
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.3
  google_sign_in: ^4.1.1
  carousel_pro: ^1.0.0
  share: ^0.6.3+5
  url_launcher: ^5.4.1
  flutter_html: ^0.11.1
  multi_image_picker: ^4.6.0
  cached_network_image: ^2.0.0-rc.1
  eva_icons_flutter: ^2.0.0
  photo_view: ^0.9.0
  flutter_facebook_login: ^3.0.0
  country_pickers: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  Widget buildGridView() {
    return ListView(
      physics: BouncingScrollPhysics(),
      shrinkWrap: true,
      addAutomaticKeepAlives: true,
      scrollDirection: Axis.horizontal,
      children: List.generate(images.length, (index) {
        Asset asset = images[index];
        return Container(
          padding: EdgeInsets.only(left: 4.0,right: 4.0),
          width: 70,
          height: 70,
          child: AssetThumb(
            quality: 100,
            asset: asset,
            width: 70,
            height: 70,
          ),
        );
      }),
    );
  }

  Future<void> loadAssets() async {
    List<Asset> resultList = List<Asset>();
    resultList = await MultiImagePicker.pickImages(
      maxImages: 9,
      enableCamera: true,
      selectedAssets: images,
      cupertinoOptions: CupertinoOptions(
          takePhotoIcon: "chat",
      ),
      materialOptions: MaterialOptions(
        actionBarColor: "#ffffff",
        actionBarTitle: "عالم المرأة",
        allViewTitle: "جميع الصور",
        useDetailsView: false,
        selectCircleStrokeColor: "#ffffff",
        selectionLimitReachedText: 'يمكنك اختيار 9 صور كحد اقصى.',
        textOnNothingSelected: 'لم تقم باختيار الصورة.',
        lightStatusBar: false,
        statusBarColor: "#333333",
        actionBarTitleColor: "#333333"
      ),
    );

    if (!mounted) return;

    setState(() {
      images = resultList;
    });
  }

**Comment by topex-psy** [comment]
unfortunately my repo is private and users must login / register before they can go to a page that uploads multiple photos using `multi_image_picker`, but I will try to make new repo to reproduce this problem.

**Comment by topex-psy** [comment]
this is my simple reproduce repository for this issue. I definitely try to help until this issue fixed because I need my app to run smoothly for my users too.

https://github.com/topex-psy/multi_image_picker_error

**Comment by Sh1d0w** [comment]
@dimiril  @topex-psy  Please try version 4.6.1, it should be fixed there.

**Comment by dimiril** [comment]
Thanks, brother, it works great very Thanks
