### ISSUE TITLE
Wont compile under Flutter 1.12.13+hotfix.5

### ISSUE THREAD

**Issue by tilk48** [Sh1d0w/multi_image_picker#343]
**Bug Report**

`multi_image_picker` version: 4.5.5

Is it happening on Android: Yes
Is it happening on iOS: Yes
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[!] Android Studio (version 3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2019.2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.41.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Describe the bug**

Compilation under Flutter 1.12.13+hotfix.5 fails with the following error:

``Compiler message:                                                       
../../flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.5.5/lib/src/asset_thumb_provider.dart:31:24: Error: The method 'AssetThumbImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(AssetThumbImageProvider key) {              
                       ^                                                
../../flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);``

This happens on iOS and android.

**Comment by Sh1d0w** [comment]
@tilk48 you are using old version 

Please use latest version of the plugin 4.6.0 which will solve your problem
