### ISSUE TITLE
Thumbs in different sizes

### ISSUE THREAD

**Issue by simkepal** [Sh1d0w/multi_image_picker#350]
**Bug Report**

`multi_image_picker` version: 4.6.0

Is it happening on Android: Yes

Is it happening on iOS: Yes

```
 Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.13.2, on Mac OS X 10.15.1 19B88, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
[✓] VS Code (version 1.41.0)
[✓] Connected device (1 available)

• No issues found!
```
Hello,

Can anyone please help me with something, If I want to get two thumbs in different sizes, getThumbByteData future is not being finished for second size. Is this meant to work like this or is a bug?
Other than that .... great package!!

Thanks for help!

**Comment by Sh1d0w** [comment]
Please provide example code / repo so I can reproduce the error
