### ISSUE TITLE
could not display gifs in gallery since update to 4.6.0

### ISSUE THREAD

**Issue by iyuhang** [Sh1d0w/multi_image_picker#361]
**Bug Report**

`multi_image_picker` version: 

Is it happening on Android:  yes

Is it happening on iOS: yes

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G87, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.41.1)
[✓] Connected device (2 available)
```

**Describe the bug**

In android , even cannot see gifs in gallery,
In iOS, gifs become still picture.

**Comment by Sh1d0w** [comment]
Gifs are not supported currently and are delibarately excluded from the gallery on Android.

PRs adding support for such are welcome if you wish.
