### ISSUE TITLE
App Crash after allowing permission on first run

### ISSUE THREAD

**Issue by Chunlee17** [Sh1d0w/multi_image_picker#362]
**Bug Report**

`multi_image_picker` version: 4.6.0

Is it happening on Android: YES

Is it happening on iOS: YES

```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.35.0)
[√] Connected device (2 available)
```

**Describe the bug**

App crash on android device after allow both permission require by this plugin.

Message from debugger:

E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example.project, PID: 17193
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=2001, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.example.project/com.example.project.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object io.flutter.plugin.common.MethodCall.argument(java.lang.String)' on a null object reference

**Comment by Sh1d0w** [comment]
Please try version 4.6.1, it should be fixed there.
