### ISSUE TITLE
Is it possible to work with Firebase Vision Image?

### ISSUE THREAD

**Issue by bhanuka96** [Sh1d0w/multi_image_picker#366]
I used old version of this package and I updated, Now file-path not supported.  

```
        ByteData byteData = await a.getByteData();
        List<int> imageData = byteData.buffer.asUint8List();

        final FirebaseVisionImage visionImage = FirebaseVisionImage.fromBytes(
            imageData,
            FirebaseVisionImageMetadata(
                size: Size(),// How to set size of asset?
                rawFormat: ,/ How to set rawFormat of asset?
                planeData: / How to set planeData of asset?
                ));
```

**Comment by Sh1d0w** [comment]
Hi.

So I assume Size expects width and height, which can be obtained from the Asset object with `originalWidth` and `originalHeight` getters.

Unfortunately I am not so familiar with FirebaseVisionImage. From what I see the metadata parameter is not required. In case you want to provide it you can either ask in the official firebase repo or just create temporary file from the byte data  in a temp folder and pass it to your FirebaseVisionImage which will do the trick.

**Comment by bhanuka96** [comment]
> Hi.
> 
> So I assume Size expects width and height, which can be obtained from the Asset object with `originalWidth` and `originalHeight` getters.
> 
> Unfortunately I am not so familiar with FirebaseVisionImage. From what I see the metadata parameter is not required. In case you want to provide it you can either ask in the official firebase repo or just create temporary file from the byte data in a temp folder and pass it to your FirebaseVisionImage which will do the trick.

I think, It's impossible to use firebaseVision with this package.
