### ISSUE TITLE
About the bug of turning on the camera button on android

### ISSUE THREAD

**Issue by DNetORM** [Sh1d0w/multi_image_picker#367]
I found a bug. When there is no photo in my mobile phone, I can only click the camera button to take photos, but the camera button is flat and can't be clicked. It's a matter of style. You can try, try to build a new simulator, or delete all the photos and try again

**Comment by Sh1d0w** [comment]
Thanks for your report.

However this is issue related to FishBun, the native Android library I am using. Please report it there and once fixed I will update it’s version in my plugin.

You can find link to FishBun repo in the readme file.
