### ISSUE TITLE
Camera icon is not complete

### ISSUE THREAD

**Issue by zywj** [Sh1d0w/multi_image_picker#37]
![image](https://user-images.githubusercontent.com/5554211/50091836-6449c300-0247-11e9-87ae-516d04e2e49d.png)

My phone is iPhone 7(iOS 12.1)
It seems a bug of BSImagePicker. 
Is there any way can set the icon property?

**Comment by Sh1d0w** [comment]
This is now implemented in version `2.3.01` of the plugin. For example usage see the example folder, as well as the instructions here https://github.com/Sh1d0w/multi_image_picker/blob/master/doc/ios.md

**Comment by zywj** [comment]
WOW,  Thanks!!!

**Comment by kalismeras61** [comment]
I am using last version and in iphone 8 plus i have same issue!
