### ISSUE TITLE
First of all thanks for great plugin! Can you please let me know how to get images path so i can create File need to send selected images to server

### ISSUE THREAD

**Issue by androidexperts155** [Sh1d0w/multi_image_picker#370]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Sh1d0w** [comment]
Hi and thanks, I am glad the plugin is useful to you.

You don't need file path to upload images to the server, please read the docs of the plugin https://sh1d0w.github.io/multi_image_picker/#/upload
