### ISSUE TITLE
When creating AssetThumbs , the AssetThumb in the PageView.Builder doesn't show the image only a circular progress indicator

### ISSUE THREAD

**Issue by DyaryRaoof** [Sh1d0w/multi_image_picker#371]
**Bug Report**

`multi_image_picker` version: ^4.6.0-rc.3

Is it happening on Android: Yes

Is it happening on iOS: Yes

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.13.9-pre.69, on Mac OS X 10.14.6 18G103, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!

```

**Describe the bug**

When creating AssetThumbs , One in a PageView.Builder Widget and any number of AssetThumbs using a GridView.count , the AssetThumb in the PageView.Builder doesn't show the image only a circular progress indicator, which shouldn't be the case because it still there are a long while. I have to change the current PageView image to the next one and return to this one, then it will display it.

Your help is appreciated.
Thanks.

**Comment by Sh1d0w** [comment]
Can you provide repo where I can reproduce this? It does not happens with the example app in this repository.

**Comment by DyaryRaoof** [comment]
Sorry, @Sh1d0w The app is a huge one and is a commercial one so I can't share the repo. I can send you Images and screenshots if you need be though.

**Comment by Sh1d0w** [comment]
Unfortunately that won't help me to point you where the problem is. It does not happen with the example app in this repository so it is something in your code that causes the widget to not re-render.

If you can provide minimal example repo where I can reproduce it I will look into it.
