### ISSUE TITLE
android: Select GIF and flash back directly

### ISSUE THREAD

**Issue by huangzuyan110** [Sh1d0w/multi_image_picker#372]
**Bug Report**

`multi_image_picker` version: 

Is it happening on Android: 

Is it happening on iOS: 

```
 <!-- run `flutter doctor` and paste the output here: -->
```

**Describe the bug**

**Comment by Sh1d0w** [comment]
Please describe what the problem is exactly? Gifs are not supported and are [excluded](https://github.com/Sh1d0w/multi_image_picker/blob/master/android/src/main/java/com/vitanov/multiimagepicker/MultiImagePickerPlugin.java#L508) from the picker, you should not see them?

**Comment by Sh1d0w** [comment]
Closing dua to inactivity.
