### ISSUE TITLE
Where is the filePath

### ISSUE THREAD

**Issue by EchoPuda** [Sh1d0w/multi_image_picker#379]
After up to 4.6.0, the "filePath" in "Asset" is gone. 
When I use metadata to get information, like fileSource, Datetime in exif, return "null" back.
so how can I get the filePath?

**Comment by Sh1d0w** [comment]
https://sh1d0w.github.io/multi_image_picker/#/faq?id=why-the-plugin-don39t-return-image-paths-directly

In general you don't need file paths. If you do you can always save the image byte data to the app tmp directory and use it from there.

**Comment by jpainam** [comment]
hi, what if i need the original fileName. using the filepath, you can easily extract the original file name. Now that it's gone. is there any way of getting the file name?

**Comment by Sh1d0w** [comment]
@jpainam Did you try `Asset.name` ?

**Comment by jpainam** [comment]
Thanks.

**Comment by marianoarga** [comment]
@Sh1d0w how can I get the original filePath in order to delete the image (since the app is trying to move the image from the gallery)
