### ISSUE TITLE
iOS Build issue. Useful advices

### ISSUE THREAD

**Issue by I-am-original** [Sh1d0w/multi_image_picker#38]
Hi again. I have started with this plugin again. For now _ Ihave issues with iOS and cant install app. Many issues while running. and then Xcode crashes. 

Please ask me what should I configure, because nothing helps. I have configured Swift version in Runner. Bridge not creates.

Config in Runner settings:
![screen shot 2018-12-19 at 8 03 19 pm](https://user-images.githubusercontent.com/9134717/50238877-355b5a80-03c9-11e9-8793-d46553955ca4.png)
Config in Pods settings:
![screen shot 2018-12-19 at 8 03 31 pm](https://user-images.githubusercontent.com/9134717/50238879-355b5a80-03c9-11e9-895f-438b1dc721b7.png)

**Comment by Sh1d0w** [comment]
Hi, please let me know what errors do you get and what version of the plugin do you have? Did you try to run the example app?

**Comment by I-am-original** [comment]
Hi @Sh1d0w  
Here is output and many more

![screen shot 2018-12-20 at 11 19 19 am](https://user-images.githubusercontent.com/9134717/50275876-26b48800-0449-11e9-936a-d4240b4d9f35.png)

**Comment by I-am-original** [comment]
Or more extended
![screen shot 2018-12-20 at 11 54 45 am](https://user-images.githubusercontent.com/9134717/50277811-194dcc80-044e-11e9-8c7c-074a88359ca7.png)

**Comment by Sh1d0w** [comment]
Hm, can you give me the output of `flutter doctor`, please?

**Comment by I-am-original** [comment]
@Sh1d0w 
`[✓] Flutter (Channel unknown, v1.1.1, on Mac OS X 10.14.1 18B75, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2018.2.2)
[✓] VS Code (version 1.29.1)
[✓] Connected device (2 available)

• No issues found!
`

**Comment by Sh1d0w** [comment]
@I-am-original It seems like you did not created the bridging header.

Can you please try this https://stackoverflow.com/questions/50096025/it-gives-errors-when-using-swift-static-library-with-objective-c-project/50495316#50495316

e.g. create empty swift file in your project via Xcode, and follow what is suggest for the bridging header.

**Comment by I-am-original** [comment]
@Sh1d0w 

<img width="773" alt="screen shot 2018-12-20 at 12 42 58 pm" src="https://user-images.githubusercontent.com/9134717/50280308-d0e5dd00-0454-11e9-8df9-20818fc24ff7.png">

**Comment by Sh1d0w** [comment]
@I-am-original But do you have the empty .swift file in your project as well?

If you have then can you try the following:

1. Remove the plugin
2. Remove `/ios/Podfile.lock` and `Pods` folder
3. Add the latest version of the plugin which currently is `2.3.22`

And try to run the project again.

**Comment by I-am-original** [comment]
@Sh1d0w  will check in 10 minutes.

**Comment by I-am-original** [comment]
@Sh1d0w maybe it can be fixed like this? Without additional files?

Apparently for pure objective-c projects you will need to add this $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME) to the library search paths of your target. This worked for me when I was including a library written in swift to a project in objective-c

cant say how to do that ) at all. have no idea where to push it

**Comment by Sh1d0w** [comment]
@I-am-original To add path to the library search paths, go to your Project -> Build Settings and search for Library Search Paths.

You can then add it there. This is the other way to fix it, but it will be easier if you just create an empty swift file in your project.

FYI this problem occurs because you have created your flutter app without Swift support, if you create it with `flutter create -i swift [projectName]` as described in the readme it should work as well.

**Comment by I-am-original** [comment]
@Sh1d0w So this bridge and empty swift files should be in Runner. Yup?

**Comment by I-am-original** [comment]
@Sh1d0w  update

![screen shot 2018-12-20 at 1 42 33 pm](https://user-images.githubusercontent.com/9134717/50282971-22926580-045d-11e9-8605-6bddd3823635.png)

**Comment by I-am-original** [comment]
@Sh1d0w I have build it somehow. But here is one more strange issue

![screen shot 2018-12-20 at 1 59 34 pm](https://user-images.githubusercontent.com/9134717/50283740-89188300-045f-11e9-8575-ee662b5f4eb0.png)

**Comment by I-am-original** [comment]
HI @Sh1d0w. For how all fixed. But in future maybe I will need this recommendations. Thanks you a lot. Issue can be closed
