### ISSUE TITLE
Hello all!

### ISSUE THREAD

**Issue by eugene-kalaganov** [Sh1d0w/multi_image_picker#380]
It has a weird behaviour when I'm picking image with transparent background it shows in Flutter with black background on IOS and white on Android.

Does anybody tried to pick images with transparent regions?

**Comment by Sh1d0w** [comment]
This is expected, as the plugin does convert all picked images to JPEG, thus loosing the transparency. It currently does not support returning GIF or PNG images, if you wish to introduce that functionality PRs are welcome.
