### ISSUE TITLE
Allow single image selection

### ISSUE THREAD

**Issue by safoelc252** [Sh1d0w/multi_image_picker#381]
**Is your feature request related to a problem? Please describe.**
When using this alongside with the official `image_picker`, build error occurs. This is for use cases when an app design requires multiple image selection in one screen and single image selection in another screen.

**Describe the solution you'd like**
Just a flag in MultiImagePicker.pickImages(maxImages: 300, singleSelection: true) // default to false

**Describe alternatives you've considered**
In my code, I allowed multiple image selection but I only get the first images[0] in the returned list.

**Additional context**
n/a

**Comment by Sh1d0w** [comment]
If you set maxImages to 1 it will act like a single image picker.

**Comment by safoelc252** [comment]
> If you set maxImages to 1 it will act like a single image picker.

Thanks man. It works!
