### ISSUE TITLE
upload on graphql 

### ISSUE THREAD

**Issue by Hellomik2002** [Sh1d0w/multi_image_picker#384]
Sorry, please. I'm not sure that error connected with package but have you work with graphql ?
https://stackoverflow.com/questions/60209274/upload-photo-graphql-by-flutter

**Comment by Hellomik2002** [comment]
I see an undefined location, maybe is it connected with path of a file or another

**Comment by Sh1d0w** [comment]
Hi. From the flutter graphql documentation it seems it expects the passed variable to be of type File, however you are passong MultipartFile, which is different type and does not inherit file.

Just save the asset to a local file in the tmp directory and pass it and it will work.

**Comment by Hellomik2002** [comment]
I tried to use file however it also didn't work and also deprecated, 
![image](https://user-images.githubusercontent.com/30003495/74501604-e2216100-4f14-11ea-974f-0862aa61a1dd.png)
```
I/flutter (10169): ⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️ DEPRECATION WARNING ⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️
I/flutter (10169):
I/flutter (10169): Please do not use `File` direcly anymore. Instead, use
I/flutter (10169): `MultipartFile`. There's also a utitlity method to help you
I/flutter (10169): `import 'package:graphql/utilities.dart' show multipartFileFrom;`
```
My code that failed (i create a temporary file)
```
String dir = (await getTemporaryDirectory()).path;
      File temp = new File('$dir/temp.file');
      temp.writeAsBytesSync((await iconImage.getThumbByteData(
              iconImage.originalWidth, iconImage.originalHeight))
          .buffer
          .asUint8List());
```
Sorry if i do some silly mistakes

**Comment by Sh1d0w** [comment]
Hi the error seems coming from the graphql package so I can't help you with that unfortunately.

**Comment by Hellomik2002** [comment]
You responce so quickly, thank you very much

**Comment by Hellomik2002** [comment]
You response so quickly, thank you very much
