### ISSUE TITLE
Android 10 Camera mulfunction

### ISSUE THREAD

**Issue by liongkj** [Sh1d0w/multi_image_picker#388]
**Bug Report**

`multi_image_picker` version: 4.6.1

Is it happening on Android: Yes  

Is it happening on iOS: N/A

![image](https://user-images.githubusercontent.com/20205301/74725821-64918400-5279-11ea-9337-b09183ad697e.png)

**Describe the bug**
In Android 10 API 29, the camera is not working with the following error code:
![image](https://user-images.githubusercontent.com/20205301/74726410-60b23180-527a-11ea-8473-8666fafef149.png)

I tested on an emulator and physical device on API 28, the camera in image picker is usable.

I also have set the max sdk version fix found in Stackoverflow but the problem still exist
![image](https://user-images.githubusercontent.com/20205301/74726541-9c4cfb80-527a-11ea-8c90-18996203e31a.png)

Can you guide me on other troubleshooting steps and let me know what to do?

**Comment by Sh1d0w** [comment]
I think you should handle camera permissions at runtime, with plugin like https://pub.dev/packages/simple_permissions

You need to make sure the user has granted the correct permission before invoking the image picker.

**Comment by liongkj** [comment]
It did show a user permission box for camera permission, but after accepting it, nothing happen, the log is shown in the first image.

**Comment by himsa** [comment]
same issue here

**Comment by himsa** [comment]
I tested on an emulator and physical device on API 28, the camera in image picker is usable.
but when I use device API 29, camera is not work, but select image from gallery is working fine.
 I already do manual permission request, but the error log still show the same as @liongkj

**Comment by Sh1d0w** [comment]
Maybe it is related to https://github.com/sangcomz/FishBun/issues/102

Either way you have to report it in the FishBun repo, as I don't have control over the native plugin used. Once the owner fixes it (if there is any problem) I will update the FishBun version.

**Comment by liongkj** [comment]
@himsa i ended up switching to api level 28 for now

**Comment by Yunus0or1** [comment]
The problem still persists in Android 10. Everything is okay in Debug Mode but whenever I release the app, multi_image_picker can not function with Camera option although gallery image selection is okay. Play store made it mandatory to switch to API level 29 so we need a solution please.
