### ISSUE TITLE
multi_image_picker/multi_image_picker-Swift.h' file not found

### ISSUE THREAD

**Issue by 1knight520** [Sh1d0w/multi_image_picker#390]
iOS multi_image_picker: ^4.5.9 
multi_image_picker/multi_image_picker-Swift.h' file not found

**Comment by Sh1d0w** [comment]
You need to have Swift support enabled and a bridging header as described in the docs.

**Comment by 1knight520** [comment]
> 您需要启用Swift支持，并按照文档中的说明桥接标题。

![BFA2022B-B89A-482E-8441-D443CA432AB6](https://user-images.githubusercontent.com/23653418/75003832-29bf6400-54a4-11ea-9541-0b44fc649bd4.png)

![9CE0D6FC-3197-495E-96FE-590CB2471C15](https://user-images.githubusercontent.com/23653418/75003849-38a61680-54a4-11ea-8cf8-b218d1c602e8.png)
![image](https://user-images.githubusercontent.com/23653418/75003870-49ef2300-54a4-11ea-8427-2f15cc64dd6e.png)
已支持swift

**Comment by 1knight520** [comment]
But the  multi_image_picker/multi_image_picker-Swift.h' file not found

**Comment by Sh1d0w** [comment]
As I said you need a bridging header. Please read the documentation of the plugin https://sh1d0w.github.io/multi_image_picker/#/initialsetup
