### ISSUE TITLE
Allowing showing already selected image

### ISSUE THREAD

**Issue by PritishSawant** [Sh1d0w/multi_image_picker#396]
Suppose i open multi image picker and select some images. Now again i open multi image picker ,is it possible to already  have a check mark on already selected image

**Comment by Sh1d0w** [comment]
Yes, it is possible, please read the plugin documentation.

**Comment by PritishSawant** [comment]
Request you to please point me the exact location if possible. I am not able to find it in the docs

**Comment by Sh1d0w** [comment]
Sure, you can pass list of selected Assets object to the pickImages function in order to mark them as selected. See the function signature [here](https://github.com/Sh1d0w/multi_image_picker/blob/master/lib/src/picker.dart#L39)

**Comment by PritishSawant** [comment]
@Sh1d0w Thanks alot for such  quick reply. Appreciate it
