### ISSUE TITLE
Example of Integration Testing

### ISSUE THREAD

**Issue by pwnywiz** [Sh1d0w/multi_image_picker#398]
I'm trying to do some integration testing while using this package but I'm having a hard time, since it differs from unit tests.
Mocking the channel and the invocations of the method calls results in infinite awaits.
I would be very glad if you had any example :)

**Comment by Sh1d0w** [comment]
Hi, did you take a look at the tests folder in this repo https://github.com/Sh1d0w/multi_image_picker/tree/master/test ?

**Comment by pwnywiz** [comment]
@Sh1d0w Hi, I did yes, but unit tests mock the android / iOS calls entirely which results in images not getting rendered at all. I tried to mock the 'pickImages' method call to prevent the picker from opening and return a hardcoded map of an image's details but still there are more underlying actions from this call in android / iOS level which get ignored.

**Comment by Sh1d0w** [comment]
Well, there are several other methods in [this](https://github.com/Sh1d0w/multi_image_picker/blob/master/lib/src/picker.dart) class that you have to mock, `pickImages` is only responsible to invoke the image picker and return Assets, but the actual image data is transferred through `requestOriginal` and `requestThumbnail` methods. If you mock them as well I think you should be in a good spot to do some testing, especially if you provide some mock byte data. You can simulate it by reading a file fixture with Dart for example and complexly avoid the native layer.

**Comment by pwnywiz** [comment]
My actual problem is passing mock byte data. I understand that `requestOriginal` / `requestThumbnail` are responsible for that work and I tried both mocking them and letting them run but got stuck at resolving the bytedata, since the actual return of these calls is just a boolean. I can't figure out how to fake pass the bytedata to my Asset since I don't have access to it during an integration test.

**Comment by Sh1d0w** [comment]
Ah, right. So the actual return value of the method is not important, [see here](https://github.com/Sh1d0w/multi_image_picker/blob/master/lib/src/asset.dart#L77). The only way we can obtain ByteData from the native layer to Dart is through the method channel. Basically each Asset listens to it's own method channel (one for thumbs and one for original image) scoped by the asset unique identifier [see here](https://github.com/Sh1d0w/multi_image_picker/blob/master/lib/src/asset.dart#L27). So in order to return byte data you should not mock the requestThumb method, rather than send it to the default binary messenger on the channel for that Asset.

I hope this makes sense.

**Comment by pwnywiz** [comment]
Ah I see, makes more sense now. I will give it a try.
Thanks a lot :)

**Comment by pwnywiz** [comment]
Hi again @Sh1d0w,
So, I tried testing the way you  proposed but with no result, unfortunatelly.
From peeking into the native android code, I can tell that `requestThumbnail` is the method that passes the bytedata to the specific Asset channel. I did mock the latter method call and inside it, loaded an image as ByteData, which was then sent to the specific channel, expecting that the message handler inside  `getThumbByteData` would catch it and complete its future. Although the handler of that specific channel never fires, which means that I'm either sending something wrong or the wrong way.

`if (methodCall.method == 'requestThumbnail') {
      final ByteData imageByteData =
          await rootBundle.load('assets/images/image.png');

      await ServicesBinding.instance.defaultBinaryMessenger
          .send('multi_image_picker/image/content://media/external/images/media/149868.thumb', imageByteData);

      return true;
    }`

This is the corresponding code inside the method call in case it helps.
Any ideas?

**Comment by Sh1d0w** [comment]
Sure, did you check that the asset you are returning from the mocked image picker has the correct identifier, in this case `content://media/external/images/media/149868` ?

If it is, then maybe it something with the defaultBinaryMessenger, I haven't been using it in tests, so maybe either ask in the official flutter repository how one should be approached during testing, or just create mock asset class that extends the original asset class and override the thumb method. You don't need to be concerned about testing 3rd party plugins after all, only your part the code.

**Comment by pwnywiz** [comment]
Yes I've double checked the identifier and its the same.
I'm not trying to test a plugin at any case, but rather trying to find a way to automate the selection of an image in an integration testing flow.
Thank you deeply for your help, though! As you mentioned I might look for further help at the flutter repository regarding the `defaultBinaryMessenger`.
Have a great day!

**Comment by pwnywiz** [comment]
After some more testing, it looks like that the `setMessageHandler` method does not fire during integration testing, although if it gets replaced with `setMockMessageHandler` it works.
The problem is that the handler inside this method completes a Future with the required ByteData which  I can't find a way to mock outside the `getThumbByteData` method, since the Completer is local.

**Comment by Sh1d0w** [comment]
You can just create mock Asset object that extends the original asset class and override get thumb method and just return it from the image picker.

**Comment by spiritinlife** [comment]
@Sh1d0w could you elaborate on this or provide an example?
You are suggesting to use mockito to mock Asset's getThumbByteData and MultiImagePicker's pickImages methods?
