### ISSUE TITLE
Asset from byteData?

### ISSUE THREAD

**Issue by Hadii1** [Sh1d0w/multi_image_picker#401]
Hello, first thank you for the library. I'm currently trying to create an asset from an image url i've got stored somewhere. Is there a way for that or it's impossible by design?

**Comment by Sh1d0w** [comment]
Hi, by design it is not possible to create an Asset object outside of this library, it is only possible to create it when calling the pickImages method as it will properly assign the asset identifier for the given platform (on iOS this is PHAssetID, on Android it is the content URI).
