### ISSUE TITLE
Taking a photo and show the wrong orientation.

### ISSUE THREAD

**Issue by shingohu** [Sh1d0w/multi_image_picker#403]
*Bug Report**

`multi_image_picker` version:4.6.1

Is it happening on Android: Yes

Is it happening on iOS: No

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76,
    locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.42.1)
[✓] Connected device (2 available)
```

**Describe the bug**

Open the image picker，and take a photo and select it,the AssetThumb show the wrong orientation,but when you select the image again, it will display correctly

1、take a photo and it will show right
![image](https://user-images.githubusercontent.com/4944887/76048184-0d412280-5fa0-11ea-96cc-27e0323f85b5.png)

2、select it and it will show wrong
![image](https://user-images.githubusercontent.com/4944887/76048240-32359580-5fa0-11ea-811a-7ece5595c020.png)

3、select it again and it will show right
![image](https://user-images.githubusercontent.com/4944887/76048308-5e511680-5fa0-11ea-98f4-0d6f8f3bdb00.png)

**Comment by Sh1d0w** [comment]
Please follow the issue template and provide the needed info from Flutter doctor, otherwise the issue will be closed. Thanks.

**Comment by shingohu** [comment]
@Sh1d0w  Why close this issue

**Comment by Sh1d0w** [comment]
Sorry, forgot to notify you that this issue was regression and is fixed in version 4.6.3

**Comment by shingohu** [comment]
@Sh1d0w The problem is still remains

**Comment by Sh1d0w** [comment]
What device are you testing or is it simulator or real device? If real what’s the brand?

**Comment by shingohu** [comment]
real device
Android Version:9.0
Models: Redmi Note 7

**Comment by taninjs** [comment]
I have the same issue

tested on real device, Samsung Galaxy S9
