### ISSUE TITLE
Selected Assets have wrong index on iOS

### ISSUE THREAD

**Issue by CtrlAltDft** [Sh1d0w/multi_image_picker#404]
**Bug Report**

`multi_image_picker` version: **4.6.2**

Is it happening on Android: **No**

Is it happening on iOS:  **Yes**

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
[✓] VS Code (version 1.42.1)
[✓] Connected device (3 available)

• No issues found!
```

After I selected a list of images when I come back to the image picker, the index showed is not correct.
When first selected, the indices are 1, 2, 3, 4:
![image](https://user-images.githubusercontent.com/24569270/76081760-c1fd3300-5fe4-11ea-9ace-cd620ad440ab.png)

After coming back, the indices are 3, 4, 1, 2:
![image](https://user-images.githubusercontent.com/24569270/76081782-d2151280-5fe4-11ea-970f-af797aaf04ff.png)

Code:
![image](https://user-images.githubusercontent.com/24569270/76081822-ebb65a00-5fe4-11ea-8d28-7014b1bcf089.png)

One point to notice is that the second time onwards, the indices remain at 3, 4, 1, 2

**Comment by Purelightme** [comment]
i got same problem

**Comment by chjsun** [comment]
i got same problem. not only in ios,android also
