### ISSUE TITLE
Since 4.6.2 rotation is incorrect

### ISSUE THREAD

**Issue by Martibis** [Sh1d0w/multi_image_picker#405]
**Bug Report**

`multi_image_picker` version: 4.6.2

Is it happening on Android: Yes (Android 10)

Is it happening on iOS: Not sure

**Describe the bug**

After selecting the images the rotation is wrong by a few degrees, causing it to show incorrectly. As shown here: [https://ibb.co/cFRJMhR](https://ibb.co/cFRJMhR)

**Comment by Martibis** [comment]
I assume the commit causing the issue is: #399

**Comment by Sh1d0w** [comment]
I have reverted this PR, sorry for the inconvenience, it should have been released as RC.

Thanks for the report.
