### ISSUE TITLE
deprecated call

### ISSUE THREAD

**Issue by deakjahn** [Sh1d0w/multi_image_picker#407]
**Bug Report**

`multi_image_picker` version: 4.6.3

Is it happening on Android: Yes

Is it happening on iOS: No

**Describe the bug**

FileDirectory.java:37: warning: [deprecation] getExternalStorageDirectory() in Environment has been deprecated

This has been deprecated in API 29. Please, use one of the supported calls (probably getExternalMediaDir() here).

**Comment by Sh1d0w** [comment]
This should be fixed in https://github.com/Sh1d0w/multi_image_picker/pull/414 which I will release shortly.
