### ISSUE TITLE
Android load image failed

### ISSUE THREAD

**Issue by Jsharkc** [Sh1d0w/multi_image_picker#408]
**Bug Report**

`multi_image_picker` version: 4.5.5

Is it happening on Android: Yes

Is it happening on iOS: No

```
 <!-- run `flutter doctor` and paste the output here: -->
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.9.1, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 10.3)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on
        the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
        pod setup
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Describe the bug**

Multi_image_picker is a good plug-in, but when I select images, many images fail to load, and it's blank.
![bug_eg](https://user-images.githubusercontent.com/17465198/76513271-04b18600-6491-11ea-8f46-1678beb60880.jpg)

**Comment by Sh1d0w** [comment]
You are using outdated version of the plugin, please upgrade to the latest one and check if it still happens?

If it still happens please report this to the maintainer of [FishBun](https://github.com/sangcomz/FishBun) - this is the native Android library I am using in the picker.
