### ISSUE TITLE
Failed to build for android

### ISSUE THREAD

**Issue by JoaoOBF** [Sh1d0w/multi_image_picker#41]
MultiImagePickerPlugin.java:283: error: cannot find symbol
                ExifInterface.TAG_ISO_SPEED,
                             ^
  symbol:   variable TAG_ISO_SPEED
  location: class ExifInterface
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':multi_image_picker:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by Sh1d0w** [comment]
Hi, can you give me the output from `flutter doctor`

Also what have you set for `compileSdkVersion` and `targetSdkVersion` in your `android/app/build.gradle`? Can you try to set them to 27 and see if this will resolve your issue?

**Comment by JoaoOBF** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [versÃ£o 10.0.17134.472], locale pt-BR)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.2)
[√] Connected device (1 available)

**Comment by JoaoOBF** [comment]
they are already in 27

**Comment by maxnemoy** [comment]
I have this problem too

```
C:\flutter\.pub-cache\hosted\pub.dartlang.org\multi_image_picker-2.3.25\android\src\main\java\com\vitanov\multiimagepicker\MultiImagePickerPlugin.java:283: error: cannot find symbol
                ExifInterface.TAG_ISO_SPEED,
                             ^
  symbol:   variable TAG_ISO_SPEED
  location: class ExifInterface
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':multi_image_picker:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

flutter doctor

```
[√] Flutter (Channel master, v1.1.2-pre.36, on Microsoft Windows [Version 10.0.17763.134], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
[√] Connected device (1 available)

• No issues found!
```
android/app/build.gradle

```
android {
    compileSdkVersion 27
==================
     defaultConfig {
           minSdkVersion 19
           targetSdkVersion 27
==================
```

**Comment by Sh1d0w** [comment]
@maxnemoy Are you able to setup sample repo where I can reproduce the issue?

I've tried creating empty project and adding latest version of the plugin, and it built successfully.

I guess the problem is related to your specific project or other plugins in your project.

I will need more info in order to reproduce the issue, so if you guys can provide example repo where the problem exists it will be very helpful in order to find why this happens.

**Comment by maxnemoy** [comment]
I added a multi image picker 2.3.26 to a clean project, the build is successful.
The problem in the current project persisted.

I compared the configurations of my projects.
in a problematic project in /android / build.gradle
used tag

```
subprojects {
     project.configurations.all {
         resolutionStrategy.eachDependency {details ->
             if (details.requested.group == 'com.android.support'
                     &&! details.requested.name.contains ('multidex')) {
                 details.useVersion "26.1.0"
             }
         }
     }
}
```

I removed it.
build is successful.
thank. sorry for my English.

**Comment by Sh1d0w** [comment]
@maxnemoy Yes that code overwrites the import of Exif support library, which is 27.1.0, and downgrades it to 26.1.0, which does not have that tag.

Great, I am glad it is working now.
