### ISSUE TITLE
On pickImages method call, my app just closes without any exception throwing.

### ISSUE THREAD

**Issue by oxydron** [Sh1d0w/multi_image_picker#410]
**Bug Report**

`multi_image_picker` version: 

Is it happening on Android: Yes

Is it happening on iOS: Not tested.

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)
```

**Describe the bug**

This bug do not occur on a simple test app, as I've tested it on a sample app.

But on my current project, it just closes the app on the pickImages method call, and drop this lines on the debug output:

`Failed to send request: {"jsonrpc":"2.0","id":"1397","method":"resume","params":{"isolateId":"isolates/4275718744151023"}}`

I've put the correct permissions on AndroidManifest.xml and all. The app just closes and outputs the above message.

**Comment by Sh1d0w** [comment]
There is something specific to your project that breaks the picker, if it does not happen on the example app. It could be conflict with other plugin you are using or something else.

In order for me to be able to help you, please provider link to a repository which I can checkout and reproduce the problem.

**Comment by oxydron** [comment]
I found that this problem maybe is a problem with memory of the flutter app related to https://github.com/flutter/flutter/issues/9707
I saw that this plugin invoke native android code.
Unfortunelly my code is company private and I can't share. But I'm trying to do the exactly same thing as the sample app described here on this repository.

Plus this new message that I got when I enabled verbose logging:

```dart
[+10514 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +2 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/br.com.<my_company_name>.<secret_project_name>/code_cache/<secret_project_name>YGPRCR/<secret_project_name>/)
[        ] Sending to VM service: _deleteDevFS({fsName: <secret_project_name>})
[{"id":28,"result":true}]
```

**Comment by Sh1d0w** [comment]
Can you at least share some example code, where and how you are using the images picked form the image picker?

Requesting image data really allocates memory, so you need to be careful when you are requesting / rendering it and also make sure you are displaying thumbs not original data in your app.

**Comment by oxydron** [comment]
This problem seem to be related to a Flutter bug and not to this lib in specific, therefore I'll close this issue.
