### ISSUE TITLE
Implement a pickImages method with a return of List<File> or another better solution with a File pointer.

### ISSUE THREAD

**Issue by oxydron** [Sh1d0w/multi_image_picker#412]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Currently we have a `pickImages` method with a output of `List<Asset>`, which can generate a `ByteData` object. But several other libs use the `File` class to manipulate files.
Would be nice to have an output like `List<File>` or a simple method on the Asset class like `File /Future<File>getAsFile()` or any other better solution which outputs File instead somewhere.

**Describe alternatives you've considered**
Currently, I need to convert your `Asset` data to `DataByte` and then to a temporary `File` to create a file to use.

**Additional context**
Firstly I was using other plugin named **image_picker** which return `File`. My code was developed considering that. Then I got the necessity to load multiple images and got to yout plugin. But I have this problem to convert a Asset to a File.

**Comment by Sh1d0w** [comment]
You can always request the byte data and save it to a temporary file and use that. Reasons why the plugin does not return files are described in the FAQ section of the plugin docs.
