### ISSUE TITLE
Zoom and share image?

### ISSUE THREAD

**Issue by PritishSawant** [Sh1d0w/multi_image_picker#413]
I would like to zoom and share image for my app, so i would like to share the AssetThumb. I tried integrating a library in my app called photo_view and tried wrapping AssetTumb with it but it requires imageprovider and not image as its child. Here is the library https://pub.dev/packages/photo_view

Also i would like to share the image via whatsapp so I integrated the share library but it shares text
https://pub.dev/packages/share

Is it possible to share AssetThumb

**Comment by Sh1d0w** [comment]
In case you need provider, we have [AssetThumbProvider](https://github.com/Sh1d0w/multi_image_picker/blob/master/lib/src/asset_thumb_provider.dart).

Yes it is possible, you can simply save the asset byte data to a temporary file and then use that file whenever you want, in a cropper or to share it.

**Comment by PritishSawant** [comment]
@Sh1d0w  Can you share some code snippet to save asset byte data and share it? Thanks for the reply.

**Comment by Sh1d0w** [comment]
I am on my phone now, but you can use [File.writeAsBytes](https://api.dart.dev/dev/2.0.0-dev.52.0/dart-io/File/writeAsBytes.html) to save the asset byte data to a file. See an example [here](https://stackoverflow.com/questions/50119676/how-to-write-a-bytedata-instance-to-a-file-in-dart)

**Comment by PritishSawant** [comment]
@Sh1d0w Thanks but i dont think you can share file using Share plugin

**Comment by Sh1d0w** [comment]
Well that's question you can ask in the share plugin repository :)

**Comment by PritishSawant** [comment]
@Sh1d0w Thanks for these quick replys. Appreciate it

**Comment by PritishSawant** [comment]
Whenever i tried to convert Asset to List<int> I get an error saying Unhandled Exception: FileSystemException: Cannot create file, 

I tried in 2 ways

First way 

ByteData byteData = await asset.getByteData();
final temp = byteData.buffer.asUint8List()

Second way

 ByteData byteData = await asset
                            .getThumbByteData(
                               asset
                                    .originalWidth,
                            asset
                                    .originalHeight);
final temp = byteData.buffer.asUint8List()

**Comment by Sh1d0w** [comment]
You need to save the file to the app temporary directory where you have access to write. Also you need to request the proper filesystem write permission on Android.

**Comment by PritishSawant** [comment]
@Sh1d0w Is it possible to conver Asset to a File?
