### ISSUE TITLE
How to only see the All Photos page in flutter?

### ISSUE THREAD

**Issue by Maadhav** [Sh1d0w/multi_image_picker#416]
I wanted only have the image picker inside my own page without needing to clicking the button
Check the image: https://i.imgur.com/P3RPFvF.jpg

**Comment by Sh1d0w** [comment]
You can invoke the `pickImages` method programatically without button. I don't see a question here?

**Comment by Maadhav** [comment]
I want to show that inside my own screen with not as a different screen.

**Comment by Sh1d0w** [comment]
Unfortunately this is not how the plugin works, it uses native libraries to present the picker which have their own native views. They are quite customizable you can see the plugin docs.
