### ISSUE TITLE
quality not working on iOS, cos declared as Int on SwiftMultiImagePickerPlugin.swift ?

### ISSUE THREAD

**Issue by dariolr** [Sh1d0w/multi_image_picker#417]
**Bug Report**

`multi_image_picker` version: 4.6.3

Is it happening on Android: 

Is it happening on iOS: 

```
 ✓] Flutter (Channel master, v1.16.1-pre.18, on Mac OS X 10.14.6 18G103, locale it-IT)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.43.1)
[✓] Connected device (3 available)

• No issues found!
```

**Describe the bug**

Hi thanks for your nice work and sorry for my english.

On iOS, compression quality is determined through CGFloat(quality / 100) 
the result is always 0.0 for quality value < 100.
Can you consider to use CGFloat(Float(quality) / 100) ?

thank you

**Comment by Sh1d0w** [comment]
Oh, that's a good catch! Actually Swift is very odd when dividing integers (just found out this), so with your example it still will evaluate quality / 100 first to 0.

The correct fix would be:

`Float(quality) / Float(100)`

I've just fixed that and rebased version 4.6.4.

Thanks for the report!
