### ISSUE TITLE
iOS NoImagesSelectedException does not throw when window swipe down

### ISSUE THREAD

**Issue by FroseMan97** [Sh1d0w/multi_image_picker#418]
**Bug Report**

`multi_image_picker` version: ```4.6.4```

Is it happening on Android: ``` No```

Is it happening on iOS: ```Yes```
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.43.2)
[✓] Connected device (1 available)

• No issues found!
```

NoImagesSelectedException does not throw when swiping the window down. Only throw when you click the close button 

IOS 13

**Comment by Sh1d0w** [comment]
Thanks for the report. This should be fixed in version `4.6.5+rc.1`, I've disabled swipe to dismiss, so the user is forced either to press done or cancel.
