### ISSUE TITLE
Request for compress image option

### ISSUE THREAD

**Issue by inshaf** [Sh1d0w/multi_image_picker#420]
Getting error when I upload high-resolution images (5 MB files). But it works fine when the image is low resolution (300 KB). Anyway, I wanted to have low-resolution images, so upload to the server and compress at the server. I will be very helpful if there are anyway we can compress the image at the phone and send it to the server.

**Comment by Sh1d0w** [comment]
When using the plugin you can either request original image data which will be the raw image, or thumbnail which is resized version of the image.

When requesting either original image data or thumb you can specify the quality of the image which will further reduce its size.

Please read the docs of the plugin, it is well explained there.
