### ISSUE TITLE
Android Platform Exceptions Handling

### ISSUE THREAD

**Issue by pwnywiz** [Sh1d0w/multi_image_picker#422]
`multi_image_picker` version: ^4.6.5+rc.1

Is it happening on Android: Yes
Is it happening on iOS: Not Tested

Platform exceptions seem that they are not propagated properly in Android by the underlying platform code. Trying to handle some specific cases of exceptions (e.g. Permission Denied) but when the Deny button is clicked, the plugin closes and returns a `NoImagesSelectedException`.

**Comment by Sh1d0w** [comment]
Hi. Since version 4.6.1 permission handling was removed from the plugin, you need to make sure you have appropriate permissions before invoking the plugin. You can use another plugin to handle permissions by yourself, like simple_permissions.

**Comment by pwnywiz** [comment]
FishBun and BSImagePicker handle permission requests by themselves, so there is no need to handle the permissions since the platform libraries do handle them.
But shouldn't the permission exceptions / errors be propagated to dart with proper codes, since the underlying platform libraries do handle them?
Also what about `AssetNotFound` exception that is handled by `MultiImagePicker.pickImages`, although there are more exceptions available in other methods such as `requestThumbnail`?
