### ISSUE TITLE
Need take the photo on ios

### ISSUE THREAD

**Issue by minhduc1827** [Sh1d0w/multi_image_picker#423]
Hi,
Your library is nice, but when i run on ios i don't see the grid of taking the photo.
Can you add it to your library.
Thank you very much.

**Comment by Sh1d0w** [comment]
Hi, in order to be able to see the take photo icon in the grid you have to enable it when invoking the picker as per the docs suggest and also to run your app on a real iOS device. Camera is not available on iOS simulators thus the option does not appear there.

**Comment by pro100svitlo** [comment]
@Sh1d0w please, add some msg to the doc about the emulator :)
I came from the android  world,  so  I was not aware about it but confused as well... 🙏
