### ISSUE TITLE
There is a chance that the picture is not displayed

### ISSUE THREAD

**Issue by tiantianaixuexi** [Sh1d0w/multi_image_picker#424]
**Bug Report**

`multi_image_picker` version: 

Is it happening on Android:   

```
 <!-- run `flutter doctor` and paste the output here: -->No error
```

**Describe the bug**

![Screenshot_2020-04-06-18-23-34-44_d558f1d3473b80c](https://user-images.githubusercontent.com/31758095/78548789-e9d5f580-7833-11ea-8177-2ea9cf6adf2c.png)

There is a chance that the picture is not displayed,Have been circling

**Comment by tiantianaixuexi** [comment]
version is :^4.6.5+rc.1

**Comment by Sh1d0w** [comment]
Please report this issue to FishBun repo. This is the native Android picker I am using in this plugin. You can find link to the repo in the README file.
