### ISSUE TITLE
No such file or directory import 'package:multi_image_picker/asset.dart';

### ISSUE THREAD

**Issue by danny-4884** [Sh1d0w/multi_image_picker#425]
Error: Error when reading '../../../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.6.5+rc.1/lib/asset.dart': No such file or directory
import 'package:multi_image_picker/asset.dart';
error suggestion:
Target of URI doesn't exist: 'package:multi_image_picker/asset.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.dart(uri_does_not_exist)
multi_image_picker: 4.6.4

**Comment by Sh1d0w** [comment]
This seems like a cache issue. Please remove the plugin from your project and re-install it.

You can also run `flutter clean` before that.

**Comment by danny-4884** [comment]
ohk thanks its done ...my mistake i'm upgrading it to letest so there is some changes in asset ....i got it from 
https://sh1d0w.github.io/multi_image_picker/#/upgrading
