### ISSUE TITLE
Allow empty selection

### ISSUE THREAD

**Issue by NaikSoftware** [Sh1d0w/multi_image_picker#427]
Use case - I can select several images, but have no option to unselect all.

**Comment by Sh1d0w** [comment]
Can you describe what exactly do you mean, please?

Do you mean you want a button in the picker to deselect all selected images?

**Comment by NaikSoftware** [comment]
@Sh1d0w I want deselect all selected photos and by pressing "ok" button dont get warning message that nothing selected, but just receive empty result.

**Comment by Sh1d0w** [comment]
Unfortunately this is not supported by either of the two native image pickers I am using. Also there is a cancel button that the user can tap to cancel the selection.
