### ISSUE TITLE
Not Working after creating a build giving error Depricated api

### ISSUE THREAD

**Issue by bhanupratapchrome** [Sh1d0w/multi_image_picker#428]
**Bug Report**

4.6.4: 

Yes: 

```
 <!-- run `flutter doctor` and paste the output here: -->
Note: Recompile with -Xlint:deprecation for details.

Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\multi_image_picker-4.6.5+rc.1\android\src\main\java\com\vitanov\multiimagepicker\FileDirectory.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.
```

**Describe the bug**

While Creating build i am getting this error and when i run the build in debug mode its working fine but after creating build noting happening

**Comment by Sh1d0w** [comment]
Hi, this is a warning not error and it should not cause any problems.

Can you please what exactly do you mean by "nothing happening"? Are you able to run the app or is it crashing?

**Comment by bhanupratapchrome** [comment]
i am opening image picker on button click , at the time of debug mode its working fine , but when i m creating build of that app , gradle is showing  that warning above and when i run the builded app , nothing will appear on button click

**Comment by Sh1d0w** [comment]
Are you able to debug it with ADB when running the builded app and paste the logs here?

**Comment by adrianbarbe** [comment]
I'm facing the same issue.
