### ISSUE TITLE
Resizing an image causes jagged lines

### ISSUE THREAD

**Issue by Martibis** [Sh1d0w/multi_image_picker#429]
**Is your feature request related to a problem? Please describe.**
Resizing an image makes it looks jagged

**Describe the solution you'd like**
I assume this is due to the resizing algorithm used, I found an article which might help on that regard: http://vocaro.com/trevor/blog/2009/10/12/resize-a-uiimage-the-right-way/

**Describe alternatives you've considered**
A library that already implements this seemingly is Flutter_native_image, I am not familar with objc, so no clue how helpful it is: https://pub.dev/packages/flutter_native_image

**Additional context**
Eitherway, I absolutely love what you're doing here and will get you a few more coffees in the meantime!

**Comment by Sh1d0w** [comment]
Hey @Martibis , thanks for the support!

Can I ask you if you could provide screenshot of what exactly you are seeing when requesting image? 

Also it matters in what size you request the image and in what size you display it. In ideal case it should be similar sized container. E.g. if you are requesting 100x100 image but you are displaying it in 500x500 container and it is stretched it will look janky. Also are you supplying the quality parameter as well? If it is low number it can also cause the image to be low quality.

I took a look at the link you've provided. It seems pretty old (from 2009). This plugin uses [PHImageManager](https://github.com/Sh1d0w/multi_image_picker/blob/master/ios/Classes/SwiftMultiImagePickerPlugin.swift#L186) to request the resized image, which I think is the native way to resize image in iOS.

**Comment by Martibis** [comment]
Hey, absolute pleasure! Yeah sure, you can find them below. I am actually decreasing the size to compress the image (I also lower the quality, but I tested with max. quality and it didn't seem to make much difference), the main issue lies with the resizing (I assume because it crams more pixels in a smaller container). As you can see below the entire image is more jagged when scaling down!

![original](https://user-images.githubusercontent.com/13279066/79006378-52391580-7b59-11ea-9a48-fb08ed8625c7.jpeg)

![edited](https://user-images.githubusercontent.com/13279066/79006374-4fd6bb80-7b59-11ea-94f2-9a26a8993e2d.jpg)

**Comment by Martibis** [comment]
Read up on it a bit more, is there an option to change interpolation?
Something like CGContextSetInterpolationQuality

**Comment by Martibis** [comment]
Probably also import is that I experience this issue on Android (don't have an iOS device to test on atm)

**Comment by Sh1d0w** [comment]
Ah I assumed it is happening on iOS as you provided link to Obj-C article. 

I will investigate and get back to you. I can clearly see now the difference between the two images.

**Comment by Martibis** [comment]
Yeah, I think it might happen on both! I don't really think it's a bug necessarily, it's just what happens when you scale so many pixels down. If there is an option to change interpolation on Android / iOS, might be nice to also offer that option through multi image picker (I assume the scaling will take a bit longer if enabled though).

**Comment by Sh1d0w** [comment]
Hey @Martibis 

I've just released version 4.6.5 which should solve the problem. Can you test on your end and confirm?

You were right I had to calculate `inSampleSize` for the bitmap before decoding the input stream.

**Comment by Sh1d0w** [comment]
Version 4.6.6*

**Comment by Martibis** [comment]
I will test it in a bit and get back to you!

**Comment by Martibis** [comment]
Whilst the jagged lines still seem to be the same, it does seem like it is faster now somehow (but that might just be my perception). Here again the edited vs original.

![edited](https://user-images.githubusercontent.com/13279066/79049613-ecb25b00-7c24-11ea-8364-2442e225b78f.jpg)

![original](https://user-images.githubusercontent.com/13279066/79049611-e9b76a80-7c24-11ea-9d1d-edd9803e995d.jpeg)

Also a small sidenote, it would be great if there was an option for max-width, max-height in the getByteData function, or the option to allow double in the getThumbByteData(). I currently use getThumbByteData((( orginalheight / originalwidth) * 1080).toInt(), 1080, quality: 100), but because it has to convert a double value to int it doesn't keep the exact aspect ratio and crops the image a bit.

**Comment by Sh1d0w** [comment]
@Martibis How are you testing this? Are you observing this on the device, or you are sending cropped version to an API and then you are comparing the image? Btw just pushed `4.6.6+rc.1` with a small fix.

This method is meant to be used only on the device itself, to present a low res version of the image so it does not go OOM, it is not reliable way of cropping it before sending to a server because it takes into consideration the pixel density of the device. And looking at that same image on a device with different pixel density can render it jagged or blurry.

Regarding your suggestion about the resizing I hear you, but this should be introduced as new method. What you request is to scale the image preserving the aspect ratio. The current method crops the image and changing that will break backwards compatibility.

**Comment by Martibis** [comment]
I save all the assets, as part of a class, than I loop over them and use:
````
ByteData img = await i.asset.getThumbByteData( ((i.asset.originalWidth / i.asset.originalHeight) * 1080).toInt() , 1080, quality: 100);
String encodedImg = base64Encode( Uint8List.fromList(img.buffer.asUint8List()) ); 
````
Afterwards I send this through a post request to my NodeJS backend where it gets uploaded to S3.

So I assume that that is indeed causing the issue in that case. I tried the following package as well with the same result by the way: https://pub.dev/packages/flutter_image_compress

With regards to resize with aspect ratio, yeah, would be great to have something like that!

**Comment by Sh1d0w** [comment]
Yeah, so in that case if you need to crop or resize the image I would suggest to do it on the server side.

It is always good idea to send the original image anyways. You can still kind of compress it, the `getByteData` method also accepts quality parameter, so you can play with that and find the balance between size and quality. I've found that for me a number between 60 and 100 usually provides great level of size reduction with not much of a visual loss.

Bear in mind that it will be better to upload them one by one, you loop allocates memory for each image you base64 encode and possibly can crash your app with OOM.

I've opened a new issue to implement the scaling https://github.com/Sh1d0w/multi_image_picker/issues/430

Thanks!

**Comment by Martibis** [comment]
It's for a social media app, so the uploading should be quite fast, wouldn't resizing server side need more time as I need to send the multiple images over to server side (even with lowered quality)?

**Comment by Sh1d0w** [comment]
Well it depends on the implementation on the server. Usually resource hungry and long tasks are not run in the context of the same request that you are uploading the images, rather than on a queued job. As I mentioned earlier it is always a good practice to upload the original full sized images for a lot of reasons, you should not rely on the client to provide it in the correct size. Later if you decide you need another dimensions of the image, or simply want to generate additional set of cropped images it won't be possible. When having the original image you can always store it and generate as many and whatever sizes cropped thumbs you want and your application needs. Also you can regenerate crops etc.

I am going to do some more research on the topic and improve the image resizing if possible, but so far it seems the last changes I've pushed are the best we can do on the device side.

**Comment by Martibis** [comment]
Alright, let me play around a bit with resizing on server side! Thanks for the advice, working with optimizing images is a pretty new topic to me, but it's an interesting one so far! 😄

**Comment by Martibis** [comment]
Small update: did the resizing on the server side, it did indeed get rid of the jagged lines! Thanks a lot!

**Comment by amorenew** [comment]
My Image Picker

```
import 'dart:io';
import 'dart:math' as math;

import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:logging/logging.dart';
import 'package:multi_image_picker/multi_image_picker.dart';
import 'package:path/path.dart';
import 'package:path_provider/path_provider.dart';

import 'hex_color.dart';

const _bytesInMB = 1000000;
const _maxResolution = 1024 * 4;
final _logger = Logger('image_picker');

class ImagePicker {
  static Future<List<File>> takePhoto(
    BuildContext context, {
    bool isSmallImage = false,
    String prefix = '',
    int maxImages = 5,
    bool isOptimizeSize = false,
    int maxSizeInMB = 2,
  }) async {
    var resultList = <Asset>[];
    try {
      resultList = await MultiImagePicker.pickImages(
        maxImages: maxImages,
        enableCamera: true,
        cupertinoOptions: CupertinoOptions(
          selectionStrokeColor: Colors.white.toHex(),
          selectionFillColor: Theme.of(context).primaryColor.toHex(),
          selectionTextColor: Colors.white.toHex(),
          selectionCharacter: '✓',
        ),
        materialOptions: MaterialOptions(
          actionBarTitle: 'Gallery',
          allViewTitle: 'All Photos',
          useDetailsView: true,
          actionBarColor: Theme.of(context).primaryColor.toHex(),
          actionBarTitleColor: Colors.white.toHex(),
          lightStatusBar: false,
          statusBarColor: Theme.of(context).primaryColor.toHex(),
          startInAllView: true,
          selectCircleStrokeColor: Colors.white.toHex(),
          selectionLimitReachedText: "You can't select any more.",
        ),
      );
    } on NoImagesSelectedException catch (e) {
      _logger.finest(e.toString());
    }

    final resultFiles = await _convertImageAssetToFiles(
      assets: resultList,
      prefix: prefix,
      isOptimizeSize: isOptimizeSize,
      maxSizeInMB: maxSizeInMB,
    );

    return resultFiles;
  }

  /// Store the images in the temp directory
  /// as some files could be from the cloud and available
  /// for a temporary time like icloud images on ios
  static Future<List<File>> _convertImageAssetToFiles({
    @required List<Asset> assets,
    @required String prefix,
    bool isOptimizeSize = false,
    int maxSizeInMB = 2,
  }) async {
    final files = <File>[];
    if (assets == null) {
      return files;
    }

    for (final asset in assets) {
      var byteData = await asset.getByteData();

      final isExceedMaxSize =
          byteData.lengthInBytes > (maxSizeInMB * _bytesInMB);
      if (isOptimizeSize && isExceedMaxSize) {
        byteData = await _optimizeAssetSize(
          asset,
          byteData,
        );
      }

      final file = await _convertAssetToFile(
        prefix,
        asset,
        byteData,
      );
      files.add(file);
    }

    return files;
  }

  static Future<File> _convertAssetToFile(
    String prefix,
    Asset asset,
    ByteData byteData,
  ) async {
    final file = File(
      join(
        (await getTemporaryDirectory()).path,
        '$prefix${asset.name}',
      ),
    );
    await file.writeAsBytes(
      byteData.buffer.asUint8List(
        byteData.offsetInBytes,
        byteData.lengthInBytes,
      ),
    );

    return file;
  }

  static Future<ByteData> _optimizeAssetSize(
    Asset asset,
    ByteData byteData,
  ) async {
    final ratio = math.min<double>(
      _maxResolution / asset.originalWidth,
      _maxResolution / asset.originalHeight,
    );

    return asset.getThumbByteData(
      (asset.originalWidth * ratio).toInt(),
      (asset.originalHeight * ratio).toInt(),
    );
  }
}

```
