### ISSUE TITLE
providing file information

### ISSUE THREAD

**Issue by poshpawstudio** [Sh1d0w/multi_image_picker#431]
**Is your feature request related to a problem? Please describe.**
Kind of. I need to get the "file creation time" to handle the case when it's different to the timestamps in EXIF. File name will be also useful to deal with the case when the file name is actually time format.

**Describe the solution you'd like**
exposing a new structure FileMetadata with fileCreationTime, fileName, size, etc.

**Describe alternatives you've considered**
-

**Additional context**
I am trying to cover the edge case when there is no EXIF information. So I want to use 1) file creation time or 2) guesses time from regex match with the file name
Neither is possible now.

**Comment by Sh1d0w** [comment]
Thanks for the suggestion I will look into it.
