### ISSUE TITLE
混编项目使用multi_image_picker: '4.6.3'，报PlatformException(already_active, Image picker is already active, null)错误。

### ISSUE THREAD

**Issue by gaoshan85** [Sh1d0w/multi_image_picker#432]
**Bug Report**

`multi_image_picker` version: 

Is it happening on Android: 

Is it happening on iOS: 

```
 <!-- run `flutter doctor` and paste the output here: -->
```

**Describe the bug**
Flutter构建的项目，但内部自定义了一个蓝牙插件调用原生程序，写法一样，无特别之处。
使用multi_image_picker控制选择图像，点击后页面无反应，后台报错PlatformException(already_active, Image picker is already active, null)。
单独运行提供Demo是没有问题，可正常获取图片。

上述问题推测是只发生在混编情况下。之前看到网上也有相关描述，但均未解决。
如：https://blog.csdn.net/u011212112/article/details/92797474
还有人提出是使用flutter_boost插件导致的，但我项目本身无使用此插件。
alibaba/flutter_boost#263
https://github.com/alibaba/flutter_boost/issues/263

目前没找到好的解决方式，故求助于作者看是否可以修改此问题。

具体报错信息：
4-15 17:33:07.515 2269-2284/com.green.zhzq.yz E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null)
    #0      MultiImagePicker.requestThumbnail (package:multi_image_picker/src/picker.dart:130:11)
    <asynchronous suspension>
    #1      Asset.getThumbByteData (package:multi_image_picker/src/asset.dart:104:28)
    #2      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:47:6)
    #3      Asset.getThumbByteData (package:multi_image_picker/src/asset.dart:77:36)
    #4      Asset.requestThumbnail (package:multi_image_picker/src/asset.dart:157:12)
    #5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:47:6)
    #6      Asset.requestThumbnail (package:multi_image_picker/src/asset.dart:152:36)
    #7      AssetState._loadImage (package:zhzq_master/ui/widgets/PhotoSelect/asset_view.dart:45:31)
    #8      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:47:6)
    #9      AssetState._loadImage

**Comment by Sh1d0w** [comment]
Please make your post in English, I do not speak Chinese.

**Comment by CatEatFishs** [comment]
I meet same questoin
