### ISSUE TITLE
Cannot run app in android emulator 

### ISSUE THREAD

**Issue by danny-4884** [Sh1d0w/multi_image_picker#433]
04-15 19:18:45.548  4643  4643 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.vitanov.multiimagepicker.MultiImagePickerFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.vitanov.multiimagepicker.MultiImagePickerFileProvider" on path: DexPathList[[zip file "/data/app/com.relfor.sevadeep-1/base.apk"],nativeLibraryDirectories=[/data/app/com.relfor.sevadeep-1/lib/x86, /data/app/com.relfor.sevadeep-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]

**Comment by Sh1d0w** [comment]
Please follow the issue template, issues that does not follow the issue template are being instantly closed.

The error suggests that you have not migrated your project to AndroidX as the plugin docs describe.

**Comment by danny-4884** [comment]
I already migrated
thanks
