### ISSUE TITLE
建议开放api 文本 支持中文

### ISSUE THREAD

**Issue by kangshibiao123** [Sh1d0w/multi_image_picker#435]
建议开放api 文本 支持中文

**Comment by Sh1d0w** [comment]
Please type in english and follow the issue template.

**Comment by yuexunshi** [comment]
> 建议开放api 文本 支持中文


打开Xode “Runner” -> “info.plist”，添加一项“Localized resources can be mixed”，值设置为“yes”即可！
`但是done没有中文翻译，需要自己添加ios的国际化文件，在文件里写下翻译。"Done" = "确定";`
[ios国际化连接](https://www.jianshu.com/p/88c1b65e3ddb)
