### ISSUE TITLE
Initial Asset GridView

### ISSUE THREAD

**Issue by alfavat** [Sh1d0w/multi_image_picker#436]
hi
when i choose images from imagepicker it works fine and GridView shows the images 
now i want to show thumbnails from url but it is not working.
this is what i tried so far :
**```
thumbnails.add(
                     new Asset(fileId, fileUrl(network), 300, 300)
                     );
```**
Is there any way that i can add my images to gridview ?

**Comment by Sh1d0w** [comment]
The asset class is meant to be created only from this plugin, not manually.

Yes you can add images to your grid view, there are a lot of ways you can achieve this - implement logic that handles both asset or file types and pass files for your images, or save the assets as files once picked etc
