### ISSUE TITLE
Asset.name results in a .plist file with edited photos on iOS.

### ISSUE THREAD

**Issue by calebisstupid** [Sh1d0w/multi_image_picker#441]
I've been putting in some more work on our fork of this library with videos enabled, and I came an issue that was impacting our work. Thought I would point it out here in case the issue exists for anyone else.

**Bug Report**

Is it happening on Android: No

Is it happening on iOS: Yes

**Describe the bug**

This impacts any photos (or videos in our case) edited using the native Photos app edit features.

Getting the name of an Asset when selecting an edited photo (or video) on iOS results in the name being "Adjustments.plist". This is probably OK for most cases, but if you need to pull a MIME type off the filename, it will not be recognized as a media file.

In the PHAsset extension `originalFileName`, the following code is causing this:

`
let resources = PHAssetResource.assetResources(for: self)
            if let resource = resources.first {
                fname = resource.originalFilename
            }
`

For edited images, you will get multiple PHAssetResources, the first of which is always the .plist editing adjustments file.

In my testing, I have found that the using `resources.last` resource is what we always wanted (for a live image, the last resource is the still image with the edits applied).

**Comment by Sh1d0w** [comment]
Thanks for the report @calebisstupid , I will amend it.

**Comment by trustmefelix** [comment]
I have encountered this issue too, may I know is this fixed yet?

**Comment by Sh1d0w** [comment]
Hi, yes it is released in version 4.7.13

**Comment by trustmefelix** [comment]
Hi, I still have this issue. When I select multi images, all file names are FullSizeRender.jpg which leads to duplicated images if I use these names
