### ISSUE TITLE
How do I implement your metadata class

### ISSUE THREAD

**Issue by qalqal1212** [Sh1d0w/multi_image_picker#449]
Hi there is there a wrong thing I did that it cannot read the metadata 

Future<void> loadAssets(BuildContext context) async {
    List<Asset> resultList = List<Asset>();
    List<MultipartFile> multiPart = List<MultipartFile>();
    String error = 'No Error Dectected';

    try {
      ///This is the fucntion to capture image using gallery/camera
      resultList = await MultiImagePicker.pickImages(
        maxImages: 5,
        enableCamera: true,
        selectedAssets: images,
        cupertinoOptions: CupertinoOptions(takePhotoIcon: 'chat'),
        materialOptions: MaterialOptions(
          actionBarColor: '#abcdef',
          actionBarTitle: 'Gallery',
          allViewTitle: 'All Photos',
          useDetailsView: false,
          selectCircleStrokeColor: '#000000',
        ),
      );
    } on Exception catch (e) {
      error = e.toString();
    }
    if (!mounted) return;
     // this is to set the state of the image after pick
    setState(() {
      images = resultList;
    });
      for(var x=0; x < images.length; x++){
      Asset asset = images[x];
      Metadata metadata = await asset.metadata;
      print(metadata.exif.dateTime.toString());
      print(metadata.exif.imageDescription.toString());
      print(metadata.exif.dateTimeDigitized.toString());
    }
    Navigator.of(context).pop();
  }

**Comment by Sh1d0w** [comment]
Hi, yes thats correct way to obtain the metadata. Bear in mind that the images may not have some of the metadata properties, so in that case the values you are printing will return null. Can you describe whats the problem?

**Comment by qalqal1212** [comment]
Ohh i see thats how it is. I am having trouble extracting out the datetime and imagedescription because I thought I have put wrongly for the code that causes it to return null 
<img width="981" alt="Screenshot 2020-04-28 at 11 47 22 AM" src="https://user-images.githubusercontent.com/49523152/80445096-09999e80-8946-11ea-959d-8bbad578f6fc.png">
if I use the getbytedata i can only get the name so how do I get the metadata the image I am using is from the camera of my phone but I am running the app from an emulator

**Comment by Sh1d0w** [comment]
First of all you don't need to call getByteData there. This function returns the contents of the image, which you are not using there. To obtain the metadata you need to call `Metadata metadata = await asset.metadata;` as in your example above.

**Comment by qalqal1212** [comment]
<img width="1131" alt="Screenshot 2020-04-28 at 12 46 57 PM" src="https://user-images.githubusercontent.com/49523152/80448282-613c0800-894e-11ea-8733-e06a46f91458.png">
Hi sir these is what I get when declaring the metadata
