### ISSUE TITLE
Bug Camera: Android 10: java.io.IOException: No such file or directory

### ISSUE THREAD

**Issue by salim-lachdhaf** [Sh1d0w/multi_image_picker#450]
**Bug Report**

`multi_image_picker` version: 4.6.4-rc.1

Is it happening on Android: Yes

Is it happening on iOS: not tested

```
 [√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [version 6.1.7601], locale fr-FR)
    • Flutter version 1.12.13+hotfix.9 at E:\SDK\FlutterSDK
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at E:\SDK\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = E:\SDK\Android\Sdk
    • ANDROID_SDK_ROOT = E:\SDK\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (2 available)
    • SM T813                   • 64fd402f04e9bba0 • android-arm64 • Android 7.0 (API 24)
    • Android SDK built for x86 • emulator-5554    • android-x86   • Android 10 (API 29) (emulator)

• No issues found!
Process finished with exit code 0
```

**Describe the bug**

on Android 10 camera does not open and i got this exception:

> W/System.err( 7172): java.io.IOException: No such file or directory
> W/System.err( 7172): 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
> W/System.err( 7172): 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
> W/System.err( 7172): 	at java.io.File.createTempFile(File.java:2018)
> W/System.err( 7172): 	at com.sangcomz.fishbun.util.CameraUtil.createImageFile(CameraUtil.java:64)
> W/System.err( 7172): 	at com.sangcomz.fishbun.util.CameraUtil.takePicture(CameraUtil.java:31)
> W/System.err( 7172): 	at com.sangcomz.fishbun.ui.album.AlbumController.takePicture(AlbumController.java:151)
> W/System.err( 7172): 	at com.sangcomz.fishbun.ui.album.AlbumActivity$1.onClick(AlbumActivity.java:105)
> W/System.err( 7172): 	at android.view.View.performClick(View.java:7125)
> W/System.err( 7172): 	at android.view.View.performClickInternal(View.java:7102)
> W/System.err( 7172): 	at android.view.View.access$3500(View.java:801)
> W/System.err( 7172): 	at android.view.View$PerformClick.run(View.java:27336)
> W/System.err( 7172): 	at android.os.Handler.handleCallback(Handler.java:883)
> W/System.err( 7172): 	at android.os.Handler.dispatchMessage(Handler.java:100)
> W/System.err( 7172): 	at android.os.Looper.loop(Looper.java:214)
> W/System.err( 7172): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
> W/System.err( 7172): 	at java.lang.reflect.Method.invoke(Native Method)
> W/System.err( 7172): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> W/System.err( 7172): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by Sh1d0w** [comment]
Hi this issue seems to originate from the FishBun library, so there is nothing I can do about it. Please report this to the official FishBun repo and once the owner fixes it I will update the plugin immediately.

Thanks.

**Comment by marianoarga** [comment]
This fixed the issue?
https://github.com/sangcomz/FishBun/pull/127

**Comment by salim-lachdhaf** [comment]
no, the issue is related to android 10

**Comment by Yunus0or1** [comment]
Facing problem on this issue. What is the solution. Using 4.7.14 version of multi_image_picker.

**Comment by greymag** [comment]
@salim-lachdhaf @Yunus0or1 as a temporary solution you could try add `android:requestLegacyExternalStorage="true"` as an attribute to the `<application>` tag in `AndroidManifest.xml`. Works for me.
