### ISSUE TITLE
Add metadata to asset bytes

### ISSUE THREAD

**Issue by aloisdeniel** [Sh1d0w/multi_image_picker#451]
**Is your feature request related to a problem? Please describe.**

When I read the byte data from an assets with `asset.getByteData()`, the metadata aren't present (at least on Android). They are accessible from the `asset.metadata`, but I need to keep the data into the bytes sent it to my backend, and I don't know how to append them.

**Describe the solution you'd like**

Ideally, I would like to have the medata in the bytes out of the `asset.getByteData()`. That is how image_picker works for example. They added several helpers to manage that in the sources.

* [ExifDataCopier.java](https://github.com/flutter/plugins/blob/master/packages/image_picker/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ExifDataCopier.java)

**Describe alternatives you've considered**

Maybe switch back to a single selection with `image_picker` package. Il will also study this package source.

**Comment by Sh1d0w** [comment]
PRs introducing this functionality are welcome, until then there is the `asset.metadata` accessor you can use to obtain the metadata.
