### ISSUE TITLE
Unified UI

### ISSUE THREAD

**Issue by aloisdeniel** [Sh1d0w/multi_image_picker#452]
**Is your feature request related to a problem? Please describe.**

It would be better to have a unified picker for all platforms, developed with Flutter and just an abstraction of the native API for listing all the gallery content (collections of assets).

**Describe the solution you'd like**

I would be able to customize the UI with Flutter widgets.

**Describe alternatives you've considered**

I didn't find a plugin that list the content of the gallery for each platform, but it seems doable since BSImagePicker and FishBun do that.

**Comment by Sh1d0w** [comment]
There are already such pickers, this is not the goal of this library.
