### ISSUE TITLE
Asset path

### ISSUE THREAD

**Issue by sergeatoma** [Sh1d0w/multi_image_picker#453]
Any possible solution to get Asset path using multi_image_picker? 

Points: 
1. String path provide a memory efficient way to manipulate with huge amount of photos & pictures.
2. Easily fit any system contract that require File type.
3. Possibilities to make CRUD operations

**Comment by Sh1d0w** [comment]
Please read the [FAQ](https://sh1d0w.github.io/multi_image_picker/#/faq?id=why-the-plugin-don39t-return-image-paths-directly) section of the documentation .
