### ISSUE TITLE
Done button is not localized from system localization.

### ISSUE THREAD

**Issue by liyang1518** [Sh1d0w/multi_image_picker#459]
[see this](https://github.com/mikaoj/BSImagePicker/issues/249).
waiting for you update.

**Comment by Sh1d0w** [comment]
Unfortunately I can not update to version 3 of BSImagePicker as the author decided to remove the camera option in version 3 for some reason, so I am stuck with version 2 here. I don't want to introduce breaking change so I've already opened https://github.com/Sh1d0w/multi_image_picker/issues/373 to switch to another iOS library instead BSImagePicker that supports taking pictures as well.
