### ISSUE TITLE
Unhandled Exception: The user has cancelled the selection

### ISSUE THREAD

**Issue by tbm98** [Sh1d0w/multi_image_picker#462]
**Bug Report**

`multi_image_picker` version: 4.6.7

Is it happening on Android: Not yet test

Is it happening on iOS: Yes

[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: The user has cancelled the selection
#0      MultiImagePicker.pickImages (package:multi_image_picker/src/picker.dart:78:11)
<asynchronous suspension>
#1      _InputFormState._pickImage (package:wedding/src/views/widgets/order/order_statement_of_deposit_form.dart:80:43)
#2      _InputFormState.build.<anonymous closure> (package:wedding/src/views/widgets/order/order_statement_of_deposit_form.dart:89:9)
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:918:19)
#4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1004:38)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:522:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
#8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:254:7<…>
[VERBOSE-2:profiler_metrics_ios.mm(65)] Error retrieving thread information: (ipc/send) invalid destination port

**Comment by apodacaduron** [comment]
Try using a try catch around your code:
```
    try {
      List files = await MultiImagePicker.pickImages(
        enableCamera: true,
        maxImages: 300,
      );
      if (files != null) {
        setState(() {
          formData['files'] = files;
        });
      }
    } catch (e) {
      print(e);
    }
```

**Comment by tbm98** [comment]
@apodacaduron Yep. But I think it should be return null if user cancelled.

**Comment by Sh1d0w** [comment]
That intentional, you need to follow @apodacaduron advice. The plugin returns array of assets if successful, for consistency it is not good idea to return null.
