### ISSUE TITLE
Selected Images gets reset on pressing back button

### ISSUE THREAD

**Issue by gouthamkumar253** [Sh1d0w/multi_image_picker#471]
**Bug Report**

`multi_image_picker` version: 4.6.7

Is it happening on Android: Yes 

Is it happening on iOS: Yes 

**Describe the bug**

I have an empty list of assets called images and i press a button which calls pickImages method. Now I select 3 images and click on done. I'm seeing all 3 images in my app within the AssetThumb. Now I again press the button to choose more images and I'm passing selectedAssets. Now if I click on back button, my selectedAssets are reset to empty list. I should be able to maintain the initially passed assets even if I press back without selecting/deselecting any more images.

**Comment by nhtlquan** [comment]
Me too, please fix it

**Comment by Sh1d0w** [comment]
The back button triggers NoAssetsSelected exception, which you can handle to not overwrite your currently selected images.

**Comment by Goolpe** [comment]
> The back button triggers NoAssetsSelected exception, which you can handle to not overwrite your currently selected images.

If set startInAllView: true in materialOptions, back button doesn't trigger any exceptions and return empty list.

```
try {
      final _selectedAssets = await MultiImagePicker.pickImages(
        selectedAssets: assets,
        maxImages: 100,
        enableCamera: true,
        materialOptions: const MaterialOptions(
          startInAllView: true,
        )
      );
      print(_selectedAssets);
    } on Exception catch (e) {
      print(e);
    }
```
