### ISSUE TITLE
Image loading in the same window

### ISSUE THREAD

**Issue by Guidogl** [Sh1d0w/multi_image_picker#472]
Hi,

Currently, your package is creating a new page with an actionBar where you can pick images but in my app design, I would like to load all images in the same page where I click "Pick Images" button and then send picked images to other widget. I am new to Flutter, so I would like to know, if it would be difficult to customize this package?

**Comment by Sh1d0w** [comment]
Hi,

this plugin uses a native libraries for iOS and Android to present the image picker, so no it is not possible.

However it supports number of customisation options you can check them out in the plugin docs.
