### ISSUE TITLE
Language localization on iOS need improve

### ISSUE THREAD

**Issue by AiguangLi** [Sh1d0w/multi_image_picker#473]
**Describe the solution you'd like**
The button 'Done' in the right top corner cannot be customized. It's better to pass a String to set the button title.

**Describe alternatives you've considered**
 Change the Done button title based on the app main location in info.plist setting.

![image](https://user-images.githubusercontent.com/7286419/83240631-40283a80-a1cc-11ea-9f35-ff30f80343d8.png)

**Comment by Sh1d0w** [comment]
I agree, feel free to open a PR to fix this and I will review it.

**Comment by temirfe** [comment]
My phone language is Russian and I have added 'ru' to supportedLocales, however I still get 'Cancel', 'Recens' and 'Done' in english on iOS. Радослав, ну что же так? )
