### ISSUE TITLE
FileSize issue 

### ISSUE THREAD

**Issue by alfavat** [Sh1d0w/multi_image_picker#477]
hi
thanks for the Great package
but when I upload images to my server the files length are different than the original file size.
this is the code that I am using : 
// Asset file; 
`var fileName = path.basename(file.name);
    ByteData byteData = await file.getByteData();
    List<int> imageData = byteData.buffer.asUint8List();
    MultipartFile multipartFile = MultipartFile.fromBytes(
      imageData,
      filename: fileName,
      contentType: MediaType("image", "jpg"),
    );
FormData formData =
        new FormData.fromMap(<String, dynamic>{"file": multipartFile});
`

when I print out file metadata length it is : 4041
but when I print out formData.length it is 799108
am I doing something wrong ?
thanks

**Comment by Sh1d0w** [comment]
Hi, what do you mean by "print out file metadata"? Which platform is Android or iOS? Also formData.length does not represent the file size.

**Comment by alfavat** [comment]
I am testing on android.
by print I mean : 
var data = await file.metadata;
print(data.exif.imageLength);// 4041

**Comment by Sh1d0w** [comment]
The focal length of the image has nothing to do with the file size.

If you want to compare the file size just inspect the image size in your android app gallery and download and compare the size of the uploaded image. The uploaded image however should be slightly smaller than the original (give you provider 100 for quality) because when you call `getByteData` it strips all image metadata.

**Comment by AxesandGrinds** [comment]
@Sh1d0w , Can you just state how exactly to get file size from Asset? Is it metadata.length?

**Comment by Sh1d0w** [comment]
You can obtain the byte data and calculate it yourself with a function like this https://gist.github.com/zzpmaster/ec51afdbbfa5b2bf6ced13374ff891d9

**Comment by AxesandGrinds** [comment]
Thank you but can you in-build size function into Asset file type in a future release?

**Comment by Sh1d0w** [comment]
Sure that seems reasonable.
