### ISSUE TITLE
Is there a way to get the selected images as Files or at least their Path?

### ISSUE THREAD

**Issue by agavrel** [Sh1d0w/multi_image_picker#479]
Images are ultimately sent to a REST api, so:

**Is your feature request related to a problem? Please describe.**
Is there a way to get the selected images as Files or at least their path?

**Describe the solution you'd like**
return a list of files instead of a list of assets

**Describe alternatives you've considered**
 (unless there is a solution to get the file from asset, which I am unaware of?)

**Comment by agavrel** [comment]
Ok figured out thanks to documentation https://pub.dev/documentation/multi_image_picker/latest/multi_image_picker/Asset-class.html

**Comment by e-e** [comment]
@agavrel What was your solution for this? I have the same question.
