### ISSUE TITLE
Failed resolution of: Landroidx/lifecycle/LifecycleEventObserver

### ISSUE THREAD

**Issue by tree1891** [Sh1d0w/multi_image_picker#480]
Flutter 1.17.3 

`E/AndroidRuntime(27758): java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/LifecycleEventObserver;
E/AndroidRuntime(27758): 	at java.lang.Class.newInstance(Native Method)
E/AndroidRuntime(27758): 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
E/AndroidRuntime(27758): 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
E/AndroidRuntime(27758): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
E/AndroidRuntime(27758): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
E/AndroidRuntime(27758): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
E/AndroidRuntime(27758): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/AndroidRuntime(27758): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(27758): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(27758): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
E/AndroidRuntime(27758): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(27758): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(27758): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(27758): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27758): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(27758): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(27758): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.LifecycleEventObserver" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.mct.wallbird-0G2XcO-He8nYs5PH2Fbiug==/base.apk"],nativeLibraryDirectories=[/data/app/com.mct.wallbird-0G2XcO-He8nYs5PH2Fbiug==/lib/x86, /data/app/com.mct.wallbird-0G2XcO-He8nYs5PH2Fbiug==/base.apk!/lib/x86, /system/lib]]
E/AndroidRuntime(27758): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/AndroidRuntime(27758): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(27758): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)`

**Comment by Sh1d0w** [comment]
You need to migrate your project to AndroidX as described in the docs.

**Comment by tree1891** [comment]
what is the version not needed androidx?

**Comment by tree1891** [comment]
already use androidx, but error occurs.
