### ISSUE TITLE
The Localizations is not working for zh-cn

### ISSUE THREAD

**Issue by mbb007** [Sh1d0w/multi_image_picker#481]
the language on my iphone is "简体中文"， but the label of the image picker is still displaying in English, is there any thing I did wrong? Here is my code,
 ```
List<Asset> resultList = List<Asset>();
    String error = 'No Error Dectected';

    try {
      resultList = await MultiImagePicker.pickImages(
        maxImages: 300,
        enableCamera: true,
        selectedAssets: images,
        cupertinoOptions: CupertinoOptions(
            takePhotoIcon: "chat",
        ),
        materialOptions: MaterialOptions(
          actionBarTitle: "图片选择",
          allViewTitle: "所有图片",
          useDetailsView: false,
          selectCircleStrokeColor: "#000000",
        ),

      );
    } on Exception catch (e) {
      error = e.toString();
    }

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;

    setState(() {
      images = resultList;
      _error = error;
    });
```

**Comment by mbb007** [comment]
The "Cancel" Problem is solved by changing the Localization native development region to China, but the done button is still displayed in English. I am not an IOSer, but I am able to track down the done button title in PhotosViewController.swift, it feels like that the origin code NSLocalizedString("Done", comment: "Done") is not working as expected, so I use "完成" to replace it directly since my app is only used in China, but it will be appreciated if any one can offer a more elegant solution.

**Comment by Sh1d0w** [comment]
Hi, this is known bug with the current image picker for iOS. It will be solved once this task it implemented https://github.com/Sh1d0w/multi_image_picker/issues/373

**Comment by yuexunshi** [comment]
> The "Cancel" Problem is solved by changing the Localization native development region to China, but the done button is still displayed in English. I am not an IOSer, but I am able to track down the done button title in PhotosViewController.swift, it feels like that the origin code NSLocalizedString("Done", comment: "Done") is not working as expected, so I use "完成" to replace it directly since my app is only used in China, but it will be appreciated if any one can offer a more elegant solution.


打开Xode “Runner” -> “info.plist”，添加一项“Localized resources can be mixed”，值设置为“yes”即可！
`但是done没有中文翻译，需要自己添加ios的国际化文件，在文件里写下翻译。"Done" = "确定";`
[ios国际化连接](https://www.jianshu.com/p/88c1b65e3ddb)

**Comment by niyangup** [comment]
> > The "Cancel" Problem is solved by changing the Localization native development region to China, but the done button is still displayed in English. I am not an IOSer, but I am able to track down the done button title in PhotosViewController.swift, it feels like that the origin code NSLocalizedString("Done", comment: "Done") is not working as expected, so I use "完成" to replace it directly since my app is only used in China, but it will be appreciated if any one can offer a more elegant solution.
> 
> 打开Xode “Runner” -> “info.plist”，添加一项“Localized resources can be mixed”，值设置为“yes”即可！
> `但是done没有中文翻译，需要自己添加ios的国际化文件，在文件里写下翻译。"Done" = "确定";`
> [ios国际化连接](https://www.jianshu.com/p/88c1b65e3ddb)

非常感谢!

**Comment by xiejibiao** [comment]
我配置了 在文件里写下翻译。"Done" = "确定"; 后无效，这个是什么问题？
