### ISSUE TITLE
Support for video files

### ISSUE THREAD

**Issue by Martibis** [Sh1d0w/multi_image_picker#482]
**Is your feature request related to a problem? Please describe.**
No, just would be a good option to have.

**Describe the solution you'd like**
The option to also select video files.

**Describe alternatives you've considered**
Using the base image picker library for video, but well, it's kind of an iffy solution.

**Additional context**
If I recall correctly, you mentioned in the past you were not looking to support video. Just wondering if this is still the case, and if you had a rough idea on the work needed to add this functionality?

**Comment by Sh1d0w** [comment]
Hi, yes that's correct, I do not plan to add video support by myself. I don't need it, nor I have the time currently. To be honest I'd expect this to be a huge change simply because how the plugin works.
