### ISSUE TITLE
Deprecated API FileDirectory.java

### ISSUE THREAD

**Issue by urmatt** [Sh1d0w/multi_image_picker#484]
**Bug Report**

`multi_image_picker` version: 4.6.7

Is it happening on Android: Yes

```
 Flutter doctor FINE
```

**Describe the bug**

pub.dartlang.org\multi_image_picker- ...4.6.7\android\src\main\java\com\vitanov\multiimagepicker\FileDirectory.java uses or overrides a deprecated API.

It causes on android api 29 in others I don't know.

**Comment by mohdtaha60** [comment]
This bug still exists
