### ISSUE TITLE
Pre-select already selected images

### ISSUE THREAD

**Issue by topex-psy** [Sh1d0w/multi_image_picker#488]
**Is your feature request related to a problem? Please describe.**
Let say I have selected 2 images, the I launch image picker again, then the former 2 selected images have to be checked, currently none is checked.

**Describe the solution you'd like**
The former 2 selected images should be checked/pre-selected, thus I can select other images to add and it can prevent duplication. Like in the Facebook app.

**Describe alternatives you've considered**

**Additional context**

**Comment by Sh1d0w** [comment]
This is already supported see the docs of the plugin and the [example app](https://github.com/Sh1d0w/multi_image_picker/blob/master/example/lib/main.dart#L44)
