### ISSUE TITLE
can you enhance Assert to return also full path of image?

### ISSUE THREAD

**Issue by kw2019ltd** [Sh1d0w/multi_image_picker#490]
can you enhance Assert to return also full path of image?

**Comment by aditya21** [comment]
@kw2019ltd I was able to get path by doing below:

`  Future<File> getImageFileFromAssets(ByteData byteData) async {
    // Store the picture in the temp directory.
    // Find the temp directory using the `path_provider` plugin.
    final file = File(join(
      (await getTemporaryDirectory()).path,
      '${DateTime.now().millisecond}.jpg',
    ));
    await file.writeAsBytes(byteData.buffer
        .asUint8List(byteData.offsetInBytes, byteData.lengthInBytes));

    return file;
  }`

Then call the function like this:
`for (var asset in files) {
                  if (asset != null) {
                    final file =
                        **await getImageFileFromAssets(await asset.getByteData());**
                  }
  }`

**Comment by jonathanbonzali** [comment]
how do you  get the file extension before saving to file?
