### ISSUE TITLE
java.io.IOException: Permission denied

### ISSUE THREAD

**Issue by dvzhou** [Sh1d0w/multi_image_picker#492]
**Bug Report**

`multi_image_picker` version: 4.6.7

Is it happening on Android: Yes

Is it happening on iOS: No

```
 <!-- run `flutter doctor` and paste the output here: -->
```

**Describe the bug**

<img width="907" alt="WX20200702-172336@2x" src="https://user-images.githubusercontent.com/40446804/86341549-080f8e00-bc89-11ea-8a28-1b10e96e92b9.png">

When set the enableCamera attribute is true, and when you click the camera, you will report the error information in the picture, which is compared with the example project, and the configuration is exactly the same.

**Comment by Ranjithsp6** [comment]
Same issue for me too. @dvzhou Did you find any solution?

**Comment by Arialena** [comment]
遇到同样的问题，请问解决了吗？

**Comment by dvzhou** [comment]
> Same issue for me too. @dvzhou Did you find any solution?

no.

**Comment by dvzhou** [comment]
> 遇到同样的问题，请问解决了吗？

no

**Comment by EbramAtef** [comment]
If you are targeting android 10, please make sure that compileSdkVersion in the gradle file is 29 and please add this `android:requestLegacyExternalStorage="true"` to application tag in the android manifest.

Make sure to run `flutter clean` and rebuild you app afterwards.

**Comment by dvzhou** [comment]
> android:requestLegacyExternalStorage="true"



> If you are targeting android 10, please make sure that compileSdkVersion in the gradle file is 29 and please add this `android:requestLegacyExternalStorage="true"` to application tag in the android manifest.
> 
> Make sure to run `flutter clean` and rebuild you app afterwards.

Yes, the problem is solved. Thank you for your answer！
