### ISSUE TITLE
Bug on IOS 13, live image return file .MOV

### ISSUE THREAD

**Issue by nhtlquan** [Sh1d0w/multi_image_picker#493]
**Bug Report**

`multi_image_picker` version: 4.6.7

Is it happening on Android: No
Is it happening on iOS: Yes

When I use Iphone and picker multi image. If live Image return file .MOV and can not upload to server!

**Comment by drosa88** [comment]
Same issue here... and this causes my app to crash..

**Comment by Sh1d0w** [comment]
Hi @drosa88 , this should be fixed in 4.7.13, did you try this version?

**Comment by yangyxd** [comment]
I have the same problem. I hope users can't select mov files when selecting photos. Thank you~
