### ISSUE TITLE
Plugin Problem

### ISSUE THREAD

**Issue by mariofraga84** [Sh1d0w/multi_image_picker#50]
C:\flutter\.pub-cache\hosted\pub.dartlang.org\multi_image_picker-2.3.28\android\src\main\java\com\vitanov\multiimagepicker\MultiImagePickerPlugin.java:310: error: cannot find symbol
                ExifInterface.TAG_ISO_SPEED,
                             ^
  symbol:   variable TAG_ISO_SPEED
  location: class ExifInterface
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':multi_image_picker:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by mariofraga84** [comment]
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [versÃ£o 10.0.17134.472], locale pt-BR)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.2)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by Sh1d0w** [comment]
@mariofraga84 Please read the documentation, it is explained how to resolve this

https://sh1d0w.github.io/multi_image_picker/#/androudtroubleshooting

**Comment by ronaldG19** [comment]
does not work
