### ISSUE TITLE
FileSystemException: Cannot retrieve length of file, path whenever try to select multiple images

### ISSUE THREAD

**Issue by amitkumar19** [Sh1d0w/multi_image_picker#504]
Debug service listening on ws://127.0.0.1:58513/H_P6-aSBheI=/ws
Syncing files to device iPhone SE (2nd generation)...
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: FileSystemException: Cannot retrieve length of file, path = 'IMG_0001.JPG' (OS Error: No such file or directory, errno = 2)
#0      _File.length.<anonymous closure> (dart:io/file_impl.dart:366:9)
#1      _rootRunUnary (dart:async/zone.dart:1198:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#8      _rootRun (dart:async/zone.dart:1190:13)
#9      _CustomZone.run (dart:async/zone.dart:1093:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:<…>

**Comment by alleyng** [comment]
same issue here

**Comment by mamd33** [comment]
+1

**Comment by amitkumar19** [comment]
@Sh1d0w please help us to resolve this issue.

**Comment by Sh1d0w** [comment]
Well the error says the image file does not exist. Can you give more context on how to reproduce?

**Comment by amitkumar19** [comment]
I am trying to upload multiple images by api. From selecting the images from device those images visible in preview and in image list I get the data but whenever I try to upload it by using mention code I get this error.

var url = Uri.parse(completeURL);
      var request = new dartHttp.MultipartRequest("POST", url);
      request.fields['authKey'] = uniqueHash;
      request.fields['title'] = newsUploadRequest.title;
      request.fields['caption'] = newsUploadRequest.description;
      for (int i = 0; i < newsUploadRequest.fileList.length; i++) {
        request.files.add(await dartHttp.MultipartFile.fromPath(
            newsUploadRequest.type, newsUploadRequest.fileList[i].name));
      }

**Comment by Sh1d0w** [comment]
The path property of the asset is not the path on the file system. You should not use it for file upload. 

Please read the docs there is an example for file upload there.
