### ISSUE TITLE
Unhandled Exception: PlatformException(already_active, Image picker is already active, null)

### ISSUE THREAD

**Issue by vilashp** [Sh1d0w/multi_image_picker#511]
**Bug Report**
E/flutter (19381): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null)
E/flutter (19381): #0      MultiImagePicker.pickImages (package:multi_image_picker/src/picker.dart:80:11)
E/flutter (19381): <asynchronous suspension>
E/flutter (19381): #1      _MyAppState.loadAssets (package:patient_form/main.dart:89:43)
E/flutter (19381): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter (19381): #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (19381): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (19381): #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (19381): #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (19381): #7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter (19381): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter (19381): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (19381): #10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (19381): #11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (19381): #12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (19381): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (19381): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (19381): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (19381): #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (19381): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (19381): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (19381): #19     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (19381): #20     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (19381): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (19381): #22     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (19381): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
E/flutter (19381): 

`multi_image_picker` version: ^4.6.9

Is it happening on Android: Yes

Is it happening on iOS: No

```
 Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E266, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[!] Android Studio (version 3.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2019.3.4)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.

```

I am getting this exception whenever I try to use MultiImagePicker.pickImages.
```
await MultiImagePicker.pickImages(
        maxImages: 300,
        enableCamera: true,
        selectedAssets: images,
        cupertinoOptions: CupertinoOptions(takePhotoIcon: "chat"),
        materialOptions: MaterialOptions(
          actionBarColor: "#abcdef",
          actionBarTitle: "Example App",
          allViewTitle: "All Photos",
          useDetailsView: false,
          selectCircleStrokeColor: "#000000",
        ),
```

**Comment by MilosKarakas** [comment]
Same here. It works properly the first time I use it, then it just keeps giving that error. When I kill the app and open it again it works fine for the first time and then stops again.

**Comment by vilashp** [comment]
> Same here. It works properly the first time I use it, then it just keeps giving that error. When I kill the app and open it again it works fine for the first time and then stops again.

Just downgrade the multi_image_picker version to 4.6.7

Changing 
```
multi_image_picker version: ^4.6.9
```

to

```
multi_image_picker version:  4.6.7
```

worked for me.

**Comment by MilosKarakas** [comment]
Thanks, version 4.6.7 seems to be working fine for now.

**Comment by kris1919** [comment]
Thanks, version 4.6.7 seems to be working fine for now.

**Comment by CatEatFishs** [comment]
the version 4.6.7  doesn't  solve this problems.   who to solve it ?

**Comment by Sh1d0w** [comment]
@CatEatFishs As I said in https://github.com/Sh1d0w/multi_image_picker/issues/517 , please provide example how to reproduce the issue. I can't reproduce it with the example app in this repo.

**Comment by CatEatFishs** [comment]
this is my company project i can't provide to you,but i can tell you how to use the plugin




1.open photo album

2.debug&nbsp;&nbsp;MultiImagePicker.dart







Can enter the page of album for the first time, no data returned after confirmation.



I couldn't open the album the second time and reported an error: PlatformException(already_active, Image picker is already active, null)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sh1d0w/multi_image_picker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月12日(星期三) 中午11:07
收件人:&nbsp;"Sh1d0w/multi_image_picker"<multi_image_picker@noreply.github.com&gt;;
抄送:&nbsp;"李明"<1002464056@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Sh1d0w/multi_image_picker] Unhandled Exception: PlatformException(already_active, Image picker is already active, null) (#511)





 
@CatEatFishs As I said in #517 , please provide example how to reproduce the issue. I can't reproduce it with the example app in this repo.

**Comment by CatEatFishs** [comment]
multi_image_picker: ^4.7.10



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "李明"                                                                                    <1002464056@qq.com&gt;;
发送时间:&nbsp;2020年8月12日(星期三) 中午11:24
收件人:&nbsp;"Sh1d0w/multi_image_picker"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [Sh1d0w/multi_image_picker] Unhandled Exception: PlatformException(already_active, Image picker is already active, null) (#511)



this is my company project i can't provide to you,but i can tell you how to use the plugin




1.open photo album

2.debug&nbsp; MultiImagePicker.dart







Can enter the page of album for the first time, no data returned after confirmation.



I couldn't open the album the second time and reported an error: PlatformException(already_active, Image picker is already active, null)




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Sh1d0w/multi_image_picker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月12日(星期三) 中午11:07
收件人:&nbsp;"Sh1d0w/multi_image_picker"<multi_image_picker@noreply.github.com&gt;;
抄送:&nbsp;"李明"<1002464056@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Sh1d0w/multi_image_picker] Unhandled Exception: PlatformException(already_active, Image picker is already active, null) (#511)





 
@CatEatFishs As I said in #517 , please provide example how to reproduce the issue. I can't reproduce it with the example app in this repo.

**Comment by Sh1d0w** [comment]
@CatEatFishs can you checkout the example app in this repo, run it and check if it happens there? If it does not happen it may be specific to your project setup.

**Comment by CatEatFishs** [comment]
your github demo is ok, i copy this code to my project, run app&nbsp; report that error ,i dont no why report error

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sh1d0w/multi_image_picker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月12日(星期三) 中午11:27
收件人:&nbsp;"Sh1d0w/multi_image_picker"<multi_image_picker@noreply.github.com&gt;;
抄送:&nbsp;"李明"<1002464056@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Sh1d0w/multi_image_picker] Unhandled Exception: PlatformException(already_active, Image picker is already active, null) (#511)





 
@CatEatFishs can you checkout the example app in this repo, run it and check if it happens there? If it does not happen it may be specific to your project setup.

**Comment by Sh1d0w** [comment]
It could be because of a conflict with another plugin that you are using. You need to find out which.

Previously another users found out `flutter_boost` had conflicting request code it could be another plugin in your project as well.

**Comment by CatEatFishs** [comment]
maybe!&nbsp; &nbsp;my project not use&nbsp;flutter_boost&nbsp; ,Let me check it again . thanks !




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sh1d0w/multi_image_picker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月12日(星期三) 中午11:56
收件人:&nbsp;"Sh1d0w/multi_image_picker"<multi_image_picker@noreply.github.com&gt;;
抄送:&nbsp;"李明"<1002464056@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Sh1d0w/multi_image_picker] Unhandled Exception: PlatformException(already_active, Image picker is already active, null) (#511)





 
It could be because of a conflict with another plugin that you are using. You need to find out which.
 
Previously another users found out flutter_boost had conflicting request code it could be another plugin in your project as well.
