### ISSUE TITLE
iOS - Image sort issue when select from "Recent"

### ISSUE THREAD

**Issue by PhantomRay** [Sh1d0w/multi_image_picker#512]
**Is your feature request related to a problem? Please describe.**
Often, when I want to pick some photos recently saved from other apps, I cannot find these images. Initially I thought these images just cannot be seen by the image picker for whatever reason. One day by accident, I just found out that they are far down in the list. However, these images can be seen on the top spots in "Recent" photo list in other apps (preferred behaviour). This is quite frustrating for end users. You never know where these images could be.

**Describe the solution you'd like**
I suspect files have at least three types of timestamps in iOS: creation time, last modified and access time . I guess multi_image_picker uses one of the first two timestamps to sort images in the Recent folder. This behaviour should be changed to sorting by access time. 

**Describe alternatives you've considered**
At the very least, the plugin should offer an option as to how to sort images in the Recent folder.

**Comment by AJ1219** [comment]
I have this question too
