### ISSUE TITLE
Duplication of requestcode with other plugin causes NPE

### ISSUE THREAD

**Issue by JosephNK** [Sh1d0w/multi_image_picker#513]
@Sh1d0w 
```
List<Uri> photos = data.getParcelableArrayListExtra(Define.INTENT_PATH);
```
Can't you add the null check logic to that photos variable?

_Originally posted by @JosephNK in https://github.com/Sh1d0w/multi_image_picker/issues/127#issuecomment-667657559_

**Comment by Sh1d0w** [comment]
Hi, please feel free to open a PR. Thanks.

**Comment by JosephNK** [comment]
@Sh1d0w OK. :)

**Comment by Sh1d0w** [comment]
Merged thanks!
