### ISSUE TITLE
Allow camera option for iOS

### ISSUE THREAD

**Issue by Sujal1** [Sh1d0w/multi_image_picker#515]
While selecting images, I would like to have a camera option. This feature is available in android but not in iOS. Please refer to the screenshots. Thus, considering uniformity across platforms, I think this would be important.

![117248396_910184469458387_2443363537006500356_n](https://user-images.githubusercontent.com/6914866/89369049-c2693980-d6fc-11ea-91c6-7d76bb4b9259.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-04 at 15 05 39](https://user-images.githubusercontent.com/6914866/89369057-c7c68400-d6fc-11ea-908d-819db1d28ab2.png)

**Comment by Sh1d0w** [comment]
Hi, it is available on iOS, but you need a real device. If you are using simulator, they don't have camera, thus the option does not show.
