### ISSUE TITLE
Invalid image: ExifInterface got an unsupported image format file

### ISSUE THREAD

**Issue by liqiang1995** [Sh1d0w/multi_image_picker#520]
![image](https://user-images.githubusercontent.com/54995513/89698050-ba560780-d951-11ea-84d9-64d80a584409.png)

**Comment by liqiang1995** [comment]
How are you?
If I call multi-image picker, i face the error log.
and Never return selected images.
and I can call the multi-image picker anymore.
PlatformException(already_active, Image picker is already active, null)

**Comment by Sh1d0w** [comment]
Hi, which version of the package are you using? From the error it seems like the image is corrupted, can you provide the original image file. you are trying to pick so I can reproduce it?

**Comment by beygee** [comment]
I used multi_image_picker v4.6.7.
It worked fine before.
But it's not working after upgrading Flutter version to 1.20.1

**Comment by Sh1d0w** [comment]
Hi, this warning should not prevent you from using the picker. The problem should be fixed in version 4.7.11, see this thread for more info https://github.com/Sh1d0w/multi_image_picker/issues/517
