### ISSUE TITLE
How can I get the filename

### ISSUE THREAD

**Issue by arashbi** [Sh1d0w/multi_image_picker#522]
I am trying to get the file name from the `Asset` class. Is it possible at all?

**Comment by Sh1d0w** [comment]
You can obtain the image byte data and save it as a file in the apps directory.

**Comment by arashbi** [comment]
I want to upload the images in background. I thought about this approach, but duplicating tens of files might not be a good choice. 

I noticed that I can get the absolute path from the identifier. I ended up using a plugin for this. It might be helpful to incorporate this inside this plugin.

**Comment by Sh1d0w** [comment]
Please read the plugin docs there is a whole section about uploading...
