### ISSUE TITLE
 java.io.FileNotFoundException: java.io.FileNotFoundException: No item at content://media/external/images/media/310589

### ISSUE THREAD

**Issue by itchybumDev** [Sh1d0w/multi_image_picker#523]
**Bug Report**

`multi_image_picker` version: 4.7.10 

Is it happening on Android: Yes 

Is it happening on iOS: Yes 

```
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.1016], locale en-US)
    • Flutter version 1.17.1 at C:\src\flutter
    • Framework revision f7a6a7906b (3 months ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\nlchu\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • Mi MIX 2S • 647f841b • android-arm64 • Android 10 (API 29)```

**Describe the bug**

I am using the plugin to pick 3 images as a List<Asset> images, if I go to Gallery and delete one of the image, and go back to open the application, this Exception will come up. How should I catch this error.

**Comment by itchybumDev** [comment]
Is there a method to check if the Asset exists?

**Comment by Sh1d0w** [comment]
Currently there isn't a dedicated method for this, feel free to open a PR with such implementation and I will review it. 

Btw when this happens, there is a check in those both methods if the file does not exists it will throw a native Flutter error which you can catch ( see [here](https://github.com/Sh1d0w/multi_image_picker/blob/master/android/src/main/java/com/vitanov/multiimagepicker/MultiImagePickerPlugin.java#L268) )?

**Comment by liuguangmao** [comment]
> Currently there isn't a dedicated method for this, feel free to open a PR with such implementation and I will review it.
> 
> Btw when this happens, there is a check in those both methods if the file does not exists it will throw a native Flutter error which you can catch ( see [here](https://github.com/Sh1d0w/multi_image_picker/blob/master/android/src/main/java/com/vitanov/multiimagepicker/MultiImagePickerPlugin.java#L268) )?

**Also meet this exception when call getByteData() of the asset object returned by pickImages.**

`E/flutter ( 4612): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FileSystemException: Cannot open file, path = 'content://media/external/images/media/37' (OS Error: No such file or directory, errno = 2)
E/flutter ( 4612): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:366:9)
E/flutter ( 4612): #1      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 4612): #2      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 4612): #3      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter ( 4612): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter ( 4612): #5      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter ( 4612): #6      Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter ( 4612): #7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
E/flutter ( 4612): #8      _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 4612): #9      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 4612): #10     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 4612): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter ( 4612): #12     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 4612): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter ( 4612): 
`
