### ISSUE TITLE
How can I  change the word "Done" to other languages

### ISSUE THREAD

**Issue by zywj** [Sh1d0w/multi_image_picker#53]
It doesn't seems to be configurable

**Comment by Sh1d0w** [comment]
On Android you can follow the guide here: https://sh1d0w.github.io/multi_image_picker/#/theming?id=android-customization

For iOS it is not possible to override this from Flutter yet, the library I am using will automatically detect the language on your iPhone and set the button label to whatever "Done" translates into your language.

I will consider adding feature to change that from within Flutter in some of the upcoming releases.

**Comment by zywj** [comment]
thanks very much

**Comment by ZMNOTZ** [comment]
> On Android you can follow the guide here: https://sh1d0w.github.io/multi_image_picker/#/theming?id=android-customization
> 
> For iOS it is not possible to override this from Flutter yet, the library I am using will automatically detect the language on your iPhone and set the button label to whatever "Done" translates into your language.
> 
> I will consider adding feature to change that from within Flutter in some of the upcoming releases.

There is still no fix
