### ISSUE TITLE
NameNotFoundException[run no problem,just has this error on print] 运行选择图片没问题，就是终端有这个错误

### ISSUE THREAD

**Issue by lujie-hybrid** [Sh1d0w/multi_image_picker#531]
NameNotFoundException
android.content.pm.PackageManager$NameNotFoundException: com.miui.contentcatcher
![image](https://user-images.githubusercontent.com/19526208/90846869-bbe4ee00-e39b-11ea-835f-98d501327dd7.png)

**Comment by Sh1d0w** [comment]
Feel free to fix it and provide a PR, I don't have xiaomi device.
