### ISSUE TITLE
Display Camera indicator

### ISSUE THREAD

**Issue by Sujal1** [Sh1d0w/multi_image_picker#536]
When I use the library to select photos, then the camera option is seen as blank white screen (this is when the user has not provided camera access, please refer to screenshot attached). So it is likely that users might not know there is a camera feature available.

Therefore, I would like to suggest to show a camera indicator.

![IMG_0975](https://user-images.githubusercontent.com/6914866/91693537-dfbde600-eb8a-11ea-8aca-c6d31d5795cc.PNG)

The above screenshot has been taken from iOS device.

**Comment by hhelmric** [comment]
Yes please -- we have had several confused users not knowing they need to tap on the white square to enable the camera. I think all that needs to be done is to ask the user for permission to use the camera when this grid-view is displayed (currently it is only asking for permission for photo library).

**Comment by Sh1d0w** [comment]
The camera permission dialog should show the first time you open the image picker. Did you by any chance denied it the first time?

**Comment by hhelmric** [comment]
We just tested this on a new phone yesterday and it did not ask for Camera permissions when the image picker was first presented, it just asked for Photo Library permissions. I realize now we were using version 4.6.1 ... did you recently implement this change in a newer version since then?

**Comment by Sujal1** [comment]
@Sh1d0w As @hhelmric has mentioned, the permission is asked only for Photo library when the image picker is opened the first time. Camera permission is asked when the user then taps on the white grid. So a camera indicator over that white grid would be helpful considering the user experience.
P.S. Once the user gives camera permission, a real time camera is being shown in place of the white grid, which is fine.

**Comment by Sh1d0w** [comment]
I think you are missing the icon. Did you pass any in the configuration object when initializing the picker?

**Comment by Sujal1** [comment]
I am currently passing  **maxImages** and **enableCamera** parameters.
Going through the library, I can see a **takePhotoIcon** parameter for **CupertinoOptions** that takes String value. Is this the one that needs to be set?

**Comment by Sh1d0w** [comment]
Yes you can check the docs how to add your icon on iOS https://sh1d0w.github.io/multi_image_picker/#/theming

**Comment by Sujal1** [comment]
I am now able to show the icon. Thank you @Sh1d0w for the support.
