### ISSUE TITLE
Original file name

### ISSUE THREAD

**Issue by I-am-original** [Sh1d0w/multi_image_picker#55]
Is it possible to save original files names in Asset?
Thanks

**Comment by Sh1d0w** [comment]
It is possible to be implemented, I will consider it in one of the upcoming releases.

**Comment by I-am-original** [comment]
@Sh1d0w  thanks . a lot )

**Comment by Sh1d0w** [comment]
@I-am-original This is now implemented in version 2.3.31.

You can access Asset.name to obtain the original image name.
