### ISSUE TITLE
Better single file selection

### ISSUE THREAD

**Issue by monsieurtanuki** [Sh1d0w/multi_image_picker#555]
**Is your feature request related to a problem? Please describe.**
Of course the general idea of this project is to select multiple file. The interface matches that.
But the current implementation of the "I only need one file" side effect is not satisfying.
If the set up is "max file number is 1", I see a list of files: I can click on file A, but then if I click on file B nothing happens, the file A stays selected. I need to click again on file A to deselect it, and then I'm able to click on file B to select it. Then I click on "Done".

**Describe the solution you'd like**
A solution would be to implement something specific when only one file is needed:
* like "first selected file = final choice", where I don't even have to click on "Done" (which is not even there) because I've already selected the file and that's enough in my case
* or if I click on whatever file then it's considered as the only one selected, even if I clicked on another file before. And then I click on "Done"

**Describe alternatives you've considered**
I used to be using the more "flutter standard" **image_picker** project, but currently there's a [bug/crash apparently due to the new xcode 12 / iOS 14 upgrade](https://github.com/flutter/flutter/issues/65995).

**Comment by Sh1d0w** [comment]
I like the idea, feel free to open a PR with this implementation and I will review it.

**Comment by monsieurtanuki** [comment]
@Sh1d0w I wish I could, but AFAICS that would need not only flutter/dart code, but mainly Xcode/swift code. And that I cannot do. I might be able to help on the Android part, though.
