### ISSUE TITLE
App crashes: Didn't find class "androidx.core.view.NestedScrollingParent3"

### ISSUE THREAD

**Issue by supardyke** [Sh1d0w/multi_image_picker#556]
**Bug Report**

`multi_image_picker` version: 4.7.14

Is it happening on Android: yes

Is it happening on iOS: Did not check ios

```
 Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.14.6 18G103, locale en-NG)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 10.1)
    ✗ Flutter requires a minimum Xcode version of 11.0.0.
      Download the latest version or update via the Mac App Store.
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.49.0)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Describe the bug**

Rejecting re-init on previously-failed class java.lang.Class<androidx.recyclerview.widget.RecyclerView>: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/view/NestedScrollingChild3;

App crashes when i call the plugin to upload a file
<img width="1159" alt="Screenshot 2020-09-21 at 11 03 02" src="https://user-images.githubusercontent.com/30954966/93754703-0c997200-fbfa-11ea-8c0a-999aaf16f599.png">

**Comment by Sh1d0w** [comment]
You need to migrate your project to AndroidX as described int he plugin docs.

**Comment by supardyke** [comment]
I have already migrated to AndroidX according to the flutter docs, is there any other doc??
