### ISSUE TITLE
Permission error on Android Q (10) + Android SDK 29

### ISSUE THREAD

**Issue by ianpark** [Sh1d0w/multi_image_picker#557]
**Bug Report**

`multi_image_picker` version: 4.7.14

Is it happening on Android: Yes

Is it happening on iOS: No

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.14.6 18G6020, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.49.1)
[✓] Connected device (1 available)

• No issues found!
```

**Describe the bug**

Picking an image fails with a permission error for `ACCESS_MEDIA_LOCATION`
`/MethodChannel#multi_image_picker(22324): java.lang.UnsupportedOperationException: Caller must hold ACCESS_MEDIA_LOCATION permission to access original`

```
E/MethodChannel#multi_image_picker(22324): Failed to handle method call
E/MethodChannel#multi_image_picker(22324): java.lang.UnsupportedOperationException: Caller must hold ACCESS_MEDIA_LOCATION permission to access original
E/MethodChannel#multi_image_picker(22324): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
E/MethodChannel#multi_image_picker(22324): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
E/MethodChannel#multi_image_picker(22324): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
E/MethodChannel#multi_image_picker(22324): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1687)
E/MethodChannel#multi_image_picker(22324): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1503)
E/MethodChannel#multi_image_picker(22324): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1187)
E/MethodChannel#multi_image_picker(22324): 	at com.vitanov.multiimagepicker.MultiImagePickerPlugin.onMethodCall(MultiImagePickerPlugin.java:299)
E/MethodChannel#multi_image_picker(22324): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/MethodChannel#multi_image_picker(22324): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#multi_image_picker(22324): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#multi_image_picker(22324): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#multi_image_picker(22324): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#multi_image_picker(22324): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#multi_image_picker(22324): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#multi_image_picker(22324): 	at java.lang.reflect.Method.invoke(Native Method)

```

**Comment by ismailslmnv** [comment]
Could you solve it? I added the permission but happens again.

**Comment by whatamelon** [comment]
Same issue. I think it must be solved quickly.

**Comment by s-abinash** [comment]
I am also getting the same issue

**Comment by Sh1d0w** [comment]
> Same issue. I think it must be solved quickly.

Feel free to debug and provide a PR with a fix.

**Comment by oscarshaitan** [comment]
there is no solution yet? should be open

**Comment by esDotDev** [comment]
> Feel free to debug and provide a PR with a fix.

This is the big problem with Flutter currently. Volunteer developers (fairly) feel no responsibility to keep their plugins bug free, and the official plugins from google are also full of bugs.

image_picker has 200+ open bugs,  multi_image_picker has close to 40. This is the current state of simply picking an image in flutter, in 2021 :( 

Probably the most fundamental task of any application framework running on a phone, and we can't even get it done without crashes and bugs.

**Comment by Sh1d0w** [comment]
@esDotDev I would argue it is the maintainer responsibility only. As it is open source anyone who have issues / want to add functionality can do so. But developers are lazy and instead of doing something by themselves they want to get everything from free if they can, but not give back. 

That's the problem. I've created this plugin because at the time I've needed it for personal project there wasn't one. I've decided to open source it so other people don't struggle like me. Unfortunately several years later I am no longer able to commit a lot of time into the plugin, thats why I've asked several times Flutter community to help with what they can.

But people like to complain rather do something, that's how it is.

**Comment by esDotDev** [comment]
I mean it depends how you look at it, developers aren't "lazy" they have 50 things to do in some set timeline, and fixing image_picker is not on that list. They just want something that works so they can get back to building their UI. 

But I totally understand your position, and you can't just work for free either. This is what I mean about a big problem across the whole eco-system. 

We really need a paid plugin store like Unity has.
