### ISSUE TITLE
On android not working as expected

### ISSUE THREAD

**Issue by MarcelEdward** [Sh1d0w/multi_image_picker#56]
**Describe the bug**
On ios when I take a photo with the camera I go back to the gallery and see the photo selected with the other gallery images.
On android when I take a photo I return to a screen with only the photo I took but with no other gallery images. The photo taken with the camera seems to get lost, I do not see it in the gallery. Also there does not seem te be a cancel button as on ios.

**Expected behavior**
More or less the same behaviour as on ios

https://github.com/zhihu/Matisse/issues/291

**Comment by Sh1d0w** [comment]
@MarcelEdward Thanks for opening the issue on the official Android image picker plugin that I am using. As you understand there is nothing I can do unless this behaviour is changed in Matisse. 

I will subscribe to the issue you have opened there, and if fixed I will update the library version accordingly.

Also please bear in mind that in the Matisse docs it is explicitly said that image capture is experimental feature, so if you are not happy with it you can disable camera in the gallery and use the standalone camera plugin https://pub.dartlang.org/packages/camera

**Comment by Sh1d0w** [comment]
This is now fixed in version 4.0.0 of the plugin.
