### ISSUE TITLE
Camera is not opening when targetSdkVersion is 29 or higher

### ISSUE THREAD

**Issue by davidcz95** [Sh1d0w/multi_image_picker#563]
**Bug Report**

`multi_image_picker` version: 4.7.14

Is it happening on Android: YES

Is it happening on iOS: Don't know

```
 Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.19041.508], locale pl-PL)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

• No issues found!
```

Camera is not opening there is nothing in the logs and it happens ONLY when I change targetSdkVersion to 29 which is 
required to upload an app to Play Store. 

The gallery is opening and I can see the pictures it is just the button to open camera that is not responding. And In the android manifest I have 
```
<uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.CAMERA" />
```

And it is asking permissions but still don't work.

**Comment by linxkaa** [comment]
i get the same error too, on ios the camera is not opening too

**Comment by linxkaa** [comment]
my targetSdkVersion is 28

**Comment by Octet83** [comment]
Same here with 29

**Comment by Octet83** [comment]
It seems to be an issue with fishBun, this lib is using fishbun 0.11.2 and this issue seems to be fixed on 0.11.4

**Comment by ZCJ** [comment]
I have the same issue, but it only works on the emulator @davidcz95 does it work on the emulator for you?

**Comment by Octet83** [comment]
I don't understand why we're only 3 facing this issue, everyone up-to-date should have this problem and not be able to take pictures on android. There is no fork which bump fishBun version, I tried this but don't have java skills to make it work.

@Sh1d0w is it a known issue ?

**Comment by Octet83** [comment]
I think I've found a solution : 
- Add this permission to your android manifest : 

`<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />`

**Comment by ZCJ** [comment]
Thank you @Octet83 - I have just tried it and it works

**Comment by Octet83** [comment]
Nevermind, it doesn't work. When you try to publish to playstore, your app is rejected with:
`Cannot use MANAGE_EXTERNAL_STORAGE permission`

It seems that google will reject it until early 2021 👍 
https://support.google.com/googleplay/android-developer/answer/9956427?hl=en

They talk about SDK 30 but it seems to be the same on 29

**Comment by Octet83** [comment]
Quick summary:
There is a permission issue to take pictures on target SDK 29.
You could add :
`<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />`

to Android manifest, and it would work fine, but you won't be able to publish to google play until early 2021 (https://support.google.com/googleplay/android-developer/answer/9956427?hl=en).

As a workaround for SDK 29 (and 29 ONLY), you can add the following property in Android manifest <application>:
`android:requestLegacyExternalStorage="true"`

It works and you're able to publish, but on SDK >= 30 this property will be ignored.
