### ISSUE TITLE
iOS 14 camera indicator never turns off

### ISSUE THREAD

**Issue by aanelson** [Sh1d0w/multi_image_picker#565]
**Bug Report**

`multi_image_picker` version: 4.7.14

Is it happening on Android:No
Is it happening on iOS: Yes iOS 14 only

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G2021, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.49.3)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.```

**Describe the bug**

A clear and concise description of what the bug is.

iOS 14 added an indicator to show that the camera is on.
When exiting the screen with the live camera feed this indicator never turns off.  

There is a green icon above the network quality indicator in the example app.

**Comment by aanelson** [comment]
![IMG_3034](https://user-images.githubusercontent.com/51463729/95492286-b47ba300-094f-11eb-9f86-e9e570de404f.png)

**Comment by gwsh** [comment]
I have the same problem

**Comment by nobanhasan2** [comment]
Same problem. Can't find any solution.

**Comment by zzterrozz** [comment]
Same issue, any solution please?

**Comment by Sh1d0w** [comment]
The iOS library used is quite outdated it will be solved by https://github.com/Sh1d0w/multi_image_picker/issues/373 if anyone wants to pick that up PRs are welcome.

**Comment by zzterrozz** [comment]
> The iOS library used is quite outdated it will be solved by #373 if anyone wants to pick that up PRs are welcome.

Hi @Sh1d0w 
Thank you for your work on this great package.
Still having the issue with the indicator never turning off.
It would be awesome if you could fix it.

**Comment by cubissimo** [comment]
Any news about it? Same here.. any clues?

**Comment by Sh1d0w** [comment]
Unfortunately I haven't been able to find spare time recently to work on this as I currently have too much on my plate at work.

However feel free to provide a PR with a fix and I will review it. It's open source you don't have to wait for me to fix it :)
