### ISSUE TITLE
Issuse build

### ISSUE THREAD

**Issue by momoDragon** [Sh1d0w/multi_image_picker#57]
******ERROR******

D:\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\multi_image_picker-2.3.31\android\src\main\java\com\vitanov\multiimagepicker\MultiImagePickerPlugin.java:313: error: cannot find symbol
                ExifInterface.TAG_ISO_SPEED,
                             ^
  symbol:   variable TAG_ISO_SPEED
  location: class ExifInterface
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':multi_image_picker:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
Finished with error: Gradle task assembleDebug failed with exit code 1

*******FLUTTER DOC******

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.2)
[√] IntelliJ IDEA Community Edition (version 2018.1)
[√] VS Code, 64-bit edition (version 1.24.1)
[√] Connected device (1 available)

• No issues found!

****** STEPS TO REPRODUCE ******
1. Running the example code on the repo
2. I Tried to run the code with package version 2.3.1 and it works. anything above fails including the latest version.

****** DEVICE ******
Pixel 2XL
Android 8.1

**Comment by Sh1d0w** [comment]
Please read the documentation, troubleshooting section for Android: https://sh1d0w.github.io/multi_image_picker/#/androudtroubleshooting
