### ISSUE TITLE
update dependencies implementation on com.github.bumptech.glide and androidx.exifinterface 

### ISSUE THREAD

**Issue by kw2019ltd** [Sh1d0w/multi_image_picker#574]
hi,
can you update dependencies implementation on com.github.bumptech.glide and androidx.exifinterface to latest versions

i see com.github.bumptech.glide latest ver contain many bug fixes

**Comment by Sh1d0w** [comment]
Feel free to open a PR and test it. If all good I will merge it.

**Comment by kw2019ltd** [comment]
seems working fine with no issue, currently 4000 users on my production app is using the update plugin with the updated version of com.github.bumptech.glide and androidx.exifinterface

below version of my app has the new forked version of multi_image_picker with update plugin with the updated version of com.github.bumptech.glide and androidx.exifinterface.

before i was getting issues in Firebase regarding multi_image_picker  now most issue gone.


![image](https://user-images.githubusercontent.com/47334522/98094809-74e2a100-1e92-11eb-9757-912d23f800dd.png)



![image](https://user-images.githubusercontent.com/47334522/98094532-174e5480-1e92-11eb-902a-99ed6b83a903.png)

**Comment by kw2019ltd** [comment]
hi can i go ahead and create a PR?

**Comment by Sh1d0w** [comment]
Hi, yes sure 👍

**Comment by kw2019ltd** [comment]
PR:
https://github.com/Sh1d0w/multi_image_picker/pull/591

**Comment by kw2019ltd** [comment]
hi @Sh1d0w can you release new version multi_image_picker since my PR was merged

**Comment by Sh1d0w** [comment]
@kw2019ltd Sure just released 4.7.15
