### ISSUE TITLE
Camera won't launch on Android 11

### ISSUE THREAD

**Issue by NickalasB** [Sh1d0w/multi_image_picker#577]
**Bug Report**

`multi_image_picker` version: ^4.7.11

Is it happening on Android: Yes 

Is it happening on iOS:  No

```
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G2021, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.48.0)
 
[✓] Connected device (2 available)    
```
**Note:** The above errors are due to a [flutter issue with Android Studio 4.1](https://github.com/flutter/flutter/issues/67986) (both plugins are actually installed)

**Describe the bug**

The camera button is unresponsive on devices targeting Android 11 (API 30).

This is actually due to an issue in the FishBun library. I have submitted a PR to fix it [here](https://github.com/sangcomz/FishBun/issues/224).

**If that PR is approved and merged, requesting that this library upgrade to target the latest version of FishBun**

Thank you

**Comment by NickalasB** [comment]
FWIW- the FishBun PR was approved and merged https://github.com/sangcomz/FishBun/pull/225

**Comment by Chris1234567899** [comment]
Will this be integrated soon?

**Comment by NickalasB** [comment]
Not sure if this will be reopened simply by adding a comment here- but this seems like a major breaking bug for this plugin that shouldn't just be auto-closed
