### ISSUE TITLE
ios支持10.0后报错：compiling for iOS 9.0, but module 'BSGridCollectionViewLayout' has a minimum deployment target of iOS 10.0

### ISSUE THREAD

**Issue by 18664927896** [Sh1d0w/multi_image_picker#580]
**Bug Report**

`multi_image_picker` version: 

Is it happening on Android: No

Is it happening on iOS: Yes

```
 <!-- run `flutter doctor` and paste the output here: -->

• Flutter version 1.23.0-18.1.pre at /Users/shanggang/app/flutter
    • Framework revision 198df796aa (3 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

**Describe the bug**
iOS最低支持10.0后报错：
compiling for iOS 9.0, but module 'BSGridCollectionViewLayout' has a minimum deployment target of iOS 10.0

修改方案：
修改ios/multi_image_picker.podspec文件代码：
```
s.dependency 'BSImagePicker', '~> 3.3.1
s.ios.deployment_target = ’10.0’
```

**Comment by VladShturma** [comment]
@18664927896 Try to set deployment target manually from 9.0 to 10.0 for these three pods. This worked for me.
But you will have to reset deployment target from 9 to 10 after every `flutter pub get`.
And build is only working from Xcode, not from Terminal

![Screenshot 2020-11-13 at 20 49 44](https://user-images.githubusercontent.com/4832407/99098231-2780d500-25f2-11eb-8746-444d860b3dd9.png)

**Comment by sakyoyuto** [comment]
I am experiencing the same problem.

**Comment by thmr** [comment]
I have the same issue after upgrading Flutter and Xcode.

`[✓] Flutter (Channel master, 1.25.0-5.0.pre.108, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (3 available)
`

**Comment by 18664927896** [comment]
> @18664927896 Try to set deployment target manually from 9.0 to 10.0 for these three pods. This worked for me.
> But you will have to reset deployment target from 9 to 10 after every `flutter pub get`.
> And build is only working from Xcode, not from Terminal
> 
> ![Screenshot 2020-11-13 at 20 49 44](https://user-images.githubusercontent.com/4832407/99098231-2780d500-25f2-11eb-8746-444d860b3dd9.png)
是的，如果只是一个人开发的话

> @18664927896 Try to set deployment target manually from 9.0 to 10.0 for these three pods. This worked for me.
> But you will have to reset deployment target from 9 to 10 after every `flutter pub get`.
> And build is only working from Xcode, not from Terminal
> 
> ![Screenshot 2020-11-13 at 20 49 44](https://user-images.githubusercontent.com/4832407/99098231-2780d500-25f2-11eb-8746-444d860b3dd9.png)

Yes
