### ISSUE TITLE
ios14 localization cannot be translated into Chinese

### ISSUE THREAD

**Issue by hl9565** [Sh1d0w/multi_image_picker#582]
I used the localized code and system language setting is Chinese. But some words are still shows English, like 'Recents','Done' ...
```
localizationsDelegates: const [
    S.delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ],
```
What can I do to fix it?

**Comment by PergenDeveloper** [comment]
I have the same bug.

**Comment by CallMeInk** [comment]
> I used the localized code and system language setting is Chinese. But some words are still shows English, like 'Recents','Done' ...
> 
> ```
> localizationsDelegates: const [
>     S.delegate,
>     GlobalMaterialLocalizations.delegate,
>     GlobalWidgetsLocalizations.delegate,
>     GlobalCupertinoLocalizations.delegate,
>   ],
> ```
> 
> What can I do to fix it?

This plugin uses BSImagePicker to support iOS platform, which can't be fixed by this flutter plugin's author.Try "native iOS localizable".




Besides, I'm the man behind you.= =

**Comment by niyangup** [comment]
> https://github.com/Sh1d0w/multi_image_picker/issues/481#issuecomment-718380749 
look here

**Comment by wcoder** [comment]
Bug in native picker: https://github.com/mikaoj/BSImagePicker/issues/249
