### ISSUE TITLE
Camera in the main view

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [Sh1d0w/multi_image_picker#583]
**Is your feature request related to a problem? Please describe.**
I feel frustrated when having to go into one of the views of images to see the camera option.

**Describe the solution you'd like**
I prefer having a lit tile for the camera in the categories/main view

**Describe alternatives you've considered**
I haven't

**Additional context**
Maybe allow custom UI, a builder constructor for building custom ui.

**Comment by ivelichkovich** [comment]
I can't find the camera option anywhere, where exactly does it show up?

**Comment by YazeedAlKhalaf** [comment]
When you have folders, click in one of them there will be a camera block at the beginning
