### ISSUE TITLE
Show only photos in Photo gallery

### ISSUE THREAD

**Issue by PeppeGiHub** [Sh1d0w/multi_image_picker#588]
I have a problem with IOS, because I have to select only photos. 
In IOS with live mode, 2 files .mov and .jpg are generated.
When I call the gallery I only see the .mov files

`multi_image_picker` version: ^4.7.14

Is it happening on Android: No

Is it happening on iOS: Yes

```
 <!-- run `flutter doctor` and paste the output here: -->
```

**Describe the bug**
Because? Is it possible to show only photo files?

**Comment by yangyxd** [comment]
I have the same problem. I hope users can't select mov files when selecting photos. Thank you~
