### ISSUE TITLE
Resume Image Selection

### ISSUE THREAD

**Issue by cyberIndia** [Sh1d0w/multi_image_picker#60]
Once the selection is made user should be able to call the plugin again to edit the selection.
In this case the already selected images should remain pre selected.

**Comment by chusmf** [comment]
that would be great

**Comment by Sh1d0w** [comment]
There is no problem for me to implement this, I agree it is cool feature.

However before I can do that the two native libraries I use have to do that.

For matisse I see there is already such feature request which is put in 0.5.2 milestone: https://github.com/zhihu/Matisse/issues/472

Looking at BSImagePicker source I can see it already has this https://github.com/mikaoj/BSImagePicker/blob/master/Sources/Controller/BSImagePickerViewController.swift#L49

So once Matisse implements it, this will be unblocked.

**Comment by girubhai** [comment]
@Sh1d0w FishBun have this feature, can you please implement this.

**Comment by Sh1d0w** [comment]
@girubhai Yep, will look into it.

**Comment by Sh1d0w** [comment]
I've implemented this for iOS, however I can't seem to get it work with FishBun. Opened [this](https://github.com/sangcomz/FishBun/issues/149) issue with feature request. Once implemented I will release this for both iOS and Android.

**Comment by Sh1d0w** [comment]
This is now implemented in version 4.3.0.
