### ISSUE TITLE
How can I point images source to a custom directory in phone?

### ISSUE THREAD

**Issue by vijaykanta** [Sh1d0w/multi_image_picker#61]
**Is your feature request related to a problem? Please describe.**
I am trying to load images from a particular directory I had created with path_provider API under app documents directory. I can load them up using Image.file() but the performance is very poor and causes crashes

**Describe the solution you'd like**
I'd like to use this library which I also use for picking from regular gallery. However, there doesn't seem or maybe I couldn't find how to implement that

**Describe alternatives you've considered**
I tried to use AssetImage class, but don't know how to send the file to it

**Additional context**
I don't want to do native programming as this library already shows pictures as thumbs inside a grid which I tried, but this library has awesome performance and doesn't crash while scrolling whereas my custom solution crashed on first scroll itself.

**Comment by Sh1d0w** [comment]
Hi and thanks for using the plugin.

Unfortunately you can't create Asset classes manually without some native programming. The only suggested approach is to use the multi image picker, as the Asset class needs the unique identifier in order to properly create thumbs and use the other class methods (Content URI on Android and PHAsset id on iOS).

**Comment by vijaykanta** [comment]
Okay, but how can I use multi image picker for a custom folder? Is it at all a viable option? All I saw for ImagePicker.source were camera or gallery only.

**Comment by Sh1d0w** [comment]
@vijaykanta The native image gallery plugins I am using does not support picking image only from certain directory. As long as your directory is indexed in Media Store on Android it will appear in the gallery folder dropdown so the users can navigate to it.

**Comment by vijaykanta** [comment]
I tried, but it crashes when rebuild UI as this gallery is in a page view. I switch pages and scroll, the page crashes again. Each image in being rendered by a new Stateful widget and initstate() calls a function that calls readasbytes() on the file. On complete, I call setstate() thus showing the image in the build(), and there is no difference as when doing it directly in gridview.count() before

**Comment by vijaykanta** [comment]
@Sh1d0w I am sorry, I was loading the full size original images before. Now I load the resized and compressed thumbnails and the crashes and freezing have gone entirely. I am still using your solution of rendering using an independent stateful widget. Cheers!!!
