### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by kw2019ltd** [Sh1d0w/multi_image_picker#633]
The new Dart version with null-safety was just released
https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87

**Comment by fzyzcjy** [comment]
looking forward to this update! Since flutter has make null safety **stable** today!

**Comment by SametSahin10** [comment]
There's already an issue about null safety support. It would be better if we keep track of this feature on a single issue rather than creating duplicate ones. [This](https://github.com/Sh1d0w/multi_image_picker/issues/630) the issue I'm talking about. Can you please close this issue? @kw2019ltd

**Comment by fzyzcjy** [comment]
I have made a PR: https://github.com/Sh1d0w/multi_image_picker/pull/634

**Comment by SametSahin10** [comment]
Oops, I was just about the send the PR. I'm sending it anyway. Maybe there is something better on any of the PR's.

**Comment by Sh1d0w** [comment]
Thanks for the PRs guys, left a comment on both, there are some issues running the example app with the new version.

Thanks you both for your contributions, much appreciated !

**Comment by zzterrozz** [comment]
@SametSahin10 @fzyzcjy @Sh1d0w Thank you for your work on the package and for keeping it alive & updated !
