### ISSUE TITLE
Terrible performance when looking at images from Camera

### ISSUE THREAD

**Issue by frankyvij** [Sh1d0w/multi_image_picker#638]
**Bug Report**

`multi_image_picker` version: 4.7.15

Is it happening on Android: Yes

Is it happening on iOS: Not sure

```
 Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.4 19E287 darwin-x64, locale en-SG)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
[✓] Connected device (3 available)
```

**Describe the bug**

1. Open multi-image picker
2. Attempt to select images from the camera folder
3. Scroll down, and notice the terrible performance

Possible Reasons:
1. It seems that the library is attempting to render all images from the top in sequence (perhaps to cache? I am assuming this because the issue only can be replicated when there is no cache). There is no need to do that, why can't we just render images that are in the view?
2. Images nowadays are inevitably larger in size; perhaps the design expectation of the library is that users will only pick the latest images and not the ones they clicked 6 months ago?

Possible Fix:
1. Implement something on the lines of GridView.builder so that only the images on the screen are rendered, and processes for other images are canceled.

Good to have (must have nowadays by the way):
1. Can we also add a scrollbar so that users can easily move up and down when they have 1000s of images?

I have enclosed the video for your perusal.

https://user-images.githubusercontent.com/26051431/110250374-f1f36380-7fb5-11eb-91b0-a02e495cf7bc.mp4

**Comment by Sh1d0w** [comment]
Thanks for the report @frankyvij 

Unfortunately I can not do anything about this. As you've already read in the plugin documentation I use two native plugins to render the image pickers - FishBun for android and BSImagePicker for iOS.

The issue happens in the FishBun plugin, which I don't own. You can report this issue to the FishBun maintainers (link to the repo is in the README) and if they fix it I will update the plugin version I am using.

Thanks
