### ISSUE TITLE
I created a new project, added multi_image_picker, and ran into the ios virtual machine and I got an error.

### ISSUE THREAD

**Issue by gaojuanjuan** [Sh1d0w/multi_image_picker#64]
![image](https://user-images.githubusercontent.com/14133759/51423030-116f7c80-1bf4-11e9-98a0-b2df4111564d.png)

**Comment by Sh1d0w** [comment]
Please read the documentation, you are missing Bridging Header

https://sh1d0w.github.io/multi_image_picker/#/initialsetup
