### ISSUE TITLE
I fail to get ArraySet

### ISSUE THREAD

**Issue by dewsy** [Sh1d0w/multi_image_picker#72]
**Bug Report**

`multi_image_picker` version:  ^3.0.11

Is it happening on Android: Yes

Is it happening on iOS: n/a

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale hu-HU)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.3)
[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 1 category.

```
- I do not use IntelliJ for this, VS Code and Android studio produces the same error.

**Describe the bug**

I'm new to all of this, most likely the bug is on me, but still, could you help me pls! So i installed everything, followed the very detailed and nice documentation. Importing checks out, no warnings found. I copied the two files (main and asset_view) directly from you. The app loads up, but when i click on the open button, it stops, and i get this:

**E/flutter ( 7327): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArraySet;**

I tried with your troubleshooting method, also different virtual devices with different API levels (23 and 28), different minSdkVersions (19 is the final choice), and different buildToolVersions as well, from 20.0.0 up to 28.0.3.

I attach the full log as txt. Thank 
[log.txt](https://github.com/Sh1d0w/multi_image_picker/files/2832353/log.txt)
you for the help!

**Comment by dewsy** [comment]
Alo, i checked my SDK installation, and i have the supporttools installed. Seriously, i have no idea...

**Comment by Sh1d0w** [comment]
Hi thats a bug, because the Android library have not implemented AndroidX yet.

There is an open PR https://github.com/zhihu/Matisse/pull/566

But until it is merged I will have to use my own fork with the patch.

I will make a new release that fixes the error and will let you know.

Thanks for reporting this issue.

**Comment by Sh1d0w** [comment]
This should be fixed in version 3.0.12

Sorry for the confusion, let me know if all is working ok now.

**Comment by dewsy** [comment]
I got further this time! With the new package i was able to load up the picker, when there was no images in the AVM. However, then i opened the dummy camera, took some photos to have something to pick, and now clicking on the open files button crashes again. The error is roughly the same, but now the missing class is the:
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/Fragment;

**Comment by Sh1d0w** [comment]
@dewsy Seems liek your project is using Android Support Library which was deprecated.

Did you follow the steps to migrate to AndroidX as described here https://developer.android.com/jetpack/androidx/migrate ?

**Comment by dewsy** [comment]
Man, it works now! Thank you for all the help! I'm so happy! (quick question: Is there any way i can make a 'select all' button in the picker, to get all images in the current folder selected at once?)
Thank you again for the help, wishing you the best!

**Comment by Sh1d0w** [comment]
No worries, glad it is working now.

There is no way to do this currently, nor the iOS nor the Android native libraries I am using the the plugin can do that, sorry.

**Comment by dewsy** [comment]
okay, thank you for the heads up!
