### ISSUE TITLE
package android.support.media does not exist

### ISSUE THREAD

**Issue by Dr-Legend** [Sh1d0w/multi_image_picker#74]
**Bug Report**

`multi_image_picker` version: 2.4.11

Is it happening on Android: Yes

Is it happening on iOS: No

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.2.1-pre.180, on Microsoft Windows [Version 10.0.17134.165], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.30.2)
[√] Connected device (1 available)

• No issues found!

```

**Describe the bug**
when tried to run my project, 
AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\multi_image_picker-2.4.11\android\src\main\java\com\vitanov\multiimagepicker\MultiImagePickerPlugin.java:43: error: package android.support.media does not exist
import android.support.media.`ExifInterface;`
                                                                                        
this error occurs please help!

I have this code as well in my `build.gradle` file,
```
subprojects {
    project.evaluationDependsOn(':app')
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "27.1.1"
            }
        }
    }
}
```
as mentioned in this guide https://sh1d0w.github.io/multi_image_picker/#/androudtroubleshooting

**Comment by Sh1d0w** [comment]
Hi,

there must be something weird in your build config, as I am using the support ExifInterface library and the class path is correct: https://developer.android.com/reference/android/support/media/ExifInterface.html

Can you try either to remove / add the plugin again or do `flutter clean` and then `flutter build apk`?

In case this does not help can you provide example repository where I can reproduce the issue, as there might be conflict with some other plugin?

**Comment by Sh1d0w** [comment]
Also are you sure you haven't migrated your project to AndroidX, in which case you should use version 3.0.* of the plugin?

**Comment by Dr-Legend** [comment]
> Hi,
> 
> there must be something weird in your build config, as I am using the support ExifInterface library and the classpath is correct: https://developer.android.com/reference/android/support/media/ExifInterface.html
> 
> Can you try either to remove/add the plugin again or do `flutter clean` and then `flutter build apk`?
> 
> In case this does not help can you provide example repository where I can reproduce the issue, as there might be conflict with some other plugin?

thanks for your quick reply, I'll try that.

**Comment by Dr-Legend** [comment]
> Also are you sure you haven't migrated your project to AndroidX, in which case you should use version 3.0.* of the plugin?

No, not migrated yet, but we will soon...

**Comment by Dr-Legend** [comment]
Thanks, @Sh1d0w,
I removed the folder from `AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org`
and then in project `flutter packages get`  solved my problem.
Thank you very much for your help!

**Comment by Sh1d0w** [comment]
Great!
