### ISSUE TITLE
How do we customize header buttons and title. 

### ISSUE THREAD

**Issue by v2Nitesh** [Sh1d0w/multi_image_picker#76]
Hi I am Nitesh, I have just started learning Flutter I don't have much idea on this technology. 

Please help me on this.

How do we customize header buttons and title.  Like I don't want to header buttons. 
I wanted to build something like this...Is there any way to customise the component...

![multiselection](https://user-images.githubusercontent.com/7920123/52993582-bae79f00-343a-11e9-9b96-9c7106f69cb4.png)

**Comment by Sh1d0w** [comment]
Hi @v2Nitesh . This plugin is just a wrapper around Android and iOS native libraries, so you can not completely re design the UI that is already in place.

You can however customize different aspects of it, like the background color, selection color and symbols and more. How to do this you can read in the official documentation of the plugin

https://sh1d0w.github.io/multi_image_picker/#/theming

**Comment by v2Nitesh** [comment]
Thank you for your reply....As I am very new with Flutter can you please suggest me how to build plugins using existing Android and iOS libraries/framework. 

Thank you in Advance.

**Comment by Sh1d0w** [comment]
@v2Nitesh There is a good article on the official Flutter docs website: https://flutter.io/docs/development/packages-and-plugins/developing-packages

**Comment by aloisdeniel** [comment]
If I remember well my old days as an iOS developer, the header accent color can be updated with theming variables. 

It would be great to be able to define at least the accent color of the controller. :)

**Comment by Sh1d0w** [comment]
@aloisdeniel PRs are welcome :)
