### ISSUE TITLE
Failed to build iOS app - 'multi_image_picker/multi_image_picker-Swift.h' file not found

### ISSUE THREAD

**Issue by mariofraga84** [Sh1d0w/multi_image_picker#77]
**Bug Report**

`multi_image_picker` version:   
  image_picker: ^0.5.0+3
  multi_image_picker: ^3.0.14
Is it happening on Android: NO - ANDROID OK

Is it happening on iOS: YES

```
 <!-- run `flutter doctor` and paste the output here: -->
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D42, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

• No issues found!


```

**Describe the bug**

Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/mariofraga/development/flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-3.0.14/ios/Classes/MultiImagePickerPlugin.m:2:9: fatal error: 'multi_image_picker/multi_image_picker-Swift.h' file not found
    #import <multi_image_picker/multi_image_picker-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone XR.

**Comment by Sh1d0w** [comment]
You are missing Swift Bridging Header. Follow this steps in the docs https://sh1d0w.github.io/multi_image_picker/#/iostroubleshooting

**Comment by bobwiller** [comment]
I have this exact same error - same file. Where does this file get created (what folder), what do you name it, and what do you put in it (if anything?)

**Comment by Sh1d0w** [comment]
@bobwiller You just need to create an empty Swift file in the project, it does not matter where exactly but have to do it from XCode in order the prompt for the bridging header to show up.

**Comment by hieuseesaa** [comment]
I did the following and it worked

Open file Podfile (ios/Podfile) and change.

add `use_frameworks!`
add `config.build_settings['SWIFT_VERSION'] = '5.0'`

```
target 'Runner' do
  use_frameworks! # add this line

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0' # add this line
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```
