### ISSUE TITLE
 'androidx.lifecycle:lifecycle-viewmodel' has different version for the compile (2.0.0-rc01) and runtime (2.0.0) classpath

### ISSUE THREAD

**Issue by chrisoftech** [Sh1d0w/multi_image_picker#78]
**Launching lib\main.dart on Android SDK built for x86 in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.lifecycle:lifecycle-viewmodel' has different version for the compile (2.0.0-rc01) and runtime (2.0.0) classpath. You should manually set the same version via DependencyResolution
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 15s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)**

`multi_image_picker` version: multi_image_picker: ^3.0.14

Is it happening on Android: Yes

Is it happening on iOS: 

```
 $ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.2.2-pre.46, on Microsoft Windows [Version 10.0.16299.309], locale en-GH)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.3)
[√] VS Code (version 1.31.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Describe the bug**

**Comment by Sh1d0w** [comment]
This is android dependency problem between two plugins you are using, to resolve it do as the message suggests - resolve via dependency resolution. It has nothing to do with the plugin it is Android thing.

```
subprojects {
    project.configurations.all {
	resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'androidx.lifecycle' &&
	       !details.requested.name.contains('androidx')) {
		details.useVersion "2.0.0"
            }
	}
    }    
}
```

More info here https://github.com/flutter/flutter/issues/27254

**Comment by Hu-Wentao** [comment]
I just change  
```gradle
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
    }
}
```
to
```gradle
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
    }
}
```
