### ISSUE TITLE
How to customize Android view?

### ISSUE THREAD

**Issue by psyanite** [Sh1d0w/multi_image_picker#81]
There's a couple of things I want to do, I want to move the Preview button to the top right hand corner, and remove the bottom bar etc. I understand I will need to do this in "Android". 

What I might have to do is fork this project and then register it as my own on Flutter (or some how plug it into my parent project). 

But even when I do that how can I update the UI elements in the Android codebase? All I see in the .java files are methods. 

If you can give some advice on the easiest way to do this I would really appreciate it 🌺

**Comment by Sh1d0w** [comment]
Hi, this plugin is using [Matisse](https://github.com/zhihu/Matisse) to present the Android image picker. If you know java, you can fork the project and also for Matisse, cusstomize it and then use your custom Matisse fork in your multi_image_picker plugin.

**Comment by psyanite** [comment]
@Sh1d0w Thanks a for the quick and detailed response.
