### ISSUE TITLE
How to customize the Android appbar text?

### ISSUE THREAD

**Issue by psyanite** [Sh1d0w/multi_image_picker#82]
I've set the appBar to be white and want to set the text on top (e.g. "All Media" and the back button) to be black. Is this current customizable?

**Comment by Sh1d0w** [comment]
Hi, all available options for customization are listed in the documentation here https://sh1d0w.github.io/multi_image_picker/#/theming?id=android-customization

**Comment by psyanite** [comment]
@Sh1d0w. I have successfully customised some of the text and colour fields but was unable to customise the text. 

I have tried to set album.dropdown.title.color to black but was unsuccessful.
