### ISSUE TITLE
Get GPS Coordinates from Images 

### ISSUE THREAD

**Issue by sh0umik** [Sh1d0w/multi_image_picker#83]
It would be very nice if this plugin could extract geo location coordinates from images taken from camera or already stored pictures from the gallery and show it as a meta data like `requestMeta()` method.

It is possible as defined by android api in the `TAG_GPS_LATITUDE` and `TAG_GPS_LONGITUDE` tag
https://developer.android.com/reference/android/media/ExifInterface.html

I have also found a library (dart) to extract the info but not sure if you want to do it in the native android side or in dart side !
https://pub.dartlang.org/packages/exif

Please let us know your plan regarding this feature in the multi_image_picker library

**Comment by Sh1d0w** [comment]
@sh0umik I am not sure I understand the requested feature here? You already have full access to the image metadata as described here https://sh1d0w.github.io/multi_image_picker/#/metadata

The `metadata.gps` object contains all GPS related metadata that the image has and you can access it from there?

**Comment by sh0umik** [comment]
@Sh1d0w I have missed that part of the document. You can close it now .. Thank you for your quick reply

**Comment by Sh1d0w** [comment]
No worries.
