### ISSUE TITLE
Build failed with exception when using version 3.0.23

### ISSUE THREAD

**Issue by kaxp** [Sh1d0w/multi_image_picker#86]
**Bug Report**

`multi_image_picker` version: <3.0.23>
compileSdkVersion 27
targetSdkVersion 27
minSdkVersion 19

Build falied on Android.

flutter-doctor = 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.0.0, on Linux, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.30.1)
[✓] Connected device (1 available)

• No issues found!

The app runs when using the multi_image_picker till version 2.4.11
but when I use the version above 3.0.11 the app won't build and give me the following error log

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  warn: removing resource dharma.binarynumbers.io.dharma:plurals/error_over_count without required default value.
  warn: removing resource dharma.binarynumbers.io.dharma:string/error_over_original_count without required default value.
  warn: removing resource dharma.binarynumbers.io.dharma:string/error_over_original_size without required default value.
 /home/kapil/Documents/Projects/Dharma/dharma/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.

 /home/kapil/Documents/Projects/Dharma/dharma/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.

 /home/kapil/Documents/Projects/Dharma/dharma/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:931: error: resource android:attr/fontVariationSettings not found.

 /home/kapil/Documents/Projects/Dharma/dharma/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:931: error: resource android:attr/ttcIndex not found.

  error: failed linking references.
  Command: /home/kapil/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-linux.jar/6723f686b3ba7cac1112f98b29e2c15b/aapt2-3.2.1-4818971-linux/aapt2 link -I\
          /home/kapil/Android/Sdk/platforms/android-27/android.jar\--manifest\        /home/kapil/Documents/Projects/Dharma/dharma/build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\ -o\
          /home/kapil/Documents/Projects/Dharma/dharma/build/app/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\-R\
          @/home/kapil/Documents/Projects/Dharma/dharma/build/app/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\--auto-add-overlay\--java\
          /home/kapil/Documents/Projects/Dharma/dharma/build/app/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\ --custom-package\dharma.binarynumbers.io.dharma\-0\apk\-output-text-symbols\

 /home/kapil/Documents/Projects/Dharma/dharma/build/app/intermediates/symbols/debug/R.txt\--no-version-vectors

**Comment by Sh1d0w** [comment]
@kaxp As stated in the docs https://sh1d0w.github.io/multi_image_picker/#/gettingstarted the plugin was migrated to AndroidX, as most of the other Flutter plugins.

If you haven't migrated your project to AndroidX, you should use version 2.4.11. Version 3 and above only supports AndroidX.
