### ISSUE TITLE
Android open camera erro

### ISSUE THREAD

**Issue by BTPJ** [Sh1d0w/multi_image_picker#97]
**Bug Report**

`multi_image_picker` version 4.0.0

when use enableCamera: true, Android 8.1.0 do nothing and print some error info like this

W/System.err( 1813): java.io.IOException: No such file or directory
W/System.err( 1813): 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
W/System.err( 1813): 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
W/System.err( 1813): 	at java.io.File.createTempFile(File.java:2001)
W/System.err( 1813): 	at com.sangcomz.fishbun.util.CameraUtil.createImageFile(CameraUtil.java:58)
W/System.err( 1813): 	at com.sangcomz.fishbun.util.CameraUtil.takePicture(CameraUtil.java:31)
W/System.err( 1813): 	at com.sangcomz.fishbun.ui.picker.PickerController.takePicture(PickerController.java:38)
W/System.err( 1813): 	at com.sangcomz.fishbun.adapter.view.PickerGridAdapter$1.onClick(PickerGridAdapter.java:70)
W/System.err( 1813): 	at android.view.View.performClick(View.java:6308)
W/System.err( 1813): 	at android.view.View$PerformClick.run(View.java:24858)
W/System.err( 1813): 	at android.os.Handler.handleCallback(Handler.java:790)
W/System.err( 1813): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 1813): 	at android.os.Looper.loop(Looper.java:164)
W/System.err( 1813): 	at android.app.ActivityThread.main(ActivityThread.java:6785)
W/System.err( 1813): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 1813): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)

**Comment by Sh1d0w** [comment]
This is related to https://github.com/sangcomz/FishBun/issues/102

I will submit a PR with fix, when I have time if anyone does not fixes it before me.

**Comment by acherkashyn** [comment]
@Sh1d0w I figured out how to reproduce this issue, and added a comment in FishBun. Hope it helps.

**Comment by Sh1d0w** [comment]
Closing this as stale. Once FishBun implements a fix I will update its version here.
