### ISSUE TITLE
Does not resolve every metadata available

### ISSUE THREAD

**Issue by Quanalogy** [Sh1d0w/multi_image_picker#99]
When using the built-in camera on Nexus 5x (emulator) with android P to take a photo and getting the metadata from it using this plugin the following is returned:

```
0 = {map entry} "ApertureValue" -> 2.97
1 = {map entry} "ExifVersion" -> "0220"
2 = {map entry} "GPSAltitude" -> 5.0
3 = {map entry} "GPSLongitudeRef" -> "W"
4 = {map entry} "PixelXDimension" -> 960.0
5 = {map entry} "PixelYDimension" -> 1280.0
6 = {map entry} "GPSTimeStamp" -> "17:02:27"
7 = {map entry} "ImageLength" -> 1280.0
8 = {map entry} "Make" -> "Google"
9 = {map entry} "Orientation" -> 1.0
10 = {map entry} "SubSecTimeDigitized" -> "873"
11 = {map entry} "DateTime" -> 1547744548000
12 = {map entry} "DateTimeOriginal" -> "2019:03:17 17:02:28"
13 = {map entry} "SubSecTimeOriginal" -> "873"
14 = {map entry} "GPSLatitudeRef" -> "N"
15 = {map entry} "ShutterSpeedValue" -> 6.643
16 = {map entry} "FocalLength" -> 5.0
17 = {map entry} "ImageWidth" -> 960.0
18 = {map entry} "ExposureTime" -> 0.01
19 = {map entry} "Model" -> "Android SDK built for x86"
20 = {map entry} "FNumber" -> 2.8
```
This miss values like `gpsLatitude` and `gpsLongitude`, which are possible to get when using an exif reader to read it instead of this plugin.

**Comment by Sh1d0w** [comment]
@Quanalogy if you check the [docs](https://sh1d0w.github.io/multi_image_picker/#/metadata) you will see the metadata object has 3 properties:

```
print(metadata.gps.gpsDestLatitude);
print(metadata.exif.artist);
print(metadata.device.model);
```

The GPS data will be in metadata.gps prop. Full reference of all available properties you can find here https://pub.dartlang.org/documentation/multi_image_picker/latest/metadata/Metadata-class.html

**Comment by Quanalogy** [comment]
Are you even reading what I'm telling you? I am quite aware that you have this functionality but the latitude and longitude parameters are null, hence cannot be used. If however I'm using an exif reader these values are present!

**Comment by Sh1d0w** [comment]
Please provide image that I can reproduce this with.

**Comment by Quanalogy** [comment]
![GoogleEmulatedCameraImage](https://user-images.githubusercontent.com/6534708/55192885-e2eac080-51a5-11e9-9a6b-faa86560ffd0.jpg)

**Comment by Sh1d0w** [comment]
@Quanalogy I was able to take a look at the problem.

I wasn't able to obtain the GPS coordinates from your image either. I think you need to enable the GPS tag in the emulator camera when taking photos, before the Exif interface can parse it.

However testing with real images like these ones: https://github.com/ianare/exif-samples/tree/master/jpg/gps

It returns the GPS coordinates correctly.
